### ISSUE TITLE
Inconsistent display

### ISSUE THREAD

**Issue by Kaor** [loomio/loomio#10031]
Hi,
Since 2.18.0, we are now on 2.21.3
we have strange things like that : 
![image](https://github.com/loomio/loomio/assets/5570992/8c1688a0-9d17-479c-9cd1-3c8981b6864d)
Has anyone had a similar problem?
Thanks a lot

**Comment by robguthrie** [comment]
Hi, that's not good eh?

Have you tried editing the thread layout settings - that might fix it.

If it does fix it, and you have other threads that need to be fixed, you can login to the rails console and run 

EventService.repair_all_threads

Let me know how you get on.
