### ISSUE TITLE
Set name for generic OAUTH login button?

### ISSUE THREAD

**Issue by poVoq** [loomio/loomio#10113]
It would be nice if there was a way to set a custom name and maybe an image for the generic Oauth2 login button for specific custom integrations.

Right now few people understand what "OAUTH" means and thus are left confused what the button is about.

Thanks!

**Comment by robguthrie** [comment]
Maybe we don't need a custom name, we just need a better label on the button?

**Comment by robguthrie** [comment]
Can you send a screenshot so I can easily imagine what we're talking about.. (without setting up an oauth config myself)

**Comment by poVoq** [comment]
This is what it currently looks like with my Gitea OAUTH integration, which works fine but I would rather have the option to write something as a name people will understand:

![image](https://github.com/loomio/loomio/assets/940360/c6e74264-b8ef-48c2-9f52-c7c99c699608)

Like how it says "Nextcloud" when you use that integration. But just a custom string set via an ENV variable.

**Comment by robguthrie** [comment]
Hi I've added support for this via SAML_LOGIN_PROVIDER_NAME and OAUTH_LOGIN_PROVIDER_NAME

If you're running against master it should be there now.
