### ISSUE TITLE
Dot score polls only display users score if they chose the first option

### ISSUE THREAD

**Issue by anarute** [loomio/loomio#10152]
After the latest release, dot score polls are not displaying the users votes correctly in the poll view.

It only shows the score for the first option:

[Screencast from 2023-12-29 18-37-27.webm](https://github.com/loomio/loomio/assets/333447/b5f76a18-ac99-4dc5-b74e-e8c480ae6d35)

In the example above I've voted for options A and B and it only shows the score for A.

**Comment by robguthrie** [comment]
Thanks for finding this bug. I've fixed it. Please let me know if there are any odd behaviours you notice after this.
