### ISSUE TITLE
Tags filter

### ISSUE THREAD

**Issue by LucaGabi** [loomio/loomio#10155]
Hi,

Having a lot of tags makes it difficult to use them to get the thread associated, a filter would be needed inside the ui selector.

**Comment by robguthrie** [comment]
Hi, thanks for Looking into Loomio. 

I don't think I understand the problem. Can you provide more detail, possibly including screenshots?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/loomio/loomio/issues/10155#event-11674965197

@robguthrie, what commit or PR was this fixed in?

**Comment by robguthrie** [comment]
There is not enough detail to understand the issue

**Comment by RokeJulianLockhart** [comment]
> https://github.com/loomio/loomio/issues/10155#issuecomment-1922235955

I'll assume from that that it isn't complete then. In which case, it should have been closed as “Not planned” instead (rather than https://github.com/loomio/loomio/issues?q=is%3Aissue+reason%3Acompleted).
