### ISSUE TITLE
Users keep being added in polls set as "Anyone in the group"

### ISSUE THREAD

**Issue by anarute** [loomio/loomio#10273]
We are creating polls using the feature "Anyone in the group" so we don't need to manually invite people but if we remove people from the poll or have bot users in the group they are re-added after a few hours.

During the creation it works well and the bot users are not added, but after a few hours they are added and removing them manually doesn't work because they will be added again in the next sync.

**Comment by robguthrie** [comment]
hrrmm. I'll look at this next week - on holiday this week. 

It should handle this correctly. Thanks for reporting

**Comment by robguthrie** [comment]
Hi @anarute - I'm fairly sure I found and fixed this issue. Sorry you had to experience it.

**Comment by anarute** [comment]
Thank you for the quick fix, I confirm the issue has been fixed for us.
