### ISSUE TITLE
markdown quotes are broken

### ISSUE THREAD

**Issue by sradigan** [loomio/loomio#10367]
It looks like in the latest version of the app, markdown quotes are not being rendered correctly.

The quotes show up correctly when using the preview button, but they do no render once the post is made.

I found an older post that was demonstrating markdown usage and all the quotes are broken here too. So I believe it is something in the deployed web app currently.

https://www.loomio.com/d/Wh7vHaTk/markdown-text-formatting-made-easy

**Comment by robguthrie** [comment]
Hi, I've fixed this in master. Thanks for the report.

Are you running your own server, or using loomio.com?

**Comment by sradigan** [comment]
Thanks @robguthrie ! We are using loomio.com
