### ISSUE TITLE
Unable to disable translations

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#10420]
I am using a German Loomio group. I accidentally clicked on "Translate", now all the texts are live-translated to English. I cannot seem to revert that.

**Comment by robguthrie** [comment]
That sounds quite odd. Could you send me (rob@loomio.org) a link to the thread where this is happening and I'll have a look?

**Comment by madduck** [comment]
It's back to German. And I also cannot find a button anymore to translate.

**Comment by robguthrie** [comment]
I feel there is nothing I can do about this issue. My testing recently shows the feature is working well, and there are no steps to reproduce here. Happy to reopen if there is something to go on
