### ISSUE TITLE
Disable email notifications on edits?

### ISSUE THREAD

**Issue by poVoq** [loomio/loomio#10528]
Right now it seems like Loomio is sending an email on every minor edit to a thread. This is especially annoying when the post that starts the thread is edited to include some of the discussed further details.

This is despite having set notifications only for mentions and replies.

**Comment by robguthrie** [comment]
Uhmm.. this isn't the design or my experience of how it works. Maybe a bug or setting confusion?

Are you sure you're not subscribed to the thread, and that you're not adding anyone to the "notify" field when saving edits?

**Comment by poVoq** [comment]
Hmm, I can ask the person doing the edits if they are specifically adding me to the notify field on edits.

**Comment by robguthrie** [comment]
oh really? yes that will be the issue. It should default to blank. 

That's likely a new bug since introducing thread templates with support for notifications. New threads will inherit the notification setting saved in the template. But this should not happen for thread edits too. I'll have a look.

**Comment by robguthrie** [comment]
Ok this is fixed in master now. Thanks for letting me know.
