### ISSUE TITLE
Link formatting in Slack webhooks

### ISSUE THREAD

**Issue by poVoq** [loomio/loomio#10558]
The way the links are formatted when send via Slack webhooks causes some issues with link parsing.

Originally I thought is was an issue with the XMPP notification bot, see:

https://codeberg.org/aryak/xmpp-webhook/issues/3

But apparently it just takes what it gets from Loomio.

Maybe there is a way to add some padding to links (like a space) so that it is more clear where the link ends?

Thanks!

**Comment by robguthrie** [comment]
Can I confirm, are you using Slack? These notifications are formatted specifically for it's weird message syntax. There is also a markdown and html webhoook, which might work better for xmpp.

**Comment by poVoq** [comment]
I can try and see if this XMPP bot that is explicitly listening to Slack like webhooks also works with other kind of webhooks. Otherwise it would require to write a custom bot which I sadly don't have the time  (and skills) for.

**Comment by robguthrie** [comment]
Yea, I was trying to be helpful.. most people use those services and don't know what tech they use.

Matrix is html, 
Slack is slackmd, 
Discord, Ms Teams and Mattermost are markdown

I still don't understand what's going on though. What was the screenshot from?

**Comment by poVoq** [comment]
The screenshot is from an XMPP client that is connected to an XMPP channel where the bot is connected that translates Slack-like webhooks to XMPP. This generally works fine, but the formatting is odd and breaks some URLs as seen in the screenshot.

**Comment by robguthrie** [comment]
Oh ok. I've just checked, links look good in Slack,  I would say the bot isn't handling something correctly.

But the format is dumb and I would suggest sending markdown if you can.

**Comment by poVoq** [comment]
I tried it with the Mattermost markdown, which does work, but the formatting is even worse for parsing links (as XMPP only understands a small subset of Markdown):

![grafik](https://github.com/loomio/loomio/assets/940360/2676fe4c-2ef1-4529-b7f5-9124f38b7fc2)

But I agree, it probably needs to be bend to work better on XMPP in the bot. Sorry for bothering.

**Comment by robguthrie** [comment]
You're not bothering!!  I really appreciate you taking Loomio to weird places, and also accepting that sometimes I won't be able to support it.

The chatbot stuff is really modular, and if this is important enough to you, you can create your own serializer that handles links a specific way.

See https://github.com/loomio/loomio/tree/master/app/views/chatbot - it's not a lot of code
