### ISSUE TITLE
New threads include draft of previously created threads

### ISSUE THREAD

**Issue by poVoq** [loomio/loomio#11079]
Since the recent introduction of the hocuspocus backend, I have this issue that when creating a new thread, it automatically puts the content of a previously created but unrelated thread as a draft into the text field.

So to create a new thread one has to first discard the draft and then start again, which is a bit annoying.

I guess the backend gets somehow confused with previous drafts and new threads?

**Comment by robguthrie** [comment]
It's amazing to me what bugs go unreported.. thanks for this. Working on it now

**Comment by robguthrie** [comment]
This commit should fix this issue https://github.com/loomio/loomio/commit/432650ca7f64293d85cb261c9190c41f10f3e175
