### ISSUE TITLE
Thread creation occasionally fails

### ISSUE THREAD

**Issue by atomicthumbs** [loomio/loomio#11149]
Occasionally, when one of our users tries to post a thread, the interface will blink the loading throbber and fail to post it, leaving them at the thread creation page. If they try again, it fails again. 

I have experienced this once; I attempted to turn on debug logging by editing .env to set RAILS_LOG_LEVEL=DEBUG (this did not work) and restarting the container. The problem still occurred. I copied my work, refreshed, pasted, and tried again, and it posted correctly.

No error is given to the user, and these are the only log entries about it:

```
loomio-app         | I, [2024-09-26T19:18:35.694612 #15]  INFO -- : [a0929bd0-ef58-46a4-a001-3251057a2d8f] method=POST path=/api/v1/discussions format=json controller=API::V1::DiscussionsController action=create status=403 allocations=7408 duration=19.65 view=0.14 db=6.49
loomio-app         | I, [2024-09-26T19:18:35.695151 #15]  INFO -- : source=rack-timeout id=a0929bd0-ef58-46a4-a001-3251057a2d8f timeout=15000ms service=24ms state=completed
```

**Comment by robguthrie** [comment]
What's the response code and body from the server when this happens?

**Comment by atomicthumbs** [comment]
That's the odd thing; we're reverse-proxying behind Caddy and Caddy did not emit a log entry for the failed requests, but Loomio did. I'll see if I can retrieve anything the next time it happens.

**Comment by robguthrie** [comment]
Ideally, open inspector in the browser before hitting post, and see the network request there

**Comment by atomicthumbs** [comment]
will do so if someone notes the problem occurring again.

**Comment by robguthrie** [comment]
closing until someone else can confirm there is a problem
