### ISSUE TITLE
Group privacy set to "open;" threads are publicly visible, but decisions are not

### ISSUE THREAD

**Issue by atomicthumbs** [loomio/loomio#11148]
Expected behavior: a group set to "open" will have its contents publicly viewable, save for the member list.

Actual behavior: contents are only partially visible:

<img width="1052" alt="image" src="https://github.com/user-attachments/assets/480f7ef5-a5fa-4ca2-9c80-0ce18f2ca5b4">

<img width="1098" alt="image" src="https://github.com/user-attachments/assets/42d5bf81-ba5f-4ec3-b04c-52ab94ee7106">

we are building a voluntarist organization (an online community), using Loomio to find consensus, and it's proved extraordinarily helpful, but being able to have full transparency to users who aren't members of our decision-making group is important to us.

**Comment by robguthrie** [comment]
Nice to hear about how you're using Loomio. As far as I know this works well. I feel like I can't see what's going on from this level of info.

Oh, you're saying polls are not public! Is that the problem?

**Comment by atomicthumbs** [comment]
yeah, nothing in the Decisions tab shows up for logged-out users. for us this means that when we conclude discussions with a poll, and the poll finishes, users of the software system we are operating cooperatively can no longer see them.

this is what it's like logged in:
<img width="1074" alt="image" src="https://github.com/user-attachments/assets/08cbcdf6-e359-4684-bd00-d59cb3dcb3a1">

**Comment by robguthrie** [comment]
Please update to latest image from master branch (`LOOMIO_CONTAINER_TAG=master` in your  `.env` file) and let me know how it goes.

**Comment by atomicthumbs** [comment]
Works now, thank you.
