### ISSUE TITLE
When group is set to publicly-viewable but invite-only for participation, logged-out viewers directed to log in get trapped in limbo and can no longer view Loomio

### ISSUE THREAD

**Issue by atomicthumbs** [loomio/loomio#11173]
We're having a follow-on problem to #11148. Our users will go to our group and click a button, or attempt to visit the base URL for the Loomio; doing the latter takes them to the dashboard, which is only visible if you have an account.

This causes the login dialog to show up, which renders the entire Loomio unviewable. Clicking the close button on the "create an account" dialog takes them back to the unclosable login dialog, which blocks interaction to the site and persists across visits.

Our users can't get out of this without manually clearing their cookies.

<img width="1023" alt="image" src="https://github.com/user-attachments/assets/4f07a597-eecb-44db-9377-81a4ec5da032">
<img width="1057" alt="image" src="https://github.com/user-attachments/assets/91b64dab-6473-41ff-9d2b-7fa0f4222830">

**Comment by robguthrie** [comment]
Sorry I've not had time to look at this. If you're a funded organization, it would be good to have a chat about how you can prioritize my time, if this is important to you.

**Comment by robguthrie** [comment]
I've had a look at your site. It's awesome to see you making use of Loomio. I'll get back to this issue when I can

**Comment by atomicthumbs** [comment]
> I've had a look at your site. It's awesome to see you making use of Loomio. I'll get back to this issue when I can

thank you, we appreciate it a lot whenever you're able.

**Comment by robguthrie** [comment]
Hi, I've recently added something that might help with your situation. We've added a FEATURES_DEFAULT_PATH ENV, which you can set to your main group URL. 

I'm skimming the issue here, so let me know if that does not solve the problem

**Comment by atomicthumbs** [comment]
It's fixed, thank you.
