### ISSUE TITLE
Provide docker image for easy installation anywhere

### ISSUE THREAD

**Issue by geekpete** [loomio/loomio#1476]

**Comment by pierreozoux** [comment]
Hey, sorry to bother here, can't find dockerfile anywhere :/ If you can help me out figure where it is, I would be glad!

Thanks!

**Comment by robguthrie** [comment]
Hi @pierreozoux we have installation instructions here: https://github.com/loomio/loomio/wiki

Right now the recommended installation method is to use Dokku-alt, a docker based mini heroku system. We may develop a less flexible/more straightforward docker image in the future. Please do let me know how you get on with your installation - we have a Loomio group for supporting you here: https://www.loomio.org/g/C7I2YAPN

**Comment by pierreozoux** [comment]
Thanks for your answer! I'll check this out!
