### ISSUE TITLE
revision history for discussion context does not accurately report which person authored each version

### ISSUE THREAD

**Issue by hugetim** [loomio/loomio#1582]
To reproduce: Create a discussion with one account (A) and then have another account (B) edit it. Look at the revision history. It will say "Edited...by B (current)". Click "Prev." It will say "Edited...by B (Restore this version)" when it should say "Edited...by A..."

**Comment by denjello** [comment]
Is this still happening? Can anyone confirm?

**Comment by robguthrie** [comment]
Loomio beta issue. Closing
