### ISSUE TITLE
Closing date not set properly on calendar blur

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#1600]
From Quentin Grimaud via Loomio

When I create a proposal and select the date, then the choice of the time appears, and a given hour is selected by default. If I am happy with this given hour and click outside the select box, the date field does not change with my date! But we have the impression that the date is correctly set, because we see the content of the field changing. It changes actually only slightly: “pm” becomes “PM”, but the date is still the default one. The only way to make it work is to select the date and then click on any hour.

I have very often had the problem that the proposals I created had a wrong closing date, I changed them afterwards. At the beginning I thought that I had forgotten to set the date or had made a calculation error when counting the number of days. But as it happens to me very often, today I tried to create a fake discussion and proposal and see what the matter was with this date, and I think the problem is what I exposed.

**Comment by denjello** [comment]
That issue in  smalot/bootstrap-datetimepicker#300 has not been resolved according to github. Is this still happening? If so, we need to resolve it. I see three options:
1. A different library
2. Patch the library ourselves
3. Slap wontfix on it

**Comment by robguthrie** [comment]
Not going to use a different library. Would be best to patch the library
ourselves.

**Comment by robguthrie** [comment]
It's super unlikely we'll fix issues like this in lomio beta now. Closing
