### ISSUE TITLE
Put pie graph into proposal closing soon email

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#1607]
We are already doing this in the Yesterday on Loomio email: see views/user_mailer/missed_yesterday/_motion_pie.html.haml

**Comment by denjello** [comment]
Has this been finished, is it in 1.0 ?

**Comment by robguthrie** [comment]
This has been done. 
Also relevant - Emails (and all the backend stuff) are/is shared between beta and 1.0.
