### ISSUE TITLE
Incorrect invitation to subgroup email

### ISSUE THREAD

**Issue by HSalmon** [loomio/loomio#1619]
I received two invitations to join the "help" subgroup from Alanna who said she was no longer a coordinator. One of these (I suspect) actually came from Rich, and the other definitely came from Ben (see "dog dinger" comment)...not sure what's going on with the incorrect sender information

![screen shot 2014-08-06 at 4 16 41 pm](https://cloud.githubusercontent.com/assets/2882097/3822309/11ecb4c4-1d21-11e4-99d9-882a4a6d8b04.png)

**Comment by denjello** [comment]
Is this still happening, or was it a quirk? There have been several newer Ruby versions since then...

**Comment by robguthrie** [comment]
Yes, let's close
