### ISSUE TITLE
Left align discussion titles in daily summary email

### ISSUE THREAD

**Issue by jonlemmon** [loomio/loomio#1629]
See https://www.loomio.org/d/3gckm0d4/easy-improvement-to-the-daily-summary-email

**Comment by denjello** [comment]
Is this still "active" ???

**Comment by robguthrie** [comment]
This is something we would like done. It's a nice easy job for someone

**Comment by HSalmon** [comment]
@robguthrie - this has been done, right? Can we close it?

**Comment by robguthrie** [comment]
Nope. It's super simple and would improve the email a lot.

Simply list Discussions/Motions by title, and follow them either by names
or icons (implementors choice) and remove the crappy sentence structure
stuff entirely.

**Comment by robguthrie** [comment]
I did this job ages ago
