### ISSUE TITLE
Add preview on all forms that accept markdown.

### ISSUE THREAD

**Issue by jorgecarleitao** [loomio/loomio#1630]
Currently, creating or editing a proposal, comment or discussion does not allow to preview the end result. At the moment I have to go to stackoverflow or github and copy paste the text to see how the final result will be.

I propose that all forms that accept markdown have a preview, either live, like stackoverflow, or upon request, like github.

**Comment by denjello** [comment]
I totally agree about that, there is a discussion taking place right now here:

<https://www.loomio.org/d/ag9nP5hG/markdown-love-it>

**Comment by gdpelican** [comment]
Going to close this for now; it's definitely a needed feature, but it'll be placed on the roadmap and completed in due time in the new interface (and likely not with Markdown.)
