### ISSUE TITLE
Duplication of paginated items on /explore page

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#1635]
Something is going wrong with the kaminari pagination on [the Explore page](https://www.loomio.org/explore) since we upgraded to Rails 4 - there's duplication between pages and pages aren't loading the correct number of items.

**Comment by denjello** [comment]
I would classify this as urgent, if it is still happening. 
As it is I first see 5 pages, then 9, then 10 and it does seem that things are repeating themselves.

**Comment by gdpelican** [comment]
Closing this as we're not going to touch the explore page again in beta. Shiny new explore page likely coming soon!
