### ISSUE TITLE
Option to allow creation of subgroups within subgroups is confusing

### ISSUE THREAD

**Issue by alannaloomio** [loomio/loomio#1637]
Currently when setting up a new subgroup, you are shown the permissions tab, including the option to create subgroups. This doesn't make any sense in the context of setting up a subgroup, since you can't have sub-subgroups. Suggest removing this option when creating a subgroup to avoid confusion.

![screen shot 2014-08-14 at 2 58 00 pm](https://cloud.githubusercontent.com/assets/5498878/3915433/f900dc26-235e-11e4-9122-4e13ffaf1281.png)

**Comment by denjello** [comment]
So it can be closed???

**Comment by robguthrie** [comment]
Nope. This bug still exists and is an easy fix. Would be great if someone wanted to add the 1 condition needed.

**Comment by HSalmon** [comment]
Mix and I are picking this up :)

**Comment by gdpelican** [comment]
:fireworks: !
