### ISSUE TITLE
h2 not working in markdown

### ISSUE THREAD

**Issue by s01us** [loomio/loomio#1642]
```
# Heading A

content with 'heading a' above it 

---

#Heading B

content with 'heading b' above it 

---

## Heading C

content with 'heading c' above it 

---

##Heading D

content with 'heading d' above it 
```
Generates: 

![image](https://cloud.githubusercontent.com/assets/2665886/3975373/bf8221f6-2806-11e4-9d4c-a99c44883eed.png)

**Comment by denjello** [comment]
I am not seeing this behaviour any more - just tested on loomio. This can be closed. @rdbartlett @gdpelican

**Comment by robguthrie** [comment]
Thanks @denjello
