### ISSUE TITLE
Lines starting with "and" in "Yesterday on Loomio" email

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#1656]
For some reason, sentences are starting with "and" in what seems like every line in "Yesterday on Loomio" - maybe there's something meant to be printed there that's missing?

![screen shot 2014-08-31 at 2 12 03 pm](https://cloud.githubusercontent.com/assets/5498878/4100776/68d05b46-30b4-11e4-97a2-f609c0c69cbe.png)

**Comment by s01us** [comment]
None of this is translated either 
:sob:

**Comment by robguthrie** [comment]
Wow.. it would really be a great idea to remove all concepts of sentence
construction from this..

**Comment by robguthrie** [comment]
no longer an issue
