### ISSUE TITLE
Glitch with unread comments in a discussion with more than a "page" of unread content

### ISSUE THREAD

**Issue by HSalmon** [loomio/loomio#1675]
When viewing a discussion with more than a “page” of unread content for the first time you are taken to the correct place, but when you click “next page” it does not scroll to the correct unread comment.

Images seem to affect navigation to the right discussion point as well.

[View relevant Loomio discussion](https://www.loomio.org/d/ZOlb5VYe#comment-222128)

**Comment by denjello** [comment]
@HSalmon & @rdbartlett : Is this a similar paging issue to loomio/loomio/issues/1635 ?

**Comment by robguthrie** [comment]
Beta issue. Closing
