### ISSUE TITLE
bad html-zation of an URL while commenting

### ISSUE THREAD

**Issue by nando** [loomio/loomio#1678]
I've tried to add a link [0] on a discussion [1] and it didn't work :(

Thanks anyway guys!!! 
-- nando

[0] https://medium.com/@colgado/fondo-1893de64a84b
[1] https://www.loomio.org/d/tAvsXxFr/monedas-alternativas-y-superacion-del-monetarismo?page=1

**Comment by denjello** [comment]
Yeah, the @ symbol is a newcomer to URLs - and furthermore there is a function that checks comments for the existence of the "@" symbol and looks for loomio users with it (that lookahead thingy).

With all three versions of technically valid markdown:
```
http://me.you.com/@me.hello
<http://me.you.com/@me.hello>
[me.hello](http://me.you.com/@me.hello)
```

This was the result
```
@me.hello" target="_blank">http://me.you.com/@me.hello
```
Which is TERRIBLY broken.

**Comment by robguthrie** [comment]
No longer a problem in angular interface
