### ISSUE TITLE
"Upload a new image" button fails to work

### ISSUE THREAD

**Issue by stadtwald** [loomio/loomio#1697]
The "Upload a new image" button on the profiles page of loomio (https://www.loomio.org/profile) doesn't work on my browser (Iceweasel 24.8.0 / Debian 7.0).

Upon clicking the button, the page jumps up but nothing else occurs.  No JavaScript exceptions seem to bubble to the top.

**Comment by zeigerpuppy** [comment]
image upload fails for me in development mode with error:
``
Missing required arguments: aws_access_key_id, aws_secret_access_key
```
any way to enable local storage?
