### ISSUE TITLE
Some emailed comments are not being posted

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#1698]
Praveen emailed a comment to [this discussion](https://www.loomio.org/d/mj5OMnSN/constitution-amendment-explain-our-perspective-on-this-world) and it never got posted. He's experienced this a couple of times - I have a copy of one of the emails so we can take a closer look to see what's going on.

**Comment by robguthrie** [comment]
I'm pretty sure we have not had this problem in ages. I would love to be able to work out what specific thing about the email being sent or the discussion is causing the problem. Are you able to reproduce this @rdbartlett ?

**Comment by mlncn** [comment]
It has been two days and the below e-mail to https://www.loomio.org/d/OGPs25cE/welcome-to-agaric still has not reached there:

> I'm replying from e-mail!!!  Tell Chuck it works!
> 
> Agaric · http://agaric.com · 508 283 3557

Definitely was sent to the long @reply.loomio.org e-mail.  Was really excited to tell Chuck that replying from e-mail worked, too.  ;-)
