### ISSUE TITLE
header image strangeness

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#1701]
I upload a 970x200px header image — which appears to be the right size, but it's weirdly resized on upload:

![image](https://cloud.githubusercontent.com/assets/1380991/4413171/4a89cb0c-4501-11e4-872a-2552ce46addb.png)

Here's the image I uploaded:
![screen shot 2014-09-26 at 8 53 10 am](https://cloud.githubusercontent.com/assets/1380991/4413185/74e943fa-4501-11e4-9f42-2ae7cfc20c6a.png)

**Comment by denjello** [comment]
I can not reproduce this problem with your image. @mhjb can you confirm this is still happening?

**Comment by mhjb** [comment]
Looks all fixed now.
