### ISSUE TITLE
Last read line incorrectly placed

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#1702]
I read this comment yesterday, but today it's back beneath the last read line:
![image](https://cloud.githubusercontent.com/assets/1380991/4413214/c51e13aa-4501-11e4-9e46-b8d5d7f09250.png)

**Comment by denjello** [comment]
Is this still happening?

**Comment by mhjb** [comment]
I believe it's fixed. A week or two back it was still happening but not now.

**Comment by mhjb** [comment]
Actually, yes this is still happening. Relatedly, if I open old YoL emails the last read counts in the app are wound back to that point.
