### ISSUE TITLE
Should be able to follow a thread from email. 

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#1711]
Currently when you receive any emails from a followed thread, there's a link to unfollow the thread, directly from the email. For emails about unfollowed threads, it would be great to add a follow link in the same way. The email_actions controller is all ready and waiting for this extension.

**Comment by denjello** [comment]
This is a great idea.

**Comment by robguthrie** [comment]
Yea, that looks right. Would be cool to have a little test on it somehow, maybe just a controller test, or maybe start a new cucumber.feature, create a discussion and manually hit the url to test that you're now following it.

**Comment by s01us** [comment]
working on this
