### ISSUE TITLE
Plain text "Yesterday on Loomio" digest emails

### ISSUE THREAD

**Issue by Ram-Z** [loomio/loomio#1737]
Similar to #519, please also send plain text email with the "Yesterday on Loomio" email.

**Comment by denjello** [comment]
Is this done already? I already seem to be receiving plain text mails. (Of course I only ever get plain text mails.)

**Comment by Ram-Z** [comment]
No, the notification email are sent in plain text aswell as html but the "Yesterday on Loomio" digest mail are still sent in html only. To get them you need to enable the "daily summary" in the email options.
