### ISSUE TITLE
crazy image/text jumble displayed on page load via mobile

### ISSUE THREAD

**Issue by BenjaminKnight** [loomio/loomio#1743]
I know there's a known problem with caching that will be fixed up with the new interface deploy, but wanted to flag this cos something seems to be getting much worse. 

Four or five times in the last few days I've loaded loomio.org on my mobile (Android, in Chrome), and just get served a jumble of images and text that stays on screen for a long long time (sometimes 5s, sometimes 10s, sometimes it just gets stuck there). 

Any ideas?

**Comment by denjello** [comment]
@BenjaminKnight Can you make a screenshot with your phone please? Or has this been resolved?

**Comment by robguthrie** [comment]
Closing. I think this is fine now.
