### ISSUE TITLE
Crazy layout in Firefox 28

### ISSUE THREAD

**Issue by HSalmon** [loomio/loomio#1749]
![image](https://cloud.githubusercontent.com/assets/2882097/4984819/29d9aaea-6927-11e4-98f7-eeb4ac7b38e2.png)
Screenshot: https://uploads.intercomcdn.com/i/o/522219/615b29c787205c7a8aebc8a8/image.png

**Comment by denjello** [comment]
That looks like a bootstrap column error. Is this still happening with current Firefox?

**Comment by robguthrie** [comment]
that firefox is way too old. closing
