### ISSUE TITLE
Gemfile requires ruby 2.1.4 but Dockerfile install 2.1.2

### ISSUE THREAD

**Issue by gilesp** [loomio/loomio#1754]
The app can't currently be installed using Docker as the phusion/passenger-ruby21 image the Dockerfile uses installs ruby 2.1.2 so the `RUN bundle install --deployment fails`

**Comment by denjello** [comment]
This can't be an issue anymore, @gdpelican -> we are on Ruby 2.2.0 now. Close?

**Comment by robguthrie** [comment]
yep
