### ISSUE TITLE
Yesterday on Loomio emails mark-as-read inconsistency

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#1755]
They now auto-mark-as-read on open detection, but the text at the top implies they don't: "Here's what happened on Loomio yesterday. Once you've read it, click mark as read to remove it from your Loomio Inbox."

**Comment by denjello** [comment]
Still happening? Has the text message been changed?

**Comment by mhjb** [comment]
Unknown — I no longer use Y-o-L as I found it was sending me stuff I'd already read.

**Comment by denjello** [comment]
It appears to still be in the codebase: 

`app/views/wall/show.html.haml`
```
%strong= "Subject:  #{t("email.missed_yesterday.subject")}"

%p
  %em
    %small
      Here's the stuff that happened yesterday on Loomio. Once you've read it, click
      = link_to 'Mark as read', mark_summary_as_read_url_for(current_user)
      to remove it from your Loomio Inbox.

```
