### ISSUE TITLE
Yesterday on Loomio oddness

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#1756]
At the bottom of the 'table of contents':
![image](https://cloud.githubusercontent.com/assets/1380991/5050301/f25977f8-6c91-11e4-81b4-f220bfd8fb07.png)

At the bottom of the email: 
![image](https://cloud.githubusercontent.com/assets/1380991/5050296/e7ea8f78-6c91-11e4-86f1-8b8aa47e9fbb.png)

**Comment by denjello** [comment]
Did anyone fix this?

**Comment by robguthrie** [comment]
Closing. Have not seen this myself, and I read this every day.
