### ISSUE TITLE
Problem when metion user with dot

### ISSUE THREAD

**Issue by rafaelmr2** [loomio/loomio#1765]
There's a problem when I metion a user that has "." (dot) in username. See in attached image.
![metion](https://cloud.githubusercontent.com/assets/4471805/5154466/ba0bffd2-7246-11e4-8587-3b4f856b42a2.png)

**Comment by denjello** [comment]
@gdpelican > can you please share the code that resolves this issue for a potential backport?

**Comment by robguthrie** [comment]
we've resolved this by validating that usernames do not have a dot.
