### ISSUE TITLE
Inbox clearing is a bit b0rked

### ISSUE THREAD

**Issue by jessykate** [loomio/loomio#1805]
i can't seem to clear my inbox. when i go to my inbox and clear out everything, a last item constantly re-appears. the number of items in the inbox also doesn't match the number displayed on the inbox icon. 

![screenshot 2014-12-16 12 04 37](https://cloud.githubusercontent.com/assets/59882/5445794/e79ee828-851b-11e4-924b-654ea74a95a0.png)

if i clear this last item, it will disappear (looks like an ajax call), the inbox is empty but the the count on the icon still reads 1. 

![screenshot 2014-12-16 12 04 51](https://cloud.githubusercontent.com/assets/59882/5445845/5ea3db86-851c-11e4-9510-7ecf733a1dc3.png)

If I refresh the page I'm back to where I started.

![screenshot 2014-12-16 12 04 37](https://cloud.githubusercontent.com/assets/59882/5445794/e79ee828-851b-11e4-924b-654ea74a95a0.png)

**Comment by denjello** [comment]
Again, how has this been rewritten in 1.0? A backport of angular logic would be a good fix, no?

**Comment by gdpelican** [comment]
This should be resolved with Rob's recent thread sequencing work. Happy to reopen if it crops up again.
