### ISSUE TITLE
Some avatar images are broken in "Yesterday on Loomio" email

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#1807]
I can't post a screenshot of the example I have because it contains confidential info, but about half the avatar images of users in the Yesterday on Loomio email are coming up as broken image links.

**Comment by denjello** [comment]
If this hasn't been fixed, can you please take screenshot and photoshop/gimp out the confidential stuff?

**Comment by s01us** [comment]
I'm picking this up

**Comment by s01us** [comment]
here's an example I'm working with : 
https://ci4.googleusercontent.com/proxy/fbbM_zT3BKYpOrA6qtF_K6UPrUMljiSnb-alNi7UkftPq3aIKKBQue9vadzA54uohNwKj7tXhrQ6B2qD4qW0CJDocG8r7SSrKfHP8qrqqXVlxiBDSb4CUrgFlZQnu5qdgrD2bBNSyr36kRTopgtd6kUhzn4ism0LTJKZD9G7pPL13P6-fL6cue5v3i_yMGI=s0-d-e1-ft#https://loomio-attachments.s3.amazonaws.com/users/uploaded_avatars/000/000/007/medium/Rich_portrait_square.jpg?1401915900
![](https://ci4.googleusercontent.com/proxy/fbbM_zT3BKYpOrA6qtF_K6UPrUMljiSnb-alNi7UkftPq3aIKKBQue9vadzA54uohNwKj7tXhrQ6B2qD4qW0CJDocG8r7SSrKfHP8qrqqXVlxiBDSb4CUrgFlZQnu5qdgrD2bBNSyr36kRTopgtd6kUhzn4ism0LTJKZD9G7pPL13P6-fL6cue5v3i_yMGI=s0-d-e1-ft#https://loomio-attachments.s3.amazonaws.com/users/uploaded_avatars/000/000/007/medium/Rich_portrait_square.jpg?1401915900)

vesus


![](https://ci6.googleusercontent.com/proxy/bTvTgp4tvgH7TVotD949S4IeyLWNbnkpqosxv_FJ4-wxZAGN-pFYpSN9zHHf4SM0i8t2n0S7q12DxpzJ6lpdBhSO5qiRNtgJ72F9USW_ZQ=s0-d-e1-ft#http://www.loomio.org/uploaded_avatars/medium/missing.png)
https://ci6.googleusercontent.com/proxy/bTvTgp4tvgH7TVotD949S4IeyLWNbnkpqosxv_FJ4-wxZAGN-pFYpSN9zHHf4SM0i8t2n0S7q12DxpzJ6lpdBhSO5qiRNtgJ72F9USW_ZQ=s0-d-e1-ft#http://www.loomio.org/uploaded_avatars/medium/missing.png

**Comment by s01us** [comment]
NAILED it 

this will be auto-closed when that pull request merges

**Comment by gdpelican** [comment]
#2726
