### ISSUE TITLE
Invite all members of parent group

### ISSUE THREAD

**Issue by bennidi** [loomio/loomio#1821]
Hi there,
first of all, I need to say that I am very grateful you guys are building this amazing tool. When I was looking for something to use as a primary decision tool for the non-profit I am planning to found, I almost could not believe the luck of finding Loomio. It's almost a perfect match.

There is just one small feature missing that I feel would be very easy to add: When I create a sub-group I would like to have an easy way to have all members of the parent group be added as members of the sub group.

I have seen that the invite members dialogue already contains a user directory of members if the group has a parent group. If there were a select all members option, this would already to the trick. Another possibility would be to include an `invite members of parent group to this group` option during the creation of the sub-group.

In my case I would almost always need all members of the parent group to be added as members of the sub group because our organizations "constitution" requires participation of all members for decisions to be legitimate.

I would have a go myself and create a PR but I am so swamped with work on my project and I am a Ruby newbie, so I feel that me having a go would not be very efficient.

**Comment by denjello** [comment]
If this is not an issue it should be closed.

**Comment by gdpelican** [comment]
Closing as this is a 1.0 feature that been developed.
