### ISSUE TITLE
Inbox showing incorrect unread count

### ISSUE THREAD

**Issue by alannaloomio** [loomio/loomio#1822]
![screen shot 2014-12-28 at 2 07 28 pm](https://cloud.githubusercontent.com/assets/5498878/5562725/f1937640-8e9a-11e4-8313-025707d7748e.png)

Shows 2 unread notifications, but there's only unread item.

**Comment by gdpelican** [comment]
Would super-love someone to take a closer look at this if there's interest; I have a feeling this is a problem that will extend to Loomio 1.0 if we leave it alone. :rabbit2:

**Comment by joshuavial** [comment]
@gdpelican @HSalmon any tips on which part of the code to look at to fix this? Also would you be able to get me a data snapshot of the relevant tables to the comments in https://www.loomio.org/d/M6jguqEy/craftworks-service-idea-code-quality-insert-flash-name

Happy to help fix.

**Comment by gdpelican** [comment]
`inbox_controller.rb#size` and `inbox_controller.rb#load_inbox` would be the right place to start.

At first glance, it looks like size is loaded like this:
```
    size = Queries::VisibleDiscussions.new(groups: current_user.inbox_groups, user: current_user).unread.count

```

While individual groups on the inbox page are loaded like this:
```
    Queries::VisibleDiscussions.
      new(user: @user, groups: group_or_groups).
      unread.
      last_comment_after(3.months.ago).
      includes(:group).
      order_by_latest_comment.readonly(false).limit(100)
```

Which seems like that `last_comment_after(3.months.ago)` might be a cause for concern. (Just a guess, though)

**Comment by gdpelican** [comment]
Also related to this bit of code is #1805, which I know heavy inbox users like yourself would love to see fixed as well. :santa:

**Comment by gdpelican** [comment]
I believe Rob's grabbing this one as part of the read items revamp.

**Comment by robguthrie** [comment]
Sure am.

**Comment by gdpelican** [comment]
This should be fixed with the new salient item goodness.

**Comment by robguthrie** [comment]
correction.. it should already be fixed. fine that it's closed. should be reopened if we can fix more cases of it.
