### ISSUE TITLE
urls with @ character in them breaks in loomio

### ISSUE THREAD

**Issue by pravi** [loomio/loomio#1827]
I could not post this url -> https://medium.com/@hansdezwart/ai-weiwei-is-living-in-our-future-474e5dd15e4f even with markdown formatting for links 

Finally I had to use a url shortening service http://is.gd/TAftGv

**Comment by elimisteve** [comment]
@pravi You couldn't post a _comment_ on Loomio that included a URL with an `@` character in it?  What error did you get?  Or if the comment posted fine but is malformatted, can you link to that comment?   Thanks.

**Comment by pravi** [comment]
formatting is messed up and link is broken. See
https://www.loomio.org/d/Rrz47ytl/campaign-website

**Comment by denjello** [comment]
This was reported here: loomio/loomio/issues/1678

**Comment by robguthrie** [comment]
Seems like this is not a problem in angular
