### ISSUE TITLE
Create subgroup button is not disabled once clicked #angular

### ISSUE THREAD

**Issue by borisrorsvort** [loomio/loomio#1832]
It happens in the angular version. 
This leads to multiple subgroup creation when users click multiple time before the subgroup is created.
![screen shot 2015-01-08 at 2 00 37 pm](https://cloud.githubusercontent.com/assets/39081/5662870/0f016e2e-973f-11e4-8cbc-843ff32c3d27.png)

**Comment by gdpelican** [comment]
Thanks for making a note of this; we'll patch it up.
