### ISSUE TITLE
Dropdown closes when focusing on search field

### ISSUE THREAD

**Issue by borisrorsvort** [loomio/loomio#1833]
When you click on the search field to search it closes the dropdown
![screen shot 2015-01-09 at 9 26 22 am](https://cloud.githubusercontent.com/assets/39081/5677111/e45ba3bc-97e1-11e4-8069-04ab7e9c21fc.png)

**Comment by gdpelican** [comment]
This has been fixed and will be released soon. I'll close after it's pushed.
