### ISSUE TITLE
memberships API endpoint only lists first 5 users

### ISSUE THREAD

**Issue by yourcelf** [loomio/loomio#1838]
The API endpoint at ``/api/v1/memberships?group_id=<id>`` limits the returned results to [5 users](https://github.com/loomio/loomio/blob/51c799a239e7be5e26f1fae8217a7d54a067d25e/app/controllers/api/memberships_controller.rb#L7) (presumably because it was originally written just to support autocomplete?). This breaks the angular memberships display (go to https://www.loomio.org/angular and click "Show More" under members), as well as limiting utility of the endpoint for 3rd party integrations.

Is it safe to simply remove the "limit: 5" from the API call?  Or would this break an autocomplete or some such elsewhere?

**Comment by gdpelican** [comment]
Thanks for pointing that out! Seems like a simple oversight; we should be accepting a limit query parameter for queries like that.

**Comment by robguthrie** [comment]
Thanks for bringing this up @yourcelf. We've been talking about how to solve this problem for all API endpoints. Our thinking goes like this:

Common default page size, maybe 100 items.
Common way of including pagination metadata in response: https://github.com/davidcelis/api-pagination looks pretty good.
Common way of specifying alternative page size and page. - Same as kaminari.

What do you think?

**Comment by gdpelican** [comment]
We've just merged in a nice upgrade to our pagination API, which will allow us some more fine-grained control over pagination in the future. Closing this for now.
