### ISSUE TITLE
If a user is just a member of a subgroup, their group is not visible on dashboard

### ISSUE THREAD

**Issue by HSalmon** [loomio/loomio#1847]
![screen shot 2015-01-24 at 3 38 19 pm](https://cloud.githubusercontent.com/assets/2882097/5885835/0efc6e2c-a3df-11e4-8b03-ac8f63f657f6.png)

**Comment by HSalmon** [comment]
![screen shot 2015-01-24 at 3 40 39 pm](https://cloud.githubusercontent.com/assets/2882097/5885848/643a44b8-a3df-11e4-8727-921ee3f08320.png)

**Comment by robguthrie** [comment]
Ooooohhh. Thanks, now I get it.
