### ISSUE TITLE
Hand Icons

### ISSUE THREAD

**Issue by denjello** [loomio/loomio#1849]
Although I am pretty impressed with the interface for the most part, I feel that the hand symbols symbolizing "your position"-- are not as highly polished as the rest of the platform. It seems that the hand icons with inset drop shadows & highlights and rather dubious colour-choices appear to be slated for replacement with flat png icons as can be found in the `app/assets/images/1.0` folder. This is definitely a step forward, but it still makes me kind of wonder why it wasn't decided just to use http://fortawesome.github.io/Font-Awesome/icon/thumbs-up/ because that will at least scale nicely on a retina display. (And is exactly the same icon...)

But this all got me thinking about the voting we do in our organization, and we NEVER use thumbs up or thumbs down when building consensus within the group. (Maybe we aren't hipster enough.)

We are more likely to use hand signals like these:

Agreement
![sign_04_agreement](https://cloud.githubusercontent.com/assets/6129121/5890592/ea05aa82-a462-11e4-91ff-a42350e77849.png)

Disagreement
![sign_05_disagreement](https://cloud.githubusercontent.com/assets/6129121/5890593/efb92576-a462-11e4-82c3-7ac00ef9b184.png)

Veto
![sign_06_veto](https://cloud.githubusercontent.com/assets/6129121/5890594/f3665702-a462-11e4-9ef9-afa8c0e3e8f7.png)

These are from a colleague Martin Mueller in Berlin, who I am sure would be proud to see them used again. 
[ his website: http://183off.com ]

Here is a page with English descriptions and all the images.
https://occupyconcepts.org/wiki/General_Assembly

A German page with higher quality images:
https://diskussionshandzeichen.wordpress.com/materialdownloads/

And this is what it could look like:
![newicons](https://cloud.githubusercontent.com/assets/6129121/5891348/613e14c2-a490-11e4-9b07-61eaa5f9e95b.png)

**Comment by rdbartlett** [comment]
Interesting! Thanks for this @denjello :)

I think it is fair to say there has never really been a concerted effort on the graphical elements of Loomio. The images you see in the images/1.0 folder are just rough slices that we exported from Sketch (the software we're using for making design mockups). I think of them as placeholders.

Ideally, I'd like us to collaborate with some graphic designers to come up with an overall identity for Loomio that ties together some/all of these concepts into a coherent visual vocabulary, right from the "marketing" site, right down to the critical UI elements of the app:

* 'loom' as in 'a tool for weaving textiles'
* 'thread' as in textiles, and as in discussion thread
* 'lum' as in 'illuminate'
* something better than a pie chart
* new iconography for the voting buttons

Regarding the images you've shared, I love the social context that they refer to, but they don't feel "iconic" to me. I would be interested to see the concept refined and stylised, e.g. what might a clear 16px version look like?

**Comment by gdpelican** [comment]
Hey @denjello,

I think this is a matter worthy of debate, which means we should move this conversation to the feature ideas thread on Loomio, since this isn't really a code issue: https://www.loomio.org/g/GN7EFQTK/loomio-community-feature-ideas
