### ISSUE TITLE
Profile Page shows Active User Avatar for Thumbnail of both Gravatar and Image

### ISSUE THREAD

**Issue by denjello** [loomio/loomio#1850]
This is a bit disconcerting. Whichever Profile image is currently being used (Gravatar or Uploaded Image), the thumbnail of the active image is shown as the thumbnail for both gravatar and uploaded image. Here is a gif to show the issue. (The triangle thingy is my gravatar, the other one is asciiart in retroterm that I uploaded to the local filesystem.) Furthermore, it appears that the string "Use Gravatar" has not been translated into Esperanto or any other language yet...

![bildo](https://cloud.githubusercontent.com/assets/6129121/5891228/4363626a-a489-11e4-8f04-1a37a3fbcdee.gif)

**Comment by gdpelican** [comment]
This is a pretty easy win for any open source contributor that wanted to pick it up, I think.

**Comment by denjello** [comment]
Pretty easy fix (only found it because some intelligent crew actually wrote specs!!!)

In `/app/models/user.rb` the avatar_url actually expects two args, but only one was provided by `/app/views/base/_avatar.html.haml`.

## /app/models/user.rb ##
```
was:
  def avatar_url(size=nil)

should be:  
  def avatar_url(size=nil,avatar_kind)
```

## /app/views/base/_avatar.html.haml ##
```
was
      = image_tag user.avatar_url(size)

should be
      = image_tag user.avatar_url(size,kind)

```
What do I win?

**Comment by gdpelican** [comment]
You win an opportunity to submit a successful pull request!

'Rewritten in 1.0' means that this change won't make it into the new Loomio 1.0 interface (www.loomio.org/angular), since we'll be revamping the user page (along with many, many other things)
