### ISSUE TITLE
Switch AWS Attachment Upload to SHA256

### ISSUE THREAD

**Issue by denjello** [loomio/loomio#1852]
"Amazon S3 supports Signature Version 4, a protocol for authenticating inbound API requests to AWS services, in all AWS regions. At this time, existing AWS regions continue to support the previous protocol, Signature Version 2. **Any new regions after January 30, 2014 will support only Signature Version 4 and therefore all requests to those regions must be made with Signature Version 4.**" (My emphasis)

As far as I could tell, the main difference here is that Version 4 uses sha256, not sha1. I believe, for example, that this would be a show-stopper for users of the Frankfurt S3 service. Because I do not use Amazon services, there is no efficient way for me to test this. I did however switch     `OpenSSL::Digest.new('sha1')` to `OpenSSL::Digest.new('sha256')` without my installation of loomio complaining.

Of course sha256 is [a bit slower](http://crypto.stackexchange.com/questions/15382/hmac-sha1-vs-hmac-sha256), but remaining compliant with all AWS regions must be integral for a project like loomio that has made the decision to store assets there.

Here is the relevant code [ `/app/helpers/upload_helper.rb` ]
```
    def signature
      Base64.encode64(
        OpenSSL::HMAC.digest(
          OpenSSL::Digest.new('sha1'),
          @options[:aws_secret_access_key] || "", policy
        )
      ).gsub("\n", "")
    end
```

**Comment by denjello** [comment]
V2:  http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingHTTPPOST.html
V4:  http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-post-example.html

**Comment by denjello** [comment]
And there might be a **GPL3 violation** here, because OpenSSL is not GPL compliant as described by https://www.gnu.org/licenses/license-list.html#OpenSSL

```
The license of OpenSSL is a conjunction of two licenses, one of them
being the license of SSLeay. You must follow both. The combination
results in a copyleft free software license that is incompatible with the 
GNU GPL. It also has an advertising clause like the original BSD license 
and the Apache 1 license.
```
http://openssl.org/source/license.html

**Comment by robguthrie** [comment]
Thanks for this @denjello. Is changing sha1 to sha256 the only thing we have to change? I feel like we might need to indicate that we're using a version 4 signature somehow.

**Comment by denjello** [comment]
@robguthrie It looks like you're right. For example the following is a valid request for an image post on v4 (note e.g. x-amz-algorithm)

```
{ "expiration": "2013-08-06T12:00:00.000Z",
  "conditions": [
    {"bucket": "examplebucket"},
    ["starts-with", "$key", "user/user1/"],
    {"acl": "public-read"},
    {"success_action_redirect": "http://acl6.s3.amazonaws.com/successful_upload.html"},
    ["starts-with", "$Content-Type", "image/"],
    {"x-amz-meta-uuid": "14365123651274"},
    ["starts-with", "$x-amz-meta-tag", ""],

    {"x-amz-credential": "AKIAIOSFODNN7EXAMPLE/20130806/us-east-1/s3/aws4_request"},
    {"x-amz-algorithm": "AWS4-HMAC-SHA256"},
    {"x-amz-date": "20130806T000000Z" }
  ]
}
```
