### ISSUE TITLE
use_gravatar Naming Error in locales

### ISSUE THREAD

**Issue by denjello** [loomio/loomio#1853]
How did no one ever see this?
```
    /config/locales/en.yml
    use_gravtar: 'Use Gravatar'

    /config/locales/de.yml
    use_gravtar: Gravatar benutzen


```

**Comment by gdpelican** [comment]
Good catch!

@s01us, what's the best way to update a translation key without losing the
translations?

How did no one ever see this?

    /config/locales/en.yml
    use_gravtar: 'Use Gravatar'

    /config/locales/de.yml
    use_gravtar: Gravatar benutzen



—
Reply to this email directly or view it on GitHub
<https://github.com/loomio/loomio/issues/1853>.

**Comment by s01us** [comment]
Oh no. I think this was my doing. ironically i was making this more
translatable but uses a typo.

Changing keys is a pain, you would have to edit transifex. My suggestions
are we can either eat the typo (add a line to deal with it), or just
correct the key and it will have to be translated by everyone again.

**Comment by gdpelican** [comment]
Hm. I think this particular bit of code is a little gnarly to jam a typo into; I don't have a great sense for how much of an ask it is to have that string translated again across languages, but I think I prefer that approach.

**Comment by denjello** [comment]
This is on the transifex website:

As long as your source file is accessible from a public URL, such as [this raw file](https://github.com/transifex/txc/raw/master/transifex/locale/en/LC_MESSAGES/django.po) on GitHub, Transifex will periodically check the URL for updates. You can also use a file from a private repo in Github as long as the URL has the respective token that Github provides. If there are updates in the file, Transifex automatically fetches the file and updates your content.

You can find this option under Project Details → Resources → Auto-update Resources.

It is important to note this solution depends on Transifex polling for updates. As a result, there will a delay between the moment you update your file and Transifex picking up the changes. If you would rather update your content in Transifex as soon as your files change, use the client or API instead.

Here’s how differences in the content will be handled:

    New strings will be added
    Modified strings will be considered as new ones and added
    Strings that are not in the new source file (including ones which have been modified) will be removed along with their translations.
