### ISSUE TITLE
Too many Issues

### ISSUE THREAD

**Issue by denjello** [loomio/loomio#1857]
You may have noticed that I just commented on almost every single issue that is still open. (Nice job @mhjb for closing several of yours!). I couldn't believe that there were over 60 issues still open. In my opinion this is not exactly what is meant by tending to your digital garden - especially because some of the issues even make reference to versions of Ruby that are no longer being used in the Master branch.

All the same, it was an informative experience because many of the issues that continue to crop up can really be boiled down to a very few areas that need focused attention:

1. Links in Markdown-ified comments
2. User Profile incl. visibility from `@mentions`
3. Mail System
4. Voter Counting & Reporting
5. Cross-browser Issues

Once the repo gets below 10 open issues I will close this issue and throw an internet party.

**Comment by gdpelican** [comment]
Hi @denjello: You're likely right that some of these issues are closeable, but hopefully you can understand that triaging every single issue we've ever opened isn't very high on our list of priorities at the moment. I can poke through a few of these and close them, but closing an issue without testing it thoroughly and proving to myself (and probably others) that it's fixed is something I'm not willing to do - for many of these, testing them is a time-consuming process which yields very little payoff.

I appreciate the enthusiasm, but please don't cause more work for us! :octopus:

**Comment by denjello** [comment]
Sorry - didn't want to seem heavy-handed there. I found several duplicates among the issues and where I thought my input might make a difference, I made a comment or a suggestion. Furthermore, and as a result of my diligence, I am now going to be notified on every change to these issues - which I see as a good thing for a number of reasons.

Reading through the issues is a great experience in knowing where the breaking points are and really understanding the limits of a system that I intend on installing and managing. This way I am prepared to maintain a community of 200+ users. Consider it thusly: I was just doing my homework. By asking the Issue Reporter if it the problem is still an issue (especially on those issues where there was not a single reply) I was asking them to own their issues - which should ultimately lead to more quality pull requests.

**Comment by gdpelican** [comment]
Cool, thanks so much @denjello!

**Comment by s01us** [comment]
Wow @denjell I love your commitment and totally appreciate you taking the
time to analyse the list for trends.

One of the things I'd love to open source sometime (when we have resource
to do good communication around it) is how we are resourcing this core work
of coordinating everything code. We're doing our best to keep up with
building and supporting on literally a shoestring budget.

Thanks again for your support and contribution to date, you rock :)

**Comment by s01us** [comment]
Edit * @denjello (no autocomplete in email!)
