### ISSUE TITLE
[UI] Text in form fields is cropped

### ISSUE THREAD

**Issue by denjello** [loomio/loomio#1860]
In some form input type=text fields like login the text is cropped.

![croppedlogin](https://cloud.githubusercontent.com/assets/6129121/5987893/51636052-a945-11e4-8f07-9ec3d2a35cc3.png)

Screenshot from Debian > Firefox > 35.0.1

The same effect is present on Android > Firefox, but does not appear to be happening either in Debian > Chrome > 40.0.2214.91 or Android > Chrome

**Comment by robguthrie** [comment]
jsut tested in latest firefox and not a problem anymore
