### ISSUE TITLE
use group.full_name in "added to group" email notification rather than group.name

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#1865]
![screen_shot_2014-12-29_at_9 34 26_pm](https://cloud.githubusercontent.com/assets/970124/6012869/5017b10c-abb2-11e4-9d68-54be8542e220.png)

**Comment by gdpelican** [comment]
This is a cookie for someone; swap out `name` for `full_name` in `user_mailer.rb#added_to_group`, write a little test in `user_mailer_spec.rb`, and you'll have yourself a pull request.

**Comment by s01us** [comment]
we're picking this up WOOP

**Comment by gdpelican** [comment]
Hold fire! There's already a PR in for this. #1906

**Comment by s01us** [comment]
too late. 
would be good for us to have a process where people clearly pick up issues ... 
D:

also, ours hits the described case, which is invited_to_group  #1907

**Comment by s01us** [comment]
also, there's this nice feature we could use : 
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by gdpelican** [comment]
Can you guys please be more careful about investigating what's open before you start a feature? There was a pull request ready to merge for this issue (which is clearly marked on the issue itself), from a new contributor.

I'm going to merge theirs in, then deal with the merge conflict before merging yours.
