### ISSUE TITLE
group.motion_count and group.discussion_count are inaccurate

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#1867]
I don't have 100% clear idea of what is going wrong here. E.g. on production, `Group.find(16230).discussions_count = -8` but `Discussion.where(group_id: 16230).count = 0`. I am guessing this has something to do with the delete/archive actions not updating the counts correctly. 

This is how the counts should work:

* counts should update correctly on create and archive
* archived discussions and motions attached to archived discussions should not be counted (maybe you need to use the `.published` scope?)
* organisation_discussions_count and organisation_motions_count should ignore archived subgroups
* group.discussion_count and group.motion_count should exclude auto-generated content i.e. `where('author_id != 5562')`
* all of this should be tested

@robguthrie does this sound like a fair set of requirements?

**Comment by robguthrie** [comment]
Yep. sounds right. Only published stuff should be counted.. but I wonder if
there are places in the system where we want to know counts of everything..
I can't think of any cases like that though.

**Comment by robguthrie** [comment]
closing.. we've decided that anything using a rails counter cache should be considered inaccurate. We have manually built counter caches that are ok.. but these are to be disregarded
