### ISSUE TITLE
Require passwords to be sufficiently complex

### ISSUE THREAD

**Issue by jakub-** [loomio/loomio#1872]
Right now it looks like you can sign up with any password, including an empty one (in which case you won't be able to subsequently sign in... fun times!). I think a certain degree of complexity should be required.

There are off-the-shelf gems that make this very easy  such as [devise_security_extension](https://github.com/phatworx/devise_security_extension).

**Comment by denjello** [comment]
I think that is a great idea - and probably helps to resolve [this trello card](https://trello.com/c/JysuTj4o/343-do-something-about-spam).

**Comment by jakub-** [comment]
FYI, I will do this, just filing for the record. :)

**Comment by denjello** [comment]
adding a the required flag to the registration form input field for password might also help.

`required='required'`

**Comment by robguthrie** [comment]
This article is really great: http://blog.codinghorror.com/the-god-login/

restricting passwords to being a minimum length, and not in top 10,000 words seem like reasonable restrictions. 

I'll just say that I cannot stand rules about including particular characters etc - eg requiring a number or uppercase etc.

**Comment by gdpelican** [comment]
+1 to avoiding stupid password rules.

**Comment by denjello** [comment]
This is also a great resource: https://passfault.appspot.com/password_strength.html

For your reference, I just created a [gist with the 10000 most commons from 2014](https://gist.github.com/denjello/7e1c70ea77f3b9c6c711)

**Comment by denjello** [comment]
And here is a shortened one using `awk 'length($0)>=8' 10000.txt > 2000.txt` because if the first check is `at least 8 characters long`: 
https://gist.github.com/denjello/d326051a643aa8521660

**Comment by robguthrie** [comment]
Cool. I think the next most effective and least annoying thing we can do is
ensure that we have good rate limiting.

**Comment by jakub-** [comment]
I think blacklisting that particular list is a great start and an improvement over what we have now but it would be nice to scale this solution beyond the Anglophone world. :)

Certainly +1 to avoiding annoying password rules.

**Comment by robguthrie** [comment]
Just to be clear, the suggestion was to include a list of top 10,000 passwords (I don't know how it was collected, possibly from english websites), not english words.

See https://github.com/discourse/discourse/blob/master/lib/common_passwords/10k-common-passwords.txt

**Comment by jakub-** [comment]
@robguthrie The point still stands, though, that the more generic password strength validators (like the one from Dropbox) would be language-agnostic. Looking through this list it's definitely skewed towards English-speaking websites. I think that's fine for now, though. :-)

**Comment by rdbartlett** [comment]
It's probably fair to guess that password crackers will also be skewed
towards English words.

On 8 February 2015 at 10:41, Jakub <notifications@github.com> wrote:

> @robguthrie <https://github.com/robguthrie> The point still stands,
> though, that the more generic password strength validators (like the one
> from Dropbox) would be language-agnostic. Looking through this list it's
> definitely skewed towards English-speaking websites. I think that's fine
> for now, though. :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/loomio/loomio/issues/1872#issuecomment-73384533>.
>



-- 

Richard D. Bartlett
Loomio co-founder
rich@loomio.org

<http://loomio.org/>
