### ISSUE TITLE
rake jobs:work not being called in non-heroku production

### ISSUE THREAD

**Issue by denjello** [loomio/loomio#1880]
To recreate this issue, install a production server that is not hosted at Heroku. Mails will not be sent. The workaround I used to go live was:

```
$ cd %projectdir
$ bundle exec rake jobs:work RAILS_ENV="production" & disown
```
Of course the problem is that if the VM / Server crashes, this needs to be done by hand. It would probably be better to have this run at INIT while spinning up the system, but I am open to suggestions.

I understand that this is because Heroku charges separately for worker threads, however in my opinionated version of the Open Source Universe, this type of behaviour should rather be an "opt-in".

**Comment by gdpelican** [comment]
I believe this type of command should go in a deploy script (like Capistrano's `deploy.rb`)

The loomio codebase has a `deploy.rb`, although it looks like it hasn't been used in eons (it still has Loomio's super-sekrit original name in it, and the old enspiral git address)

Maybe sprucing that up and deploying with it (and sending us a copy of what you ended up with) would be immensely useful? :gem:

**Comment by robguthrie** [comment]
I would advise against using Capistrano. It's not something I want to support people with.

The dokku based approach, that I've [documented in the wiki](https://github.com/loomio/loomio/wiki/Install-Dokku), follows the [12 factor](http://12factor.net/) design. 

This method of deploying Loomio will take notice of the Procfile and start the workers for you when you deploy your app.

**Comment by gdpelican** [comment]
:+1:

**Comment by denjello** [comment]
For the record this was a pain. I tried using `disown` to no avail. As soon as I closed my shell connection to the server the process still died. `nohup` didn't work either. This is what I ended up using:

```
echo '#!/bin/sh
# execRake.sh
cd ~/loomio
bundle exec rake jobs:work RAILS_ENV="production"' > execRake.sh

```

And then I called it thusly:

`ssh $user@$site '/home/$user/execRake.sh </dev/null >/dev/null 2>&1 &' `

Still a pain, but because we are live I needed a quick solution. I think a more proper way would be to:

0. use a cron job to run the following script once every 10 minutes
1. is there a PID of the exec rake in /home/$user/execRake.pid and if so is that PID still active?
2. if not, start the exec rake with nohup and background it (so we still get access to the log)
3. immediately register the new PID in /home/$user/execRake.pid
4. exit the script
