### ISSUE TITLE
Search Results in Beta have unparsed markdown.

### ISSUE THREAD

**Issue by denjello** [loomio/loomio#1881]
![search](https://cloud.githubusercontent.com/assets/6129121/6107171/983587a6-b068-11e4-9709-052d0726a6c0.png)

I see that this is not really the case in 1.0 - but think that whatever is shown should be parsed correctly and Beta is still going to be around for a while...

Here is my solution in `app/views/searches/_discussion_line_item.html.haml`
```
      %span.description= truncate(render_rich_text(item.description,item.uses_markdown), length: 180, omission: '...', separator: " ", :escape => false) unless item.description.blank?
```

**Comment by denjello** [comment]
And this is what the above solution parses out to:

![wow](https://cloud.githubusercontent.com/assets/6129121/6108729/b83e9c56-b075-11e4-8358-dfc569d5be88.png)

**Comment by marceloboeira** [comment]
length will remain "hard-coded" ?

**Comment by robguthrie** [comment]
I think I'm happy to merge this. Is it ready to go?

**Comment by gdpelican** [comment]
I think it's a good solution as well, but it'd be good to have a branch and a PR with the suggested solution in it so we can take a peek and merge it.

As a nice-to-have, it'd be cool to separate that view logic out into a helper so it could be reused in other places if we needed it. `render_truncated_markdown(text, length)` or something.

**Comment by denjello** [comment]
@marceloboeira > The fixed length was the way it was, and honestly I don't think it matters much. At the same time, it should be pretty easy to add what @gdpelican suggested - however my timebudget for loomio has been used up for February.
