### ISSUE TITLE
User id in atom feed entries

### ISSUE THREAD

**Issue by simontegg** [loomio/loomio#1884]
[Assembl](http://assembl.org/) are importing loomio discussions into their app using the atom feed.

They wish to have entries identified by user id (ideally a uri). Currently a feed entry looks like this:
```
...
    <author>
      <name>Simon Tegg</name>
    </author>
  </entry>
```
and they want:
```
...
    <author>
      <name>Simon Tegg</name>
      <uri> https://www.loomio.org/u/DEwK5FS0/simon-tegg</uri>
    </author>
  </entry>
```

Is the profile uri a property of  ```entry.author``` in  ```app/views/groups/show.xml.builder```? If it isn't what property should I use?

**Comment by robguthrie** [comment]
What you've suggested is fine.

**Comment by gdpelican** [comment]
:+1:

**Comment by simontegg** [comment]
comment wasn't formatted properly. edited.

**Comment by gdpelican** [comment]
What's the timeline on this, @simontegg?

**Comment by gdpelican** [comment]
Actually, I think I just fixed it. :snail:

**Comment by simontegg** [comment]
sweet. Ta
