### ISSUE TITLE
redirect subdomains

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#1892]
When I am on a group with a subdomain, and I visit a discussion from that group, the subdomain should be included in the discussion path. So far so good.

When I then visit a discussion from another group though, the subdomain should not be included.

i.e. https://internet-party.loomio.org/d/LuAlGpC3/introduce-yourself-to-the-loomio-community should redirect to https://www.loomio.org/d/LuAlGpC3/introduce-yourself-to-the-loomio-community

This bug means that Google is indexing the same discussion on multiple subdomains, which makes Loomio look like a spammy content farm.

**Comment by robguthrie** [comment]
resolved now.. subdomains are just redirects
