### ISSUE TITLE
Missed Yesterday email: headline improvements

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#1894]
Remove headline sentence structure, add avatars rather than names to indicate who's participating

**Comment by gdpelican** [comment]
Originally from #1565

**Comment by marceloboeira** [comment]
:+1:

**Comment by denjello** [comment]
Maybe we should retain names for those of us 'ahem' who only read plaintext emails in Pine and NEVER open single-pixel transparent tracking gifs.

**Comment by robguthrie** [comment]
Names should be in the alt text of the images.

The small but vocal plaintext email client users should implement the
plaintext version of the email, rather than trying to make the html version
meet both use cases.
