### ISSUE TITLE
Missed Yesterday email: Some avatars are missing

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#1895]
Originally from #1565

**Comment by robguthrie** [comment]
Still happening: 
![image](https://cloud.githubusercontent.com/assets/486367/11223557/719f22b4-8dd5-11e5-9e1f-ebcd26466fee.png)

In this case Joseph should have his initials showing.

**Comment by gdpelican** [comment]
I'm going to fix this. :ok:!

**Comment by gdpelican** [comment]
Fixed per #2726
