### ISSUE TITLE
[Translation] German string for "email" inconsistent

### ISSUE THREAD

**Issue by denjello** [loomio/loomio#1902]
I only noticed it after completing the German translation locale `de.yml` on transifex and used what I thought was appropriate. I would have changed all of the strings at transifex, but that didn't seem to be an option. (I have already done this on my production server.)

After discussing it with a number of colleagues from different industries, the translation for email in German is incorrect and the commonly accepted German version of the string is "E-Mail", not "eMail".

@s01us, what is the best way to resolve this?

**Comment by s01us** [comment]
I could find and replace in the yaml then upload to transifex to over-write
the transnation there i think.

Shall i go ahead and try that?

**Comment by denjello** [comment]
Yeah - that would rock. :+1:

**Comment by gdpelican** [comment]
This should be handled from the Transifex side, not the other way round. I'm fairly certain you can log into transifex and suggest an improvement from there for a particular translation. There's a guide to translating Loomio [here](https://www.loomio.org/d/hB1Oijwv/overview-of-the-translation-process-for-translators).

Closing as this isn't a code issue. :smile:
