### ISSUE TITLE
Cloudfare just threw a 400 Bad Request on a Discussion view.

### ISSUE THREAD

**Issue by denjello** [loomio/loomio#1911]
I have no idea why. This was at about 14:47 UMT+1

I was logged in and tried visiting this page:
https://www.loomio.org/d/L4XZ7bvB/live-translation-for-international-working

Solution:
All 400's should redirect to dashboard and log the error / flash a message instead of freezing and showing this error.

![400](https://cloud.githubusercontent.com/assets/6129121/6203424/ea7790aa-b521-11e4-9e07-6457ab0fc119.png)

I could not repeat this and have no further information about the event.

**Comment by gdpelican** [comment]
Without repro steps or further information this isn't worthy of being an issue. Closing for now.

**Comment by robguthrie** [comment]
That's useful to hear about. I have not seen that happen before. If it's just a once off then I'm happy for this to not be an issue, but am keen to hear about it if it happens regularly.

I've found that being behind Cloudflare is not totally perfect all the time, but I think it's a super valuable service.

**Comment by denjello** [comment]
I would actually leave this open and add some logic to redirect all 400 type server responses to the front page - whatever that is.

**Comment by robguthrie** [comment]
Sorry, but there is nothing we can do. The error came from Cloudflare. Happy to review any new information on it if you can find it, but I'm fairly confident that there is no setting within cloudflare to change 400 responses to redirects.

**Comment by denjello** [comment]
Not sure exactly how your live server is setup, but you could just drop this into your `.htaccess` ???

```
ErrorDocument 404 /
```

**Comment by robguthrie** [comment]
The request never reaches our server. Cloudflare is a service which sits in front of our servers. It returned the 400 before we ever saw it.

**Comment by robguthrie** [comment]
Check out http://cloudflare.com/

**Comment by rdbartlett** [comment]
FWIW one of our friends got this error over the weekend:

![image](https://cloud.githubusercontent.com/assets/970124/6204631/7db01848-b5b7-11e4-8cf5-03d9dff0eb8f.png)

**Comment by robguthrie** [comment]
Good to know. However I think this is all down to Cloudflare hiccups. Would love to hear from anyone with  more insight.
