### ISSUE TITLE
Authentication for private discussion atom feeds

### ISSUE THREAD

**Issue by simontegg** [loomio/loomio#1912]

**Comment by gdpelican** [comment]
Happy to put this in our backlog (it's definitely something we want to support), but we won't be able to implement this in the immediate future.

**Comment by simontegg** [comment]
great.

**Comment by swergas** [comment]
At the Catalyst consortium ( http://catalyst-fp7.eu/ ), we are trying to code collective intelligence tools which are as much interoperable as possible with other tools, and which integrate easily with other processes and websites. So we are very interested in interoperability standards, notably import/export formats. Atom feeds are very common on the internet and could be an interesting source to import data :).

Atom feeds are currently available on loomio for public discussions, but not for private discussions. How could we enable this? I see different possible solutions:
- Solution 1: give access to this Atom feed to logged in users who are members of the group. I guess this is the easiest solution, and would be totally fine four our own use cas. But we understand it may not be very useful in the most classic use cases (for example if the participant uses a feed reader tool)
- Solution 2: give access to this Atom feed if the URL has a parameter which is the API key of a participant. So you could use feed reader tools. I guess that we would have to enable it only if the loomio instance uses HTTPS
What do you think of this?

We do not know the Ruby programming language at all, but we have tried to implement solution 1, and we managed to make it work. You can find the patch below, could you please review it and tell us if there is a problem we did not see? Also, as this patch is simple and only removes some ifs, the question arises: for which reason has it initially been desactivated for private discussions?

Thanks in advance


diff --git a/app/views/discussions/show.xml.builder b/app/views/discussions/show.xml.builder
index 889f3db..0eade80 100644
--- a/app/views/discussions/show.xml.builder
+++ b/app/views/discussions/show.xml.builder
@@ -21,4 +21,4 @@ atom_feed do |feed|
       entry.link discussion_url(@discussion)
     end
   end
-end if @discussion.public?
+end
diff --git a/app/views/groups/show.xml.builder b/app/views/groups/show.xml.builder
index 7d480ee..1382595 100644
--- a/app/views/groups/show.xml.builder
+++ b/app/views/groups/show.xml.builder
@@ -14,4 +14,4 @@ atom_feed do |feed|
          end
     end
   end
-end if @group.is_visible_to_public?
+end

**Comment by gdpelican** [comment]
After some further research on this, the conclusion I'm hearing is that while private RSS feeds exist, they're not so common a thing, and that they're largely implemented with HTTP basic auth, which is kinda not good enough for me to consider sending private info out there.

Happy to hear further thoughts on the issue, but at the moment I'm thinking that if you want to syndicate your content via RSS, you'll have to make it public.
