### ISSUE TITLE
Wonky position formatting on dashboard

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#1913]
This seems to have been introduced recently:

![screenshot from 2015-02-16 17 42 45](https://cloud.githubusercontent.com/assets/750477/6207287/47a255b2-b603-11e4-95e0-3e6429400b5f.png)

Seems like a simple css fix for someone.

**Comment by rdbartlett** [comment]
Whoops did this get borked in #1871?

**Comment by gdpelican** [comment]
Looks like it.

This is the part where a one-armed man pops out of the bushes and yells "And that's why you don't just uncomment lines of code" :muscle:

**Comment by rdbartlett** [comment]
and the other guy is like 'this is why you namespace your css!'

On 16 February 2015 at 19:56, James Kiesel <notifications@github.com> wrote:

> Looks like it.
>
> This is the part where a one-armed man pops out of the bushes and yells
> "And that's why you don't just uncomment lines of code" [image: :muscle:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/loomio/loomio/issues/1913#issuecomment-74466786>.
>



-- 

Richard D. Bartlett
Loomio co-founder
rich@loomio.org

<http://loomio.org/>

**Comment by gdpelican** [comment]
I'll fix real quick.

**Comment by gdpelican** [comment]
So many one-armed men running around... :runner:
