### ISSUE TITLE
If you have Loomio's git repo checked out, you'll need to read this!

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#1926]
We've just done some cleanup work on the git history of the Loomio repo.

Previously the git repo for Loomio master branch was about 900 Megabytes, which is kinda nuts. So we've used some aggressive settings with bfg-repo-cleaner and slimmed master down to 22 MB.

What do you have to do as a result of this history butchery?

If you have loomio checked out, you'll need to run the following to correctly fetch the new master history into your existing repo.

```
# from your loomio git repo, master branch
git pull --rebase origin master
```

And if you have any branches, then I recommend you use github or git log to find the commit id's of your work, and cherry pick them into an new branch off master.

So for example, I've just cherry picked my work from a old branch called `item-indicator`

```
git co -b new-branch
git cherry-pick commitIdsOfMyWork # repeat this step for each of your commits you need to rescue
git commit -m "salvaging my work after loomio's slim down"
git br -D item-indicator #remove the old branch based on the old history
git br -m item-indicator #rename the new branch to the old name
git push origin item-indicator -f
```

Please don't hesitate to reach out to me in this thread to ask for help if you get stuck. 

I'm super sorry for any inconvenience I've caused you by doing this!

**Comment by rdbartlett** [comment]
Thank you baby jesus :godmode:

**Comment by gdpelican** [comment]
If you happen to have a commit running with several commits in it that you'd rather not cherry-pick, you can do the following:

```
gco my-feature-branch
gb -m my-feature-branch-old
git rebase origin/master -i # perform an ordinary rebase
git log # grab the squashed commit you just created
gco master
gco -b my-feature-branch # create a new feature branch off of master
git cherry-pick abcd1234 # the hash of the squash commit you created earlier
git push origin my-feature-branch -f
```
(Sorry for my mildly kludgy git instructions)

Thanks for bearing with us! This'll lower the barrier to entry for a lot of new developers to work on Loomio I think, and make your open source experience that much better. :balloon:
