### ISSUE TITLE
Verifying a user from an email link

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#1928]
A specific use case:

- A user clicks a link in an email from a loomio account (Account A) to follow a discussion
- That user is signed into a different loomio account (Account B), than the one the email was sent to
- The user lands on loomio.org, signed into Account B, but with a message saying that s/he is now following a discussion (even though s/he isn't.)

Basically, we need to come up  with some kind of strategy for handling auth from emails, be it forcing the user to sign into the account the email came from, or something else.

A relevant article: https://neosmart.net/blog/2015/using-hmac-signatures-to-avoid-database-writes/

Originally brought up in #1908

**Comment by robguthrie** [comment]
I want to ask if we should be spending more energy ensuring that users don't end up with two Loomio accounts, rather than trying to support it once they do.
