### ISSUE TITLE
Incorrect participation count on proposals where proposer explicitly states position

### ISSUE THREAD

**Issue by stadtwald** [loomio/loomio#1939]
I recently noticed that, under a new proposal I had created, that it had the count of "2/x" after I explicitly stated approval, but no one else had.

I suspect that is a bug caused by 1 always being added to the count, regardless of whether or not the proposer has explicitly stated their opinion.  I suggest adding 1 if and only if the proposer has not explicitly stated their opinion.

**Comment by robguthrie** [comment]
Thanks for this William, would you mind posting some relevant record id's so I can drive out the issue?

**Comment by stadtwald** [comment]
Sorry for the delayed response.  I can't seem to reproduce this bug anymore.

**Comment by robguthrie** [comment]
whooo hoo
