### ISSUE TITLE
Allow manual toggling of angular interface

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#1949]
We'd like to be able to have users be able to manually toggle on and off the new interface as they see fit

I imagine our requirements are something like this:

- If a user is logged in, they can visit `/angular/on`, which will redirect them to the angular interface (perhaps defaulting to the Loomio Community as a homepage for now.) This should set a user preference (an `angular_enabled` boolean on the User model), which allows them to receive the angular interface whenever they visit the site. This boolean should default to false for all users.
- If a user is logged in, they can visit `/angular/off`, which will set the boolean to false, meaning they see the normal beta interface when visiting the site.
- If a user is logged out and tries to perform either `/angular/on` or `/angular/off`, they are redirected to the sign in page with a 'You must be logged in to do this' message.
- `www.loomio.org/angular` should no longer function.

**Comment by gdpelican** [comment]
Feel free to jump in if those requirements seem off, @robguthrie

**Comment by robguthrie** [comment]
Looks good. Thanks

**Comment by s01us** [comment]
task breakdown: 

[ ] create boolean `angular_enabled` column on `User` table
[ ] create a switch in controller which checks whether user has `angular_enabled` AND drops user on loomio community page

(extra)
[ ] create 2 switching routes `/angular/on` & `/angular/off`
[ ] disable `/angular` route

**Comment by s01us** [comment]
WIP here https://github.com/loomio/loomio/pull/1955

**Comment by gdpelican** [comment]
This is merged and functional :exclamation:
