### ISSUE TITLE
is it just me or is the inbox borked?

### ISSUE THREAD

**Issue by denjello** [loomio/loomio#1951]
![inbox](https://cloud.githubusercontent.com/assets/6129121/6380487/47526690-bd3a-11e4-9e24-e466e0a37ca3.png)

**Comment by Yachtsman** [comment]
The same is here!

**Comment by robguthrie** [comment]
it's not just you. but it might be fixed now. Please let me know

**Comment by gdpelican** [comment]
Looks better to me.

**Comment by denjello** [comment]
that's how i am used to it.
