### ISSUE TITLE
Subgroup discussion visibility misrepresented on new discussion form

### ISSUE THREAD

**Issue by HSalmon** [loomio/loomio#1957]
When a subgroup's settings reflect that discussions should be visible to members of the group only (and not members of the parent), on the form for creating a new discussion in the subgroup you are told it will be visible to members of the subgroup, and the parent.

![screen shot 2015-03-01 at 11 58 21 am](https://cloud.githubusercontent.com/assets/2882097/6428542/cf672b9c-c00a-11e4-8305-676949403fa3.png)

![screen shot 2015-03-01 at 11 57 32 am](https://cloud.githubusercontent.com/assets/2882097/6428543/d8655d68-c00a-11e4-95d9-8521d629c9d0.png)

**Comment by HSalmon** [comment]
https://github.com/loomio/loomio/pull/1961

**Comment by gdpelican** [comment]
Sorry, the group privacy stuff always tweaks my brain a little bit for some reason.

Is this a problem with the functionality, or just the messaging?

**Comment by HSalmon** [comment]
Just the messaging @gdpelican
