### ISSUE TITLE
@mention broken on edge case

### ISSUE THREAD

**Issue by denjello** [loomio/loomio#1967]
If a user changes their username from `henrysmith` to `henry smith` then the @mention would look like `@henry smith` which is correctly offered by the autosuggest, however the space breaks the mention parser.

**Comment by gdpelican** [comment]
This fix is to disallow people updating their usernames to have whitespace in them, which is just asking for trouble.

**Comment by HSalmon** [comment]
https://github.com/loomio/loomio/pull/2006
