### ISSUE TITLE
default subdomain?

### ISSUE THREAD

**Issue by fauno** [loomio/loomio#1970]
hi!, we've finally setup loomio at the pirate party argentina[0] but some links are returning a bogus domain "com.ar".  i've traced it to the DEFAULT_SUBDOMAIN env var, which apparently assumes working domains have only two parts :)

anyway i've set the DEFAULT_SUBDOMAIN var to the missing part of the domain ("consenso.partidopirata") and it seemed to fix the urls, but now we're seeing that only some of them are.

for instance, visiting a group from the top nav bar is working again, but submitting a position on a propposal redirects to http://com.ar/ again.

is there a way to disable this behaviour entirely? or where should we look at?

[0]: https://consenso.partidopirata.com.ar

**Comment by robguthrie** [comment]
Hi fauno, You can set the TLD_LENGTH to tell rails how many parts are in
your domain name. The DEFAULT_SUBDOMAIN is usually "www" or blank - we use
it when we give groups their own subdomain eg: 'coolgroup.loomio.org' vs '
www.loomio.org'

**Comment by fauno** [comment]
Robert Guthrie <notifications@github.com> writes:

> Hi fauno, You can set the TLD_LENGTH to tell rails how many parts are in
> your domain name. The DEFAULT_SUBDOMAIN is usually "www" or blank - we use
> it when we give groups their own subdomain eg: 'coolgroup.loomio.org' vs '
> www.loomio.org'

tld_length = 3 seems to fix it, thanks!

-- 
http://utopia.partidopirata.com.ar/
