### ISSUE TITLE
Negative update counter bug

### ISSUE THREAD

**Issue by Tekarihoken** [loomio/loomio#1990]
For an unknown reason , I have a thread/discussion with its update counter starting to -1 instead of 0.

The behaviour is very strange : If I have no new update , it show the "update icon with -1 in it", if there is 1 update it do not show any icon, if there is 2 update it show the "update icon with 1 in it" etc...

**Comment by robguthrie** [comment]
Uh oh! @Tekarihoken is this on loomio.org or your own instance? If loomio.org, could you give me the discussion id and your user id?

**Comment by Tekarihoken** [comment]
It is on loomio.org, and my user is Tekarihoken (but it seems that other users have the same bug).
The url of the discussion is : https://www.loomio.org/d/a43tX6TJ/refonte-de-l-interface-reseau

**Comment by denjello** [comment]
Apparently this is still happening:

https://www.loomio.org/d/0x8kTUyO/number-of-comments-unread-in-a-discussion-with-negative-number

**Comment by rdbartlett** [comment]
Yep just had another report of this from charlie :(

**Comment by robguthrie** [comment]
@gdpelican I feel like this might somehow be related to the "discussion was delegated to x but something is nil" bugs where seeing. Sounds like deletion bombing out before cleanup is finished.

**Comment by robguthrie** [comment]
Had another report of this, first in a long time. I think the only way it can happen is through race condition now. I think just displaying anything less than 0 as 0 will be fine as a working hack fix.

**Comment by strypey** [comment]
I used to see the -1 frequently about a year and a half ago, and this recent occurance is the first time I've seen -1 for a long time. The work you've done on this is definitely paying off, and after a quick web search to see what "race conditions" are, that definitely sums it up :)

**Comment by robguthrie** [comment]
Anyone seen it recently?
