### ISSUE TITLE
markdown not converted into html in rss/atom feeds

### ISSUE THREAD

**Issue by gentilvirus** [loomio/loomio#2025]
markdown is currently not converted into html in the rss/atom feeds.
technically it is not a problem as markdown is just plain text but i have never seen any feed client that can handle markdown syntax natively this means that each and every client that wants to use the loomio feeds (to display on their web site, to import data in ther application, etc...) should detect, parse and convert markdown which is not the most efficient and convenient way of working especially since there are [20+ different implementations](http://commonmark.org/) of markdown according to what I understood.

shouldn't loomio convert markdown into html in the feeds (I guess it shouldn't require lot of work as markdown is already converted into html to be displayed in the web client or in the mails) ?

**Comment by raphaeljolivet** [comment]
Agree.

Having that would allow better integration of Loomio with other systems / social medias :
IFFFT can plug RSS feed to almost anything.

In the case you fix this, please only keep a single "content" tag, of type HTML :
I guess client might not like handling several content wih different types.

**Comment by robguthrie** [comment]
Yep. I agree, it should be converted into html. Feel free to make a pull
request. The method to markdown stuff is fairly simple.
