### ISSUE TITLE
default group logo broken

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#2039]
the default group logo (on the group page) is pointing to a resource that doesn't exist:
https://www.loomio.org/images/default-logo-medium.png

**Comment by baschtl** [comment]
@rdbartlett Is this still the case? When I look at https://www.loomio.org/g/CY61pwAE/llengues-d-arago-catala the default logo shows up.

**Comment by rdbartlett** [comment]
Thanks for checking in @baschtl - yep it is still broken for new groups.

**Comment by baschtl** [comment]
Ah, I was able to verify this locally. I will look into it.
