### ISSUE TITLE
Inbox showing discussions where the only new content is content I've created

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#2041]
![image](https://cloud.githubusercontent.com/assets/1380991/6816641/c06631b2-d2fa-11e4-8abd-2a917d0605f3.png)

**Comment by robguthrie** [comment]
That's a discussion thread! Thank you though, duely noted!

**Comment by mhjb** [comment]
O yeah, but it's a discussion thread visited from the inbox, where the blue
new content line is above material that I myself just wrote.
