### ISSUE TITLE
Opening old email notifications messes with inbox counts & read-to-here line

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#2079]
E.g. I read the discussion with the proposal "I've helped to connect OS//OS with my networks" and the discussions below it, so they disappeared from my inbox. Then I happened to look at an old notification email from Loomio, and revisit inbox, and the counts look like this: 
![image](https://cloud.githubusercontent.com/assets/1380991/6952565/5c64ce96-d91f-11e4-9269-30ec615bc105.png)

**Comment by robguthrie** [comment]
AMAZING! There must be a bug ... it's resetting your read counts.

**Comment by mhjb** [comment]
Fwiw this has happened since forever

**Comment by robguthrie** [comment]
Thanks @mhjb.
