### ISSUE TITLE
Error when trying to import contacts from Google

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#2115]
From ../invitations/new I click 'Google'
Google asks me to choose which account, I do.
I'm Returned to this page: https://www.loomio.org/contacts/gmail/callback?code=4/jaFBrcXjvVTxqot3bVX_7UOidlWZkJ-htkW4gFFhbXo.IpRl_Bo6RBIYgrKXntQAax3U8vKrmQI with: 
"We're sorry, but something went wrong.
We've been notified about this issue and we'll take a look at it shortly.
Return to your home page"

**Comment by gdpelican** [comment]
Closing as a beta issue which we won't spend time on... someday angular will have google contacts and everyone will get a unicorn as part of the UBI. :horse:
