### ISSUE TITLE
Markdown ruins some ordered lists with nested unordered lists 

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#2167]
![image](https://cloud.githubusercontent.com/assets/1380991/7692237/d901da6e-fe15-11e4-8637-a674f9473013.png)     --->     ![image](https://cloud.githubusercontent.com/assets/1380991/7692208/79bb5f62-fe15-11e4-8f34-6c076611766e.png)

**Comment by rdbartlett** [comment]
This is just how Markdown works. I would be sad if we put energy into overwriting Markdown instead of investing in a more accessible rich text editor.
