### ISSUE TITLE
Broken link on the wiki home page

### ISSUE THREAD

**Issue by zacharystenger** [loomio/loomio#2168]
The link to the [development process](https://github.com/loomio/loomio/wiki/2-Development-process) in the [Help develop the software](https://github.com/loomio/loomio/wiki#help-develop-the-software) section links to a page that has not been created.  I was wondering if it should link to the [Coding Style Guide Stuff](https://github.com/loomio/loomio/wiki/Coding-Style-Guide-Stuff)?

**Comment by gdpelican** [comment]
Thanks for the tip @zacharystenger!

Hm, I'm not sure that Coding Style Guide is the right place for that link to go; I'd think we probably want a `CONTRIBUTING.md` file somewhere that outlines the steps for making an open source contribution.

Does this file exist already somewhere @robguthrie? I'm thinking some amalgamation of 'How to clone + cut a branch' + https://github.com/loomio/loomio/wiki/How-to-squash

**Comment by robguthrie** [comment]
I agree. I want to move most of the core documentation into the source
code, it feels weird to have it just in github.
