### ISSUE TITLE
[Refactor]: Loomio attachments

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#2174]
Our current attachment system is a little inflexible, and married to S3, which is no good for a system that wants to be distributable.

Here's my current thinking on fixing that:

- :boom: the UploadHelper class; it's married to S3 and is a needlessly complex solution I think.
- add `has_attached_file :upload` to the Attachment class
- Figure out what fiddling needs to be done from there to get attachments to upload correctly through paperclip (instead of S3 directly)... I think it may just be a bit of parameter acro.
- (maybe?) Delegate the methods on avatar's upload so we don't have to worry about changing them everywhere
```
class Attachment
  has_attached_file :upload
  delegate :url, to: :upload, prefix: false
end
```
- Move hardcoded paperclip defaults out of application.rb and into development.rb / production.rb
  - For development, default to the local filesystem; no one wants to deal with buckets while they're devving.
  - For production, switch on an ENV variable to pick between config hashes for S3, local filesystem etc.

I'd be super keen to hear some feedback, or if there was anyone interested in hacking on this as a medium-sized project.

**Comment by robguthrie** [comment]
I was thinking that the attachment model should be used rather than has_attached_file. So a group would 

```
belong_to :background_image_attachment, class_name: 'Attachment'
```

So we just have one controller where attachments are uploaded, the attachments_controller and it returns an attachment id we can use. Then we will find that we can reuse the upload form code anywhere we like.

Attachments in proposals and discussions would be really easy then.

**Comment by robguthrie** [comment]
@gdpelican is this still relevant to you?

**Comment by gdpelican** [comment]
Nah, close it.

**Comment by gdpelican** [comment]
We'll be working on this in the near future.
