### ISSUE TITLE
Mime type/HTTP header for Content Type is not being set on attachment uploads

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#2187]
Attachments don't seem to catchup the Content Type given by the uploading browser, so attachments when downloaded from amazon have a blank content type and browsers are doing a bad job of guessing how to present them to the users.

**Comment by HSalmon** [comment]
Confirmed that this is still happening, would be good to save mime type when uploading.

@gdpelican, relevant to you...

**Comment by gdpelican** [comment]
I believe this is fixed in angular now.
