### ISSUE TITLE
No max-width on lists in notification emails

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#2222]
The email stylesheets specify max-width on most of the content, but ol's and ul's appear to have been overlooked:

![image](https://cloud.githubusercontent.com/assets/970124/8050319/2d81412e-0ebf-11e5-8b0f-226d586e4fde.png)

**Comment by robguthrie** [comment]
confirming this is still an issue

**Comment by rdbartlett** [comment]
@robguthrie will fix it!
