### ISSUE TITLE
Allow several suggestions for a given problem.

### ISSUE THREAD

**Issue by roipoussiere** [loomio/loomio#2224]
I'm just testing loomio and it seems that we can't propose 2 solutions to a given problem.
It should be easier to define if a solution is good if we see the others solutions at the same time.

**Comment by fauno** [comment]
:+1:

**Comment by gdpelican** [comment]
Hey @roipoussiere; this seems like a topic totally ripe for discussion. We have a public loomio group for feature ideas, which seems like it might be a better place for this than the github issues list: check it out here: https://www.loomio.org/g/GN7EFQTK

Going to close this for now; we'll open it back up if there ends up being some more concrete tasks associated with it.

Thanks! :tangerine:
