### ISSUE TITLE
Attachment Filenames Not sanitised

### ISSUE THREAD

**Issue by TheShiteKnight** [loomio/loomio#2241]
We hit a bug when someone tried to attach an odt document with a '#' in the title.
Got an xml access denied message:
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>AEEBAA18D33544B3</RequestId>
<HostId>
2GGt7bqxs18zTR70VoCFyEy6WmbQMU52p95Lx5IH+EyZ9Tz/94gTZUZbDJBvpnGX
</HostId>
</Error>

**Comment by gdpelican** [comment]
Thanks for the heads up, @TheShiteKnight. Revamping attachment uploading is on our medium-term roadmap, so we'll be sure to keep this in mind.

**Comment by gdpelican** [comment]
The new attachments which have just been deployed should fix this (on angular at least)
