### ISSUE TITLE
Profile update results in blank redirect page

### ISSUE THREAD

**Issue by kapziel** [loomio/loomio#2284]
Starting off like this:
<img width="1594" alt="screenshot 2015-07-03 20 29 01" src="https://cloud.githubusercontent.com/assets/5645311/8495509/40e01982-21c2-11e5-8a44-5d9ba269a64c.png">

When trying to change account details such as alter email address or change username, it ends up going to this page:

<img width="1594" alt="screenshot 2015-07-03 20 31 10" src="https://cloud.githubusercontent.com/assets/5645311/8495543/762c4b24-21c2-11e5-9093-8e290dc2ce2e.png">

**Comment by robguthrie** [comment]
Seems like this is fixed now
