### ISSUE TITLE
Difference with democracyos? 

### ISSUE THREAD

**Issue by johnfelipe** [loomio/loomio#2340]

**Comment by johnfelipe** [comment]
Dos.felipeurrego.com

**Comment by johnfelipe** [comment]
I need to know difference, pls

**Comment by rdbartlett** [comment]
Maybe you can expand the question a little felipe? e.g. what are you trying
to achieve, what do you know about each platform, what would you like
clarification on...

**Comment by johnfelipe** [comment]
My need is for bills or projects in legislation

**Comment by rdbartlett** [comment]
Cool. DemocracyOS is focussed on legislation. It is specifically designed
for engagement between citizens and legislators. As I understand it, the
legislators set the terms of engagement, and the key engagement mechanism
is voting.

Loomio is designed primarily for relatively small collaborative groups
where all the participants have equal power. It has been used increasingly
for citizen engagement (most recently by Statistics NZ
https://2018census.loomio.org), and the key engagement mechanism is
deliberation.

Does that help?

**Comment by planspark** [comment]
I've added the Statistics NZ project to ParticipateDB here:

http://www.participatedb.com/projects/295

DemocracyOS already has a couple of project examples listed here:

http://www.participatedb.com/tools/269

If anyone has additional projects they'd like to share, please feel free to add them. Start by creating your account here:

http://www.participatedb.com/users/sign_up

Thanks!

**Comment by rdbartlett** [comment]
Nice one, thanks Tim :)
