### ISSUE TITLE
html visible in header explore page

### ISSUE THREAD

**Issue by peteruithoven** [loomio/loomio#2525]
Please let me know if this is not the right place to comment on this, but after enabling the new (angular) loomio I get html elements in the header of the loomio.org/explore page. 
![screen shot 2015-09-30 at 23 32 15](https://cloud.githubusercontent.com/assets/523210/10207430/74e45e1e-67cc-11e5-92b6-80aaf2f375cb.png)
It didn't matter if I changed my language (English or dutch). 
When I change back to the old Loomio this html disappears. 
To be clear, this happens with the version that is currently on loomio.org.

**Comment by rdbartlett** [comment]
Thanks for the report @peteruithoven, this is a known issue. 

@robguthrie have you got a solution in mind?

**Comment by robguthrie** [comment]
this is fixed!
