### ISSUE TITLE
new voting options?

### ISSUE THREAD

**Issue by fauno** [loomio/loomio#2691]
at [consenso pirata we're discussing](https://consenso.partidopirata.com.ar/d/4OHpG2Sf/piratizar-loomio) on how to invite people not only to reach consensus about propposals, but also to take action.  so we're thinking in new voting options:

* "i'm in!" or something like that, meaning you agree with the propposal and also you'll work towards fulfilling its goals
* "i don't understand", meaning the propposal is too vague or you don't get it

i'm looking at the code and there's arrays of "yes, no, abstain, block" everywhere, is there interest on some refactoring so it's easier to add custom options?  i guess it's considerable work so we may end adding our two options without changing much, but maybe you can get a pull request back too :P

**Comment by gdpelican** [comment]
Hm, yeah. At some point we'll be taking a good hard look at this kind of customization... it keeps being brought up in the Loomio community as something missing from the decisionmaking experience, but I'm not sure allowing customization of the vote options (which is the core tenet of Loomio, above all else), is the way we'll go about it... will be interesting to see what happens when that comes up on the roadmap.

**Comment by fauno** [comment]
i mean currently it involves a lot of retouching, options are hardcoded everywhere, chart colors are unrelated...

[the "i'm in!" option is already in production](https://consenso.partidopirata.com.ar/d/WOQEFagn/reunion-piratil-para-hablar-sobre-seguridad-informatica) :)

**Comment by gdpelican** [comment]
I meant to say... that is very cool.

I'm going to take a little time and get the backend a little more friendly for this work; I think prepping this correctly will lead to some very neat customizations in the future.

**Comment by gdpelican** [comment]
Hey @fauno , we're just about to merge in a new [plugin architecture](https://github.com/loomio/loomio/pull/2863), and I think the 'adding new voting positions' might make for a super interesting addition. Wonder if there's a diff of some kind out there of how you got that going?

(I couldn't help but notice you've got an ether-pad integration of some kind on there as well, which would be another great plugin. ;P)

**Comment by rdbartlett** [comment]
OMG etherpad integration :heart:

**Comment by gdpelican** [comment]
Closing this; would be cool to see a plugin in this direction at some point.
