### ISSUE TITLE
404 on all assets files after login

### ISSUE THREAD

**Issue by massimeddu** [loomio/loomio#2694]
Hi,

I get a 404 error message on all assets files (for example /css/app.css?1446765022) after login in a fresh install.

Any ideas to solve this?

**Comment by massimeddu** [comment]
I resolved changing to not-angular UI.

**Comment by ybabel** [comment]
Hello, how do you change to "not-angular" ? I think I have the same problem.

**Comment by robguthrie** [comment]
Hi, what steps are you following? The [loomio-deploy](https://github.com/loomio/loomio-deploy) steps using the docker container or the [setup a development environment](https://help.loomio.org/en/dev_manual/setup_dev_environment/) steps?

**Comment by ybabel** [comment]
loomio-deploy in my case. I have raised an issue : https://github.com/loomio/loomio-deploy/issues/35
