### ISSUE TITLE
Proposal I participated in showing as undecided

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#2696]
The proposal is showing a **?** symbol, indicating I didn't participate.

![screen shot 2015-11-08 at 2 24 08 pm](https://cloud.githubusercontent.com/assets/5498878/11023132/d8b4f752-8624-11e5-9e3d-90c73b7c74c3.png)

But when I open the proposal details, you can see that I did participate.

![screen shot 2015-11-08 at 2 24 22 pm](https://cloud.githubusercontent.com/assets/5498878/11023138/e7da31de-8624-11e5-957b-fe2b37c53269.png)

**Comment by gdpelican** [comment]
Got a fix for this in #2766
