### ISSUE TITLE
Accented characters rendering issue (comment likers)

### ISSUE THREAD

**Issue by hangya** [loomio/loomio#2697]
When a comment is liked by a user, who has accents in his name (stored as html entities), the interface escapes the starting '&':

    Liked by Kov&amp;#225;cs Andr&amp;#225;s.

so instead of the accented characters, the interface shows their html entities, like this:

> Liked by Kov&amp;#225;cs Andr&amp;#225;s.

The expected output would be:

> Liked by Kov&#225;cs Andr&#225;s.

**Comment by gdpelican** [comment]
Thanks, we're on it!

**Comment by hangya** [comment]
Thanks for the quick fix, it works right now!
