### ISSUE TITLE
Files uploaded to private loomio are publicly available without authentication

### ISSUE THREAD

**Issue by gardner** [loomio/loomio#2707]
A security issue which I was driven to test after reading [this](https://www.ibuildings.nl/blog/2015/11/hidden-plain-sight-brute-forcing-slack-private-files) article about Slack.

**Steps to reproduce**

* Login to upload a file to a private loomio
* Copy the url of the image
* Open up a new private browser window
* Paste the url to download the file
* Please note that no login credentials are requested and the file is downloaded without passing any session cookies

**Step 1) Upload a file**
![Upload a file](http://i.imgur.com/uRAVld9.png)

**Step 2) Copy the URL**
![Copy the URL](http://i.imgur.com/oBzqOet.png)

**Step 3) Download with no cookies or auth**
![Download with no cookies or auth](http://i.imgur.com/cCT7HtB.png)

Please fix this or update the UI to set user expectations appropriately.

**Comment by rdbartlett** [comment]
Thanks for the exquisite bug report @gardner. This is actually by design, coz we thought that is the best we could do at the time due to the limitations of uploading to S3. When we review how we're doing attachments, it would be ideal to tie thread privacy to the attached file.

**Comment by gardner** [comment]
It looks like an attacker would need to brute force the md5 hash as well as the filename. To brute force the md5 sum it could take up to 2,339,099,464,253,592,691 tries. I am not sure what the limits are on s3 filenames so I can't say how difficult it would be to brute force but I'm going to close. We can always reopen it after terabit internet and quantum computers become common things.
