### ISSUE TITLE
Getting some email notifications even though they are turned off

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#2708]
I use Loomio with absolutely zero email notifications turned on.

![screen shot 2015-11-13 at 11 19 09 am](https://cloud.githubusercontent.com/assets/5498878/11133197/3c01e78e-89f9-11e5-8424-12f2c8db7bb1.png)

But I am getting some emails anyway. Not for all threads/groups... having trouble finding the pattern. Here's one email from a thread in the Enspiral Members subgroup. 

![screen shot 2015-11-13 at 11 23 20 am](https://cloud.githubusercontent.com/assets/5498878/11133211/5ea6e4e2-89f9-11e5-8d40-b25219dc8771.png)

I even went to double check that the group settings have email turned off as well - they do.

![screen shot 2015-11-13 at 11 21 31 am](https://cloud.githubusercontent.com/assets/5498878/11133217/6c92de6c-89f9-11e5-995d-1808e4dec567.png)

Like I said it's not for all threads (by far...) but there are several emails coming through.

![screen shot 2015-11-13 at 11 28 35 am](https://cloud.githubusercontent.com/assets/5498878/11133282/d0e7efce-89f9-11e5-94c0-51a5f746f272.png)

Digging through my email history, it appears they began on Mar 30 2015, but I only got about one per month until Sept 2015 (which is why I didn't raise this issue before). I got 15 emails for thread replies in Sept, 6 in Oct, and 7 so far in Nov.

They appear to all be "replied to your comment" notifications. None are new thread, new proposal, new comment (not reply to me), or @mention notifications. Could this have started when the "reply to [person]" button was introduced in discussions, creating a kind of notification the settings don't cover?

My request as a user is that there be some global way to turn off all email notifications reliably.

**Comment by alannallama** [comment]
This is still happening to me, unfortunately, even though it looks like this issue was closed @robguthrie ...

**Comment by alannallama** [comment]
This issue went away for a while, but just now came back. I wonder if it could somehow be related to the BX deploy @mhjb @robguthrie ? So weird. All my emails are turned off, but Loomio switched on notifications for all activity for a thread I started a proposal in.

**Comment by robguthrie** [comment]
so crazy! Thanks for reporting so clearly. I'll look into it tomorrow!
