### ISSUE TITLE
Bugs with Date Picker

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#2711]
Two issues arise when I try to raise a proposal with a closing date other than the default 3 days.

1. There is no date picker that pops up at all. I have to manually type in a new date to change it.

2. Half the time options are invalid.

![screen shot 2015-11-16 at 9 18 33 am](https://cloud.githubusercontent.com/assets/5498878/11171301/7b7545d2-8c51-11e5-90d5-add795583e6d.png)

My browser is Firefox 42 on OSX Yosemite, if that helps.

**Comment by robguthrie** [comment]
Yikes. Thank you Alanna - I'll fix it tomorrow!

**Comment by robguthrie** [comment]
We've got a ticket to add date picker support. Closing this as I fixed the Invalid Date issue
