### ISSUE TITLE
Group description needs max-width for images (in beta interface)

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#2717]
Beta interface:
![image](https://cloud.githubusercontent.com/assets/970124/11203182/263f08ea-8d56-11e5-8f67-75d0a3605516.png)

No problem on new interface:

![image](https://cloud.githubusercontent.com/assets/970124/11203193/48e6da94-8d56-11e5-9f91-e493cd27ff81.png)

This is a bit sad because [this group](https://www.loomio.org/g/SOAzZhU8/unidad-popular) is being heavily advertised, and all visitors will see the beta interface.

**Comment by gdpelican** [comment]
I've got a fix for this here: #2718

On a side note, after the public api stuff gets merged in, I'd heavily recommend we consider some work which allows us to show visitors the angular interface.
