### ISSUE TITLE
Previous proposals marked as undecided even though I have participated

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#2724]
I have participated in most of these proposals but they are marked as undecided:

![image](https://cloud.githubusercontent.com/assets/970124/11223451/d43353ce-8dd4-11e5-9ffa-da7852c85c68.png)

**Comment by robguthrie** [comment]
I reckon this might be due to the default results limit.

**Comment by robguthrie** [comment]
Thanks Rich. This is a dupe of #2696. We'll monitor the fixing process in that issue
