### ISSUE TITLE
Deactivated groups listed in my groups page

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#2728]
Just noticed the old (archived) Contributors group is listed in my Groups page. Group key qfZ5XeEF

This list should only include non-archived groups that I am a member of.

**Comment by rdbartlett** [comment]
Also affects the list of subgroups on the group page.

**Comment by robguthrie** [comment]
angular don't have this problem

**Comment by robguthrie** [comment]
wowowowo what am I sayin

**Comment by robguthrie** [comment]
sorry

**Comment by rdbartlett** [comment]
@robguthrie this problem seems to have fixed itself. Is it safe to close?
