### ISSUE TITLE
Nonsense timestamps on notifications

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#2740]
![image](https://cloud.githubusercontent.com/assets/970124/11283477/cd26f41e-8f69-11e5-821c-1dba11d2dd73.png)

**Comment by gdpelican** [comment]
@rdbartlett Sorry, I'm not seeing the nonsense here?

**Comment by rdbartlett** [comment]
Sorry, bad explanation. I get a lot of timestamps that say "just now", but
they are actually hours old. It's like the clock gets frozen when the event
first fires.

**Comment by gdpelican** [comment]
I believe the auto-updating timestamps will fix this.
