### ISSUE TITLE
Inaccurate proposal closing time

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#2743]
Currently proposal closing time is up to 10 minutes out of accuracy, as it relies on a cron job on heroku. This means occasionally you see things like this:

![image](https://cloud.githubusercontent.com/assets/970124/11290076/ee9b6aca-8f97-11e5-933d-6b5a32c97f98.png)

@gdpelican were you proposing to use DelayedJob to handle this?

**Comment by gdpelican** [comment]
Thats the firehose solution. The easier thing it to have that reference
closing_at instead of closed_at when calcing if it's open or not
