### ISSUE TITLE
Can't invite people to group becayse angular not loading coordinator permissions

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#2745]
In Angular, when I look at the memberships page for the Enspiral group, I see me and Alanna and Charley as coordinators. When I look at it in Beta, there are a bunch more, including Phill, Malcolm. The result is that Malcolm and Phill can't invite people to join the group, i.e. they can't do their job. Yikes!

**Comment by gdpelican** [comment]
Can't repro this. Plucking the coordinators from the Enspiral group in prod gives me this:

![screen shot 2015-11-23 at 7 45 31 am](https://cloud.githubusercontent.com/assets/750477/11327085/7563366c-91b6-11e5-9a8f-a0ca0310aa94.png)

Which matches what I see on the angular interface. Beta interface doesn't have a mechanism for displaying whether people are coordinators or not, as far as I can tell. Have you gotten complaints from someone about this? Likely we just need to add Malcolm as a coordinator if he needs to be coordinating.

**Comment by gdpelican** [comment]
Oh right, I'm not a coordinator, so I can't see the coordinators in beta. Mind screenshotting me, here or privately?

**Comment by rdbartlett** [comment]
I'll send you screenshots privately.

**Comment by rdbartlett** [comment]
I will re open this when I have a reproducible error
