### ISSUE TITLE
Email settings - Group volume settings forgotten

### ISSUE THREAD

**Issue by alexanderzatko** [loomio/loomio#2747]
I used a link in an email send by loomio to unsubscribe from messages received from groups. After reaching the Email settings page I clicked the Quiet radio button and Update(d) Settings. The change seemed to "stick". However, group emails continue to arrive and when visiting the Email settings page again, the No change radio button is selected.

**Comment by rdbartlett** [comment]
Thanks for the very lucid report @alexanderzatko. Strange as it sounds, this is actually working as intended, it is just a very confusing design! 

When you have a bunch of threads in a group, they will each be at different volume settings, depending on whether or not you have participated in them. When you change your group volume, all new threads in that group will start with that volume. However, no change is made to the volume of already existing threads, so you will continue to receive notifications for them.

We are in progress on a new, much less confusing design. I'll update here once there is something to share :boat:

**Comment by HSalmon** [comment]
FYI, [here](https://www.loomio.org/d/CeMFoapG/ux-engaging-people-with-notification-emails-without-overwhelming-them-with-noise) is the Loomio discussion in which we sought feedback from the Loomio community group about changes to email settings. We've just recently implemented the next iteration :)
