### ISSUE TITLE
iPad: Nav bar de-attaches from top of page upon entering comment textarea. 

### ISSUE THREAD

**Issue by jessykate** [loomio/loomio#2749]
This seems to happen only if I am scrolled all the way to the bottom of the page. If I scroll up a bit and then enter the textarea, it doesn't happen. However, it is often the case naturally, that I am often scrolled all the way down. See screenshots. Happens in both landscape and portrait orientation. Re-attaches when I close the keyboard. 

A similar (smaller) bug is that returning in the text area doesn't push down the "Give feedback" button, so eventually my cursor ends up underneath it and I can't see what I'm typing. 

![img_0050](https://cloud.githubusercontent.com/assets/59882/11348512/9ebd8130-91ec-11e5-8f17-6f3410feaea8.jpg)
![img_0051](https://cloud.githubusercontent.com/assets/59882/11348511/9ebbdb1e-91ec-11e5-953f-7e26e4db7ad1.jpg)

**Comment by rdbartlett** [comment]
This breaks my heart. Thanks for the excellent report @jessykate - is this Chrome?

**Comment by jessykate** [comment]
Yes!






On Mon, Feb 15, 2016 at 2:51 PM -0800, "Richard D. Bartlett" <notifications@github.com> wrote:












This breaks my heart. Thanks for the excellent report @jessykate - is this Chrome?
