### ISSUE TITLE
Draft remains after I post my comment

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#2752]
Typed comment, pressed post, textarea cleared, comment posted, textarea repopulated with draft

![image](https://cloud.githubusercontent.com/assets/970124/11378373/aefb1fda-934f-11e5-8e2c-1b861b774066.png)

Fyi @gdpelican

**Comment by rdbartlett** [comment]
FYI, I've only seen this once. I've posted a bunch of comments with no problem.

I wonder if this bug is causing people to double-post comments though? Just saw this:

![image](https://cloud.githubusercontent.com/assets/970124/11379418/29b5cfea-9355-11e5-83a9-28c62b9ea42d.png)

**Comment by rdbartlett** [comment]
Bug happened to me again. When I reload the page though, the draft is gone.

**Comment by gdpelican** [comment]
Super weird, must be another race condition. I'll have a look.

**Comment by rdbartlett** [comment]
I have a hunch that it is coinciding with times when the network is slow.

**Comment by gdpelican** [comment]
#2760

**Comment by jessykate** [comment]
This just happened to me too! 

<img width="1001" alt="screenshot 2015-11-28 10 13 52" src="https://cloud.githubusercontent.com/assets/59882/11453261/dc4bc244-95b8-11e5-9690-f7c5e80e5c89.png">

**Comment by jessykate** [comment]
(Actually it's happened at least twice in two different threads, FWIW)

**Comment by gdpelican** [comment]
There is a PR in for this that will be merged soon.
