### ISSUE TITLE
"Start group" button seems to be a no-op

### ISSUE THREAD

**Issue by whit537** [loomio/loomio#2756]
**Steps to reproduce:**

 1. Navigate to https://www.loomio.org/groups as an authenticated user.
 1. Click the [ + New Group ] button.
 1. Choose an open group that anyone can join with all permissions enabled.
 1. Click [ Start Group ]
 1. Click [ OK ] on javascript `confirm` prompt, "If you proceed, all threads in this group will be made public on the web."

**Expected result:**

 - Land back on https://www.loomio.org/groups (modal disappears) with new group listed.

**Actual result:**

 - Get brief loading indicator at lower right. Then it disappears and nothing else happens. Filled-out modal form is still present.

Refreshing https://www.loomio.org/groups indicates that the new group is *not* created.

**Comment by whit537** [comment]
Looks like I'm getting a `422: Unprocessable Entity" from `/api/v1/groups`.

![screen shot 2015-11-25 at 6 23 44 pm](https://cloud.githubusercontent.com/assets/134455/11411765/adf747ec-93a1-11e5-993a-42ddc1e6c36c.png)

**Comment by gdpelican** [comment]
Hm.. I'm not able to reproduce this... here was my process; can you think of anything else that might be missing? Are you able to inspect the 422 request which comes back for error messages?
http://g.recordit.co/GnIcn2tSC7.gif

**Comment by whit537** [comment]
@gdpelican Note (3): "Choose an open group that anyone can join with all permissions enabled."

![screen shot 2015-11-25 at 7 03 57 pm](https://cloud.githubusercontent.com/assets/134455/11412180/5131c2ca-93a7-11e5-86cf-95282dd643a6.png)

**Comment by whit537** [comment]
Looks like we do have an error message:

```json
{"errors":{"discussion_privacy_options":["Discussions must be public if group is open"]}}
```

How does this map to the options I've selected?

**Comment by whit537** [comment]
At the very least, the error message should be propagated back to the user. I'm not convinced there's not another bug, though. I'm not sure what "Discussions must be public" means, but I *think* I tried to make discussions public by selecting "Open" for privacy. But is "group is open" what maps to that option? Then what maps to "Discussions must be public"?

**Comment by gdpelican** [comment]
Okay, I can repro now. This looks like a subtle gap in our group privacy matrix, @robguthrie.

**Comment by whit537** [comment]
Cool, thanks @gdpelican.

**Comment by whit537** [comment]
I've got Loomio running locally:

![screen shot 2015-11-25 at 11 29 09 pm](https://cloud.githubusercontent.com/assets/134455/11415104/5af2af8e-93cc-11e5-966d-ca3a1ef3823c.png)

I don't have a ton of Rails experience. How do I run the test suite?

**Comment by whit537** [comment]
https://github.com/loomio/loomio/wiki/using_development#testing

**Comment by whit537** [comment]
I suppose this is where the test should go, in [`group_privacy_spec.rb`](https://github.com/loomio/loomio/blob/5f9c560f52f64c4d4604ad672ff68ba950a0c5d4/spec/models/group_privacy_spec.rb).

```
$ bundle exec rake spec SPEC=spec/models/group_privacy_spec.rb 
/opt/rubies/ruby-2.2.3/bin/ruby -I/Users/whit537/personal/loomio/loomio/vendor/ruby/2.2.0/gems/rspec-core-3.2.3/lib:/Users/whit537/personal/loomio/loomio/vendor/ruby/2.2.0/gems/rspec-support-3.2.2/lib /Users/whit537/personal/loomio/loomio/vendor/ruby/2.2.0/gems/rspec-core-3.2.3/exe/rspec spec/models/group_privacy_spec.rb
.............

Finished in 2.63 seconds (files took 21.2 seconds to load)
13 examples, 0 failures

$
```

**Comment by whit537** [comment]
Here's the source of the error message: https://github.com/loomio/loomio/blob/5f9c560f52f64c4d4604ad672ff68ba950a0c5d4/app/models/group.rb#L556.

**Comment by whit537** [comment]
(Presumably.)

**Comment by whit537** [comment]
Might be an interaction with the "subgroups" option?

```
  unless is_visible_to_parent_members?
```

**Comment by whit537** [comment]
I tried creating the group again in production, unchecking "Members can create subgroups" as a workaround: same error.

**Comment by gdpelican** [comment]
So the trouble will be something related to us setting
'discussion_privacy_options' (which is not currently an option in the form)
to 'private_only' (or maybe 'public_or_private', which is incompatible with
an 'open' group at the moment. This was a relatively major change to
simplify the group options which has been rolled out recently, so we've
probably hasn't accounted for 'public_discussions_only' being set when
applying advanced options to a form.

I'm no good to help on this particular issue today, but I reckon I could
get this solved tomorrow given a little digging.

If you find the reason that the group is getting
'discussion_privacy_options' set to false, I reckon that'd be the bug.

If you want to debug yourself, have a spin at putting the line `byebug` (or
`binding.pry`) somewhere in the code you're interested in, which will halt
the request there in your `rails s` window and allow you to dig around a
little better. Good docs on those things here:
https://github.com/deivid-rodriguez/byebug,
http://yorickpeterse.com/articles/debugging-with-pry/

**Comment by gdpelican** [comment]
#2761

**Comment by whit537** [comment]
Confirmed fixed, thanks @gdpelican @robguthrie! :-)

![screen shot 2015-12-01 at 12 05 31 pm](https://cloud.githubusercontent.com/assets/134455/11507874/13010fd4-9824-11e5-8204-f895469d66f4.png)
