### ISSUE TITLE
My subgroup is configured so parent members can't see threads, but they are still coming up in the Slack integration

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#2771]

**Comment by gdpelican** [comment]
What if we didn't post subgroup stuff via slack? I feel like our privacy options are a little too hairy to navigate this elegantly, and if someone wants to post subgroup content to the same channel, they (I) can set up another webhook for each subgroup easily.

**Comment by rdbartlett** [comment]
:+1:
