### ISSUE TITLE
Stuff I read via email shows up unread

### ISSUE THREAD

**Issue by HSalmon** [loomio/loomio#2773]

**Comment by fauno** [comment]
fwiw i've seen this happen when the email client doesn't support or doesn't open the webbug url for marking the event as read.  it works in thunderbird, but not on any console client (ie mutt).  it doesn't work on k-9 either, though i'm using an old version.

maybe it needs to show a little image, like a check mark? :heavy_check_mark:

**Comment by fauno** [comment]
i don't remember if thunderbird asked me if i would like to load images from loomio's email address though

**Comment by gdpelican** [comment]
Is it possible to give a little more context on this one, @HSalmon? Is it a thread email or the yesterday on Loomio email that's not marking things as read, or both? Do the items get marked as read on reload, or not at all?

**Comment by rdbartlett** [comment]
That's an awesome idea @fauno - let's do a tick with a message explaining that it has been marked as read on Loomio.

**Comment by gdpelican** [comment]
Alright, I'm closing this as it's ancient and there's been no repro or reports of this lately.
