### ISSUE TITLE
New thread form told me I was starting a public thread but it was private

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#2780]
When I open the Start Thread modal from the Dashboard page, and select 'Loomio Community - Contributors' as the group, the privacy notice tells me the thread will be public. Then I start the thread and see that it is private (which is what I wanted).

**Comment by rdbartlett** [comment]
This should say private but it says public :pineapple:

![image](https://cloud.githubusercontent.com/assets/970124/11769976/a2d85bba-a258-11e5-80d5-0586fe5e50c6.png)

**Comment by gdpelican** [comment]
Fixed in #2870
