### ISSUE TITLE
Unable to turn off 'Yesterday on Loomio' email

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#2781]
According to my email settings, I shouldn't be receiving a 'Yesterday on Loomio' email

![screen shot 2015-12-03 at 10 45 44 am](https://cloud.githubusercontent.com/assets/750477/11550455/0bf430c6-99ab-11e5-8dcf-1d7d4375f016.png)

But yet it dutifully shows up every morning.

**Comment by gdpelican** [comment]
This is user error; I had a separate account which was sending to the same email address.

**Comment by robguthrie** [comment]
Thought it mighta beeen! ;)
