### ISSUE TITLE
Able to tag a user who is not in a group

### ISSUE THREAD

**Issue by silviazuur** [loomio/loomio#2782]
There is a user called @silvia (who is not me) and who must be in other groups. When people tag @silvia in the Enspiral group it still "tags" someone/that user. 

This is confusing. I think you should only be able to @ mention people who are only in that group. It should limit the list of option to accounts only in that group

**Comment by robguthrie** [comment]
Thanks Silvia, This is a new bug! We'll fix it soon!

**Comment by gdpelican** [comment]
This is a tricky one to fix in a performant way. We may want to consider storing mentions in the DB in a similar fashion to comment likes.

**Comment by gdpelican** [comment]
Calling this:
```
  def mentioned_group_members
    group.users.where(username: mentioned_usernames).where('users.id != ?', author.id)
  end
```
every time we serialize a comment is going to kill us.

**Comment by robguthrie** [comment]
I don't think that's the part of the system with the problem. I think its more on the mentioning side of things.. IE: when the author is typing we're displaying users to mention which do not belong to the group.

**Comment by gdpelican** [comment]
I'm not seeing that behavior; going to the Enspiral group and trying to mention @ silviazuur works as expected .

We're serializing out `mentioned_usernames` in the serializer, which uses Twitter::Extractor, which doesn't take into account group membership.

So I think people are assuming that Silv is @silvia, without actually selecting it from the mentionable menu, and then submitting it. (Plus, there's not really anything we can do about someone typing @jameskiesel into a comment when they actually mean @gdpelican)

I wonder if this @silvia person is getting notifications about these mentions or not (I don't think so?)

**Comment by robguthrie** [comment]
I am experiencing this problem too.. Rose Lu was able to mention robguthrie
which is a loomio user who only belongs to palinka. (my main account
username is robertguthrie)

**Comment by gdpelican** [comment]
Yes, I can reproduce the bug, but cannot see the behaviour of us suggesting the wrong user through autocomplete.

**Comment by rdbartlett** [comment]
So if you post a comment mentioning a random username @poopfart, it should not be rendered like a valid mention.

**Comment by rdbartlett** [comment]
What about @123klasdlasklae0120120asdadsasiispppsklasdhh?

**Comment by mhjb** [comment]
![image](https://user-images.githubusercontent.com/1380991/29011950-807385fa-7b8b-11e7-8e49-2c7d0d43e4a9.png)

this is the LC board group…

**Comment by gdpelican** [comment]
I'm going to close this in preference for #4484, which has some more up-to-date info on this bug.

(Noted there is the fact that I'm blaming mentio and intend to tear that library out this year)
