### ISSUE TITLE
allow for credit for splash photo

### ISSUE THREAD

**Issue by whit537** [loomio/loomio#2814]
I'm using a CC-BY photo and don't have a good place to put the attribution.

**Comment by gdpelican** [comment]
Closing as dup of #2815

**Comment by gdpelican** [comment]
FYI @whit537, we do get an notified for each issue raised here, and this past flood left some people feeling rather spammed. I'd love to have a conversation at some point about how we can work together more effectively, feel free to reach out! <3

**Comment by whit537** [comment]
>  this past flood left some people feeling rather spammed.

@gdpelican Eep! Sorry. :-(

> I'd love to have a conversation at some point about how we can work together more effectively

Sure! What's a good channel to use?

**Comment by whit537** [comment]
Ftr, we've dropped to private email and are currently arranging a Hangout on Air.

**Comment by whit537** [comment]
We've schedule a call for December 29 at 2pm UTC. Picking up over on https://github.com/gratipay/inside.gratipay.com/issues/421 to avoid further noise here. :-)
