### ISSUE TITLE
allow me to expand "new topic" textarea vertically

### ISSUE THREAD

**Issue by whit537** [loomio/loomio#2816]
I want to write more than will fit in the textarea as initially displayed, but I can't change the size of the textarea vertically using the browser's controls.

![screen shot 2015-12-14 at 12 13 38 am](https://cloud.githubusercontent.com/assets/134455/11773428/ac4f6262-a1f7-11e5-8826-1ba996f224fe.png)

**Comment by whit537** [comment]
Ftr the textarea *does* expand when I fill it with content:

![screen shot 2015-12-14 at 12 15 35 am](https://cloud.githubusercontent.com/assets/134455/11773434/d840602e-a1f7-11e5-8c15-aea934888542.png)

**Comment by gdpelican** [comment]
Yeah we're using a library to allow text areas to expand as content is entered into it. Likely we just want to stop the user from being able to expand the text areas manually at all.
