### ISSUE TITLE
show what the proposal title used to be

### ISSUE THREAD

**Issue by whit537** [loomio/loomio#2818]
When I change the title of a proposal, there doesn't appear to be any indication of what the title *used* to be:

![screen shot 2015-12-14 at 12 21 10 am](https://cloud.githubusercontent.com/assets/134455/11773484/9fba23f6-a1f8-11e5-9b8d-b5e95094853a.png)

**Comment by HSalmon** [comment]
@whit537 - just a heads up, visual representation of revision history is currently being designed and will be implemented soon.

**Comment by robguthrie** [comment]
Hi @whit537 I'm going to remove your design request issues.. We've recorded them into our design doc, where they will influence upcoming designs, but we want to close these issues for now.

Thanks for your input!

**Comment by whit537** [comment]
Thanks @robguthrie. Is this the [design doc](https://docs.google.com/document/d/1Wh8cON7fyUgUUwtRMdV7bJYTCY0QxkMeF7Zi7AG9y3M/edit) you're talking about?

**Comment by robguthrie** [comment]
nope!

**Comment by whit537** [comment]
Ooooookay ... I just searched the wiki and the README in this repo and came up empty as well. Can you share a link to the design doc? :-)

**Comment by rdbartlett** [comment]
Hey @whit537 we're upgrading our design and contribution processes at the moment. We'll update the repo when we have a process that is ready for your input :)

**Comment by whit537** [comment]
Okay, thanks @rdbartlett.
