### ISSUE TITLE
allow me to create multiple proposals at once

### ISSUE THREAD

**Issue by whit537** [loomio/loomio#2819]
I made a proposal on a thread, and it looks like I can't create a second proposal. Is that correct? Is it just that a given user can't create multiple proposals at a time? Or that a given thread can have only one live proposal at a time? Or ... ?

![screen shot 2015-12-14 at 12 25 57 am](https://cloud.githubusercontent.com/assets/134455/11773526/45b9287e-a1f9-11e5-8b85-9e46ff42b99b.png)

https://www.loomio.org/d/MXNPQpo1/pick-an-online-citizen-engagement-platform

**Comment by HSalmon** [comment]
Hi @whit537, thanks for raising this.

Right now, it is not possible to have multiple active proposals in a single discussion thread.

Loomio encourages groups to use the discussion thread to consider multiple options. A proposal is one proposed course of action and is used as a way of testing consensus when it looks like a one idea is gaining traction.

That being said, a multi-choice proposal feature has been discussed at length and in future we want Loomio to accommodate plugins for different decision-making mechanisms. We'll be looking into ways to design and implement the architecture for this next year.

**Comment by gdpelican** [comment]
This would be a great thing to raise in the feature ideas group on Loomio.
https://www.loomio.org/g/GN7EFQTK/loomio-community-feature-ideas
