### ISSUE TITLE
add oauth options to "Ask to join group" workflow

### ISSUE THREAD

**Issue by whit537** [loomio/loomio#2823]
Reticketed from https://github.com/Ambridge/Ambridge/issues/70. Users should be able to authenticate with Facebook as part of the "Ask to join group" workflow.

![ldzvghfwwk](https://cloud.githubusercontent.com/assets/134455/11782877/c5beccd4-a241-11e5-9d1d-a1ca5e220e8f.gif)

**Comment by gdpelican** [comment]
@robguthrie Do you have thoughts about this as it relates to the new buyer experience? We definitely want to include this particular flow in our new designs, and it seems like SSO should be an option here.

**Comment by robguthrie** [comment]
The only way we can do that is by getting users to create accounts to request access.

IE: Right now you don't need to create an account to 'ask to join', you just give a name and email and if you're approved, you're sent an invitation link, at which point you can authenticate with SSO.

So the decision here is, do we want to support this "does not matter if you are signed in or not" approach to this problem, or do we want to enforce that people authenticate first.
