### ISSUE TITLE
when comment has attachment, include link to attachment in comment notification email

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#2826]
![image](https://cloud.githubusercontent.com/assets/970124/11821031/5576e59c-a3cc-11e5-8cd4-6ba94daa402d.png)

![image](https://cloud.githubusercontent.com/assets/970124/11821035/5e2d4320-a3cc-11e5-8d72-bc54976bf5ed.png)

**Comment by gdpelican** [comment]
I'm not able to repro this behaviour on prod:
![screen shot 2015-12-23 at 2 09 27 pm](https://cloud.githubusercontent.com/assets/750477/11977023/d29497e2-a97e-11e5-92d6-bce0e59cd5c6.png)

Is it possible that MJ submitted her comment, then added the attachments later in an edit?

**Comment by gdpelican** [comment]
Ooh. That's a comment replied to email, not a new comment email.

**Comment by gdpelican** [comment]
Added in #2853
