### ISSUE TITLE
Explain why someone should use the shareable group link

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#2829]
I'm keen to a) give the shareable group link a name, so we can refer to it easily in the help docs and b) promote its use (because I think it is better than sending unique invitations). 

@natiloomio and I have just tried some new language. What do you think of this?

![invite](https://cloud.githubusercontent.com/assets/970124/11858586/c4d17d2a-a4c7-11e5-8a8b-4357c77db445.png)

Also note the Group select is hidden when we already know what group they're on.

**Comment by rdbartlett** [comment]
Next iteration:

![invite](https://cloud.githubusercontent.com/assets/970124/11883693/840f4b48-a579-11e5-9915-3ba9322d4040.png)

Next, I want to design the 'turn off link sharing' feature.

**Comment by rdbartlett** [comment]
(Oops deleted previous comment w wrong image)

Next iteration:

![invite](https://cloud.githubusercontent.com/assets/970124/11883723/a3c6aa8a-a579-11e5-925f-bc8d88dc9269.png)

**Comment by robguthrie** [comment]
I love it

**Comment by rdbartlett** [comment]
The button says 'done' until you enter an email address, when it changes to say 'send'.

Think it is a good enough next iteration?

**Comment by robguthrie** [comment]
i do

**Comment by mhjb** [comment]
I think it is an improvement and a good enough iteration.

But:

The paragraph of text is quite long. I wondered about breaking it into two paras, so there's more of an association of the first sentence with the Shareable link, and the second with Email addresses. Perhaps adding a divider between the two sentences.

It's not super clear that the custom message only applies to the Email addresses option. 

Any interest in a tiny bit of hall user-testing?

**Comment by HSalmon** [comment]
I wonder if it's worth saying a little more about what a shareable link is, e.g:

"You can copy the link and send it to people you wish to join your group. Clicking the link will automatically provide them access."

Just thinking about Teddy's confusion around what a shareable link is...

**Comment by robguthrie** [comment]
that's great text Hannah

**Comment by rdbartlett** [comment]
Thanks everyone. Here's the next iteration:

![invite](https://cloud.githubusercontent.com/assets/970124/12991409/fe16b914-d173-11e5-9fcb-513c24852315.png)

I hallway tested it with Teddy and Russell. I feel confident that this is an improvement.

**Comment by HSalmon** [comment]
Cool! I could even have a stab at building it today if it's approved

**Comment by rdbartlett** [comment]
Hallway test with Gina:

* "what does 'access' mean?" She wants to reinforce what permissions people will get from this link
* "what if someone forwards this link on to someone I don't want to have access?" - I think we're going to want a way to revoke these shareable links eh.

**Comment by robguthrie** [comment]
Hannah I reckon you could start before approval.. it's down to language at
this stage

**Comment by HSalmon** [comment]
I feel like it's quite difficult to articulate what permissions they will have here, unless we say something like "members-level access". Initially I thought about something like "grant them membership", but I don't think that _really_ makes sense...I wonder if the help docs could outline the permissions that they get and we could link to it from the form...maybe just with a question mark icon or something?

**Comment by rdbartlett** [comment]
Yeah I agree it is good enough to start building. 

I'm not too worried about explaining what access means yet, will be good to hear what other users think.

What do you think about revoking links @robguthrie - if the UI was good, it wouldn't be hard to implement eh?

**Comment by robguthrie** [comment]
I'm not worried about access either. I think the language is pretty great.
I think we can revoke links via pending invitations pretty easily. Or you
could "Cancel this link and create a new one" somehow.
