### ISSUE TITLE
URL not auto-linking in thread context

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#2840]
![image](https://cloud.githubusercontent.com/assets/970124/11889254/18d00d94-a5ac-11e5-9c31-23e5d6f5e566.png)

I would expect the www would have been recognised and the text automatically turned into a link.

**Comment by gdpelican** [comment]
This is a limitation of the marked library; we'd need to fork it in order to put in a new regex to make this go. I don't want to do that; I think I'm happy to settle for only protocol'ed urls being autolinked.
