### ISSUE TITLE
Not localized text on the email messages sent during registration process

### ISSUE THREAD

**Issue by pgerland** [loomio/loomio#2848]
Following text always appear in english :
* [name] has invited you to join [[groupName]]
* Click the link to join [[groupName]] and get started:
* Loomio is an online platform that helps groups make decisions. You can discuss issues and agree on a clear course of action together. Thanks, 

This issue should really be fixed with high priority as this email is the very first message received by future members !

**Comment by gdpelican** [comment]
These strings are translatable, and should be available in our Transifex project. (You could likely translate them yourself!)

Have you checked out https://loomio.gitbooks.io/tech-manual/content/translation.html ?

@natiloomio is currently coordinating our translations, so you could also get in touch with her if you're interested in contributing.

**Comment by pgerland** [comment]
Hi !
Indeed, I've found this string "%{member} has invited you to join %{group_name} on Loomio" (email.to_join_group.subject), already translated in french, but only for "Loomio Beta (old app)" ressource.
It should probably get translated with old app but it is not with current version.

I've already contributed to french translation that is now completed and waiting for review.
@natiloomio : validation process seems to be halted and some strings like these "email.to_join.group..." appear to be missing for current app.

Thanks

**Comment by natiloomio** [comment]
@pgerland Thanks for letting us know. 

The Transifex lines that can't be translated are because they belong to the old app, and it will be taken down in February. 
We also had some issues with the Transifex repositories and that is why some lines are missing from the new app, but we are trying to get this issue solved as soon as possible. 

Thanks
