### ISSUE TITLE
Mentioning breaks sometimes

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#2855]
Here mentions are broken:
![image](https://cloud.githubusercontent.com/assets/486367/12004201/8707062e-abaa-11e5-8d7a-7b67c1d97e29.png)

but not here:
![image](https://cloud.githubusercontent.com/assets/486367/12004202/92e10a80-abaa-11e5-8214-b6f99a120168.png)

**Comment by gdpelican** [comment]
A little dip in the database and those seem to be markdown links to github profiles that are doing it, although I can't repro that specific behaviour (even when copy-pasting the raw comment body to another instance)

Something like

```
[@the_name](github.com/the_name)
```

**Comment by rdbartlett** [comment]
Closing until it comes back
