### ISSUE TITLE
Proposal counts sometimes showing NaN

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#2866]
![image](https://cloud.githubusercontent.com/assets/1380991/12244471/a1b139fc-b908-11e5-8035-a3ec8bafe550.png)

**Comment by gdpelican** [comment]
Can you give repro steps or link to a specific proposal that's showing this behaviour?

**Comment by mhjb** [comment]
I see it e.g. on the first proposal here:
https://www.loomio.org/g/WmPCB3IR/previous_proposals

**Comment by gdpelican** [comment]
Seems like a thing with the previous proposals page in general. We may need to rework this page a little; it's related to this bug: #2777

**Comment by mhjb** [comment]
​I just went to previous proposals to find one; previous experiences of the
bug have not involved the PP page.​
