### ISSUE TITLE
indicate level of (dis)agreement and display its distribution

### ISSUE THREAD

**Issue by davidovitch** [loomio/loomio#2891]
Coincidentally I bumped into [consider.it](https://consider.it/). It think it looks really interesting that they allow participants to express their level of (dis)agreement with a proposal using a simple slider. They also show the distribution of the vote/sentiment. Maybe that could be a nice addition to Loomio as well? It might support finding a compromise when it becomes clear how strongly different participants feel about a certain proposal. I am not sure if it could/should replace the current vote system (yes, no, abstain/neutral, veto), but it might be a cool/handy addition?

**Comment by gdpelican** [comment]
There's some fun discussion going on in the Loomio strategy sessions at the moment about ways to make the voting / proposal system be able to handle a more diverse set of decisions. One of them is to modularize the entire proposal system, which would mean you could mix and match a bunch of different proposal types (agreement distribution, temperature check, multiple choice polling, etc.) into your decision making processes.

These types of features are likely going to be plugin-type material, IE someone could develop a solution and make it available to the community on their own instance. It's not a thing that's possible right this second, but setting up something like this will likely be on the medium-term roadmap. Stay tuned!
