### ISSUE TITLE
Group title link 'undefined' when viewing subgroup I'm not a member of

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#2900]
I'm logged in, and not a member of the (closed) subgroup or (closed) group. 

The underlined link is to /undefined:

![image](https://cloud.githubusercontent.com/assets/1380991/12661209/1a2473c8-c67d-11e5-8580-342f6e134867.png)

**Comment by rdbartlett** [comment]
Seems related to #2911?

**Comment by toupeira** [comment]
Seems to be an Angular issue, the link is fine if you navigate to the sub-group from the parent, but if you load/reload the sub-group directly you'll get `undefined`.

**Comment by toupeira** [comment]
Slightly related: editing a discussion (opening the dialog through the arrow-menu) changes the URL to `/true`, which leads to a 404 on reload.

**Comment by gdpelican** [comment]
Seems fixed!

**Comment by mhjb** [comment]
Alas not fixed: https://www.loomio.org/g/52jcgA8f/le-r-veil-du-gabon-gouvernance-et-institutions

**Comment by mhjb** [comment]
Sweet!
