### ISSUE TITLE
Received proposal closing email even though group is muted

### ISSUE THREAD

**Issue by HSalmon** [loomio/loomio#2901]

**Comment by gdpelican** [comment]
Is this still a thing?

**Comment by HSalmon** [comment]
This has been happening again for me, just with one group (although I've only muted one group), and it's only proposal closing soon emails

**Comment by gdpelican** [comment]
This seems to be intended behaviour, there's even a test around it:

```
User.distinct.where.any_of(Queries::UsersByVolumeQuery.normal_or_loud(motion.discussion),
                               User.email_proposal_closing_soon_for(motion.group))
```
"Discussion is normal or loud, or email_proposal_closing_soon_for group is true (even if it's muted)"

Do we want to change the behaviour?

**Comment by HSalmon** [comment]
When I muted the group I did so because I didn't want to hear anything from it...

**Comment by gdpelican** [comment]
I think we should make this change. Feel up for it @HSalmon ?

I think the proposed change is simply adding 'where memberships.volume is not == mute'  to the `email_proposal_closing_soon_for` scope.

**Comment by robguthrie** [comment]
user.email_when_proposal_closing_soon is being slowly removed from the system.

It's no longer available via the UI. So you could rip out all mentions of it.

**Comment by gdpelican** [comment]
Thought I'd poke at this one again. What should we do here?
