### ISSUE TITLE
invalid date on proposal

### ISSUE THREAD

**Issue by jdoud** [loomio/loomio#2907]
![screen shot 2016-02-03 at 10 14 15 am](https://cloud.githubusercontent.com/assets/1130890/12764491/1893af12-c9c8-11e5-8e30-39c469f1db98.png)

**Comment by rdbartlett** [comment]
Currently when I view that proposal I get a normal date. Will need more information if we can confirm and fix this bug.

**Comment by rdbartlett** [comment]
Let's re open when we see this next
