### ISSUE TITLE
Emoji renders in comment emails but not proposal starting emails

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#2931]
![image](https://cloud.githubusercontent.com/assets/1380991/12995744/9bdb8214-d18e-11e5-8b30-e9d1dc23a21e.png)

**Comment by gdpelican** [comment]
We've cleared out a bunch of these errors, and should be doing much better on rendering emails and beta pages with emojis. I've reactivated the errbit errors for these, and let me know if there are further instances of this which come through.
