### ISSUE TITLE
Category select is too long for column

### ISSUE THREAD

**Issue by peterwallhead** [loomio/loomio#2935]
On https://www.loomio.org/explore, which causes the label and select element to no longer be inline.

Forked and cloned the repo so I can work out an easy fix.

**Comment by gdpelican** [comment]
Super happy to have an easy fix for this one, but be aware that the explore page is part of our beta interface, and that it's our plan to decommission beta completely around spring or summer this year.

**Comment by gdpelican** [comment]
Closing this for now as we don't have plans to fix this. Keep an eye out in the near future for a shiny new explore page in the angular interface!

**Comment by peterwallhead** [comment]
@gdpelican, that's cool. I couldn't run Loomio up anyway to work on this because I'm on a Windows box.
