### ISSUE TITLE
Emoji link breaks tab+enter to post comment

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#2940]
Pressing tab + enter to post is a pretty standard UI element for lots of tools. But the way the emoji link has been set up on Loomio means that if you type a comment and press tab + enter, you get the emoji menu instead of posting your comment. It's a small thing, but I think Loomio should stick to standards like this when possible.

**Comment by gdpelican** [comment]
This'll be fixed before you can say :hankey:
