### ISSUE TITLE
Previous Proposals are not linked to discussion threads

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#2948]
If you browse the previous proposals in the group, there seems to be no way to get from there to the actual discussion/proposal. For example, today I was looking through the archive of decisions and I wanted to click the title and go to the discussion so I could add a comment asking for a followup. But the title is just text, not a link. In order to find that discussion and comment on it, I had to leave that page and use the search.

**Comment by robguthrie** [comment]
You're right! It's really sad huh. Thanks for chiming in about it, that helps us prioritise the work. We'll look at it tomorrow.

**Comment by rdbartlett** [comment]
@mhjb is going to update the design for this :)

**Comment by rdbartlett** [comment]
Let's also make sure we fix #2777 when we implement the next change to previous proposals.

**Comment by gdpelican** [comment]
I reckon it'd be a nice easy improvement to make that title a link to the discussion page; wonder if you'd be willing to put this on your list @HSalmon ?

**Comment by HSalmon** [comment]
Can do!

**Comment by gdpelican** [comment]
Fixed in #3048
