### ISSUE TITLE
Can't save when switching closed subgroup to secret

### ISSUE THREAD

**Issue by toupeira** [loomio/loomio#2952]
Steps to reproduce:

1. Create group
2. Create sub-group with level "Closed" and "Members of ... can see private threads" checked
3. Edit the sub-group and change the level to "Secret"
4. Clicking "Update settings" asks for confirmation but doesn't save and close the dialog, the server responds with 422 Unprocessable Entity

Workaround is to uncheck the permission before saving.

**Comment by robguthrie** [comment]
Yikes! Thanks, I'll fix it shortly!

**Comment by gdpelican** [comment]
Fixed in #3061
