### ISSUE TITLE
Link to comment from notification broken

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#2956]
If I hover over this notification...
<img width="327" alt="screen shot 2016-02-16 at 3 14 53 pm" src="https://cloud.githubusercontent.com/assets/5498878/13065320/10a1578e-d4c0-11e5-9458-7dce97649ad7.png">

The status bar indicates it should link to https://www.loomio.org/d/Hzvy54Is/members-retreat-reflections?comment=916607, but when I click it, it actually sends me to https://www.loomio.org/d/Hzvy54Is/members-retreat-reflections%3Fcomment=916607 (the ? has been replaced with %3F), which is a broken link.

**Comment by rdbartlett** [comment]
Thanks for the great report Alanna. Let's fix this on #2946.
