### ISSUE TITLE
Emoji not rendering in markdown heading

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#2963]
![image](https://cloud.githubusercontent.com/assets/1380991/13094413/591cc728-d56f-11e5-8c2c-eabd65e60839.png)
![image](https://cloud.githubusercontent.com/assets/1380991/13094419/64ad2d4e-d56f-11e5-9f47-b13f750cdbc1.png)

**Comment by gdpelican** [comment]
Fixed #2965
