### ISSUE TITLE
Make it more obvious that your vote failed due to the statement being too-long 

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#2979]
![image](https://cloud.githubusercontent.com/assets/970124/13162687/4a7d3796-d70b-11e5-97c4-e8e74e615d26.png)

If you submit a vote with a too-long statement, it should give a friendly error message, in addition to the red number. Something like "Please keep your statement under 250 characters. This provides a concise summary for people catching up with the proposal."

**Comment by mhjb** [comment]
Submit position (awkward phrase) should at least disable, eh

**Comment by fiskr** [comment]
I would add that this should be dynamic. Nothing more annoying than finding out your comment is too long after writing it - it would be nice to have a character count as you type out your statement.

Also, I would like to know why there is a 250 character limit. It seems to me that people often have much to say, and little room to say it in.

**Comment by rdbartlett** [comment]
Hi @fiskr the intention of the character limit is that it encourages people to summarise their reasoning. There's a discussion thread for long comments. In a complex thread, you can have 1000s of words of comments, which is very off-putting for people who arrive late to the conversation. Quickly reading through the vote statements is a very effective way to get up to speed without a huge effort. So I feel pretty strongly that this feature makes the deliberation more inclusive.

**Comment by fiskr** [comment]
> the intention of the character limit is that it encourages people to summarise their reasoning

I had suspicion it might be intentional. I am new to the tool, so I am glad to have learned this. Thank you.

Should I perhaps create a separate issue for my feature request of making a dynamic character count so you know how close you are to your 250 character limit?

**Comment by rdbartlett** [comment]
Yeah good idea :)

I'm not sure right now how @gdpelican and @robguthrie are prioritising feature requests. I know they have a really stacked todo list!

**Comment by fiskr** [comment]
I am a software engineer and webdev, and wouldn't mind helping out. Just need to find the time to invest in learning the ins-and-outs of this codebase. :-)
