### ISSUE TITLE
loomio.org references insecure resources

### ISSUE THREAD

**Issue by GeorgeDewar** [loomio/loomio#2981]
loomio.org does not show as secure in Chrome (and probably all browsers) because it references some resources over http.

![image](https://cloud.githubusercontent.com/assets/5344417/13205204/71b906a8-d947-11e5-813a-a3cb3b8168ac.png)

As the console warnings say, these should be referenced over https.

**Comment by rdbartlett** [comment]
Good spotting thanks George. I can confirm that those links would still work if they were being requested over https. I'm not sure where in the code that URL is being composed though.

**Comment by gdpelican** [comment]
I'll take this one actually @HSalmon ; I'll just have to update the values in the production DB. Thanks for the catch @GeorgeDewar , should be sorted soon.

**Comment by gdpelican** [comment]
Looks good to me in prod!
