### ISSUE TITLE
Show emoji title on hover

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#2988]
When an emoji is in a thread, I should be able to see what emoji it is by hovering over it.

**Comment by robguthrie** [comment]
So yea.. I was thinking this too. Currently the alt text is the emoji in
unicode.. which made me think: "What is that like for screenreaders?" I
think updating it to use the name of the emoji as the alt code would be
good.

**Comment by gdpelican** [comment]
Yep. The code that does that is buried in the emojione library at the
moment, but we should be able to find some way to do this.

**Comment by gdpelican** [comment]
https://github.com/Ranks/emojione/issues/140

**Comment by gdpelican** [comment]
Good news on this one; I think emojione has developed this feature and will turn it on by default
https://github.com/Ranks/emojione/issues/140#issuecomment-262686022
