### ISSUE TITLE
which node version does the angular app use? 

### ISSUE THREAD

**Issue by Connoropolous** [loomio/loomio#2992]
and maybe it should/could be specified in the package.json :)

**Comment by gdpelican** [comment]
We're on 4.2.6; I think @gardner mentioned the other day that you can specify the version in the 'engines' field in package.json; would you be up for throwing that in, @Connoropolous ?

**Comment by Connoropolous** [comment]
yep, I'd be happy to. I'm trying it out right now with node 5.5.0 and npm
3. A couple small issues (because it flattens a lot of the node_modules
folder tree) but looking promising. I'll put something in when I get
further along

On Tue, Feb 23, 2016 at 9:19 AM, James Kiesel <notifications@github.com>
wrote:

> We're on 4.2.6; I think @gardner <https://github.com/gardner> mentioned
> the other day that you can specify the version in the 'engines' field in
> package.json; would you be up for throwing that in, @Connoropolous
> <https://github.com/Connoropolous> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/loomio/loomio/issues/2992#issuecomment-187366994>.
>



-- 
Connor Turland
~to craft a sustainable and thriving culture within and without myself~
co-creator of Metamaps.cc

**Comment by gdpelican** [comment]
I specifically couldn't get it to work with node >5, which is why we're
playing it safe with the latest 4 version at the moment.

**Comment by gdpelican** [comment]
I've added an engines entry to the package.json file here: #3026 which will track versions of npm and node known to work with the current Loomio.
