### ISSUE TITLE
Remove Persona from the sign in options

### ISSUE THREAD

**Issue by Connoropolous** [loomio/loomio#2993]
![screen shot 2016-02-23 at 8 50 24 am](https://cloud.githubusercontent.com/assets/1409121/13230552/ae077702-da0a-11e5-8a5b-eb22890f0df4.png)

from: https://developer.mozilla.org/en-US/Persona

**Comment by gdpelican** [comment]
Yep, we've discussed this but haven't gotten to it. But now that there's an issue, someone will likely pick it up, thanks.

**Comment by gdpelican** [comment]
This might be a good medium-sized project for you, @HSalmon .

Steps in my head
- Search the repo for references to persona (notably buttons on the signup form, and references to Persona in any omniauth controllers) and remove them.
- Create an account with persona (could be on production), then ensure that you can create a normal password for yourself by using the reset password flow.
- If you can, we'll want to display a flash message after people log in with persona with a reset password link.
- If you can't, we'll display a flash message saying 'please get in touch with us so we can get you a password'
