### ISSUE TITLE
Anonymous users don't get Angular UI

### ISSUE THREAD

**Issue by toupeira** [loomio/loomio#3013]
For example if you visit https://www.loomio.org/g/WmPCB3IR/loomio-community in incognito mode you'll get the old design.

**Comment by gdpelican** [comment]
Why, I was just working on this today! There's a hurdle around making sure that googlebot (which is always logged out) can effectively index our content within the new interface.

**Comment by toupeira** [comment]
Well look at that, I did make sure to search the issues but didn't think to check the PRs ;-)

And yep I forgot about indexing, I know [prerender_rails](https://github.com/prerender/prerender_rails) works well, but there might be simpler options that don't require running another service.

**Comment by gdpelican** [comment]
This is live now!

**Comment by toupeira** [comment]
Cool, thanks!
