### ISSUE TITLE
Change user mentioned email title to include discussion title

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3021]
When someone mentions me in two different threads in one group, the subject line is the same for both messages. This means my email client stacks both messages into one email thread, so the reply-to function is clumsy and confusing. 

Suggested solution: 
replace the subject line "Robert Guthrie mentioned you in the Loomio Community - Contributors group on Loomio" with a line like "Robert Guthrie mentioned you while discussing 'Loomio in te reo'"

(I think this is only the case when "Activity from the threads I participate in" is not selected in my email settings.)

**Comment by gdpelican** [comment]
@rdbartlett Do you think we need different email subjects based on whether you're following a discussion or not?
