### ISSUE TITLE
Start thread privacy notice wrong

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3024]
This is a secret subgroup.

![image](https://cloud.githubusercontent.com/assets/1380991/13341448/b37b5592-dc9d-11e5-92f4-d9c11fd4d005.png)

**Comment by robguthrie** [comment]
@gdpelican could this be a drafts issue? I cannot reproduce it

**Comment by mhjb** [comment]
It might have involved a draft, but if so it was an empty one.

**Comment by gdpelican** [comment]
It's totally a draft thing. Have to take some some to reproduce to figure
how exactly what's going on though.

**Comment by robguthrie** [comment]
I wonder if you can look into the produciton db and see

**Comment by gdpelican** [comment]
I can't repro this to save my life, and see no evidence of it in the prod DB. Are you still seeing this in a particular place, @mhjb ?

**Comment by rdbartlett** [comment]
(It's working properly for me on Contributors and Co-op Members subgroups)

**Comment by mhjb** [comment]
Still erroring for me — I could demo if that would be any help.

I notice there are 267 rows in the drafts table with my user_id on … a clue?
