### ISSUE TITLE
Validation error for upload attachment

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#3029]
"File has contents that are not what they are reported to be"

This seems to occur primarily for .doc and .txt files; I can confirm a repro by renaming a .png to .txt, and uploading it.

The end user's still getting a 422 (which is expected), so really I just want us to not throw this error.

**Comment by gdpelican** [comment]
http://errbit.loomio.org/apps/56ba953e316565000e000002/problems/56c864bb36376400df000009

**Comment by HSalmon** [comment]
Is the **Security Validations** part of the documentation relevant?

https://github.com/thoughtbot/paperclip#validations

> "NOTE: Starting at version 4.0.0, all attachments are required to include a content_type validation, a file_name validation, or to explicitly state that they're not going to have either. Paperclip will raise an error if you do not do this."

**Comment by gdpelican** [comment]
Don't think so... we're stating `do_not_validate_attachment_file_type` (I
think to keep backwards compatibility with beta), but once we move to all
angular all the time we'll want to constrain to certain file types of our
choosing (probably images, pdfs, .doc/.xls etc.) We probably don't want
folks uploading video.

**Comment by HSalmon** [comment]
So the all attachments are required to have a content_type validation thing is not relevant?

**Comment by gdpelican** [comment]
Closing this because I opened it and don't want to fix. Would rather deal with a few stray errbit emails over investing time in it.
