### ISSUE TITLE
Add wide layout for PC

### ISSUE THREAD

**Issue by s8321414** [loomio/loomio#3032]
Some PC has a wide screen (like 16:9 or other ratio), but we have a narrow layout (at least I think :P) on PC.
I will be glad to see if we have one option about this.

**Comment by gdpelican** [comment]
Hi @s8321414 

Would it be possible to take a screenshot of the layout you're finding hard to navigate? It's very possible we want to jump to a single column layout at slightly wider widths than we do now.

**Comment by s8321414** [comment]
Like ![this](https://cloud.githubusercontent.com/assets/9457283/13388760/dc183364-defd-11e5-8a1e-493642894ca3.png)
It's not hard to navigate, but I think if we can add an option to choose which layout they want to use, it will be great!

**Comment by s8321414** [comment]
I think there is too much space in two sides :P

**Comment by gdpelican** [comment]
Ah yes, I understand now!

It is in the plan for this year to add a sidebar with additional links and information to the dashboard and inbox pages... so there will be more content there at some point. An option for a wider view is a good idea too.

I also found it fascinating to read up a little on the differences between western and eastern web design... difficult to write one website for everyone!

http://www.shutterstock.com/blog/3-things-to-consider-for-culturally-relevant-web-design
http://www.slideshare.net/cxpartners/chinese-web-design-patterns-how-and-why-theyre-different/37-e_36_0_safeguard_is
https://www.minttwist.com/blog/2012/10/17/chinese-web-design-what-are-the-differences/

**Comment by s8321414** [comment]
\o/

**Comment by rdbartlett** [comment]
Something like this Jeff:

![dashboard - default view](https://cloud.githubusercontent.com/assets/970124/13407586/fb06f680-df8d-11e5-8174-7d8eade7e036.png)

**Comment by gdpelican** [comment]
Going to close this for now, but know that it's definitely on our longer term roadmap.

**Comment by s8321414** [comment]
@rdbartlett Ah, it's better!
