### ISSUE TITLE
UI tidbits

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#3040]
https://trello.com/c/gGe64Adr/1228-possible-css-and-ui-improvements

@AaronThornton00 's made some good suggestions for several visual improvements. I agree whole-heartedly with all of them except for maybe the feedback height one. (The misaligned icons and the stroke label in particular bug me quite a bit :) )

Would be nice to knock these out, @HSalmon ?

**Comment by HSalmon** [comment]
Having not a very good time trying to do these minor tweaks, must admit.
