### ISSUE TITLE
Extend google OAuth token expiration

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3041]
bug report from Jessy Kate - "ios (iPhone 6S) oauth login using chrome. not sure if this is a configuration issue or what, but the auth only lasts like 24 hours. so i constantly have to re-login. (i’m using google for login)"

**Comment by gdpelican** [comment]
This seems simple to me but I can't find where we're doing this or how to change it from a cursory glance. Will get back to it. Seems low-ish priority.
