### ISSUE TITLE
Adding or editing cohorts gives error

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3045]
"We're sorry, but something went wrong.

We've been notified about this issue and we'll take a look at it shortly.

Return to your home page"

The cohorts do get successfully created or updated, though.

**Comment by gdpelican** [comment]
Relevant errbit error:
http://errbit.loomio.org/apps/56ba953e316565000e000002/problems/56d72ddb363764013300032b

Rob or I probably ripped out something we shouldn't have when hacking off the old AAARRR table a bit ago.

**Comment by mhjb** [comment]
Possibly relevant — when I next visited loomio.org (as opposed to loomio.org/admin), I got a toast: "Cohort was successfully created"
