### ISSUE TITLE
Add 'Formatting help' link to Start Thread form, like it is on Comment form

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3049]
![image](https://cloud.githubusercontent.com/assets/970124/13479363/35a5af08-e13b-11e5-94e2-694164440a46.png)

Pls check that the submit button is still the first item in the tab order after the Thread Context input.

**Comment by rdbartlett** [comment]
I'm glad to see this link now! Can we fix the tab order though so the submit comes before the link?

**Comment by HSalmon** [comment]
@rdbartlett, do you mean add a tabindex or reorder the file?

**Comment by rdbartlett** [comment]
I don't know the best implementation, I just want to hit tab once to get
from the input field to the submit button

**Comment by gdpelican** [comment]
I think we can put 'tabindex=0' on the formatting link and it'll be golden.
