### ISSUE TITLE
Some 'Out of Office' auto messages are being posted as Loomio comments

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3050]
Got a bug report from Equally Well, I'd love if we can filter out these Out of Office messages, or at least advise on how they can ensure their Out of Office messages conform to our filter.

I can share a copy of the offending message with anyone investigating this.

**Comment by robguthrie** [comment]
send it to me, Rich.

**Comment by rdbartlett** [comment]
Done. Thanks Rob

**Comment by alannallama** [comment]
Happened again here: https://www.loomio.org/d/VK91pxio/possible-bug-changing-proposal-outcome-changes-previous-proposal-outcome-in-comment-thread

**Comment by alannallama** [comment]
I am going to delete the comment due to privacy concerns. If the developers need the data to diagnose the issue, the direct link to the comment was [here](https://www.loomio.org/d/VK91pxio/comment/1033700) - hopefully you can look that up if needed in the database.

**Comment by alannallama** [comment]
I also got a screenshot if needed, but don't want to publish it here for the same privacy reasons.

**Comment by HSalmon** [comment]
@robguthrie, is this fixed with the recent email upgrade?

**Comment by gdpelican** [comment]
I believe we've done a bunch of work to fix this.

**Comment by robguthrie** [comment]
yes.. it's fixed alright! I wonder if we want to push our fork of griddler back up
