### ISSUE TITLE
Link to zh-TW help manual

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#3060]
We've had a translator kindly translate the user help manual into zh-TW, so we should add a line to `UserHelpService` to link to it for Taiwanese / Chinese users.

**Comment by s8321414** [comment]
:+1:

**Comment by HSalmon** [comment]
The zh-TW translation doesn't seem to be live @gdpelican

**Comment by robguthrie** [comment]
I've done the stuff required in loomio-user-manual
