### ISSUE TITLE
Data export errors

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3062]
Visiting /g/GROUPKEY/export.html as a user with rights to use the data export feature, I get "We're sorry, but something went wrong."

**Comment by gdpelican** [comment]
@HSalmon we simply have to remove the `inviter_name` method from `invitation.rb`; I should have caught this in CR, sorry.

**Comment by mhjb** [comment]
Mind letting me know when this is deployed so I can test & tell ze client?
