### ISSUE TITLE
Invite people should be showing on members page

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3070]
![image](https://cloud.githubusercontent.com/assets/970124/13587149/f9f0d7be-e52a-11e5-98ec-2372192c11dd.png)

I'm a member of a group where `members_can_add_members: true`, so I would expect to see the Invite People button on the members page.

**Comment by gdpelican** [comment]
:green_apple: :yellow_heart: :red_circle: :black_large_square:

**Comment by gdpelican** [comment]
:green_apple: Whoa, I hadn't thought of doing it that way, nice!

**Comment by gdpelican** [comment]
Can't quite follow this bit :grey_question:

**Comment by gdpelican** [comment]
I think you could probably make it so you only need to call this in one place, rather than 3. :yellow_heart:

**Comment by gdpelican** [comment]
Hm, I'm pretty sure this gets called elsewhere, so we can't change the method signature like that :red_circle:

**Comment by gdpelican** [comment]
I think we've gone the wrong direction with this feature, it makes the codebase more confusing, and I want to shut it down. Thanks for your work on it! :black_large_square:

**Comment by gdpelican** [comment]
Couple little nit picks, but looks good! :green_apple:

**Comment by gdpelican** [comment]
Had some trouble smoking this, would love to take another look after the JS error gets fixed :recycle:
