### ISSUE TITLE
Comment image order differs after page refresh

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3080]
![image](https://cloud.githubusercontent.com/assets/1380991/13621175/55834146-e5fa-11e5-98da-dfd072dbb4b8.png) ![image](https://cloud.githubusercontent.com/assets/1380991/13621177/5ac50f36-e5fa-11e5-909e-8cab61393759.png)

**Comment by gdpelican** [comment]
@mhjb do you know which one of these orders you'd prefer? I'd guess order in which you added attachments?

**Comment by mhjb** [comment]
Order in which attachments were added (which was how it appears before revisiting page)
