### ISSUE TITLE
Arriving from search, thread scrolls to bottom

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3088]
I think it makes more sense for search results to imitate group page behaviour, where you're taken to the top of threads.

![image](https://cloud.githubusercontent.com/assets/1380991/13651248/67a4e7ec-e6ab-11e5-91c7-9f3f79ac3a02.png)

**Comment by mhjb** [comment]
Maybe scrolling is a bit broken at the mo? I click on a thread or proposal in Unread, and it don't scroll:

![](http://g.recordit.co/jiLfyRjbVu.gif)

**Comment by gdpelican** [comment]
It's a little slow (and we've had reports of some activity threads taking a bit to load), but it works for me.

Not sure I follow about search linking behaving differently than other types of links.

**Comment by mhjb** [comment]
It's actually kinda random for me. In the example in my second gif, I waited for ages and it didn't scroll down. Right now it is scrolling down properly.

Search — I'm almost always looking for a particular discussion (rather than one comment), and it feels weird to be landed at the bottom of the discussion, rather than up top, where I can see the context & proposal (if there is one).

**Comment by mhjb** [comment]
I wonder if good behaviour would be: if there's no unread content, stay at the top. 

(It would also be great if when I manually scroll down the page, Loomio noticed and didn't do any auto scrolling. This would be particularly nice on my iphone 4, on which Loomio is slow, so there's a bit of scrolly weirdness for every interaction with a thread.)

**Comment by gdpelican** [comment]
I think I prefer 'scroll to the last thing I read' always, although would be good to get some more user input.

Yes to cancelling autoscrolling if you interact with the page, also I'd love an easy keyboard shortcut to hop to the thread context. Also maybe making it more obvious that clicking on the lintel (or somewhere else) will take you to the context.

**Comment by gdpelican** [comment]
Going to close this for now; happy to discuss further detail when the time comes around to improve search again.
