### ISSUE TITLE
Threads showing as unread even if you've read them

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3093]
I’m experiencing an annoying bug where there’s a thread with unread activity on my dashboard (say [5]), so i click into the thread and read to the bottom. Then I go back to inbox and the same thread is there with a [1]. I click back into it and there’s no new content, but Loomio thinks the last comment (which I had just read) is still unread. So I have to look at it twice to clear it from Unread.

**Comment by alannallama** [comment]
Happened 3 or 4 times today. Not happening every time. Can't see a pattern.

**Comment by gdpelican** [comment]
#3127

**Comment by alannallama** [comment]
This seems to have come back after a while of disappearing as an issue... Now it's looking a bit different.


It’s doing that thing where I view content but it doesn’t disappear from my unread list. This time it’s not just a (1) that sticks there, but (5) or however many activities there were before I loaded the thread. 

loaded same discussion a few times and still stuck in unread

just went into two different threads and fully loaded them, then went back to unread and they were still sitting there. reloaded the unread page - no change

occasionally one thread successfully was read

the one that was successfully read only had one activity item

the others are going down by one each time i load them, even though i view all activity at once, sometimes. got one that was a (4) down to (1) and now it’s stuck at (1)

reloaded a few times - no change

**Comment by mdshearer** [comment]
Me too! Can't seem to get rid of these threads!
