### ISSUE TITLE
Private / public threads in subgroup inconsistency

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3099]
When I started a closed subgroup of an open group, it said I'd be allowed private & public threads:

![image](https://cloud.githubusercontent.com/assets/1380991/13687007/bab05df4-e77d-11e5-8a7d-bca08b32cde1.png)

But then only private threads were allowed:
![image](https://cloud.githubusercontent.com/assets/1380991/13686986/a612e038-e77d-11e5-9fb6-33c8af5af20c.png)

Now that the subgroup is set up, I can go to Edit Group Settings > Advanced Settings, and tick 'Allow public threads in this group.', but my expectation from the first screen is that would already be set.

![image](https://cloud.githubusercontent.com/assets/1380991/13687168/9e2e430c-e77e-11e5-8815-dedad1a42919.png)

**Comment by gdpelican** [comment]
Would you be willing to have a look at this one @robguthrie ?

**Comment by HSalmon** [comment]
Is this still an issue @mhjb?

**Comment by mhjb** [comment]
No!
