### ISSUE TITLE
intermitent spanish

### ISSUE THREAD

**Issue by mixmix** [loomio/loomio#3102]
this has been happening for me for a year now. 
Loomio interfaces are **mostly** english, but occassionally they are spanish. 

Here are two page loads 10 seconds apart. Same browser, same login.
This happens in the main app for me too 

![selection_299](https://cloud.githubusercontent.com/assets/2665886/13715233/5ca0f096-e838-11e5-981b-8d8708f30894.png)
![selection_298](https://cloud.githubusercontent.com/assets/2665886/13715232/5c9a34fe-e838-11e5-983a-80cd437568f1.png)

**Comment by gdpelican** [comment]
Hm, that's weird. How are you accessing that OAuth page via beta interface? Those views should only be present in the angular version, IIRC.

**Comment by mixmix** [comment]
I just put the url in in that demo app.
I get that Spanish experience in other places too though.

I'll keep an eye out for it in the future and document.

**Comment by gdpelican** [comment]
Closing this as I don't believe we have this problem in the angular interface.
