### ISSUE TITLE
double "membership request approved" notification

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3103]
![image](https://cloud.githubusercontent.com/assets/970124/13716355/64aadeee-e83f-11e5-8d21-0626eee58ab0.png)

**Comment by rdbartlett** [comment]
also got double emails

![image](https://cloud.githubusercontent.com/assets/970124/13716815/426a3bba-e842-11e5-8bf4-ed7bb641f0ad.png)

**Comment by rdbartlett** [comment]
Test that the "approve" button disables on submit.

**Comment by gdpelican** [comment]
I've put a disabled cover on the form in #3112
