### ISSUE TITLE
Shareable link endpoint should tell you what group you're about to join

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3110]
Seems like the heading should be (in this case): "Create an account to join Loomio Community"
 
![image](https://cloud.githubusercontent.com/assets/1380991/13732280/f84226bc-e9e3-11e5-8200-257988760131.png)

**Comment by gdpelican** [comment]
I think I'd like to kick this down the road to when we move the sign up page to angular, which isn't too far down the road.

**Comment by rdbartlett** [comment]
Yep I will make sure there are tickets for all the entry points by the end
of
the week

**Comment by gdpelican** [comment]
Going to close this, we'll be sure to care of it in the angular iteration.

**Comment by mhjb** [comment]
Is this still on radar?
