### ISSUE TITLE
Thread context revision history not showing previous version

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3116]
On d/U49Wi3gH, someone has edited the discussion context accidentally (content is confidential). I want to revert it back to the original, but when I open the revision history, I only see the latest version, not the original. The original was posted 22nd October 2014, 1:10pm, if that helps.

**Comment by rdbartlett** [comment]
I reverted back to angular and found that the context actually had multiple revisions, which weren't showing up in beta.

**Comment by rdbartlett** [comment]
I tried to "restore this version" in beta, but got this:

![image](https://cloud.githubusercontent.com/assets/970124/13790859/3cfe29ec-eb4f-11e5-8b40-b960a098bc68.png)

**Comment by rdbartlett** [comment]
Errbit: http://errbit.loomio.org/apps/56ba953e316565000e000002/problems/56e85f376161390042000b2d

**Comment by rdbartlett** [comment]
I have updated the thread manually now, so we don't need to worry about this specific case. But we should fix the problem with revision histories :)

@HSalmon wanna take a look?

**Comment by gdpelican** [comment]
I wouldn't worry too much about fixing the update_version in beta, but we should get it so we're sure all of the versions are showing in angular.

Also is this a feature we need to port to angular before decomming beta? Seems useful, but not sure it's worth spending time on, especially given that it took this long for anyone to notice it's broken.

**Comment by rdbartlett** [comment]
Yeah update_version is useful but I wouldn't cry if we lost it. cut and paste works pretty well

**Comment by HSalmon** [comment]
I'd be keen to pair with someone on this at some point. It's hard to reproduce.

**Comment by HSalmon** [comment]
@rdbartlett, can I close this for now? Until we get another report?
