### ISSUE TITLE
IHMO members page ought to list the coordinators first

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3117]
… so that in a group with heaps of members I can find out who the coordinators are without scrolling for miles.

**Comment by rdbartlett** [comment]
Let's use the [feedback form](https://docs.google.com/forms/d/1JS75ZdoBiA3k7IzxDPijV4kPh1fXrmWs9A8k_WG_pyE/viewform) for opinions and issues for defects.

**Comment by mhjb** [comment]
Fair enough. I had the feeling it used to work like that & this was a regression.

**Comment by mhjb** [comment]
Will put in feedback form.
