### ISSUE TITLE
Page title wrong

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3123]
![image](https://cloud.githubusercontent.com/assets/1380991/13830003/0724ee4c-ec2f-11e5-9eda-e1c28fd53ba1.png)

**Comment by gdpelican** [comment]
Can't repro; is it always happening for this particular thread? Any additional info?

**Comment by mhjb** [comment]
First time I've noticed it. Here's
<https://www.loomio.org/d/d8nzaSEG/group-categories-we-d-love-your-input->
the thread. When I refresh the title is good again.

**Comment by gdpelican** [comment]
Hm, yeah, I can't seem to repro this, either by navigating to it directly, from the group page, or search result... tried logged in and logged out.

Thanks for the report; I'm gonna close this because it's wee, but let me know if it crops up again.
