### ISSUE TITLE
Slack showing wrong user set proposal outcome

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3125]
I set all these outcomes on Loomio, and on the threads the outcome setting has my name next to it, but on Slack it’s showing as Silvia that took that action. 

<img width="609" alt="screen shot 2016-03-17 at 10 33 14 am" src="https://cloud.githubusercontent.com/assets/5498878/13831215/df08609e-ec36-11e5-83f4-61ff08027020.png">

**Comment by alexykot** [comment]
Confirming that. 

**to reproduce:**
1. create thread 
2. create proposal
3. close proposal, do not create proposal outcome
4. somebody else submits outcome to the closed proposal
5. in Slack the outcome is reported as created by you and not by the other person who actually have created it

**expected:**
In Slack it should give the name of the person who actually submitted the proposal outcome.

**Comment by gdpelican** [comment]
Seems like something @HSalmon could pick up at her leisure.

**Comment by gdpelican** [comment]
I've spent some time today rewriting the serialization logic for the loomio_webhooks plugin to allow it to handle arbitrary json payloads to arbitrary endpoints (which is what 'webhooks' actually implies 🎉 )

I'll grab this one as a side project over the next few days.
