### ISSUE TITLE
intercome not showing deactivated user ID

### ISSUE THREAD

**Issue by natiloomio** [loomio/loomio#3134]
So far I noticed it in 1 user request out of 2 that asked for their account reactivated today.

**Comment by HSalmon** [comment]
@natiloomio, do you reckon this is still a problem? Or was there another reason Intercom didn't display the user details for that particular user?

**Comment by natiloomio** [comment]
I haven't see that problem again yet.

**Comment by HSalmon** [comment]
Ok, do you mind if I close this issue for now, and we can reopen it if we encounter it again?

**Comment by natiloomio** [comment]
sure!
