### ISSUE TITLE
Proposal icon missing text alternative

### ISSUE THREAD

**Issue by chaals** [loomio/loomio#3148]
(related to #3147…)

The way I find out what proposals I haven't voted on is to look at unread messages and check the icon. It's in SVG (good!) but there is not text alternative. I suggest that at least putting in a `title` element would be nice. (SVG accessibility isn't a solved problem yet, but I'm working on it at least for things like this :( )

A [couple](http://svg-access-w3cg.github.io/svg-a11y-tests/title+aria-labelledby.html) of [tests](http://svg-access-w3cg.github.io/svg-a11y-tests/title.html) will show that this is still not brilliant. A dirty hack would be to include a `text` element...

**Comment by gdpelican** [comment]
Hey @chaals would you be able to provide a screenshot of which element you're talking about? The 'unread' tab on the navbar?

**Comment by chaals** [comment]
Yes, opening that tab, if I have unread stuff I can see the proposals and whether I voted on them or not.

**Comment by HSalmon** [comment]
This should be deployed v. soon!

**Comment by chaals** [comment]
\o/ thanks
