### ISSUE TITLE
Email notifications missing text alternatives

### ISSUE THREAD

**Issue by chaals** [loomio/loomio#3153]
When email gets sent including images like (dis)agree icons, there are no text alternatives included. They should have an `alt` attribute…

(this is an accessibility bug)

**Comment by gdpelican** [comment]
@mhjb Would you feel up to this one?

**Comment by mhjb** [comment]
sure!

**Comment by mhjb** [comment]
Great noticing, @chaals!

**Comment by chaals** [comment]
It's one of those things I'm *meant* to notice :)

If W3C keeps using Loomio, I expect to chase a few more edge cases I noticed. Although I'm also impressed that by and large the accessibility is pretty good - so thank you.

**Comment by HSalmon** [comment]
This has been addressed :)

**Comment by chaals** [comment]
Thank you :)
