### ISSUE TITLE
Spot of bother on new email settings page

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3156]
![image](https://cloud.githubusercontent.com/assets/1380991/14051813/8035d16e-f32a-11e5-8364-b24aace7a04a.png)

**Comment by rdbartlett** [comment]
Also this is a bothersome spot.

![image](https://cloud.githubusercontent.com/assets/970124/14068697/092e8394-f4e8-11e5-9bf7-626da66f8b5e.png)
