### ISSUE TITLE
long mentions!

### ISSUE THREAD

**Issue by charlie-ablett** [loomio/loomio#3160]
Looks like nicknames that are too long get 'cut off' if they are longer than what the mention engine can tolerate? If you make a nickname more than 20 letters the last bit is not linked if you use it as a mention.

**Comment by gdpelican** [comment]
Thanks Charlie; this is another strike for ment.io, which I think we want to move off in favor of a more better (material-based?) mentioning engine.

**Comment by gdpelican** [comment]
This is now fixed, hooray!
