### ISSUE TITLE
Adblocker makes contact us do nothing

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3166]
![](http://g.recordit.co/TNiwZ4y1v0.gif)

When Adblocker is off, Contact Us goes to https://www.loomio.org//contact (note the double slash). I was expecting the Intercom widget.

**Comment by gdpelican** [comment]
That's really weird. Can confirm that adblock is affecting the behaviour for some reason.

**Comment by robguthrie** [comment]
It's a really tough problem to work around adblocker here. I've spent days
on this in the past, and don't support just hammering harder as a solution.
It's a tough problem and would like to have a chat with Matthew about
solutions before we do anything.

**Comment by gdpelican** [comment]
Contact us in it's current incarnation is going away, so I'm closing this. Let me know if it crops up again.
