### ISSUE TITLE
Not all discussions showing up in group I'm not a member of, until…

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3167]
When I visited the [translation subgroup](https://www.loomio.org/g/cpaM3Hsv/loomio-community-translation) earlier today, the most recent discussion that showed up was:

![image](https://cloud.githubusercontent.com/assets/1380991/14160616/dfd66e0e-f739-11e5-9bb9-463538f0c614.png)

When I scrolled to the bottom and clicked Show more, and scrolled back up to the top, a new, more recent discussion turned up (discussion key rp0BjDcE):

![image](https://cloud.githubusercontent.com/assets/1380991/14160640/01f2d22a-f73a-11e5-8290-c1b3fad85cdc.png)

Now when I visit the group the Korean discussion shows up properly.

**Comment by gdpelican** [comment]
Hm yeah I think the thread listings on the group page is pretty b0rked. I'll have a look soon.

**Comment by gdpelican** [comment]
I'm attending to this in #3346
