### ISSUE TITLE
Open group I'm not a member of should show previous proposals panel

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3168]
![image](https://cloud.githubusercontent.com/assets/1380991/14160673/51e14da2-f73a-11e5-962f-00596ac6c3e4.png)

**Comment by gdpelican** [comment]
#3172

**Comment by mhjb** [comment]
When I first arrived at https://www.loomio.org/g/NohQxyr9/nzgoal-software-extension-discussion-of-draft (not as a member), I didn't see the Previous Proposals panel. I joined the group, browsed around a bit, then left the group. Then I browsed some more, and happened to notice a [discussion](https://www.loomio.org/d/54Vxapcb/status-of-gpl-in-govt-software-projects) that had a previous proposal.  When I returned to the group page, as a not-member, I can now see the Previous Proposals panel.

**Comment by robguthrie** [comment]
we've seen this inconsistent behaviour in the tests too.. There is a race
condition going on somewhere

**Comment by gdpelican** [comment]
This was a bug where open groups were showing proposals, but closed groups with public content weren't. Now fixed #3241

**Comment by mhjb** [comment]
Doesn't seem to be fixed — http://unctadyouthforum.loomio.org has some proposals but they didn't show up on group page for me until I visited the relevant threads.
