### ISSUE TITLE
Last proposal should be open when you arrive at a thread

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3169]

**Comment by gdpelican** [comment]
Hrm, seems like a regression at some point. I'll take this one at some point.

**Comment by gdpelican** [comment]
Well, I haven't done this yet. Maybe you could grab it @HSalmon ?

**Comment by HSalmon** [comment]
Sure

**Comment by HSalmon** [comment]
I think maybe this is fixed. I can't reproduce. Has anyone experienced this recently? @mhjb?

**Comment by mhjb** [comment]
Happening for me right now on
https://www.loomio.org/d/AyTkIcZC/who-does-loomio-want-as-enspiral-venture-stewards-?proposal=QPahfxm9

Ah a clue: that "?proposal=QPahfxm9" was trailing on my urls from some
earlier visit to perhaps a previous proposals page.

**Comment by gdpelican** [comment]
When you specify the proposal in the url, it's opened. If you take the
proposal=key off, it should work alright.

**Comment by gdpelican** [comment]
So I guess the fix is to clear the ?proposal=key after visiting a page.

**Comment by HSalmon** [comment]
@mhjb, I don't understand, in that particular example the proposal _should_ be expanded

**Comment by mhjb** [comment]
Yeah. If it's helpful, steps to reproduce are:

* visit a proposal via e.g. a closing soon email
* browse to a thread where the most recent proposal is closed (url will still include link to first proposal)
