### ISSUE TITLE
Opening a link from an email notification should ask me to log in

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3174]
If I am not logged in
And I click a link from my 'Yesterday on Loomio' email
Then I should be asked to log in (or logged in automatically?)

Right now I get "You do not have permission to do this"

![image](https://cloud.githubusercontent.com/assets/970124/14261119/6069f5e6-fb03-11e5-8860-56d1691944c6.png)

**Comment by gdpelican** [comment]
I want to design this flow, and I want to push for logging in / signing up within the angular app for this quarter.

**Comment by rdbartlett** [comment]
At very least would it be easy to do a quick fix like "[Login to view private content](#)."?

**Comment by gdpelican** [comment]
Log in with angular is going in pretty much right after beta goes away, I'd
like to get it this sprint actually.

**Comment by rdbartlett** [comment]
And will that fix this issue at the same time?

**Comment by gdpelican** [comment]
This is fixed in #3270
