### ISSUE TITLE
Proposal drafts

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3184]
I wrote a proposal in Thread A, clicked cancel, then clicked Start proposal again but the draft was not saved so the proposal modal was empty. So I shrugged and rewrote the proposal from memory and clicked Start.

I thought maybe the draft hadn't saved because I'd lost my network connection, so I reloaded the app. Then I navigated to Thread B (in the same group), and clicked 'start proposal' over there. And my draft from Thread A's proposal was there waiting for me!

Conclusion: I'm not sure how proposal drafts are supposed to work and what intelligence we have about current defects.

**Comment by gdpelican** [comment]
Can't seem to repro this

Proposal drafts should work the same as any of the other drafts; we save them to the discussion they're associated with, then load em up once you open the modal again.

Any reliable repro steps?

**Comment by gdpelican** [comment]
Ref #3302
