### ISSUE TITLE
Title of marketing page isn't being properly set

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#3189]
![screen shot 2016-04-08 at 12 11 53 pm](https://cloud.githubusercontent.com/assets/750477/14370522/1eb84486-fd83-11e5-9d0a-a4963e409c5b.png)

**Comment by gdpelican** [comment]
I've fixed this in the loomio_org_plugin repo, and it will go live with the next push

**Comment by robguthrie** [comment]
why is the word marketing in the url?

**Comment by gdpelican** [comment]
When you navigate to root, we either redirect you to `/marketing` if you're logged out, or `/dashboard` if you're logged in. This allows you to get to the marketing page manually even while you're logged in if you want to (otherwise it gets swallowed by a `/dashboard` redirect)

At  some point I'd like to host these kinds of landing pages 100% statically with a Jekyll or something, and separate from the loomio app.

**Comment by robguthrie** [comment]
Sorry but I don't think that's be behaviour we were expecting. We want to
remove the redirect to dashboard from root. So there is no /marketing. And
when you are logged in, the Login link changes to "Your Dashboard".

**Comment by gdpelican** [comment]
nooooo, please don't make everyone trudge through the marketing page every time they visit loomio.org. None of the major platforms do this, in fact I have no idea what the landing pages for facebook, github, trello, heroku, twitter,  even look like. What's the rationale for showing logged in users the marketing page?

**Comment by robguthrie** [comment]
They do it on intercom and digitalocean and other places. This is something
that Ben and others are interested in, so we might have to discuss it more
broadly.
