### ISSUE TITLE
Proposal showing "invalid date"

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3191]
<img width="468" alt="screen shot 2016-04-07 at 12 03 54 pm" src="https://cloud.githubusercontent.com/assets/5498878/14372885/d3d5fc9a-fd98-11e5-8932-f59b5203513c.png">

This doesn't seem to be happening on other proposals. If it's relevant, I manually closed this instead of waiting for the pre-set time to roll around. It doesn't show 'invalid' when the proposal is in the expanded view - I only saw it when it was in this collapsed view. However I can't figure out what I need to do to see it in the collapsed view again to check if it's even still happening. Sorry this is probably the worst bug report ever but I don't how how to investigate it more....

**Comment by gdpelican** [comment]
#3204
