### ISSUE TITLE
Unable to set proposal outcome

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3203]
I click 'set outcome' on a recently closed proposal and the modal pops up. I type in the message and click 'publish outcome'. The 'loading' circle spins for a moment, but nothing happens. I press 'publish outcome again' - same thing. I tried on Chrome and Firefox - same thing.

**Comment by gdpelican** [comment]
Hrm @alannallama I just added an outcome to that proposal. Could this be some sort of disconnect between ‘the proposal is closed, but the closing proposal job hasn’t run yet’ @robguthrie ?

**Comment by robguthrie** [comment]
@gdpelican I don't think so. Looks like there is very little validation on the "create_outcome" service method. No mention of closed or closing_at in that path that I can see.

I think that we should prioritise tracking client side errors, at least then we'd have a better chance of knowing if it was a backend or frontend issue.

**Comment by toupeira** [comment]
Just ran into the same issue, the server responds with 422 Unprocessable Entity and this JSON response:

```json
{"errors":{"closing_at":["Proposal must close in the future"]}}
```

In my case it was indeed because the `loomio:close_lapsed_motions` cronjob didn't run, as I missed that part in the docs and had not set it up yet.

**Comment by gdpelican** [comment]
@robguthrie Does the closedOrClosingAt referenced above take care of this one as well?

**Comment by robguthrie** [comment]
I'll look into it now.
