### ISSUE TITLE
Email preferences link goes to unhelpful page

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3217]
I was getting emails on all activity for this discussion (I must have set it to All Activity at some point) 

![image](https://cloud.githubusercontent.com/assets/1380991/14618197/80ed9b6c-0605-11e6-8dc0-bec33e8239f6.png)

I clicked the email preferences link hoping to be able to unsubscribe, but there is no option on the page that will affect whether or not I get emails like that:
![image](https://cloud.githubusercontent.com/assets/1380991/14618199/8647e6e4-0605-11e6-98f9-8f841ecb2f7e.png)

(It's also a Beta page, interestingly)

In this case I think the link should take me to 

![image](https://cloud.githubusercontent.com/assets/1380991/14618286/fa55ae90-0605-11e6-86ca-4daa91f1e8c5.png)

**Comment by gdpelican** [comment]
There's already a PR open for this: #3198
