### ISSUE TITLE
I got a permission denied error when following the "user has requested to join group" notification

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3218]
![image](https://cloud.githubusercontent.com/assets/970124/14623646/3cb3df92-0628-11e6-84a0-9419eda57e84.png)

**Comment by HSalmon** [comment]
Is it possible you logged out in another tab @rdbartlett?

**Comment by rdbartlett** [comment]
Not likely. I will keep an eye out to see if this is a persistent error.

**Comment by gdpelican** [comment]
I think this is fixed, and I'm going to close it for now. Let me know if it crops up again.
