### ISSUE TITLE
Start group form auto focus should be H1 but is whole modal

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3220]
![image](https://cloud.githubusercontent.com/assets/1380991/14624186/9b8f2c84-062c-11e6-9ee0-dc6d0a5d6ee9.png)

ditto at least Start Thread modal

**Comment by gdpelican** [comment]
What's the negative effect of this? Could we get an accessibility person to confirm this should change?

**Comment by mhjb** [comment]
I understand it means screen readers won't read out the modal title when it opens. @rdbartlett will know more than me. 

Do we have some accessibility guidelines published somewhere?

**Comment by gdpelican** [comment]
I'm happy to roll this into the accessibility work that's upcoming, but this bug has been around forever and I'm not convinced it needs to be fixed in this way. Closing for now.
