### ISSUE TITLE
Update FAQ to explain what happens when you remove a user from a group

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3224]
Chatting with Charley from Enspiral:

"CD: when you remove a member from Loomio, do all of their comments / discussion remain in all the threads etc.?

RB: yep, there no change to the threads, just they lose access

CD: cool, good to know! You should put it in the FAQ's (i guess it seems obvious, but as a tyrant admin we need to know these details)"

**Comment by HSalmon** [comment]
Should it go in the FAQ, or in the "Coordinating your group" section, which is where the adding/removing members information is?

**Comment by rdbartlett** [comment]
I don't have an opinion :)

**Comment by gdpelican** [comment]
I've opened this in user-manual: https://github.com/loomio/user-manual/issues/28
