### ISSUE TITLE
You can't tell from looking at the context panel when it's been updated

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3227]
![image](https://cloud.githubusercontent.com/assets/1380991/14661513/4cfa423a-0702-11e6-92a1-7b5b1f6ebd8b.png)

In this long discussion I was looking for an up-to-date summary. It turned out that the context panel had recently been updated, but I couldn't tell that by looking at it — it just tells me Rob started it 7 months ago. I think it might be more useful to roughly follow the format of the edit revisions modal and say "Edited by Alanna Krause 2 hours ago"

**Comment by HSalmon** [comment]
You can see it in the revision history modal (and as a thread activity item in the thread), but you think it would be better to have it as part of the context panel?

**Comment by mhjb** [comment]
Yeah — I think an updated context panel is usually a really significant event in a discussion thread. And particularly in a massive one like this, any individual activity item gets lost / is hard to find.

**Comment by HSalmon** [comment]
The way I'm currently thinking about this means that it’s hard to make the whole line of text a link, seeing as it is actually a button, and we need to use a directive to format the date properly. Do you have thoughts as to how to solve this @gdpelican, @robguthrie? Apologies if the solution is staring me in the face...

**Comment by mhjb** [comment]
How about like this:

![image](https://cloud.githubusercontent.com/assets/1380991/14663854/4b866cc8-0719-11e6-81fe-d16ec7fccd2a.png)

**Comment by mhjb** [comment]
Relevant conversation happening in another Enspiral thread:

![image](https://cloud.githubusercontent.com/assets/1380991/14735985/4ee92242-08c8-11e6-9d77-a41d9913939d.png)

@alannallama does your facilitators' paradise vision touch on this?

**Comment by HSalmon** [comment]
@mhjb, do you mind if I close this for now? We'll be revisiting it soon. Perhaps you could put a card in inbox on the trello board?
