### ISSUE TITLE
Starred thread not showing as starred on thread page

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3236]
https://www.loomio.org/d/en67cwpd/getting-into-the-product-with-no-group

![image](https://cloud.githubusercontent.com/assets/1380991/14663954/4c3c184c-071a-11e6-8663-a2b078ae3017.png)

![image](https://cloud.githubusercontent.com/assets/1380991/14663950/45da67e2-071a-11e6-9966-2e5299121d69.png)

**Comment by HSalmon** [comment]
I'm kinda stumped...

**Comment by camfindlay** [comment]
+1 just came across this same issue.

**Comment by gdpelican** [comment]
This has now been fixed via #3295
