### ISSUE TITLE
Users being emailed about example content

### ISSUE THREAD

**Issue by HSalmon** [loomio/loomio#3239]

**Comment by gdpelican** [comment]
Can we wrap this up into the conversation about better emails @rdbartlett @robguthrie ? I'd like to get this taken care of but don't feel like there's a shared sense on what the right path is.

**Comment by robguthrie** [comment]
yep. good idea. Thanks james

**Comment by mhjb** [comment]
Really? Isn't it clear users shouldn't get emailed the auto-discussions? Seems a small easy to fix break-off-able agile piece, quite independent of the larger better emails issue.

**Comment by gdpelican** [comment]
I fixed this a ways back #3504
