### ISSUE TITLE
No error message when trying to start invalid proposal

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3256]
I set the closing time for 7 hours ago so the form won't submit, but I get no error message:

![image](https://cloud.githubusercontent.com/assets/970124/14725773/092da990-0872-11e6-8dd5-cc165e04f451.png)

**Comment by gdpelican** [comment]
I believe this error comes back correctly through the client side, so I think the fix here is to add something like

```
%validation_errors{subject: "proposal", field:"closingAt"}
```
around the closing at field.
