### ISSUE TITLE
MS Outlook freezes due to incorrect emojione URL

### ISSUE THREAD

**Issue by uportalis** [loomio/loomio#3260]
Hi all

Here is an emojione URL used in loomio's e-mails:
src="//cdn.jsdelivr.net/emojione/assets/png/1f603.png?v=2.1.3"

As you can see, the prefix "http:" is missing.
Due to this, Outlook tries to connect to \\\cdn.jsdelivr.net\emojione\assets\png which fails after several seconds freeze.
I'm not sure how other e-mail clients would handle this incorrect URL.

Rgds,
Louis

**Comment by gdpelican** [comment]
Good catch. I'll put this one on my list.

We should be serving those images from the Loomio server anyhow, so this is a missing piece from #3115

**Comment by gdpelican** [comment]
#3351
