### ISSUE TITLE
Irrelevant notifications open proposal outcome modal 

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#3262]
Recently, we put in a change to allow users who clicked on 'proposal has closed' notifications to open the Create Proposal Outcome modal.

However, I'm seeing the modal appear when I click on an entirely unrelated notification

Something for you to pick up at some point @HSalmon ?

http://g.recordit.co/aLezdWC6Xu.gif

**Comment by HSalmon** [comment]
Can do!

**Comment by HSalmon** [comment]
I've made a PR for the first part of this (https://github.com/loomio/loomio/pull/3275), but I don't understand why it's opening for other notifications at this stage. Might need to pair on it

**Comment by gdpelican** [comment]
Looks to me like $routeParams.outcome is sticking while navigating between
threads, so will probably need to prevent that somehow.

**Comment by HSalmon** [comment]
Yeah, I'm afraid I'm not sure how to do that exactly. I could do something like this ```$routeParams.outcome = null```, but I'm not sure when the optimal time is
