### ISSUE TITLE
Gift plan card remains after setting up a subscription

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3265]
… until I refresh the page

![image](https://cloud.githubusercontent.com/assets/1380991/14805282/9c20c800-0bbe-11e6-80c2-73510151c506.png)

**Comment by gdpelican** [comment]
That implies the webhook isn't pinging Loomio correctly. I wonder if our endpoint over there has gotten messed up somehow.

**Comment by mhjb** [comment]
FYI the subscription record for that group was correctly updated

**Comment by mhjb** [comment]
Just tried this again now — same thing

**Comment by gdpelican** [comment]
Moving this into the umbrella of #3479, as they're the same issue
