### ISSUE TITLE
Strip markdown from explore page

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#3267]
Notes:
- I'm happy to clear out markdown characters entirely; If 'We're # 1' becomes 'We're 1', that's probably fine for now, let's start with a simple substitute and go from there.
- I'd either like to keep links intact, or show only their text part (so `[hello](http://hello.com)` could either stay that way, and get rendered as markdown in the preview, or it could become just `hello`)
- I want to clear out line breaks and just give a text dump of the first 100 characters or so in the description.

**Comment by HSalmon** [comment]
@gdpelican, we wanted to do this, but I wasn't sure what the easiest way was...just regex?

**Comment by gdpelican** [comment]
Yeah, I wonder what something like 'show the 1st 100 characters of the description which are alphanumeric OR common punctuation (comma, period, question mark, colon, semicolon, slash)

**Comment by robguthrie** [comment]
I'm cringing at this approach. I feel like it will result in ugly
descriptions. I think I'm up for pairing with you on this Hannah. I think
we can accurately create regexes to remove markdown.

**Comment by gdpelican** [comment]
Honest I think stripping markdown from plaintext is a Bad Idea™ because the whole point of markdown is that it's plaintext.

This is something we want to go the easy 80% on and then stop imho.

**Comment by robguthrie** [comment]
Well let's just not do it. Let's close this now.
