### ISSUE TITLE
No visible error when requesting to join a group with an existing member email

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#3279]
When requesting to join a closed group, with an email of a member already in the group, there is no error message. The 422 returns errors correctly, so we only need to add a %validation_errors element for the email field on the membership request form:

![screen shot 2016-04-28 at 10 51 57 am](https://cloud.githubusercontent.com/assets/750477/14870590/5c8196da-0d2f-11e6-8bb4-0a48ea08d22c.png)

**Comment by HSalmon** [comment]
Done!
