### ISSUE TITLE
Where is the admin panel?

### ISSUE THREAD

**Issue by chrischristo** [loomio/loomio#3283]
I can't seem to find where the admin panel is, if there is one?

I've found nothing mentioned on [Loomio's github](https://github.com/loomio/loomio) or the [help guide](https://loomio.gitbooks.io/manual/content/en/index.html).

**Comment by chrischristo** [comment]
Also, I'm hoping there is a way to alter the design of the site? (I'm assuming somewhere in the admin panel) Or is it a case of having to fork the code and create own build with custom designs? I saw [this](https://www.loomio.org/d/4vG7NMBS), but it is from 4 years ago, so not sure how much of this applies now?

**Comment by robguthrie** [comment]
Hi Chris, you will need to fork and come up with a new design. It would be
great to learn what you've changed and see if we can make modifying the
Loomio theme easier.

**Comment by robguthrie** [comment]
Also the admin panel is found at /admin. You'll need to login via the rails
console and make your user an admin first.

**Comment by chrischristo** [comment]
> Also the admin panel is found at /admin. You'll need to login via the rails
console and make your user an admin first.

Is there any sort of readme/guide anywhere I can use for this? I'm not really familiar with ruby.

**Comment by gdpelican** [comment]
Following the quickstart guide (specifically the `rake bootstrap` step) should create an admin user for you, and print out the credentials you need like this:
```
Created user with email default@loomio.org and password <a_password>
```

You can edit the email / password of this user by logging in and visiting `/profile`, and you can visit the admin panel by visiting `/admin`

**Comment by chrischristo** [comment]
Well I had setup loomio via [loomio-deploy](https://github.com/loomio/loomio-deploy) with its docker container, so I wasn't following the quickstart guide. In the loomio-deploy guide, nothing is mentioned about how to access the admin page, or how to create an admin. I guess I'm supposed to log in to the container and do something?

**Comment by chrischristo** [comment]
Ok after setting a local development, I noted the username and password from the following:

```Created user with email default@loomio.org and password <a_password>```

After logging in with this account, I still can't access the ```/admin```, it just redirects me back to the dashboard.

Issue is still not resolved, please help.

**Comment by chrischristo** [comment]
After a bit of playing around and digging, I managed to set myself as admin by updating the field ```is_admin``` in the users table. 

This was all based on shooting in the dark with no guidance whatsoever, and involved trying to find out which container held the db, then figuring out what the db name, username and password were, then figuring out there is an ```is_admin``` field on the ```users``` table, and guessing that would do something.

For anyone else looking for this, you need to do the following:

**(1) Login in to the db container**

```docker exec -i -t loomiodeploy_db_1 /bin/bash```

(You can see a list of the docker containers running with ```docker ps``` or alternatively check the ```loomio-deploy/docker_compose.yml```).

**(2) Login to postgres sql (```psql```).**

```psql -dloomio_production -Upostgres -W```

(The only information that loomio lists is the password listed in the ```loomio-deploy/docker_compose.yml``` file which is ```password```. The username I found turned out to be ```postgres``` as thats the default used by the postgres container (https://hub.docker.com/_/postgres/) which loomio uses to setup its db container. After logging in to ```psql``` I ran the ```\l``` command to show a list of databases, which showed up a ```loomio_production```)

**(3) Show the list of users.**

```select id, email, is_admin from users limit 10;```

**(4) Update the user's ```is_admin``` field.**

```update users set is_admin=true```

**Comment by popindavibe** [comment]
@chrisdchristo : thank you for the little step by step howto, very much appreciated!

**Comment by zsimoes** [comment]
Are there any news regarding this issue? As of October 2017 I found no documentation on this, and no easy way around it, except for @chrisdchristo 's comment (btw, thanks!)
