### ISSUE TITLE
Add some more info in the quickstart.md

### ISSUE THREAD

**Issue by chrischristo** [loomio/loomio#3284]
In [the quickstart guide](https://github.com/loomio/loomio/blob/master/docs/en/development_handbook/quickstart.md), please add the following commands before ```rake bootstrap```.

```gem install bundler```
```bundle install```

**Comment by gdpelican** [comment]
I'm surprised at this feedback because `rake bootstrap` runs these commands: https://github.com/loomio/loomio/blob/master/lib/tasks/bootstrap.rake#L7

What kind of trouble did you run into?

**Comment by robguthrie** [comment]
How can you run rake if you have not installed the gems though? This script
should be a shell script..

**Comment by chrischristo** [comment]
Well simple really, after trying to run ```rake bootstrap``` it gave some sort of error which I figured was related to ```bundler``` not being installed. I then installed it (```gem install bundler```) and run again to which this time, the error indicated that I needed to run ```bundle install```. After doing so, ```rake boostrap``` was able to run without error.

**Comment by chrischristo** [comment]
I also needed to have ```postgresql``` installed on my mac (```brew install postgresql```) before ```bundle install``` could even work.

**Comment by robguthrie** [comment]
Thanks Chris. Are you able to edit the document (maybe via github) and help
us improve the situation?

**Comment by chrischristo** [comment]
Hi Rob, just noticed the [Setup Environment](https://github.com/loomio/loomio/blob/master/docs/en/development_handbook/setup_environment.md), as far as I can that covers everything! Awesome :).

Will submit a pull request if I see anything missing.

**Comment by robguthrie** [comment]
Oh Great. Glad that helped.
