### ISSUE TITLE
Unable to mark as read

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3296]
![](https://i.gyazo.com/72b09c421055810163bcd2cbfbe58e11.gif)
Mark as read button is having no effect - sometimes. This is not happening on all discussions, but some seem to be "stuck".

I tried reloading inbox and clicking again, and then it worked. This has happened to be several time over the last couple days.

**Comment by rdbartlett** [comment]
I'm having the same experience on some threads. No console errors.

**Comment by rdbartlett** [comment]
I'm having the same experience on some threads. No console errors. Also when I navigate to the thread, it doesn't get marked as read.

**Comment by HSalmon** [comment]
Great bug reporting everyone!
