### ISSUE TITLE
Data export doesn't work any more

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3299]
the routes look like groupkey/export.xls and groupkey/export

**Comment by gdpelican** [comment]
I'm tempted to fix this by writing a group JSON exporter, rather than digging up the old functionality. Thoughts @robguthrie ?

**Comment by robguthrie** [comment]
Sorry, they are different things. The data export is something for sales
team, and should not be changed. I strongly reocmmend you dig it out of the
history and replace it as is.

**Comment by mhjb** [comment]
@gdpelican sorry to be a botherer, but there's an invoice dependent on this fix

**Comment by gdpelican** [comment]
Hey @mhjb I'm finishing this work off now; I've reverted export to be the way it was before, and `key/export` seems to work fine, but `key/export.xls` is broken for me; I'm getting this is my weirdo-non-Excel-spreadsheet app:

![screen shot 2016-05-09 at 2 29 14 pm](https://cloud.githubusercontent.com/assets/750477/15104375/74dde91a-15f2-11e6-9d19-b94e50539951.png)

I guess my question is, 'how did this ever work?' Are we missing another view for excel-ifying the data somewhere @robguthrie ?

**Comment by mhjb** [comment]
It just worked by magic, I think. Excel would happily open an html file containing a table with an XLS extension.

**Comment by robguthrie** [comment]
Nope. It is excel magic. It supports converting html to tables. I've used
it a few times in client contracts too
