### ISSUE TITLE
Recent Threads + login button

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3300]
Sorry if this is a dupe. This is what I get on my phone when I visit /dashboard while logged out

![2016-05-02 14 45 52](https://cloud.githubusercontent.com/assets/1380991/14946324/aecfeaca-1074-11e6-94ae-9fbebadba5ca.png)

**Comment by gdpelican** [comment]
Yeah.. we need to redirect to somewhere other than dashboard/inbox when you're not logged in.

Redirects are trickier than they should be due to our munted router, but I'll fix this somehow.

**Comment by gdpelican** [comment]
This is fixed in #3270
