### ISSUE TITLE
Unreliability with drafts

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3302]
In one tab I started writing a comment (discussion GlIEcJUZ). I loaded a new tab and browsed to discussion x273LdUm and the draft of the earlier comment showed up.

Likely related to #3184

**Comment by alannallama** [comment]
I've experienced this as well. In fact, it was a draft comment from a completely separate group.

**Comment by mhjb** [comment]
Also drafts hang around on their own threads a lot too. Might have something to do with using Cmd+Enter

**Comment by gdpelican** [comment]
Going to consolidate our drafts issues under this issue. Also, have folks been experienced this recently? I can't say I've ever seen it.

**Comment by mhjb** [comment]
Thanks JK. I haven't seen it recently
