### ISSUE TITLE
Threads that don't move properly

### ISSUE THREAD

**Issue by natiloomio** [loomio/loomio#3303]
"I've moved several threads to an Archive Subgroup, but they still appear in the Main Thread List (as well as the Archive Subgroup)... I've signed out, closed and fully exited the browser, rebooted the macbook air, reopened Loomio in the same and a few different browsers, and on different computers, and logged in as my wife on her computer to see her view."

**Comment by HSalmon** [comment]
@natiloomio, if the user is on the groups page then they will see threads group any subgroups related to that group as well. Currently we don't separate parent group threads and subgroup threads on the group page.

**Comment by robguthrie** [comment]
If there is private information we need to remove this image

**Comment by HSalmon** [comment]
I've removed the image.
