### ISSUE TITLE
Didn't get proposal closed email

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3304]
… for a proposal I started (tvxcFnSA). Did get the closing in 24 hours one.

@robguthrie I heard you said something about a Google Apps bug interacting with this? I'm on an @gmail.com address

**Comment by robguthrie** [comment]
@mhjb the bug only concerns google apps accounts.. not standard gmail accounts.

**Comment by robguthrie** [comment]
```ruby
  def self.motion_closing_soon(motion)
    User.distinct.where.any_of(Queries::UsersByVolumeQuery.normal_or_loud(motion.discussion),
                               User.email_proposal_closing_soon_for(motion.group))
  end
```

So assuming your thread was loud or normal, or you had the old global enabled.. you should have been sent an email.

I just checked the email logs from metabase and you have opened all motion_closing_soon emails that have been sent recently.

**Comment by robguthrie** [comment]
@mhjb can you look out for when the next one you should be sent is, and let me know if that arrives?

**Comment by mhjb** [comment]
ok

**Comment by HSalmon** [comment]
I received a proposal closed email yesterday (as expected). Any news on this front @mhjb? @robguthrie?

**Comment by gdpelican** [comment]
Strikes me as one of those pesky delayed email issues.

**Comment by mhjb** [comment]
I got a notification but no email for https://www.loomio.org/d/ov5bzjO9/proposal/5HlNw7dV

**Comment by robguthrie** [comment]
I don't trust google to deliver emails on time right now. It makes
resolving this really hard.

**Comment by mhjb** [comment]
To me it doesn't feel like a timing issue — those particular emails never arrived, but others related to the same threads (incl a Proposal outcome set one) did.

**Comment by robguthrie** [comment]
Thanks for keeping at it:

```
Queries::UsersToEmailQuery.motion_closing_soon(m).include?(u) => true
Queries::UsersToEmailQuery.motion_closed(m).include?(u) => false
```

Loomio says you have "normal" volume. So according to that you should get an email for closing soon, but not for closed.

**Comment by mhjb** [comment]
Ah!

That doesn't make much sense, eh?
