### ISSUE TITLE
Proposal outcome webhook showing proposal author instead of outcome author

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3307]
![image](https://cloud.githubusercontent.com/assets/1380991/14971664/8826180e-1128-11e6-9954-b896732f29b8.png)
(it was @HSalmon)

**Comment by HSalmon** [comment]
@gdpelican, you've fixed this in your latest webhook updates, eh?

**Comment by HSalmon** [comment]
It is fixed!
