### ISSUE TITLE
In reply to blank

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3309]
![image](https://cloud.githubusercontent.com/assets/970124/14973408/7ab74022-113b-11e6-9b30-ecac304f36cf.png)

Discussion id: G0BegSO8

**Comment by HSalmon** [comment]
I'm pretty sure that this is because the author of the comment you are replying to has an apostrophe in their name - testing this locally seems to prove that thinking. However, I'm not 100% sure what the best way to fix it is. @robguthrie? @gdpelican?

**Comment by robguthrie** [comment]
I suspect it's something about how we use Angular Translate. Check this
out: https://angular-translate.github.io/docs/#/guide/19_security

**Comment by HSalmon** [comment]
And it was! Thanks @robguthrie. PR over there ^^^

**Comment by HSalmon** [comment]
Should be fixed!
