### ISSUE TITLE
Intercom messenger not opening

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3311]
I see this error when I load the inbox, and I get no result when I click "Contact us"

![image](https://cloud.githubusercontent.com/assets/970124/14973574/a65bfd2e-113d-11e6-926a-cd1b6092f475.png)

@natiloomio has been in contact with Intercom, can you share what you've learned Nati?

**Comment by HSalmon** [comment]
But it works for you eh, @mhjb?

**Comment by mhjb** [comment]
Yes it does. It has in the recent past not worked, or only worked 5 minutes after clicking Contact us (!)

**Comment by HSalmon** [comment]
But it is currently working for you?

**Comment by rdbartlett** [comment]
Yeah it works for me after a few minutes, but not when I first load the app.

**Comment by gdpelican** [comment]
I'm closing this in anticipation of the new sidebar. Feel free to reopen if the behaviour persists through that.
