### ISSUE TITLE
Move markdown formatting help into angular

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3312]
I like that I can use this character `>` to delineate someone else's comment within my own. 

> Rob: Yeah it is cool eh

I wanted to share the technique with someone but noticed that it is not included in the formatting help page: http://loomio.org/markdown.

**Comment by HSalmon** [comment]
Having trouble getting this to render correctly:
<img width="704" alt="screen shot 2016-05-03 at 5 24 47 pm" src="https://cloud.githubusercontent.com/assets/2882097/14975280/284f3538-1154-11e6-8f58-6543f66831f9.png">

**Comment by rdbartlett** [comment]
Suggested language: "Quote a block of text by starting each line with a
greater-than sign."

**Comment by HSalmon** [comment]
Thanks @rdbartlett, can implement. @gdpelican, @robguthrie, I cannot get this to render properly. Is there anything I'm obviously doing wrong?

**Comment by gdpelican** [comment]
Is there code?

**Comment by HSalmon** [comment]
https://github.com/loomio/loomio/pull/3338

**Comment by gdpelican** [comment]
Renaming this because this I think is the thing that should happen here; I've had a chat with Hannah about a possible implementation.

**Comment by gdpelican** [comment]
We're not going to do this at the moment.
