### ISSUE TITLE
Viewing other user's open groups issue

### ISSUE THREAD

**Issue by chrischristo** [loomio/loomio#3316]
So I created an open group with one user, and then tried logging in with another. However, the second user can't see the group. Seems like each user can only see his own groups, regardless of whether its open, closed etc. Any ideas?

**Comment by gdpelican** [comment]
You could check out the new [explore page](www.loomio.org/explore), which will be getting some more prominence in the interface in the weeks to come.

**Comment by HSalmon** [comment]
@chrischristo, the second user will be able to see the open group if they navigate to the group url.

**Comment by chrischristo** [comment]
Thanks guys.

1. Is there any way to access the explore page except for navigating to the /explore url? I mean, I can't see it in the menu or anywhere else. Or is this a future plan?

2. Is there a way to show all group info (regardless whether you're part of it or not) in the 'Recent', 'Unread' & 'Groups'? and same question for the search tool.

**Comment by gdpelican** [comment]
Hey @chrischristo, would you be willing to point specific questions at the 'Contact Us' link in-app? That'll point you to the Customer Support folks, who're better equipped to handle queries like this than us lowly devs.

![screen shot 2016-05-04 at 2 53 34 pm](https://cloud.githubusercontent.com/assets/750477/15004220/6d0f9190-1208-11e6-8aae-1b408c4fc443.png)

To answer these questions specifically,
1. /explore just went in; it'll be exposed more as we get a better idea of the workflows that go through it.
2. That would likely be plugin territory, as it's a bit of information overload for the core product. You could start a discussion about a feature request in the [Product development subgroup](https://www.loomio.org/g/GN7EFQTK/loomio-community-product-development) to get the ball rolling if you like, seems like something which could be useful given a little design.
