### ISSUE TITLE
New content in the "unread" view not appearing unless you refresh

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3318]
Been noticing this issue more and more recently. I end up missing new posts because Unread doesn't update until I manually refresh the browser.

**Comment by alannallama** [comment]
This is still going on. My workflow now is to wait for notification of new discussions to pop up on slack, then go manually refresh the 'unread' view to get them to appear. Going into a Loomio discussion or over to the 'dashboard' view and then back to 'unread' does not trigger the new content to appear, only manually refreshing.

**Comment by gdpelican** [comment]
Okay, thanks. We're aware of it.

**Comment by alannallama** [comment]
I have noticed that this seems to often coincide with the other issue where draft comment text hangs out in the comment box even after that comment has been posted. Often it seems threads that do that also stick as unread even if they have been read.

This is what I mean about comment draft hanging out after posting. That text stays even after refresh....
<img width="600" alt="screen shot 2016-07-29 at 2 04 07 pm" src="https://cloud.githubusercontent.com/assets/5498878/17235463/60df6bc2-5595-11e6-9d25-8c27bbaaa633.png">
