### ISSUE TITLE
Missed yesterday email does not have styles

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#3319]
For some reason my missed yesterday email does not have the basic styles applied.

For instance, the avatar icons should be top aligned, and all of the same width, but they are not:

![image](https://cloud.githubusercontent.com/assets/486367/15000265/c537ad06-11e2-11e6-8a40-a4a49b8b643f.png)

**Comment by gdpelican** [comment]
Premailer regression?

**Comment by gdpelican** [comment]
Is this fixed now @robguthrie ?

**Comment by robguthrie** [comment]
Nope. I'm struggling to understand why the styles are not being inlined. A
couple are, but not all.

**Comment by gdpelican** [comment]
Hrm, I can't repro this, although I have seen it happen in prod.

I've been generating events and then sending

```
UserMailer.missed_yesterday(User.last).deliver
```
To see if I can't catch on byebugs set in the premailer gem. (check out this nifty thing for atom: https://atom.io/packages/gemsource). I can confirm it's running the right methods, but doesn't seem to be generating all the styles all the time.

Things that I thought about:
- I noticed that premailer supports both hpricot and nokogiri, and will default to hpricot if both are present, but we don't appear to have hpricot hanging around anywhere (it's old as)
- I wonder if the styles can't be generated on `td` elements, or some other error is being thrown. I wanted to throw a byebug into `lib/premailer/adapter.nokogiri.rb#51`, to see if it was coughing on anything... it seems to eat a few different errors and go on to the next if that's the case. (Ran out of time tho, sorry.)

**Comment by gdpelican** [comment]
This is affecting the new branded emails as well. @robguthrie how would you feel about switching back to Roadie?

**Comment by robguthrie** [comment]
fine indeed.
