### ISSUE TITLE
Search problem

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3320]
Searching for "activation workshop" doesn't find thread called "Activation/onboarding workshop"

**Comment by gdpelican** [comment]
Hey @mhjb I'm going to close this, as it's not a specific problem that's going to get worked on and fixed. Search needs some improvements, we're aware of this, it'll get back onto the prioritization pipeline at some point.

**Comment by mhjb** [comment]
Roger. Product owner asked me to record it as an issue.

**Comment by robguthrie** [comment]
I think that there is some requirements gathering groundwork to be done to
support the next search push. I wonder where we should collect such things.
"It should find this, given this query", "it should prioritise newer
threads this over older ones", "it should prioritise results that other
people clicked on previously"

**Comment by mhjb** [comment]
Could go in here: https://www.loomio.org/d/U6IlJRCy/ux-search-r-d

**Comment by robguthrie** [comment]
I'm afraid I'll never find it!

**Comment by mhjb** [comment]
For the sake of not baddening @gdpelican's buzz too much I want to say I actually have a pretty good time with search most of the time

**Comment by robguthrie** [comment]
awesome
