### ISSUE TITLE
Ahoy visits referrer sometimes is e.g. www.loomio.org/d/…

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3321]
… rather than the actual referrer

**Comment by mhjb** [comment]
see e.g. https://metabase.loomio.io/card/87

**Comment by robguthrie** [comment]
Actually, I think this might be the client browser rejecting cookies.

**Comment by mhjb** [comment]
In this instance it is happening for almost all the visits to the group
(there's only one 'real referrer'). Does that mean it's unlikely it's
bowsers with cookies off?

**Comment by robguthrie** [comment]
I'm still wondering how extensive the problem is... Can we pair on this to understand it?

**Comment by mhjb** [comment]
Sure. Meantime checkout https://metabase.loomio.io/card/96, which is the
last 7 days of referrers.

**Comment by gdpelican** [comment]
Did we ever get anywhere on this? I definitely don't quite understand the problem yet.

**Comment by mhjb** [comment]
No movement on this AFAIK. From the above metabase card there are still lots of visits where the referrer is a page on loomio.org. To my naive understanding anytime there's a visit to somewhere on loomio.org, the referrer (visits.referrer) should be either null, or some url other than loomio.org/… . 

If that doesn't make sense, shall we have a videochat?

Maybe it's related to #3358

**Comment by gdpelican** [comment]
Two reasons the referrer is loomio-based, both very common:

- A user clicks 'login' from the root path
- A user ctrl+clicks anywhere.

I don't think this is a bug.

**Comment by mhjb** [comment]
Seemed smelly to me in combo with Google Analytics seeing lots more 'real' referrers than Ahoy

**Comment by gdpelican** [comment]
In any case, the problem is in the ahoy library, not in our code, and so I don't want to dig through it. Google analytics will be a lot more sophisticated than this gem will be.
