### ISSUE TITLE
Leaving parent group before leaving subgroup seems to result in weird behaviour

### ISSUE THREAD

**Issue by HSalmon** [loomio/loomio#3322]

**Comment by gdpelican** [comment]
Er, you're going to have to be more specific than that, please.

**Comment by HSalmon** [comment]
Alanna reported that she left a parent group before leaving the subgroup, went to deactivate the subgroup but found she wasn't a coordinator even though she was the only person listed when she viewed all members. She couldn't leave the group because when she tried it she saw the "you can't leave because you're the last coordinator" message. When I visited the group in the admin panel she wasn't listed as a member, instead there were 3 members inc. 1 coordinator (none of which were Alanna). I've since archived the group. Group url: https://www.loomio.org/admin/groups/E0aZ6Yi4

**Comment by gdpelican** [comment]
This is something I can't work on without repro steps. I still don't quite understand what the behaviour is here. Is it still an issue?
