### ISSUE TITLE
Tooltips for markdown'd images inside links are wacky

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3324]
E.g.: 

`<a href="http://i.imgur.com/rSDzq2r.jpg" title="<img src=&quot;http://i.imgur.com/rSDzq2r.jpg&quot; alt=&quot;&quot;>" target="_blank"><img src="http://i.imgur.com/rSDzq2r.jpg" alt=""></a>`

from https://www.loomio.org/g/T9ZtzNcD/loomio-community-workers

**Comment by gdpelican** [comment]
Pretty sure that's user error. You can add an alt text to links by adding " " at the end

[Loomio!](http://loomio.org "Hello Tautoko!")

**Comment by mhjb** [comment]
Here's the actual Markdown:

`[![quarterly plan](http://i.imgur.com/rSDzq2r.jpg)](http://i.imgur.com/rSDzq2r.jpg)`

If you add e.g. "Quarterly plan" it renders properly, but if you don't, you get the aforementioned ickiness.
