### ISSUE TITLE
Rename "contact us" to "Help & Feedback"

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3325]
Just saw Google Inbox uses this language and I think it fits the job much more accurately.

**Comment by HSalmon** [comment]
Does this mean we get rid of "Help" and "Contact us" and just have "Help & Feedback" instead?
<img width="212" alt="screen shot 2016-05-05 at 3 29 42 pm" src="https://cloud.githubusercontent.com/assets/2882097/15035462/49491172-12d6-11e6-9205-dc441eaeb82c.png">

**Comment by rdbartlett** [comment]
Oh yeah, good question! I hadn't thought of that, doh. I'm happy to close this issue for now.

Google have got a good solution which prioritises help-your-self over ask-us-questions: you click "help & feedback", which opens up this modal:

![image](https://cloud.githubusercontent.com/assets/970124/15035609/d1fdd8b2-12d7-11e6-832a-9c307509b9e8.png)

Then when you click 'give feedback' it gives you a text field and the ability to take a screenshot and highlight the part you are referring too. Fancy!

There's no obvious way to get in contact.

**Comment by HSalmon** [comment]
Cool, ok, thanks. I might close for now and we can think about this more as we go forward.
