### ISSUE TITLE
Dockerfile fails by default

### ISSUE THREAD

**Issue by dachary** [loomio/loomio#3330]
Steps to reproduce:

* git clone loomio
* docker build --tag loomio .
* docker run --rm -p 3000:3000 loomio
<pre>
[5] Puma starting in cluster mode...
[5] * Version 2.15.3 (ruby 2.3.0-p0), codename: Autumn Arbor Airbrush
[5] * Min threads: 4, max threads: 4
[5] * Environment: development
[5] * Process workers: 1
[5] * Preloading application
[5] * Listening on tcp://0.0.0.0:3000
[5] Use Ctrl-C to stop
[5] - Worker 0 (pid: 8) booted, phase: 0
</pre>
* firefox http://localhost:3000/
<pre>
[8] 172.17.0.1 - - [05/May/2016:08:45:14 +0000] "GET / HTTP/1.1" 302 - 0.0899
[8] 172.17.0.1 - - [05/May/2016:08:45:14 +0000] "GET /marketing HTTP/1.1" 500 175102 0.7425
[8] 172.17.0.1 - - [05/May/2016:08:45:15 +0000] "GET %2Ffavicon.ico HTTP/1.1" 200 1150 0.0007
</pre>

![loomio1](https://cloud.githubusercontent.com/assets/433594/15039665/f79e8d88-12ae-11e6-952e-91986d59bd1c.png)

**Comment by gdpelican** [comment]
Hm, am I right in thinking the dockerfile shouldn't be pulling the
loomio_org_plugin, @robguthrie?

**Comment by gdpelican** [comment]
@robguthrie ?

**Comment by robguthrie** [comment]
it shouldn't but I don't know how to change the plugin system to fix this.

**Comment by gdpelican** [comment]
Sigh. This was the case for having multiple yml files which could load plugins.

How about we have a `plugins.loomio_org.yml`, which has

```
loomio_org_plugin:
  repo:    loomio/loomio_org_plugin
  version: master
```

in it, which is loaded in `deploy.rake`, but not the Dockerfile?

**Comment by dachary** [comment]
@robguthrie @gdpelican I tried to hack my way out of the problem with the following patch.

<pre>
diff --git a/config/plugins.yml b/config/plugins.yml
index 46be6cb..44b87bb 100644
--- a/config/plugins.yml
+++ b/config/plugins.yml
@@ -2,6 +2,3 @@ loomio_webhooks:
   repo:    loomio/loomio_webhooks
   version: master

-loomio_org_plugin:
-  repo:    loomio/loomio_org_plugin
-  version: master

</pre>

I repeated the steps from the description and this time the first page shows a new error. Progress !

![loomio](https://cloud.githubusercontent.com/assets/433594/15500464/20c145f8-21a9-11e6-9ffc-c5608e21a346.png)

**Comment by dachary** [comment]
> which is loaded in deploy.rake, but not the Dockerfile?

Would this be ok : https://github.com/loomio/loomio/pull/3384 ?

**Comment by dachary** [comment]
https://github.com/loomio/loomio/pull/3385 is a step forward

**Comment by gdpelican** [comment]
@dachary By 'a step forward' do you mean that it has resolved your issue, or are you still experiencing trouble?

**Comment by dachary** [comment]
@gdpelican I'm testing right now. I'm under the impression that the "Could not find table user" from https://github.com/loomio/loomio/issues/3330#issuecomment-221226228 unrelated to the plugins. But what do I know ;-) docker image is building, I'll see if the error persists.

**Comment by dachary** [comment]
I confirm that with the current master (30b5281ef1d093638f07448312a8249e52a147a5 ) as installed at http://149.202.174.91 following the steps from the description, the https://github.com/loomio/loomio/issues/3330#issuecomment-221226228 error shows up.

**Comment by gdpelican** [comment]
@robguthrie Do we need a `rake db:create` / `rake db:schema:load` somewhere?

**Comment by robguthrie** [comment]
Nope. https://github.com/loomio/loomio-deploy has a database setup step.

**Comment by dachary** [comment]
@robguthrie could you please confirm that the following steps work for you ? It may be something in my environment.

* git clone loomio
* docker build --tag loomio .
* docker run --rm -p 3000:3000 loomio 
* firefox http://localhost:3000/ 

thanks in advance !

**Comment by dachary** [comment]
@robguthrie ping ?

**Comment by dachary** [comment]
hum, I realized only now that you meant that I probably forgot the step required to setup the database which is found at https://github.com/loomio/loomio-deploy#initialize-the-database . I'll try that now :-)

**Comment by dachary** [comment]
@robguthrie the loomio-deploy instructions work like a charm, I'm impressed ! 

I added a comment to the Dockerfile so others know to go to loomio-deploy at https://github.com/loomio/loomio/pull/3404

**Comment by gdpelican** [comment]
Sounds good, thanks @dachary !

**Comment by robguthrie** [comment]
Ohhhh... right. Now I understand what you were going through! 

I thought you'd ignored the instructions, rather than never found them!

Glad you liked them, I worked hard to get it down to what it is!

Good luck with your Loomio install. @dachary  :)
