### ISSUE TITLE
Ahoy not tracking setup new group email invitation

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3333]
The link emailed looks like:

`https://www.loomio.org/invitations/c1fe5fa85fbebbea632?utm_campaign=invite_people_mailer&utm_medium=email&utm_source=to_start_group`

rather than something like

`https://www.loomio.org/ahoy/messages/………`

**Comment by robguthrie** [comment]
Yea.. it was breaking the tests, so I excluded it.

**Comment by gdpelican** [comment]
I just ran this through the tests again in #3501, and seems to be working alright now (I think we've upgraded the mail and premailer gem recently, so that may have been the culprit)

**Comment by gdpelican** [comment]
Fixed pending deploy
