### ISSUE TITLE
Comment text is retained in reply box after posting

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3345]
When I make a comment, it posts fine but the text sticks in the reply box instead of disappearing. I have to manually delete it to post another comment.

<img width="661" alt="screen shot 2016-05-09 at 12 20 07 pm" src="https://cloud.githubusercontent.com/assets/5498878/15101294/7ef37170-15e0-11e6-9db1-52c93cdbbfc6.png">

**Comment by gdpelican** [comment]
Closing as dupe of #3335
