### ISSUE TITLE
Thread page of group I'm not a member of isn't paginated

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3359]
https://www.loomio.org/d/qsVJ2K1t/backup-and-restore

(54 comments)

**Comment by gdpelican** [comment]
Er, I can't repro on that thread. What do you mean by 'not paginated'? I can go up and click 'previous activity' and get further back in the conversation history.

**Comment by gdpelican** [comment]
I noticed a bunch of things that could be improved about that logged out experience, though, most prevalent being that comments should have a timestamp.

**Comment by mhjb** [comment]
When I visited it two days ago; it didn't have a previous activity button, it just loaded the every comment straight away

**Comment by mhjb** [comment]
But now it's fine
