### ISSUE TITLE
Unable to select gift plan

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3363]
I got presented with the "select plan" model. I selected "gift" and it went to the confirmation screen. I ticked the box saying I was ok for my users to be contacts for donations. But when I clicked "OK Got It" nothing happened. I tested the other options - 'remind me later' and selecting a paid plan both worked. But unable to select gift plan.

Here's a gif of what I did. No matter how many times I clicked "OK got it" nothing happened and I couldn't make the box go away.

![](https://i.gyazo.com/e103ef689f24d3865987dbe81ea39e26.gif)

**Comment by alannallama** [comment]
Tested in both Firefox and Chrome - same thing.

**Comment by alannallama** [comment]
I clicked "remind me" and the modal went away, but when I reloaded the page it came straight back.

**Comment by gdpelican** [comment]
Hrm, unable to repro, I just set up a gift plan alright in prod. Seems like
a javascript error; I wonder if you'd be able to screenshot your javascript
console afterwards? (cmd+shift+I in chrome, click on 'Console')

**Comment by alannallama** [comment]
@gdpelican I tried cmd+shift+I (not sure if L or I so tried both) but nothing happened.

**Comment by gdpelican** [comment]
http://stackoverflow.com/questions/66420/how-do-you-launch-the-javascript-debugger-in-google-chrome
