### ISSUE TITLE
Unable to update group settings

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3364]
I tried to update group settings/description, but when I click the "update settings" button it flashes "loading" and then nothing happens. I'm a coordinator of the group.

![](https://i.gyazo.com/e10cea463f34e3666af3228c46d820f6.gif)

**Comment by alannallama** [comment]
Tested in Firefox and Chrome - same thing.

**Comment by gdpelican** [comment]
Also can't repro. This is smelling like you're logged out, which is a known issue that we don't handle very well. When you reload does it ask you to log in?
