### ISSUE TITLE
Locale being ignored in logged out page

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3367]
Visiting https://www.loomio.org/g/yHRVdrav/le-r-veil-du-gabon with French set in my browser, I see:

![image](https://cloud.githubusercontent.com/assets/1380991/15279307/fa4ed9c2-1b76-11e6-882e-8419cbb0ee71.png)

**Comment by mhjb** [comment]
This one is quite important, I think.

**Comment by mhjb** [comment]
May I have some attention on this one? @gdpelican @robguthrie @HSalmon ?

**Comment by gdpelican** [comment]
#3381
