### ISSUE TITLE
Threads missing until I visit subgroup

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3368]
![](http://g.recordit.co/xYDosk18ZQ.gif)

**Comment by gdpelican** [comment]
I'll grab this one.

**Comment by mhjb** [comment]
Related, I think:

Looking at the Loomio Community group page, I see a bunch of threads from subgroups organised by date descending.

![image](https://cloud.githubusercontent.com/assets/1380991/15693669/38f1d47e-27eb-11e6-9716-f6814d613fcd.png)

But missing is 'Requests from the Board' a thread I started in a subgroup. Here's part of the thread listing on that subgroup:

![image](https://cloud.githubusercontent.com/assets/1380991/15693672/4175fdf0-27eb-11e6-80db-31b204ce4f51.png)

When I return to the Loomio Community group page, that thread has now turned up:

![image](https://cloud.githubusercontent.com/assets/1380991/15693699/81cbe59a-27eb-11e6-95a0-97781a66d764.png)

**Comment by gdpelican** [comment]
Should be fixed in #3492
