### ISSUE TITLE
Margin after lists

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3379]
Unordered lists look good but ordered lists are missing a bottom margin:

![image](https://cloud.githubusercontent.com/assets/970124/15447649/d18ae888-1f49-11e6-8363-8119102f61a3.png)

**Comment by gdpelican** [comment]
Hey @rdbartlett is this on the site or in emails or both?

**Comment by rdbartlett** [comment]
Only seen it on site, haven't confirmed emails
