### ISSUE TITLE
Visiting unsubscribe link from email gives borked experience

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3386]
![image](https://cloud.githubusercontent.com/assets/1380991/15516621/bc81d694-2247-11e6-91b7-5cb6d89a53eb.png)

I seem to be able to change my email settings without logging in. 

Once I do log in from that page, I still get the logged-out header:

![image](https://cloud.githubusercontent.com/assets/1380991/15516735/4dfc9de8-2248-11e6-97e9-3fc3fbd286d5.png)

**Comment by gdpelican** [comment]
This is intended behaviour. You have the ability to change your email
settings if you have an unsubscribe token from your email, but you can't do
other things like comment or vote without logging in.

**Comment by mhjb** [comment]
True!

The second bit is still a bug, I think.

**Comment by mhjb** [comment]
Was that second bit fixed?
