### ISSUE TITLE
Crazy formatting of previous decisions list when there's a long outcome statement

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3397]
When there's an extensive outcome statement, especially with a large image, it breaks the formatting of the "previous decisions" list.

<img width="302" alt="screen shot 2016-05-27 at 11 31 34 am" src="https://cloud.githubusercontent.com/assets/5498878/15593266/bcf10876-23fe-11e6-90f8-3087bc4879a6.png">

**Comment by gdpelican** [comment]
#3399

**Comment by gdpelican** [comment]
Will be deployed soon.
