### ISSUE TITLE
changing proposal outcome changes previous proposal outcome in comment thread

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3398]
_Bug report from Strypey_

I have noticed odd behaviour in the NZ Pirates Loomio, which I think may be the result of a bug. An example of the suspected bug behaviour can be found in the thread on [Genetic Engineering](https://www.loomio.org/d/vOreTYpL/genetic-engineering) in the public Policy Incubator. Proposal outcome statements don't appear to have persistent links (which would be handy), but the first outcome statement can't be found [under this comment](https://www.loomio.org/d/vOreTYpL/comment/1015797), and the second one [under this comment](https://www.loomio.org/d/vOreTYpL/comment/1016809).

Steps to reproduce:
1) proposal goes ahead as normal and closes
2) a member sets the outcome statement
3) another member thinks they can sum up the outcome better, clicks 'Edit proposal outcome', changes the text, and clicks 'Publish outcome'
4) the previous outcome statement, recorded in the comment thread under the first members name, is changed to the new text
5) original members gets upset that someone is retrospectively editing their statements and putting words in their mouth
6) flamewar ensues

OK, 5 and 6 are not actually required to reproduce the bug ;)

**Comment by gdpelican** [comment]
We would fix this by making the set outcome event serialize out a Version, rather than a Proposal @HSalmon

**Comment by mhjb** [comment]
I just noticed this too — felt stinky

**Comment by gdpelican** [comment]
Now that we have different models for each outcome_created, this is no longer a problem. Hooray!
