### ISSUE TITLE
I'm receiving new comment emails but I think I shouldn't be

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3416]
Global settings:

![image](https://cloud.githubusercontent.com/assets/970124/16070842/284a1f90-332c-11e6-9408-0c6d1b00820d.png)

Group settings:
![image](https://cloud.githubusercontent.com/assets/970124/16070850/32bd9484-332c-11e6-9a75-95035621cbce.png)

Thread settings:
![image](https://cloud.githubusercontent.com/assets/970124/16070873/4f753cb2-332c-11e6-9b31-d1a5fccf854c.png)

How did my thread email settings get switched to "All activity"?

**Comment by gdpelican** [comment]
You created the thread, so we set the volume to loud. I believe this was
agreed upon and changed a few weeks back.

**Comment by rdbartlett** [comment]
Oh ok, I didn't pay attention to that conversation. That seems okay.

**Comment by gdpelican** [comment]
Commit for reference: https://github.com/loomio/loomio/commit/7c9f48129ec9cce0651e7223d891f644b0c0dbed
