### ISSUE TITLE
Our connection to Intercom is buggy

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3426]
Talk to me for an example

**Comment by mhjb** [comment]
Intercom is also missing group info for lots of users

**Comment by mhjb** [comment]
I lack confidence in Intercom's numbers (for e.g. MAUs) at the moment — there's a big divergence between those and Metabase's.

**Comment by mhjb** [comment]
<img width="408" alt="groups started per day according to intercom our database" src="https://cloud.githubusercontent.com/assets/1380991/16600457/41cfa23e-435b-11e6-95d4-f1e19bd9e64b.png">

**Comment by gdpelican** [comment]
I'm going to close this as it's pretty unspecific. I'd love to hear about specific intercom issues, if any are left.

**Comment by robguthrie** [comment]
Good call. I've done lots of work on this recently and I reckon it's valid to close.
