### ISSUE TITLE
Voting links on iPhone 4 seem a bit broken

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3430]
|  | I click Abstain, I get: | I log in, I get: |
| ---- | ---- | --- |
| ![2016-06-20 16 47 56](https://cloud.githubusercontent.com/assets/1380991/16188461/aa59c426-3729-11e6-9bc5-fa9a58fc4215.png)|![2016-06-20 16 48 46](https://cloud.githubusercontent.com/assets/1380991/16188459/a7a5a9c0-3729-11e6-98d7-812491c80360.png) | ![2016-06-20 16 47 46](https://cloud.githubusercontent.com/assets/1380991/16188485/c5103f34-3729-11e6-998e-6040e342fb32.png) | 
||(loomio logo not clickable, btw — I expected to be able to click it to get to loomio.org/)|

**Comment by mhjb** [comment]
Also on iPhone 4 — no threads come through in any view:
![2016-06-21 08 38 27](https://cloud.githubusercontent.com/assets/1380991/16210430/fee29aac-378f-11e6-821c-5f011f3190b0.png)

**Comment by mhjb** [comment]
FWIW, Loomio is just broken for me on iphone 4

**Comment by gdpelican** [comment]
Do you know what % of the userbase is on iPhone 4?

**Comment by mhjb** [comment]
Do you happen to know how to find that? Seems like there are a bunch of user agent strings that match iphone 4

**Comment by mhjb** [comment]
I think this particular one is not iphone 4-related — i think it's just the login bug you're already working on, @gdpelican

**Comment by gdpelican** [comment]
Alright I'm going to close then.
