### ISSUE TITLE
long URLs breaking comment formatting

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3436]
<img width="903" alt="screen shot 2016-06-23 at 10 57 14 am" src="https://cloud.githubusercontent.com/assets/5498878/16286560/5b604070-3931-11e6-8bb6-a4ec11780a88.png">

**Comment by gdpelican** [comment]
Hm, I can't repro this on desktop or mobile; my urls are showing up fine, and that comment in prod isn't there anymore. Anything particular about these urls that might be causing it to break?

**Comment by alannallama** [comment]
This was a weird comment that looked like an auto-reply, or a spam thing
that sent out to the user's address book or something. I deleted it because
it was spam on the thread. I don't know anything further. Maybe it was just
a one time thing and we shouldn't worry much about it.

On 26 June 2016 at 02:03, James Kiesel <notifications@github.com> wrote:

> Hm, I can't repro this on desktop or mobile; my urls are showing up fine,
> and that comment in prod isn't there anymore. Anything particular about
> these urls that might be causing it to break?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/loomio/loomio/issues/3436#issuecomment-228544036>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFPn_qTer2X_SKAj72Ed_tyt0Dc4WutJks5qPTUzgaJpZM4I8TgA>
> .
>



-- 
<http://loomio.org>
*Alanna Krause*
Co-Founder & Co-op Member
