### ISSUE TITLE
Paste to upload doesn't quite work for me

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3439]
I press paste, the upload progress bar appears, fills to 100%, then disappears with no error message:

![](http://g.recordit.co/c4ARa3F9MQ.gif)

In console I see:

![image](https://cloud.githubusercontent.com/assets/970124/16287857/91818e1c-393a-11e6-8d10-43a28f1e89ff.png)

Got the same response from trying to paste a .png screenshot and a .jpeg file.

**Comment by robguthrie** [comment]
Just leaving a comment to say this bug bothers me just about every day. I'd love if it were to be fixed. I'd feel so much more fluent in composing messages.

That's all. Thank you.

**Comment by gdpelican** [comment]
This was fixed, hooray!
