### ISSUE TITLE
Replies by email don't become comment replies, just normal comments

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3440]
![image](https://cloud.githubusercontent.com/assets/1380991/16290814/7991b2a4-3954-11e6-849c-1c6037345022.png)

My message was sent as a reply by email; I expected it to say 'in reply to…'

**Comment by HSalmon** [comment]
@mhjb, do you mean you just used the reply link in the email?

**Comment by mhjb** [comment]
No — I replied to the email

**Comment by gdpelican** [comment]
The tech behind this, in case someone feels like picking this up:

At the moment, all thread emails are sent with a reply key, which looks something like this:

```
d=____&u=____&k=____@reply.loomio.org
```

where d is the discussion id, u is your user id, and k is your reply by email key. You need all three of these set correctly to effectively reply by email to a thread. (We construct this reply address in `app/helpers/email_helper.rb`)

The fix here is to add a fourth parameter when sending a `new_comment` email:

```
d=____&u=____&k=____&c=____
```

where c is the id of the comment being sent. That way, when we get a response, we can check for the existence of the 'c' parameter (we parse this in `app/email_processors/email_params.rb`), and, if it exists, assign the `parent_id` of the new comment to it.

**Comment by robguthrie** [comment]
I'm not sure we want to assume that replies are replies to comments.

**Comment by robguthrie** [comment]
Yea.. I think this should be a won't fix.

**Comment by mhjb** [comment]
What else would a reply to a comment email be except a reply to a comment?

**Comment by robguthrie** [comment]
A new comment in the discussion thread.

**Comment by mhjb** [comment]
Ah — sorry that makes sense. I never use Loomio in the 'email everything' mode, only in 'email me when I'm mentioned', so if I'm replying it's always definitely a reply.
