### ISSUE TITLE
'Unresponsive script' on Firefox old PC

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3441]
On an old netbook, on Firefox, a user often gets ​_'Warning: Unresponsive script" prompt that says "A script on this page may be busy, or it may have stopped responding. You can stop the script now, or you can continue to see if the script will complete.'​ mentioning loomio.org/client/0.2.34/vendor.min.js:21

**Comment by gdpelican** [comment]
This isn't something we really have control over, although it points to the fact that our client side performance isn't great at the moment. Hopefully a series of things (upgrade to angular 2, removing unneeded or unnecessary third party scripts, moving the virtual dom rendering, etc.) on the medium term roadmap will mitigate these performance issues some.

If there's a particular user who wants to stop getting these warnings, they can visit about:config in their browser and update it to something longer than 5.

**Comment by mhjb** [comment]
Makes sense; cheers
