### ISSUE TITLE
Let's crop group icons to a square, centred

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3453]
![image](https://cloud.githubusercontent.com/assets/1380991/16507142/a537cd4e-3f7b-11e6-8914-f413ec7cebe2.png)

**Comment by gdpelican** [comment]
So the bug here is that we're storing our paperclip styles incorrectly. Right now it's

```
styles: { card: "67x67", medium: "100x100" }
```

but it should be

```
styles: { card: "67x67#", medium: "100x100#" }
```

(the hash means 'crop it to a square')

This'll involve a mildly beefy migration to resize all of our existing images though...

**Comment by mhjb** [comment]
Would there be any sense in fixing the future ones without bothering with the migration?

**Comment by gdpelican** [comment]
That much I've done; if we want to care about a migration we can do it manually in production for individual groups, or groups that are active, or something.

**Comment by mhjb** [comment]
Awesome thank you
