### ISSUE TITLE
loomio wikidata entry

### ISSUE THREAD

**Issue by dachary** [loomio/loomio#3454]
Could someone please verify that [the wikidata item](https://www.wikidata.org/wiki/Q15975673) about loomio contains accurate information ?

**Comment by gdpelican** [comment]
All of the information on there looks correct to me, although it's clearly been entered by a bot and not edited by humans.

What is the information on there that you're most interested in being accurate, @dachary ?

**Comment by dachary** [comment]
>  although it's clearly been entered by a bot and not edited by humans

I entered all the information manually and I'm **very** interested to know what makes you think it was a bot. A lot of entries for other Free Software have been created by bots though.

I'm most interested in the **developer** statement accuracy because it's non trivial, from an outsider point of view, to figure out how many loomio employees commit patches to the [source code repository](https://github.com/loomio/loomio). It is easier to figure out how many contributors (not loomio employees) also contribute. The ratio is an indicator of how much influence **Loomio Cooperative Limited** has over the software compared to the community.

I'm fully aware that this ratio may not always accurately highlight the dominant organization (or individual), but it's very rarely wrong.

**Comment by gdpelican** [comment]
Ack, sorry about that. Here's a hopefully more useful response from me.

Here are the things that set off my bot alarm:

- loomio.jpg is a screenshot of a _really_ old (like, older than I've been around) version of the product
- I'm confused by the entries under 'developer', which say 'Loomio Cooperative Limited' and 'contributor', which don't really mean anything to me; I also don't know what 'retrieved' means, or how to put a number like 3 +/- 1 to contributions. To answer your question, a pretty large majority of the existing codebase has been written by Loomio employees / contractors, but we have accepted numerous contributions from outside contributors as well. The ratio of contributions is pretty heavily skewed towards Loomio employees, though.
- We're on version 0.20.40 at the moment, it looks like the 0.20.0 tag is missing from the repo, though.
- I wasn't sure what was mean by 'Quality Assurance' as a feature.

**Comment by dachary** [comment]
> loomio.jpg is a screenshot of a really old (like, older than I've been around) version of the product

That is what is currently in commons.wikipedia.org and shows at https://en.wikipedia.org/wiki/Loomio. Which screenshot would you like to upload and use instead ?

**Comment by dachary** [comment]
> We're on version 0.20.40 at the moment, it looks like the 0.20.0 tag is missing from the repo, though.

Should we look for 0.20.40 somewhere ? I assumed https://github.com/loomio/loomio/tags was authoritative but apparently I'm wrong.

**Comment by dachary** [comment]
> I'm confused by the entries under 'developer',

This is indeed confusing. By "contributor" I meant to group people who contributed to the software base but are not affiliated to a known company. This is now clarified (hopefully) with [FLOSS contributor](https://www.wikidata.org/wiki/Q25340898) instead. The [retrieved](https://www.wikidata.org/wiki/Property:P813) property means **date or point in time that information was retrieved from a database or website (for use in online sources)**. 

Instead of using quantity (which I meant as "number of employees contributing to the code base") I changed to [developer](https://www.wikidata.org/wiki/Property:P178). So it could read like this: Loomio Cooperative Limited is an organization contributing to the code base and within this organization about (that what +-1 is intended to mean) three employees are developers contributing to the code base.

Does that sound sensible ?

**Comment by dachary** [comment]
> edit: I guess I'd also expect that the email address would be 'contact@loomio.org', rather than 'mailto:contact@loomio.org' (which is an anchor link for sending mail, but not an email address)

the [e-mail](https://www.wikidata.org/wiki/Property:P968) property is Data type URL and requires the mailto prefix.

**Comment by dachary** [comment]
> I wasn't sure what was mean by 'Quality Assurance' as a feature.

I did not figure out a way to point to the Quality Assurance process applied to the software and used this "feature added" as a temporary placeholder while the proposal for the [Software quality assurance](https://www.wikidata.org/wiki/Wikidata:Property_proposal/Creative_work#Software_quality_assurance) property is being discussed.

If you have time, it would be great if you could [comment on the proposal](https://www.wikidata.org/wiki/Wikidata:Property_proposal/Software_quality_assurance).

**Comment by gdpelican** [comment]
@mhjb Have a thought on a screenshot for the wikidata entry?

There are commits in the git log marking version updates (which correspond to production deploys), but maybe we need to just start tagging when we do minor updates.

The developer stuff sounds fine to me.

**Comment by dachary** [comment]
> The developer stuff sounds fine to me.

Cool :-) It's now documented at https://www.wikidata.org/wiki/Wikidata:WikiProject_Informatics/FLOSS#developer

**Comment by dachary** [comment]
> There are commits in the git log marking version updates

Could you give me the URL of such a commit ? It's good enough as a reference.

**Comment by gdpelican** [comment]
https://github.com/loomio/loomio/commit/63c52e73eaf3f4bb28fb837c5a9204a76c52cbd6

**Comment by dachary** [comment]
Fixed, thanks: https://www.wikidata.org/wiki/Q15975673

**Comment by dachary** [comment]
This discussion is in the wikidata entry at https://www.wikidata.org/wiki/Talk:Q965769 for cross reference

**Comment by gdpelican** [comment]
Thanks for the effort on this, @dachary !

**Comment by mhjb** [comment]
I have a better screenshot; @dachary can you tell me how to add it to the image record?

**Comment by dachary** [comment]
@mhjb you can upload it at https://commons.wikimedia.org/wiki/Special:UploadWizard and set the Loomio category. Once it's done you can go to https://www.wikidata.org/wiki/Q15975673 and look for the image property and change to the new screenshot you just uploaded.

**Comment by mhjb** [comment]
Thanks @dachary. Done. That user experience made me feel frustrated.

**Comment by dachary** [comment]
@mhjb In what way ?

**Comment by mhjb** [comment]
In this context (github), I can upload an image in roughly two steps — I'd drag it from my computer to this textbox and press comment.

On wikidata I had to visit a link on a different domain (kindly supplied by you), create an account, realise I had an existing account created years ago on wikipedia that also worked on wikimedia, go through a five-step wizard including an explanatory infographic, return to the wikidata site, guess that typing in the filename by itself (not the image's full url on wikimedia) was what was being asked for.

**Comment by dachary** [comment]
@mhjb the default mediawiki user experience is indeed sub-standard. There may be another interface but I'm not aware of it.
