### ISSUE TITLE
Group settings modal too tall

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3455]
![image](https://cloud.githubusercontent.com/assets/1380991/16536605/02fcac66-4048-11e6-8ea6-e9cb280dc78c.png)

**Comment by gdpelican** [comment]
Er, this will probably need a design in order to fix.

**Comment by mhjb** [comment]
Roger. I'll have a go. 

Would it work to have all modals be at most 100% of the viewport height, and scroll internally if necessary?

**Comment by gdpelican** [comment]
I believe material solves this problem by replacing large modals with
full-screen 'cards', which can scroll if need be. I am certainly a fan of
having less stuff on the group card. The description box there feels
massive to me, but since it auto-sizes to the group description we'll
always have to deal with scroll somehow.

**Comment by mhjb** [comment]
What's the calculation by which the Description textarea auto-sizes?

**Comment by gdpelican** [comment]
I believe it starts at 5 rows or so, then if you type more than that it
expands to fit.

**Comment by mhjb** [comment]
In that screenshot above, it looks heaps taller than the content — any idea why?

**Comment by gdpelican** [comment]
No idea, actually.

How did your play with the material modals go; is that something you'd be happy polishing off and putting into prod as a fix for this?

**Comment by mhjb** [comment]
Chatting about that [here](https://www.loomio.org/d/BDZSArRH/-ux-proposal-closing-datepicker-that-works-for-non-chrome-edge-browsers). Are you suggesting my taking your branch presently on loomiotest forward?

**Comment by gdpelican** [comment]
Nope, I'll do the work, I was just wondering if you felt that that work
would solve this problem (without introducing new ones?)

**Comment by mhjb** [comment]
Ah that makes sense. The only difference between production and the version on loomiotest that I can see presently is that there's an animation when modals open and close; and some modals are narrower. Are you envisaging replacing all the input fields on all the modals with their material equivalents?

**Comment by gdpelican** [comment]
This should be fixed with the new material modals.
