### ISSUE TITLE
Help and Guides in Spanish website

### ISSUE THREAD

**Issue by natiloomio** [loomio/loomio#3458]
'Help/Ayuda' link on the bottom of the Spanish website should be linking to the Help manual in Spanish. 
'Guides and Tips/Guias y consejos' to the Español category on the blog.

**Comment by HSalmon** [comment]
@nati? @gdpelican, is this resolved?

**Comment by gdpelican** [comment]
Nope.

**Comment by gdpelican** [comment]
Alright I actually fixed this now, pending deploy
