### ISSUE TITLE
Regular sign up is too hard to find

### ISSUE THREAD

**Issue by jhass** [loomio/loomio#3462]
In fact I couldn't find a link to it at all. https://www.loomio.org/users/sign_up should be linked from https://www.loomio.org/users/sign_in, not all users are comfortable with signing up with Google, Facebook, Twitter or Github. Or at least not with associating either account with their Loomio account. Those people shouldn't be excluded from participating.

**Comment by gdpelican** [comment]
Yep, I agree with this.

We're in the process of revamping what it's like to use Loomio with no groups at all (it's not great right now), then change this.

**Comment by jhass** [comment]
Adding a link to https://www.loomio.org/users/sign_in should be a five minute change that would alleviate that pain greatly for the time being :)

**Comment by gdpelican** [comment]
I'd love to have a look at a PR :)
