### ISSUE TITLE
From address in thread mailer is misleading.

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#3470]
Via another person. Logging here. I'm happy to fix this shortly.

> in Gmail, in the inbox, the 'From' field of the email is misleading.
> I believe it's because the 'From' address for all the emails is the same.

**Comment by gdpelican** [comment]
Do you still want to fix this @robguthrie ?

**Comment by robguthrie** [comment]
thanks.. it was fixed a long time ago.
