### ISSUE TITLE
locale autodetection is not working

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#3471]
Visiting loomio.org (in app or on marketing page) does not read browser accept-locale anymore.

**Comment by gdpelican** [comment]
I tried these steps:

- Visit chrome -> settings -> language and input settings
- Put spanish at top as preferred language
- Visited www.loomio.org
- Got page in Spanish

So that appears to be working. Are there more specific repro steps?

**Comment by gdpelican** [comment]
I can't find any evidence of this. Feel free to reopen if there's some further steps that can be taken.
