### ISSUE TITLE
Groups do not appear in your groups

### ISSUE THREAD

**Issue by jwentwistle** [loomio/loomio#3476]
If I click on Product Development link in the your groups section, then go back. It will show just the Loomio Community and only the Product Development group beneath it. Despite me being in the Loomio Community group too. If I click on the Loomio Community group, then go back, all of the other subgroups are there (Accessibility, Help, etc).

This is using Chrome (Version 51.0.2704.106).

**Comment by gdpelican** [comment]
Thanks for the report. I'd have a peek at this, but the groups page is going away imminently with the introduction to [the sidebar](https://www.loomio.org/d/PxBMvgRT/sidebar-request-for-feedback-) (which, until recently, was exhibiting the same behaviour you're describing).

I'll leave this open until we merge that in, and make sure that the sidebar isn't doing a similar annoying thing.

**Comment by gdpelican** [comment]
I believe this is taken care of in the new sidebar. Let me know if you run into this kind of behaviour again, @jwentwistle
