### ISSUE TITLE
Oversized images on marketing page

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3482]
Logo is 800px wide, illustrations 1042px, screenshot 2400px. 

This is generally bad because it's a waste of bandwidth and specifically bad when you view Loomio on say IE9 and get a really bizarre layout because the images render full width.

**Comment by gdpelican** [comment]
We should be redirecting to the 'browser not supported' page on IE9.

**Comment by rdbartlett** [comment]
Last I checked, the layout of the browser not supported page is also bung
due to the image sizes.

**Comment by gdpelican** [comment]
I vote that we spend 0% of our time on IE9 anything. We definitely need to scale those images down, though, ideally with media queries to deliver smaller images on mobile.

**Comment by rdbartlett** [comment]
I vote that we have a browser not supported page that doesn't look broken

**Comment by rdbartlett** [comment]
Did you mean to assign this to me @gdpelican?

**Comment by rdbartlett** [comment]
I need to tidy up our assets for marketing work anyway so I will resize and optimise all the website images, with a PR to update the repo + duplicate them into [this Drive folder](https://drive.google.com/drive/u/1/folders/0By3lxDcQiC3Oc29SYjA1MkVkXzA).

I won't do the media query stuff though, but it would be nice if someone wants to jump in and make that happen.
