### ISSUE TITLE
Marketing page on Safari looks broken

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#3484]
![screen shot 2016-07-11 at 3 58 23 pm](https://cloud.githubusercontent.com/assets/750477/16744717/589266b8-4780-11e6-8be1-39a274227ea2.png)

**Comment by HSalmon** [comment]
What version of Safari is this @gdpelican?

**Comment by gdpelican** [comment]
Says so right in the screenshot, heh. 8.0.8

**Comment by HSalmon** [comment]
Eep...sorry!
