### ISSUE TITLE
Create an account has turned up on log in page

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3488]
… which seems like a recipe for 0-group users

![2016-07-12 09 30 41](https://cloud.githubusercontent.com/assets/1380991/16756526/e3b7c1dc-4859-11e6-921a-aee5dfb8cebe.png)

**Comment by gdpelican** [comment]
Yep. https://github.com/loomio/loomio/issues/3462

**Comment by mhjb** [comment]
But why would we want, or users want, 'regular sign up' of that sort?

**Comment by gdpelican** [comment]
Didn't we just design an experience for 0-group users? Why would we want to shut off that avenue into our app, especially since it was requested from, bargained for, and implemented by a community member?

**Comment by mhjb** [comment]
Yeah when that's deployed it will ameliorate this. I saw the 0-group fix as a stop-gap to fill a side-effect of SSO logins. This makes the gap bigger, and feels like design by accretion, rather than as a result of considering what would be good experiences for people using the app. 
Not a huge deal — but this is my take.

**Comment by mhjb** [comment]
However it is neat great that a community member felt the pain and put the work in & thank you for supporting that.
