### ISSUE TITLE
Firefox on Ubuntu checkboxes don't appear

### ISSUE THREAD

**Issue by natiloomio** [loomio/loomio#3499]
The set up of Gift plan can't be finalised. 
When selecting Gift plan from the Plan card on the group page, it takes you to ![this card](https://cloud.githubusercontent.com/assets/15793070/16821624/65258004-49ab-11e6-85d4-f3125fc50448.png) but the I got it button is blocked, only possible to go back.

**Comment by gdpelican** [comment]
Can't repro. Browser / device?

**Comment by natiloomio** [comment]
latest version of firefox in a laptop with ubuntu.

**Comment by gdpelican** [comment]
It looks like this bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1262136
![bugzilla-attachment-form](https://cloud.githubusercontent.com/assets/750477/16828393/524e961c-495d-11e6-8994-be88a3eb802d.png)

Although that's been marked as resolved as of ff48.

Out of curiousity, can you click on the place you think the checkbox should be an have it appear?

**Comment by natiloomio** [comment]
Yes! we just figure that out with Hannah, if I try clicking I can see the selection icon, but I can't see the box.

**Comment by gdpelican** [comment]
We could fix this by moving to `md-checkbox` as part of the material upgrade.

**Comment by robguthrie** [comment]
We can close this, because we removed this checkbox from the app.
