### ISSUE TITLE
Getting two Proposal closing in 24 hours emails per proposal

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3503]
![image](https://cloud.githubusercontent.com/assets/1380991/16830965/4b5c0396-49f6-11e6-8c4e-0ad0369fa922.png)

**Comment by mhjb** [comment]
two Slack notifications too

**Comment by gdpelican** [comment]
Yeah, that was weird, eh? This was a bug before, and it seems to have cooled off a lot, but seems like there's still an edge case here somewhere.

**Comment by gdpelican** [comment]
@mhjb Do you know if that proposal was extended from its original date or not?

**Comment by mhjb** [comment]
It was

**Comment by gdpelican** [comment]
I made a dupe of this issue #3652 , then fixed the bug. Now I'm closing this. 🌈
