### ISSUE TITLE
Link in statement of position not blue in discussion stream

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3505]
Here's what the statement of position looks like under the proposal:
<img width="433" alt="screen shot 2016-07-15 at 10 49 05 am" src="https://cloud.githubusercontent.com/assets/5498878/16858274/e6305682-4a79-11e6-8e25-789055a772a5.png">

And here's what it looks like in the comments stream:

<img width="597" alt="screen shot 2016-07-15 at 10 48 53 am" src="https://cloud.githubusercontent.com/assets/5498878/16858279/e95db6f6-4a79-11e6-9093-8f980af6170f.png">

It's quite difficult to notice that there is a link in there. If you hover over it, an underline shows up, but you'd have to already know it was there pretty much. I think the in-line statements in the comments stream should be formatted the same as under the pie.

**Comment by gdpelican** [comment]
That's just a big fat styling bug. I'll fix it soon.
