### ISSUE TITLE
In reply to blank

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3520]
On comment 1077245

![image](https://cloud.githubusercontent.com/assets/970124/16904198/6e1c859e-4ce5-11e6-8e03-1244e8b9d746.png)

**Comment by gdpelican** [comment]
Retro steps?

**Comment by rdbartlett** [comment]
Repro: visit [thread](https://www.loomio.org/d/dDnaOuNh/how-can-loomio-get-the-most-out-of-os-os-), scroll down :)

**Comment by gdpelican** [comment]
No. Rage. That is not what reproduction steps are. Please provide a list of actions I can take to reproduce this behaviour on my instance.

**Comment by rdbartlett** [comment]
Sorry I don't know anything more than that you can see the bug on that thread that you and I have access to on production. I'm logging the issue, I don't have bandwidth to investigate it.

**Comment by gdpelican** [comment]
Alright, closing until someone can provide me with a way to reproduce.
