### ISSUE TITLE
incorrect grouping in side-bar

### ISSUE THREAD

**Issue by mixmix** [loomio/loomio#3525]
![selection_062](https://cloud.githubusercontent.com/assets/2665886/16905311/1b587a26-4cf8-11e6-88f9-9a8dbe2b63a7.png)

EDA Teaching : https://www.loomio.org/g/dZyIDgMK/enspiral-academy-eda-teaching
is a subgroup of Enspiral Academy : https://www.loomio.org/g/9f2O4z0x/enspiral-academy

NOT Enspiral

**Comment by gdpelican** [comment]
Cool. @HSalmon can you make sure the groups in the ng-repeat for this are ordered by fullName (and not just name)?

**Comment by gdpelican** [comment]
Think I got this one :)
