### ISSUE TITLE
bump version to 0.20.46 really is 0.20.47

### ISSUE THREAD

**Issue by dachary** [loomio/loomio#3529]
Is it expected that [0.20.46 really is 0.20.47](https://github.com/loomio/loomio/commit/63c52e73eaf3f4bb28fb837c5a9204a76c52cbd6) ? It is true of all commits that are similar to this one. Maybe there is an explanation ? Or is it a kind of bug ?

**Comment by gdpelican** [comment]
Yep, it is a bug in our deploy script, which makes those commits automatically on deployment.

A minor bug, but a bug nonetheless.

**Comment by dachary** [comment]
@gdpelican :-) So I'm guessing the content of the file is to be trusted and not the comment, right ?

**Comment by gdpelican** [comment]
Yes.

**Comment by gdpelican** [comment]
I've just fixed this while making the latest deploy 😸

**Comment by lheckemann** [comment]
This seems to have resurfaced, see for instance ecc9424733d9f7addd709053a76e3aa6944508d0
