### ISSUE TITLE
Printing broken on Firefox

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3532]
Post-sidebar, I think.

![image](https://cloud.githubusercontent.com/assets/1380991/16973830/2592de98-4e8b-11e6-8a58-6a3fe620b5bd.png)

Print now only prints one page, and the sidebar pushes heaps of stuff off that too.

**Comment by gdpelican** [comment]
@HSalmon, the sidebar element wants an '.lmo-no-print' class on it so it
doesn't show up in the printed page.

**Comment by mhjb** [comment]
The printing only one page thing seems to be related to this bit:

```<md_content class="lmo-sidebar-and-main-container _md layout-row flex" flex="" layout="row">```

When I muck about in Chrome console and get rid of the classes on that element, the print preview shows all the pages again:

![image](https://cloud.githubusercontent.com/assets/1380991/16973983/5450636c-4e8c-11e6-88b3-eee4e4dcdf2a.png)

**Comment by gdpelican** [comment]
Thanks for the thorough analysis, @mhjb . I think I've gotten this one fixed, pending deploy.

**Comment by robguthrie** [comment]
James, did we (you :) ) eventually put in the 'load all records before
print' functionality?

**Comment by mhjb** [comment]
A person in the Loomio help subgroup [reported](https://www.loomio.org/d/YObAq5gJ/unable-to-print-loomio-proposal-and-decision) that this is still broken in Firefox. He's on Windows. I've tested on latest Firefox / OS X and it's not working there either. 

<img width="1162" alt="screen shot 2016-08-02 at 11 45 20 am" src="https://cloud.githubusercontent.com/assets/1380991/17312419/a24723b6-58a6-11e6-854f-90ffc2874c40.png">

**Comment by gdpelican** [comment]
This is weird and I can't figure out why it's happening. :(

**Comment by alannallama** [comment]
Just a note that I encountered this bug on Firefox as well today. Same thing as above screenshot (headers and footers but no content). Worked fine in Chrome.

**Comment by ngm** [comment]
Just reporting that this still seems to be occurring in Firefox 60.0.1 on Ubuntu.  Trying to print [this thread](https://www.loomio.org/d/r1KuYn6q/foss-cooperatives-a-white-paper-) results in a 2 page PDF with the second page blank.

**Comment by robguthrie** [comment]
closing as this issue isn't going to help anyone. Better printing support will come
