### ISSUE TITLE
"you do not have permission to do this" when trying to join group

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3536]
<img width="1279" alt="screen shot 2016-07-22 at 9 39 13 am" src="https://cloud.githubusercontent.com/assets/5498878/17039790/206b27de-4ff0-11e6-9ab1-f5ce22810926.png">

I created a new test group, then created a subgroup within it. I invited my alternate email address to it. I copied the invite link that arrived in my email and used it in a Private Browsing window so I could log in with it. It prompted me to create an account, which I did. 

But when I finished that process, the very first page it dropped me on says "you do not have permission to do this" - and it does not appear that user is a member of any groups. My understanding was that a member of no groups was supposed to be shown the Explore page, but I was neither added to a group nor shown the Explore page.

**Comment by gdpelican** [comment]
Erg, sorry, I've read this a bunch and still can't quite parse it. This seems to be the same repro steps as the login bug, so I'm not sure if this is different somehow?

**Comment by mhjb** [comment]
@alannallama is this still happening for you?

**Comment by alannallama** [comment]
This was kind of a unique situation, so I haven't experienced it again. Feel free to close this if you can't reproduce, and we can re-open if it occurs again.
