### ISSUE TITLE
Strange sidebar layout

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3538]
Beka just shared this screenshot from Chrome 49

![image](https://cloud.githubusercontent.com/assets/970124/17044814/c1c7ee38-5017-11e6-8849-9f3a4799abab.png)

@HSalmon I wonder if a few people should get together next week for a session about next steps for sidebar?

**Comment by gdpelican** [comment]
Should be fixed in #3547, I'm going to post a proposal for smoke testing soon.

imho things that are broken like this don't need discussion; the intended behaviour is clear, so let's just fix em.
