### ISSUE TITLE
Marketing site: Toolbar layout on mobile

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3544]
Damian just shared this screenshot:

![screenshot_2016-07-27-10-20-20](https://cloud.githubusercontent.com/assets/970124/17157727/7a98987e-53e5-11e6-86f7-e66f4627df0b.png)

I was under the impression that we were going to do an iteration of the mobile toolbar with a expanding/collapsing hamburger menu thing. Can someone let me know what happened with that idea?

**Comment by robguthrie** [comment]
I don't know, who had that idea? You're welcome to put it into a card.

Meanwhile I think it would be good to fix this so it renders as intended, to do that we'll need to know Damian's browser version

**Comment by rdbartlett** [comment]
Ok I've put in a card for collapsible menu.

I've just viewed the site on Chrome on my phone, and on my laptop and I'm getting the same thing.

**Comment by robguthrie** [comment]
Yea, I just viewed it too.. the thing is not collapsing into a column as designed. Sorry.

**Comment by gdpelican** [comment]
I've got this one.
