### ISSUE TITLE
Group title text over image on Previous Proposals screen

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3551]
The text is oriented over the group image, so you can't really read it.

<img width="779" alt="screen shot 2016-08-01 at 11 02 55 am" src="https://cloud.githubusercontent.com/assets/5498878/17279968/a6f7663e-57d7-11e6-900e-7a33e4883cbb.png">

<img width="769" alt="screen shot 2016-08-01 at 11 02 20 am" src="https://cloud.githubusercontent.com/assets/5498878/17279969/a6f8a2c4-57d7-11e6-97ea-95112375c5d5.png">

**Comment by gdpelican** [comment]
Sidebar regression, I'll grab it tonight.

**Comment by gdpelican** [comment]
Fixed pending deploy :D
