### ISSUE TITLE
Previous proposals page title in the wrong spot

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3552]
<img width="1279" alt="screen shot 2016-08-01 at 1 25 24 pm" src="https://cloud.githubusercontent.com/assets/1380991/17280933/7199a902-57eb-11e6-9254-a520f1cae5f0.png">

**Comment by gdpelican** [comment]
Er, #3551.

I think one of the steps to submitting a bug will be 'check the existing issues list to ensure that the thing you're reporting isn't already captured.

**Comment by mhjb** [comment]
Yes – sorry!
