### ISSUE TITLE
Filter Threads menu should be removed?

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3557]
It was my understanding that the Filter Threads menu would be removed when the Sidebar was deployed. 

If I navigate to the Muted Threads page from the Filter Threads menu on the Dashboard, the content of the page updates, but the URL and the sidebar highlight do not:

![image](https://cloud.githubusercontent.com/assets/970124/17315374/161900c6-58bf-11e6-9ac2-90d2fa9c4690.png)

Can we just remove the Filter Threads menu?

**Comment by HSalmon** [comment]
We can but we lose the "Participating threads" option. Does that matter?

**Comment by rdbartlett** [comment]
To my mind the 'Participating' option has always been a bit of an easter egg, I don't think it was fully considered before it was deployed. Personally I wouldn't mind losing it.

**Comment by HSalmon** [comment]
it's gawn!
