### ISSUE TITLE
No toolbar on Firefox 47

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3561]
![image](https://cloud.githubusercontent.com/assets/970124/17317733/dd1a55ca-58d4-11e6-92f5-8885bb857176.png)

**Comment by rdbartlett** [comment]
Nothing scary in the console: 

![image](https://cloud.githubusercontent.com/assets/970124/17317772/1648d470-58d5-11e6-94bf-2bc34b810e43.png)

**Comment by gdpelican** [comment]
Can't repro this one either. Anything special about your ff setup?
![screen shot 2016-08-02 at 11 50 21 am](https://cloud.githubusercontent.com/assets/750477/17335263/59c51f8e-58a7-11e6-99af-cda026d3c88e.png)

**Comment by rdbartlett** [comment]
😊 I am a dork, sorry for wasting your time. I am running a custom stylesheet plugin on FF 😊
