### ISSUE TITLE
Improving search

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3566]
Sometimes Loomio search doesn't find me the thing I'm looking for, and I try to guess between 'oh well search is really flippin hard', and, 'if we changed the algorithm we'd get better results'. 

I don't really understand how it works, so this is pure conjecture, but I wonder if we can give more weighting to the recentness of a thread. I feel like I'm almost always searching for a recent thread.

E.g. I just did this search and was surprised to see that the top result was a year old:

![image](https://cloud.githubusercontent.com/assets/970124/17351996/5c640fc6-5987-11e6-97ed-f670a619da76.png)

Is there a little tweak that we can try here or is it a bigger deal?

**Comment by gdpelican** [comment]
We're basing this solely on content, not timing at the moment. The technical fix would be to write a decay function which is an under-1 modifier based on how old the thread is (ie, something created [last activity at?] last week gets multiplied by .95, something last year by .5).

Or something. That's the thing, this is _really_ unscientific, and will likely introduce as many problems as it solves for a while. There is [some precedent](https://marcobonzanini.com/2015/05/04/how-to-promote-recent-articles-in-elasticsearch/) for this (although it's still a custom job) in Elasticsearch; we'd be rolling our own with postgres. Moving to elasticsearch right now is probably a no-op for me. Maybe an OS//OS project?

The custom postgres job doesn't strike me as huge, but it also doesn't strike me as high-leverage, hugely impactful on activation, or in line with our quarterly goals that much.

**Comment by rdbartlett** [comment]
Thanks, that make sense.

I just did another search and had the same reaction:

![image](https://cloud.githubusercontent.com/assets/970124/17393242/8be0e8b0-5a76-11e6-8a11-afa3769a6c7f.png)

I'm trying to understand the rankings. Has #2 come in above #3 because there are more mentions of the search term in the content of the thread?

**Comment by robguthrie** [comment]
Could we calculate a recentness value at query time?

**Comment by gdpelican** [comment]
@rdbartlett The constants at the top of search_vector.rb define our weights:

```
  WEIGHT_VALUES = [
    1.0,   # A
    0.3,  # B
    0.1,  # C
    0.03 # D
  ].reverse.freeze

  DISCUSSION_FIELD_WEIGHTS = {
    'discussions.title'        => :A,
    'motion_names'             => :B,
    'discussions.description'  => :C,
    'motion_descriptions'      => :C,
    'comment_bodies'           => :D
  }.freeze
```

That says 'discussion titles are marked fully. Proposal names are weighted by 0.3.' etc.

**Comment by gdpelican** [comment]
@robguthrie Yeah we'd have to find some way to do that; the ranking happens entirely in SQL (ruby too slow...), so we'd have to feed recency into that. Currently the rank is calced on search_vector#35:

```
.select("ts_rank_cd('<stuff>') as rank")
```

So we'd do something like

```
.select("ts_rank_cd(<stuff>) * some_decay_function as rank")
```

**Comment by gdpelican** [comment]
This improvement has been deployed.
