### ISSUE TITLE
Zoom 110% cuts off lintel in firefox

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#3568]
See #3506

**Comment by rdbartlett** [comment]
Also at 100% zoom on FF48 for me:

![image](https://cloud.githubusercontent.com/assets/970124/17384346/a407551a-5a2f-11e6-8270-d923b6b83865.png)

Is the lintel in the wrong container? Here it is on Chrome 52, in a narrow window, where everything has wrapped to one column. The lintel is still behaving as if it is in a two-column container.

![image](https://cloud.githubusercontent.com/assets/970124/17384383/ecb8011a-5a2f-11e6-9c80-ecce4f450bb9.png)

**Comment by juliencarnot** [comment]
Not reproducing this, it seems to be fixed.
