### ISSUE TITLE
Yeserday on loomio email - proposal closed shows vote buttons

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#3569]
![image](https://cloud.githubusercontent.com/assets/486367/17381380/ac4fb326-5a1f-11e6-966e-0125f3138e80.png)

It should not show vote buttons at this stage.

'scuse the private information :)

**Comment by robguthrie** [comment]
but they look so good!

**Comment by gdpelican** [comment]
Should be fixed now.
