### ISSUE TITLE
Long comment strings don't wrap in FF

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3571]
FF 48

![image](https://cloud.githubusercontent.com/assets/970124/17384322/6663ca36-5a2f-11e6-909f-d5b38246a931.png)

Chrome 52

![image](https://cloud.githubusercontent.com/assets/970124/17384332/75b3de7c-5a2f-11e6-918b-c5caf16331d7.png)

**Comment by gdpelican** [comment]
Should be fixed pending deploy
