### ISSUE TITLE
Wrong group being sent to Intercom

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3583]
As a logged in member of many groups, intercom is receiving the same group, regardless of what group page or thread page I am on.

(I've called this high priority because it's blocking my work for the sprint.)

**Comment by gdpelican** [comment]
Won't sending over different company data every time they hit the page cause users to erractically swap between companies? If Intercom supports a many-to-many relationship between users and companies, that'd be cool, but not certain if they do.

**Comment by gdpelican** [comment]
Oops, looks like they do support being a member of multiple companies. From the docs:

```
Users can belong to multiple companies, but you should only send us the data for the company that the user is currently signed in with. You can also send other attributes within the company object. Those will be treated like custom attributes for that particular company. You can read more about custom attributes here.
```

**Comment by gdpelican** [comment]
This will be another case for the Session.currentGroup stuff that Hannah is working on.

**Comment by gdpelican** [comment]
Also, we only send info to intercom once, on page load. What's your expected behaviour here?

**Comment by rdbartlett** [comment]
We're triggering different messages to people depending on what state their group is in. E.g. if group.discussions_count is 2, we encourage people to start discussions. 

Ideally Intercom would be accurately kept up to date with the state of all user's groups.

If that is hard, maybe an interim step at least is that we deliver the current group on boot, not the first group.

**Comment by rdbartlett** [comment]
We also need to purge the out-of-date variable names (camel vs underscores):
![image](https://cloud.githubusercontent.com/assets/970124/17453946/171b7d4a-5bdb-11e6-9d82-67b5c5582a7b.png)

Also I've just learned that we archived a couple of attributes ages ago 'discussions_count' and 'motions_count', so they were being ignored, but I've unarchived them now.

**Comment by gdpelican** [comment]
Is this resolved @robguthrie ?

**Comment by mhjb** [comment]
@robguthrie ^^

**Comment by robguthrie** [comment]
yes fixed
