### ISSUE TITLE
No space before unread count

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3592]
![image](https://cloud.githubusercontent.com/assets/970124/17467678/e7aa28ea-5d74-11e6-93b5-5dfbf8a76320.png)

I'd expect there to be a space between `Inbox` and `(32)`

I'd just create a pull request but I wanted to check if this was done intentionally.

Maybe this changed when you did the accessibility change @HSalmon?

**Comment by gdpelican** [comment]
This was reported, fixed and closed here: https://github.com/loomio/loomio/issues/3589

(Pending deploy)

**Comment by rdbartlett** [comment]
bingo bango. I searched for previous issues but didn't think to look at the closed ones.

**Comment by gdpelican** [comment]
No worries!
