### ISSUE TITLE
Vote links in email don't go to vote modal

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3594]
![](http://g.recordit.co/21LCzaeuVv.gif)

Chrome / OS X

Wondering how this slipped through our QA process…

**Comment by rdbartlett** [comment]
I would have called this Medium priority as it is a Core workflow, a bit munted. While we get around this bug prioritisation system, would you mind spelling out your thought process Matt?

**Comment by HSalmon** [comment]
@mhjb, it was broken before the thread mailer deploy

**Comment by mhjb** [comment]
I wondered about 'a bit munted' too — but in this case it seemed like a core workflow that just wasn't working. On reflection the ease of the workaround probably does warrant 'a bit munted' rather than horridly confusing or whatever the higher-level one is (haven't got the doc to hand).

**Comment by HSalmon** [comment]
I'm having a gander at this now :eyes:

**Comment by gdpelican** [comment]
Fixed pending deploy
