### ISSUE TITLE
64 + 13 != 75

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3604]
![image](https://cloud.githubusercontent.com/assets/970124/17540793/70819b32-5f0d-11e6-8381-9cc64b61f6b4.png)

Gotta run so don't have more detail at this stage. Just noticed this on prod on `d/RIMCfuaT`

**Comment by rdbartlett** [comment]
What can I do to help unpick this bug?

**Comment by robguthrie** [comment]
investigating now. thanks for the bump
