### ISSUE TITLE
Alignment of links in sidebar

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3609]
In Chrome:

![image](https://cloud.githubusercontent.com/assets/970124/17570284/e093755c-5f9f-11e6-9863-e80cbe7bae2d.png)

My Unread and at least one of my Parent groups is being indented by a few pixels

**Comment by HSalmon** [comment]
Hope the PR referenced above will also fix the parent group indentation problem too, I can't reproduce that

**Comment by HSalmon** [comment]
Fixed pending deploy
