### ISSUE TITLE
I don't know what a pikachu is

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#3612]
I think the issues stuff has been improving a lot recently.. but I don't know about pokemon and I don't think the size stuff is accessible. Can we try again with that part?

**Comment by robguthrie** [comment]
Hey! That felt bad. Are you open to discussing this?

**Comment by robguthrie** [comment]
Oh. I see you've changed the sizes to really easy to understand ones. Thanks.

I just feel like the way that was closed with no words hurt my feelings. I'm sitting here feeling really weird and I wish I knew a little about your response.

**Comment by gdpelican** [comment]
Yep, sorry. There was a complaint that 'trivial' might be a slightly
off-putting name for your bug. I couldn't find a word that I liked, so
decided to try something different. But you're probably right, it's
probably not 100% accessible.

**Comment by robguthrie** [comment]
Arr. Ok. Yea... I agree Trivial seems like a weird priority. Do we need that level? Could we just use Low, Medium, High and Critical?
