### ISSUE TITLE
Intercom is erroring on blank subscription kinds

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#3615]
![screen shot 2016-08-11 at 5 10 44 pm](https://cloud.githubusercontent.com/assets/750477/17605080/a6ef3254-5fe6-11e6-95b3-8643ccd2dc80.png)

Navigating through www.loomio.org throws this error on most pages; I get it on the dashboard and when navigating to a new group. Looks like we're not accounting for subscriptionKind being null.

**Comment by robguthrie** [comment]
Yikes. Thanks - I'll fix it right away.
