### ISSUE TITLE
When there are a lot of votes, some are not showing up in the client.

### ISSUE THREAD

**Issue by HSalmon** [loomio/loomio#3620]
Proposal closing in 24 hours notification shows more proposal participants than in-app representation of proposal. People who have voted are still showing up in the undecided panel

**Comment by robguthrie** [comment]
For reference, to see the bug happening, assuming you have access: https://www.loomio.org/d/RIMCfuaT

**Comment by gdpelican** [comment]
This is because the API puts a default limit of 50 on index calls, to prevent us returning ungodly amounts of info to the client in a single call. I think the solution here is to put in a simple 'show more' solution for proposal votes on the client.

**Comment by HSalmon** [comment]
@gdpelican, how do you imagine 'show more' working with 'show undecided members'?

**Comment by robguthrie** [comment]
Lets jam on this problem at our next product group meeting. I feel like there are a few pros and considerations to talk about.

**Comment by gdpelican** [comment]
Tracked by #3623
