### ISSUE TITLE
Previous proposals only giving the last 3 months of proposals

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3622]
… when I'd like to find an older one; with no option to fetch more.

Later when I browsed around some old threads, some more old proposals then turned up on the previous proposals page. 

Reproduction steps would be to visit the previous proposals page for a long-active group (like [workers](https://www.loomio.org/g/T9ZtzNcD/previous_proposals)), check the oldest proposal, then browse older discussions with proposals & return to previous proposals page.

**Comment by gdpelican** [comment]
This is actually the same 'bug' (I'd call it unintuitive behaviour) as described in #3620; this was a 'we'll deal with it when we come to it' thing that's we've now come to and should deal with

**Comment by gdpelican** [comment]
Closing as this is a larger chunk of work tracked by #3623
