### ISSUE TITLE
Following link from proposal closing soon email gets stuck at 'redirecting to thread' 

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3625]
(on mobile so will follow up with repro steps)

**Comment by rdbartlett** [comment]
<img width="1280" alt="screen shot 2016-08-16 at 7 32 58 am" src="https://cloud.githubusercontent.com/assets/970124/17676677/b4a98dc2-6383-11e6-9b11-ac35f45afbfa.png">

Have verified this is happening on all my proposal closing soon emails.

**Comment by gdpelican** [comment]
Cool, I'm aware of this bug, I'll put it on my list.

**Comment by HSalmon** [comment]
Also, on mobile I got the 'Permission denied' error this morning...related?

**Comment by gdpelican** [comment]
Should be fixed pending deploy
