### ISSUE TITLE
"Deactivate account" option not showing on profile page

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3629]
I'm trying to understand exactly what's changed here. 

As I recall, we used to show "deactivate account" to everyone. Clicking the button opens a modal that will either let you deactivate, or explain that you need to appoint a new group coordinator before you can leave.

Now we're just hiding the button from people who can't deactivate, which is resulting in support requests because people don't understand why they can't deactivate.

Here's the design from last year, I'm not sure exactly how far we got with implementing this though, so I think we can either follow this design, or revert the last change that hid this option.

![user settings page](https://cloud.githubusercontent.com/assets/970124/17683141/9d0c5480-63a4-11e6-8e3f-1051dc37e48c.png)
![user settings - about deactivation](https://cloud.githubusercontent.com/assets/970124/17683142/9d0d32e2-63a4-11e6-97a1-fcc6db9cd41e.png)
![user settings - deactivate group](https://cloud.githubusercontent.com/assets/970124/17683140/9d0c3b58-63a4-11e6-815d-1f3bc866ec48.png)
![user settings - deactivate account](https://cloud.githubusercontent.com/assets/970124/17683139/9d0be37e-63a4-11e6-8657-6644869445a3.png)

*Process point: this is an example of where I want a label to indicate something between a bug and a feature.*

**Comment by gdpelican** [comment]
Re process point I think the discussion tag is appropriate for things like these.

**Comment by HSalmon** [comment]
This issue has been resolved!
