### ISSUE TITLE
Stylistic tweaks on Material modals

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3634]
Love the new modals! animations make it feel subjectively more responsive to me. I've noticed a couple things:

On the new thread and new proposal modals, when the context field extends, the buttons lose their margin-bottom:

![image](https://cloud.githubusercontent.com/assets/970124/17722224/b085a864-6484-11e6-9227-3b02f13d7e63.png)

Modal widths: edit comment, invite people, new thread, and new vote, are all different widths. How is this being set? Is there any explicit rationale there or is it a random artefact?

**Comment by HSalmon** [comment]
Saw this one today too:
<img width="329" alt="screen shot 2016-08-18 at 1 42 04 pm" src="https://cloud.githubusercontent.com/assets/2882097/17759221/9bc29eda-6549-11e6-8917-a061399dbee6.png">

**Comment by HSalmon** [comment]
This one still bung in Safari:
![broken-modal-safari](https://cloud.githubusercontent.com/assets/2882097/18074154/d4f3ca7a-6ebe-11e6-8210-368ecd176c67.gif)

**Comment by robguthrie** [comment]
This seems like a good thread to add modal tweeks.

When on a mobile phone, the modals should be 100% width and height.
When on desktop they should be max-height: 90% (rather than 80) and should have max-width of what the old modals were.

I'm happy to make these changes, or leave them to you, James. 

@mhjb do you agree these are the right things to do?

**Comment by mhjb** [comment]
Yes

**Comment by gdpelican** [comment]
These tweaks are done and I've put this up for QA on clone.
https://www.loomio.org/d/l41ZUMma/material-modal-tweaks

**Comment by gdpelican** [comment]
I believe this bug has reached the end of it's usefulness; if there are further tweaks to the material modals plz open a specific report <3
