### ISSUE TITLE
Login button broken on iphone4

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3635]
Cool that the button is higher in the modal, so you can see it without scrolling
Less cool that I can't push the button & that the third-party bit looks like a kind-of label for the button:

![2016-08-17 16 49 51](https://cloud.githubusercontent.com/assets/1380991/17725156/b554c5f6-649c-11e6-92a7-03c574cdce62.png)

**Comment by HSalmon** [comment]
Looks like this is related to https://github.com/loomio/loomio/issues/3634

**Comment by gdpelican** [comment]
Did we fix this with the material modals stuff?

**Comment by mhjb** [comment]
Works a treat!

**Comment by mhjb** [comment]
Closing issues is a rush
