### ISSUE TITLE
Parent group page is only loading some of the subgroup threads

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3637]
Parent group:

![image](https://cloud.githubusercontent.com/assets/970124/17759449/450a6bfc-654b-11e6-85ee-94db9384b9f1.png)

Subgroup:

![image](https://cloud.githubusercontent.com/assets/970124/17759453/5095f234-654b-11e6-9961-33264ba3d205.png)

There are two threads in the subgroup that (to my understanding) should be displayed on the group page (OSOS and Tagging).

I think this has been happening for a while and I've never figured out exactly what's going on. Any clues?

**Comment by rdbartlett** [comment]
I notice the OSOS thread is starred too, not sure if that is relevant.

**Comment by rdbartlett** [comment]
Another example of a bug with the group thread index: this time I'm on a subgroup page, and I can't see a thread in the index, but I've confirmed it exists as you can see in the search results:

![image](https://cloud.githubusercontent.com/assets/970124/18117276/b11192c0-6fa1-11e6-96a9-bcda89bdcf7f.png)

**Comment by gdpelican** [comment]
Okay, I think I just fixed this one. It's tough to repro, but let me know if you experience this again.
