### ISSUE TITLE
Migrate from CoffeeScript?

### ISSUE THREAD

**Issue by sdgluck** [loomio/loomio#3640]
Hey Loomio-ers,

First of all, thanks for such a fantastic piece of software, and for sharing it with us all! We love it at [Outlandish](https://github.com/outlandishideas).

Onto the issue... perhaps it will be quite controversial. I would love to contribute to the Loomio project, however CoffeeScript leaves a bad taste in my mouth, especially since ES2015 became complete as a standard, making many of CoffeeScript's features redundant.

I wonder if there is place for a discussion about migrating the current Angular codebase from CoffeeScript to ES2015 JavaScript? There are [tools available to help](https://github.com/js2coffee/js2coffee) (to ES5) and I think this change would make the software a more attractive place for developers like myself to make contributions.

Cheers!

**Comment by gdpelican** [comment]
Hm, yeah. I've some thought in (and against) this direction recently.

First off, es6 is in my head more than Good Enough at this point (and it will get better). If there was a magic tool which converted cs to es6 flawlessly (and with excellent code style, etc.), I'd probably be a solid aye. Here's a relevant discussion in which Discourse decides to make this switch (https://meta.discourse.org/t/is-it-better-for-discourse-to-use-javascript-or-coffeescript/3153), in which a series of contributors (including some prominent names like Yehuda Katz) argue convincingly enough that es6 is the way to go (and that was in 2013). 

However, this is a high-risk, high-cost, low-reward move for Loomio the business. We don't have the dev resources that Discourse does, and while I personally am _quite_ passionate about encouraging more open source contributions to Loomio, and building an ecosystem of developers, even I don't think I can quite justify halting clientside development and focusing on this for any length of time. Even though this is about as benign a language switch as you'll find out there (we're not talking JS to Elm, or Ruby to Python here), we're still replacing a _ton_ of Code That Pretty Much Works with a _ton_ of Code That Probably? Works, which is really high on the list of 'Stuff to Never Do': http://www.joelonsoftware.com/articles/fog0000000069.html

If this is something you feel really good about, I'd encourage you to submit a PR which updates the build system (check out here: https://github.com/loomio/loomio/blob/master/angular/tasks/app.coffee) [Sorry, it's in .coffee :P] to allow us to transpile both .coffee and es6 files into our final app.js file, which would be the best first step here, and would allow us the ability to start swapping out components one by one, which would be the best way to approach this.

**Comment by sdgluck** [comment]
Thanks for your swift reply @gdpelican!

I would personally discourage mixing both CoffeeScript and ES2015 in the hope that people migrate incrementally. I would expect that old code would be left unchanged and only new code would be written in ES2015, which is less than ideal for maintainability, etc.

A potential approach for wholesale migration could be to first convert from [CoffeeScript to ES5](https://github.com/js2coffee/js2coffee) and then from [ES5 to ES6](https://github.com/mohebifar/lebab). This isn't _rewriting_ the code as is described in Joel on Software; rather an automated migration with potentially little friction.

I am willing to give this a go in my spare time and report back if that would be useful. Of course I am also happy to stand down if you feel strongly against a migration of this kind! :-)

**Comment by gdpelican** [comment]
@robguthrie and @HSalmon should chime in here as well before you spend time on this. I'll say for my part that a wholesale migration strikes me as a much riskier move, especially given that we don't have a robust set of unit tests for components on the front-end.

**Comment by gdpelican** [comment]
@robguthrie @HSalmon could you weigh in here please?

**Comment by robguthrie** [comment]
Personally: I enjoy Coffee, I just think it's so neat that someone fixed javascript ages ago. It really made JS accessible to me at the time we started the Loomio 1.0 project. It's not perfect but it's pretty fun once you get the hang of it.

That said, it's hayday is over, some point in the future (hopefully not too far) we're going to start an upgrade to Angular 2, for which I've heard TypeScript is the best thing to use.

So I'm not in a hurry to change, but don't want to stop anyone. I don't want to move to ES5. I'd be ok with moving to ES6, but I wonder if our ideal move would be to TypeScript - it seems to have a lot of benefits.

**Comment by HSalmon** [comment]
I like Coffee too. If people feel strongly that we should migrate then I'd support that. Just wondering if this is something we can afford to do right now?

**Comment by sdgluck** [comment]
I'm not attacking CoffeeScript; my concern was just that it is only used by a minority of JavaScript developers, and by using it you limit yourself to only their potential contributions.

But if you're already discussing moving to Angular 2 w/ TypeScript then I guess my point is moot! :+1:

**Comment by gdpelican** [comment]
Thanks for raising this, @sdgluck , it's a valuable conversation to have. We'll definitely move off coffeescript, but it will likely be sometime early next year before it happens.

In the meantime, I'm going to put it on my mad science list to allow plugins to be written in other flavours of JS.
