### ISSUE TITLE
I was told I had been logged out but I wasn't

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3643]
I'm logged in in Chrome and Firefox. I logged out in Firefox. Then I returned to Chrome and got the modal telling me I've been logged out in another window. I click OK. The page reloads and I'm still logged in.

Haven't got repro steps yet but wanted to log this.

**Comment by gdpelican** [comment]
Closing this as it's ancient and I haven't heard this problem in a while. Please let me know if you see again.
