### ISSUE TITLE
Email gateway?

### ISSUE THREAD

**Issue by fauno** [loomio/loomio#3644]
Hi, it's been a long time :)

So we've been working on getting up to speed with the latest loomio at [consenso pirata](https://consenso.partidopirata.com.ar).  We ended up discarding our branch and starting a new one since everything seemed to change place :P  

We also discovered the API for comments changed (!!!) and our own gateway [loomio_pipe](https://github.com/piratas-ar/loomio_pipe) stopped working.  It seems since the API uses snorlax and doorkeeper now we can't authenticate via headers as before.  We can't seem to find your email gateway now to look at how things are.

So before spending time poking around I came here asking for directions.  Where should we look for API authentication now? :)

**Comment by HSalmon** [comment]
@robguthrie, looks like this could use your brain :)

**Comment by robguthrie** [comment]
Hi @fauno, We've merge the loomio-email-gateway code directly into Loomio, as it was more complicated to setup reply by email in that configuration.

Now mailin (the node smtp server) sends it's POST's directly to loomio.

So the API end point for mailin is `/email_processor`
Which is handled by `app/email_processors/email_processor.rb`

Hopefully that provides the entry point you need to understand what you want to do.

Sorry for changing the code and breaking your solution. It was necessary for us to make deployment (via [loomio-deploy](https://github.com/loomio/loomio-deploy)) easier
