### ISSUE TITLE
'Yesterday on Loomio' emails show older activity as well

### ISSUE THREAD

**Issue by natiloomio** [loomio/loomio#3646]
we got this message from a user:

" My daily 'Yesterday on Loomio' emails used to just include new posts since the day before. Now they go back a week or so, or even further. I haven't noticed a pattern. Even on the site it shows a 'New Activity' line at a point 5 days ago in a thread, even though I logged in to read this thread yesterday. It's a bit of a pain keeping track of longer threads and makes the daily email pretty useless. Not sure when this broke but sometime between a couple weeks and several months ago (as we had a lull in activity)"

**Comment by gdpelican** [comment]
Hm, the code here is prettay explicit about only including discussions with new activity in the past 24 hours, and I haven't been able to repro this. Have you heard this complaint from others, or experienced it yourself, @natiloomio ?

**Comment by natiloomio** [comment]
sorry for the late reply! I haven't heard about it again.

**Comment by gdpelican** [comment]
I'm going to close for now. If someone runs across this again, forward me the email you received and I can diagnose it.
