### ISSUE TITLE
Public groups page has mysterious 'Loomio Users' private group in it

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3647]
![image](https://cloud.githubusercontent.com/assets/1380991/17989272/46b7ac9a-6b80-11e6-9fd0-660500ac83e8.png)

![image](https://cloud.githubusercontent.com/assets/1380991/17989282/52034fa0-6b80-11e6-86c4-ce2a99e6c847.png)

**Comment by gdpelican** [comment]
That group is weird (and old) af; it has no members or admins, was created in 2012, and had `memberships_count` set to 193 despite having no members in it. I ran `update_memberships_count` on it, which reset it to 0, which should make it no longer appear on the explore page. <3
