### ISSUE TITLE
Garbage in alt tags on marketing site

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3651]
Alt tags look like "Loomio old way 7a4b140b4a163b50e520668753f7e4e14c395b15671745ff018d9e41bf40cb4f" on all the images on the marketing site. 

@HSalmon would you mind cleaning this up? I'm working with a group who are currently evaluating Loomio, including some members who will be navigating my screenreader.

**Comment by HSalmon** [comment]
Can do

**Comment by gdpelican** [comment]
Fixed pending deploy
