### ISSUE TITLE
I'm a member of subgroup but not parent group; parent missing from sidebar

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3653]
'Kelburn' is not a subgroup of 'OurSpace', it's a subgroup of 'Playcentre's 75th Jubilee'

![image](https://cloud.githubusercontent.com/assets/1380991/18038143/f6121522-6de7-11e6-952a-44f241a6122a.png)

**Comment by gdpelican** [comment]
Another notch against allowing users to be members of subgroups without parent groups probably.

**Comment by gdpelican** [comment]
Fixed pending deploy

**Comment by mhjb** [comment]
Sweet!
