### ISSUE TITLE
Group logos should always be displayed as a square

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3656]
Here's an example of this being slightly broken on the email_preferences page:

![image](https://cloud.githubusercontent.com/assets/970124/18039216/b525e608-6df4-11e6-9861-fd4a82e7ab30.png)

**Comment by gdpelican** [comment]
We've got a 'group_avatar' directive which (I believe) works properly. We just want to move all the times we do some garbage like

```
%img.box--medium{ng-src: "{{group.logoUrl()}}"
```

to use that directive.

```
%group_avatar{group: group}
```

**Comment by HSalmon** [comment]
@rdbartlett, I can't see this on the email settings page and I'm a member of that group...weird

**Comment by gdpelican** [comment]
Fixed pending deploy
