### ISSUE TITLE
Sidebar not listing my groups

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3667]
I left the parent group, but am still a member of the subgroup. Suddenly, all my groups disappeared from the sidebar. 

![image](https://cloud.githubusercontent.com/assets/970124/18116996/eab884e0-6f9f-11e6-84b5-b32b5849c7a6.png)

**Comment by rdbartlett** [comment]
#3653 is probably relevant

**Comment by rdbartlett** [comment]
In the groups list in the search dropdown, I can see my subgroups, but the parent group is missing, so it looks like they are subgroups of Kai Kākāriki, instead of Loomio Community.

![image](https://cloud.githubusercontent.com/assets/970124/18117047/51a2cc60-6fa0-11e6-803c-87b972b6e1ab.png)

**Comment by uportalis** [comment]
Hi
I think this issue is really problematic as it also impact top-level groups.
I'm member of groups and sub-groups.
I can't see non of them on the side bar.
Here is my Loomio user ID: @louisparisotsk
rgds,
Louis

**Comment by gdpelican** [comment]
@HSalmon could you take a peek at this one? The error coming through the console is this:

```
vendor.min.js:6 Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: group in groups() | orderBy: 'fullName' track by group.id, Duplicate key: 11075
```

So we need to de-dupe `sidebar.coffee#44` somehow.

**Comment by gdpelican** [comment]
This should be resolved now.
