### ISSUE TITLE
When I try to leave a subgroup it kicks me out of the parent group instead

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3668]
Have just done this twice to confirm: when I leave the subgroup (in this case [Installing Loomio](https://www.loomio.org/g/C7I2YAPN)), it kicks me out of the parent group, but leaves me in the subgroup.

**Comment by gdpelican** [comment]
Believe it or not this is a tagging plugin bug; it's replacing the whole group actions dropdown with parent for groups where it's enabled.

Downgrading this priority a little because it's not affecting most users, and I'll fix it up soonish.

**Comment by gdpelican** [comment]
This is fixed pending deploy.

**Comment by rdbartlett** [comment]
Weehoo thanks captain science!
