### ISSUE TITLE
Can we remove the Intercom widget from clone?

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3670]
For nicer testing:

![2016-09-01 11 20 31](https://cloud.githubusercontent.com/assets/1380991/18149829/bc2d0e2e-7036-11e6-9f25-85de896a90c9.png)

**Comment by gdpelican** [comment]
I'd like to keep the issues list to things that are happening in production I think.
This is a 'bug' that I think we want to handle by bringing the modals on clone in over the intercom widget.

**Comment by mhjb** [comment]
Fair enough. In this case I've asked about getting the Intercom widget matching prod in a few different contexts and haven't managed to get any attention on it.

**Comment by robguthrie** [comment]
@mhjb - work with me.
