### ISSUE TITLE
Scrolling on ios lacks inertia / is broken on home page

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3671]
Makes it very tedious to navigate e.g. a long thread page, and makes the whole app feel wooden compared to other websites on the ipad. 

May point to a fix: http://webdesign.tutsplus.com/tutorials/how-to-make-responsive-scrollable-panels-with-flexbox--cms-23269#comment-1850329538

**Comment by gdpelican** [comment]
How is this different from #3639 ?

**Comment by mhjb** [comment]
Oh — I'm sorry, that was stupid. I'll close the other as this has the possibly useful fix.

**Comment by gdpelican** [comment]
@mhjb Is this something that works ok on the marketing page, but not the thread page?

Honestly I'll probably have to get my mitts on an iDevice for testing somewhere to get this resolved; I don't have any way of reproducing it at the moment.

**Comment by mhjb** [comment]
!! on ipad (4th generation) / ios 9, the front page doesn't scroll vertically at all in landscape orientation (it does feel like it wants to scroll horizontally). In portrait orientation it scrolls but without inertia.

In-app it scrolls without inertia in both orientations.

**Comment by mhjb** [comment]
This is one I didn't notice when we met on Friday — just to reiterate — even on the latest version of iOS on iPad, our home page doesn't work. You can't scroll down.

@HSalmon perhaps something you'd like to tackle?

**Comment by HSalmon** [comment]
Is the styling broken @mhjb, is there something visibly broken about it? If so, could you please post a screenshot?

**Comment by mhjb** [comment]
not styling; you just can't scroll down home page

**Comment by mhjb** [comment]
@robguthrie says there's a CSS property to turn inertia back on for safari
