### ISSUE TITLE
Translate button appears for unsupported translation languages

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3673]
Reproduction steps:

* Visit public Russian thread: https://www.loomio.org/d/oksApLbV
* Click Translate 
* We get three seconds of the spinner, then nothing

**Comment by HSalmon** [comment]
Errbits too: https://errbit.loomio.io/apps/57215524657272000e000001/problems/57c790426572720f9e0009b3

**Comment by gdpelican** [comment]
Looks like bing translator doesn't support Belarusian.

**Comment by mhjb** [comment]
Probably too hard to do anything about I guess

**Comment by gdpelican** [comment]
The fix would be to hold a list of values Bing does support, and not display the translate button if we're in an unsupported language.

**Comment by gdpelican** [comment]
This is now fixed.

**Comment by mhjb** [comment]
You're awesome
