### ISSUE TITLE
Multiples of the same tag appearing

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3678]
<img width="333" alt="screen shot 2016-09-04 at 5 34 08 pm" src="https://cloud.githubusercontent.com/assets/5498878/18229247/e794ecbc-72c5-11e6-96f3-f95fdfe0b786.png">

I went in and clicked that tag a few times and the copies went away, and now I can't reproduce it again. But it seems possible to add the same tag multiple times.

**Comment by gdpelican** [comment]
Thanks. I've moved this to the tags repo here:
https://github.com/loomio/loomio_tags/issues/2

**Comment by alannallama** [comment]
This seems to be happening again @gdpelican 

<img width="564" alt="screen shot 2016-09-26 at 11 51 18 am" src="https://cloud.githubusercontent.com/assets/5498878/18818781/a2950a72-83df-11e6-97c7-0a24e2fc524b.png">
