### ISSUE TITLE
Item not disappearing from unread unless page is scrolled

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3682]
I click on a thread and it loads, and then I go back to Unread but the item is still there. You can see in this example, the Unread count stays at 4 even though the thread loads up.

![](https://i.gyazo.com/8520d6a1eb4c234c4ec505ef8d61e28a.gif)

It seems related to whether or not I scroll around the page. If I scroll up and down, the Unread count goes down and the item disappears from Unread. But simple loading the page, viewing the comment, and going back doesn't mark it as read.

This is different from [#3618](https://github.com/loomio/loomio/issues/3618), in that it doesn't show a blank space under the "new content" line, but actually does show the new comment. Also it's possible to make these items disappear by clicking "mark as read", but with the other issue even that doesn't work.

**Comment by gdpelican** [comment]
This is an issue related to the interplay between angular-scroll and angular-inview, which we use to deal with manual scrolling and telling which elements are in view, respectively.

I think we might be able to just lose angular-scroll (I've had a look at the internals of it and it made me go 'er wat?')

In the meantime I've opened an issue with angular-inview (https://github.com/thenikso/angular-inview/issues/13) to see if he can come up with a nice way for us to fix this.

**Comment by gdpelican** [comment]
This should be fixed pending deploy
