### ISSUE TITLE
As a member of no groups, when I visit /dashboard I'm not redirected to /explore

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3685]
![image](https://cloud.githubusercontent.com/assets/1380991/18337703/fd68a136-75e6-11e6-8471-828801c82728.png)

repro steps: start a new group with a new account, deactivate the group, browse to /dashboard

**Comment by HSalmon** [comment]
I don't think the current implementation specifies that you should be redirected to Explore after leaving a group, but rather that you land there after signing in (if you have no groups)

**Comment by HSalmon** [comment]
Is it ok if I close this for now? It seems more like a request for additional functionality than a bug report

**Comment by mhjb** [comment]
Sure!

**Comment by HSalmon** [comment]
Thank you :)
