### ISSUE TITLE
Markdown tables should have 10px margin-bottom to match paragraphs

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3686]
Currently they have 0px.

Before

![image](https://cloud.githubusercontent.com/assets/970124/18338789/8474fc8a-75ef-11e6-87f7-ecfaf235e63c.png)

After

![image](https://cloud.githubusercontent.com/assets/970124/18338784/77bccf90-75ef-11e6-8a85-cfb021e9023e.png)

Alternatively, if someone wants to pair with me to get my dev env back up to speed I will make a PR :)

**Comment by CruiseDevice** [comment]
which file is this?

**Comment by gdpelican** [comment]
@CruiseDevice I'd say you could put those styles in `1_utilities.scss`.

Be careful not to affect things that aren't markdown tables though!
