### ISSUE TITLE
Emoji menu in wrong position

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3695]
Just came in overnight:

![image](https://cloud.githubusercontent.com/assets/970124/18448757/6dc9cc7e-7980-11e6-8cad-226f9e80d647.png)

On Chrome and Firefox on OSX.

Potentially the most trivial bug I've ever logged?

**Comment by gdpelican** [comment]
I am very confused by this. This is a style that leaked into prod from a plugin in my dev environment. That... shouldn't happen. I've redeployed which will fix it, but need to have a look at how the heck this happened.
