### ISSUE TITLE
Crowdfunding celebration page is missing padding

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3697]
https://www.loomio.org/crowdfunding_celebration

When people mention they supported us I like to point them at that

**Comment by gdpelican** [comment]
I wince a little every time I see a bug title like 'this is a bit broken', because I _crave_ specificity. <3

**Comment by mhjb** [comment]
It looked to me like there are a bunch of things wrong with it — padding, columns, image sizing etc. It just got overlooked in the latest marketing site refresh and I figured any dev who took on the bug would know how to make it good.
