### ISSUE TITLE
'Remember me' should be the default

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#3708]
Opening this as an issue because I feel like we need to talk about it a little before we do anything here.

Here is a gluttony of quality thoughts on the issue:
http://ux.stackexchange.com/questions/20924/why-isnt-the-remember-me-checkbox-in-login-forms-enabled-by-default

My leaning is, 'make it a default (most people aren't logging into stuff from the library computer anymore, especially for productivity software - maybe we want some stats for this somehow?), but put a warning saying "uncheck this box if you're at a public computer"'

Option 2, which I like a lot but only because I'm an internet-forward madman, is to remove the checkbox entirely and enforce messaging that says 'please make sure you log out if you're on a shared computer'. I'd probably support this if there were say < 2% of users who use shared devices. Another interesting idea (moar work tho) would be a user setting, 'Log me out automatically after X hours of inactivity', for users who know they'll be accessing Loomio from the internet cafe a lot.

@mhjb @rdbartlett @robguthrie ?

EDIT: I've flip flopped on this after a short walk and think. The 1% inconvenience of having to tick a box to remember me is not worth the 1000% inconvenience of having someone else gain access to your crap, especially if we end up in cases where you can log into other websites with your Loomio creds. Let's leave it as is.

**Comment by mhjb** [comment]
Any ideas about how to guesstimate what proportion of Loomio users use shared computers?

**Comment by gdpelican** [comment]
I think we'd have to find some existing research about web trends in general; I don't think it's a thing we can track. My cursory google search on the matter didn't turn up anything interesting though.

**Comment by robguthrie** [comment]
I think it should be default. Google does it by default.

**Comment by mhjb** [comment]
Me too. For the same reason. I also notice Facebook on mobile web or app just remembers you, and doesn't even give the option of not.

![image](https://cloud.githubusercontent.com/assets/1380991/18534076/0861381e-7b3c-11e6-955b-0fafc649cccc.png)

**Comment by gdpelican** [comment]
This is now the case.
