### ISSUE TITLE
Graphical emoji helper does not insert text in post

### ISSUE THREAD

**Issue by jessykate** [loomio/loomio#3721]
![screencast](http://g.recordit.co/tJCBR577WW.gif)

mac os x , chrome browser, checked browser console and no JS errors.

**Comment by gdpelican** [comment]
Hrm, I can't reproduce this under the same OS / browser. Any other mitigating factors I should be aware of? Does it happen for all groups, all the time?

**Comment by HSalmon** [comment]
I experienced this for a short period but it's working for me now

**Comment by mhjb** [comment]
Still failing for you, @jessykate ?

**Comment by HSalmon** [comment]
I'm wondering if we can close this now, seeing as we haven't had further feedback that this is still an issue?

**Comment by HSalmon** [comment]
Closing for now, we can reopen if we get further reports
