### ISSUE TITLE
Choose plan modal appearing when chargify params are not set

### ISSUE THREAD

**Issue by fauno** [loomio/loomio#3740]
so today i merged master to our fork and found this... shouldn't it be on loomio_org_plugin? :)

![loomio](https://cloud.githubusercontent.com/assets/468204/18752847/05ece0d2-80ba-11e6-8180-ed21ce4f5ddf.png)

**Comment by gdpelican** [comment]
Emphatically yes, although when we built this the plugin system was not sophisticated enough to handle it. I'll take this as a request to disable that modal (and any other payment related stuff) it if `Loomio.chargify` is not set (which it shouldn't be on your instance)

PS - have you managed to keep the 'I volunteer' vote option through to the angular interface? I see a peek of purple in the bottom of that screenshot :)

**Comment by gdpelican** [comment]
@robguthrie Can I safely delete the trial and gift cards, which now appear abandoned to me?

**Comment by fauno** [comment]
thanks! i just saw in `angular/core/components/group_page/group_page_controller.coffee`  a `@shouldShowChoosePlanModal` that tests for chargify.

i also tried the gratis option, that opens a second modal asking if i want to donate or change plan, but it throws a 400 error when i choose to keep it that way.  i've checked the log but it didn't throw a ruby exception.


regarding your PS, yes, but since we spent some months without pulling we just decided to start our fork anew.  we also implemented linked etherpad for every discussion.  we don't know angular so our interface changes are very minimal.

**Comment by gdpelican** [comment]
That's what referenced PR does, is add in a check for chargify there.

We have ENV variables which populate that you should be going to, say `loomio.chargify.org/subscriptions/:id` from there. But of course if those aren't populated it tries to take you to `/subscriptions/:id`, which is 400 level bung.

You could hotfix that check onto your instance and probably never see that modal ever again :D
