### ISSUE TITLE
Thread title panel exceeds screen width

### ISSUE THREAD

**Issue by uportalis** [loomio/loomio#3784]
On my 1280x1024 screen, the thread title panel (the one displayed when scrolling, with the "create proposal" button) exceeds the available width, making the "create proposal" button partially out of the screen.
If I close the left panel, the display is OK.

![loomio_display_bug1](https://cloud.githubusercontent.com/assets/11533685/19342773/84384c5e-9133-11e6-9144-c8bb844d2b54.PNG)

**Comment by gdpelican** [comment]
Hey @uportalis can you confirm if this is the same issue laid out in #3568 and the referenced issue #3506?

**Comment by uportalis** [comment]
Hi @gdpelican 
Yes, this is the same issue. This bug report can be closed as a duplicate.
rgds
