### ISSUE TITLE
Thread preview looks broken on mobile

### ISSUE THREAD

**Issue by HSalmon** [loomio/loomio#3786]
Safari on phone running iOS 9.3.5

![img_0096](https://cloud.githubusercontent.com/assets/2882097/19368937/0270ed62-91ff-11e6-9f98-1730f0453245.PNG)
![img_0095](https://cloud.githubusercontent.com/assets/2882097/19368938/0275862e-91ff-11e6-839b-4dd95ec2f407.PNG)

**Comment by robguthrie** [comment]
Can confirm this does NOT happen on chrome on android.

Looks like a older safari flexbox issue.

**Comment by HSalmon** [comment]
Interesting because my phone seems to render everything else correctly.

**Comment by HSalmon** [comment]
Would be keen to hear from others whether they experience this problem.
@alannallama, @gdpelican, @rdbartlett, @natiloomio - would you mind confirming whether you see this behaviour?

**Comment by gdpelican** [comment]
I haven't been able to see it before; I have an android tablet and an HTC One android phone.

**Comment by mhjb** [comment]
Thread listings look good on iPad/IOS10.1.1/Safari

**Comment by HSalmon** [comment]
I'm gonna close this because it seems that only I'm experiencing it :)

**Comment by mhjb** [comment]
I see it on poor old iOS7/Safari
