### ISSUE TITLE
Resolution for group cover photos

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3790]
When you visit the group cover upload modal, you see the recommended size is 1400x320px. If you look in `app/models/group.rb` you'll see we call this size "largedesktop". However, when you visit the group page, we're serving the "desktop" size, which is 970x200px. 

This results in cover images having poor resolution on high density displays, and being cropped unexpectedly (the specified aspect ratio is 0.2286, but Loomio is serving images at 0.2062).

At least, the prompt should provide accurate information. 

Ideally, we would serve high resolution images to high resolution displays, and smaller files to small screens. (E.g. my 3 year old laptop display is 2600px wide.)

Does it make sense to switch out `cover_url_desktop` for `cover_url_large_desktop` as a first step, and then look at a more intelligent solution further down the line?

If there are groups with cover photos that lack a large_desktop size, I think it is easy to [generate the missing sizes](https://github.com/thoughtbot/paperclip/wiki/Thumbnail-Generation#generatingregenerating-your-thumbnails).

What do you think is the best way forward folks? I'd like to resolve this before we start telling everyone to upload new cover photos.

**Comment by gdpelican** [comment]
Hm.

- I'm not worried about generating sizes
- I'm very worried about making people download big images on mobile (the existing image is already waay too big for that.)
- I have a hunch that our current solution was a compromise for that
- It's impossible to inline @media queries, which means we can't dynamically change the image being displayed based on window sizing that way.
- I _think_ we want this: https://css-tricks.com/responsive-images-youre-just-changing-resolutions-use-srcset/, because we can serialize out all of the possible images (they're just urls, not actual image data, so it's easy), throw them into a srcset, and let the browser decide what size is best.

However, I'm a pretty unenthusiastic about doing that work right this second; how important do you feel it is?

**Comment by gdpelican** [comment]
Also, srcset _just_ got released the IE bleeding edge, so it won't work for IE10; sigh.

**Comment by rdbartlett** [comment]
I registered this ticket after setting up a real group and feeling embarrassed about the lofi image, with the wrong aspect ratio. 

I'm keen for us to make some improvement here, as we're putting a lot more emphasis on cover photos as part of the activation work.

Regarding browser compatibility, if you use `src` and `srcset`, I'm guessing IE will fall back to whatever you define in src though right?

**Comment by robguthrie** [comment]
I think we can provide the best resolution image for the viewport width without using unsupported html features.

What if we send over all the urls for sizes that we have, and have a javascript function which looks at the viewport width to decide which is the best url to use?

**Comment by gdpelican** [comment]
Fixed in #3809

**Comment by rdbartlett** [comment]
Thanks for the fix James. 

The sizes specified in group.cover_photo.styles weren't chosen with this design in mind, so I'm keen to remedy that soon. The latest change has resulted in better resolution for big screens, and worse for small screens (cos the 'card' size is only 94px tall, but the element is 320px high). 

Eg., this on an HD screen:

![image](https://cloud.githubusercontent.com/assets/970124/19747369/d40c2cbe-9c37-11e6-9c9e-ba91da4ef72c.png)

![image](https://cloud.githubusercontent.com/assets/970124/19747391/edc69f9a-9c37-11e6-8153-cdb9036597f0.png)

![image](https://cloud.githubusercontent.com/assets/970124/19747405/01b27326-9c38-11e6-8ae3-9cfce417bf47.png)

![image](https://cloud.githubusercontent.com/assets/970124/19747421/1d3ed3d2-9c38-11e6-96e1-53b67c01ded3.png)

![image](https://cloud.githubusercontent.com/assets/970124/19747469/3dd0eafe-9c38-11e6-8c3e-c8accc6cd7ba.png)

I think we want to set up a new stack of sizes, now that it is easy to deliver the right image to the right screen. 

Here's some info from GA:

![image](https://cloud.githubusercontent.com/assets/970124/19747643/77ff3edc-9c39-11e6-87bf-ba04ee5fd365.png)

I've done a little research into how the displays would change if we set the sizes to be:

* small: 480x320px (from $tiny-max in mixins)
* medium: 992x320px (from $small-max in mixins)
* large: 1984x640px (i.e. 2x medium)

Here's how that would display on various screens...

![original](https://cloud.githubusercontent.com/assets/970124/19748829/bd600ad6-9c40-11e6-8a6c-61f52a88e809.png)

![current sizes cut server side](https://cloud.githubusercontent.com/assets/970124/19748833/c819c3c2-9c40-11e6-8388-753f88be09e2.png)

![current sizes displayed client-side](https://cloud.githubusercontent.com/assets/970124/19748836/c9dae416-9c40-11e6-8eae-99d30b6ee3db.png)

![new sizes cut server side](https://cloud.githubusercontent.com/assets/970124/19748838/cf0ecccc-9c40-11e6-88d6-b1beaf90f925.png)

![new sizes displayed client side](https://cloud.githubusercontent.com/assets/970124/19748839/d1d15362-9c40-11e6-86b4-66113f83b890.png)

I think my logic is right, but there's a good chance I messed something up because it is confusing as all heck to think about stretching, cropping, and the difference between HD and SD screens.

Please someone tell me I did a good job.

**Comment by rdbartlett** [comment]
Note to self: card size was chosen for explore page. Need to investigate that before making changes.

**Comment by robguthrie** [comment]
good job!
