### ISSUE TITLE
Welcome modal shows up more than once for some people

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3791]
I can give you a tour of ahoy_events to prove it, if you like :)

**Comment by gdpelican** [comment]
I'll need some more info for this one; what kind of 'seeing more than once'? Is it more than twice?

**Comment by mhjb** [comment]
Behold! https://metabase.loomio.io/card/237

**Comment by gdpelican** [comment]
Hrm, seems like most of them are 2 (not so bad), and that the several that I checked have the correct experiences set now, although there's a few with a bunch of modal sightings.

Seems possible if there's multiple windows open, although I wonder if we could get someone to confirm that this is happening for them.

**Comment by mhjb** [comment]
It happened for me when I was mapping the start group flow last week — would it be useful to try and reproduce it again?

**Comment by gdpelican** [comment]
Yep, steps would be super useful. The code here is pretty straightforward:

```
if !Session.user().hasExperienced("welcomeModal") # if you don't have the experience
  ModalService.open GroupWelcomeModal, group: => @group # open the modal
  Records.users.saveExperience("welcomeModal") # and save the experience
```

but maybe there's some kind of edge case we're missing.

**Comment by HSalmon** [comment]
This will be irrelevant when the intro carousel gets deployed (because it replaces the Welcome modal)
