### ISSUE TITLE
Thread menu sometimes not available on thread page

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3794]
I'm a coordinator of this group:
![image](https://cloud.githubusercontent.com/assets/1380991/19460476/8cba7330-9538-11e6-9ead-832ea439ffd0.png)

but not this one:
![image](https://cloud.githubusercontent.com/assets/1380991/19460460/762de73c-9538-11e6-80e3-ee4f75bcfc04.png)

… but either way I should see the dropdown menu with Edit / Print / Mute etc

**Comment by gdpelican** [comment]
Looks like we only show the dropdown if you can edit the thread (`membersCanEditDiscussions`), but it should be there so you can mute or print the thread I guess.

**Comment by gdpelican** [comment]
#3798
