### ISSUE TITLE
Bug:  Direct URL links for old Loomio comments not working consistently

### ISSUE THREAD

**Issue by gcassel** [loomio/loomio#3797]
Right now, the direct URLs for some Loomio comments-- such as https://www.loomio.org/d/3kebtDN4/comment/1081993 -- don't seem to be working properly in Chrome, Firefox or Microsoft Edge.  That link is simply taking me to the top of the Loomio topic in question.   

The example comment above is from 21 July 2016, and has been edited by the author.  It's from a private Loomio group, but it's one which devs have access to.   I'm currently seeing the same problem with *some* comments of equal or greater age, regardless of whether or not they've been edited.  I'm *not* seeing that problem with comments from September onward.

I consider this a peripheral or minor bug (debatable).   Linking specific Loomio comments is integral to my discussion techniques, but that's probably rare.

**Comment by gdpelican** [comment]
I believe this is because we've mis-named the 'activeCommentId' param that's passed into the activity card:

```
# thread_page_controller.coffee
@requestedCommentId   = parseInt($routeParams.comment or $location.search().comment)
```
```
# thread_page.haml
      %activity_card{discussion: "threadPage.discussion", active-comment-id: "threadPage.activeCommentId"}
```

Changing `threadPage.activeCommentId` to `threadPage.requestedCommentId` should fix this, I think.

**Comment by gdpelican** [comment]
Fixed pending deploy
