### ISSUE TITLE
Intercom messenger fails to open when I click Contact Us

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3802]
<img width="462" alt="screen shot 2016-10-19 at 1 25 49 pm" src="https://cloud.githubusercontent.com/assets/970124/19501143/a118bd92-95ff-11e6-9d57-25d6e01df5e8.png">

Sometimes it fails with this error, sometimes it takes me to the rails contact form.

**Comment by gdpelican** [comment]
I think Intercom upgraded their widget recently, maybe they changed the API with that upgrade. Did you or @mhjb get any correspondence around how to upgrade? I'll try to see if I can find some docs on it too.

**Comment by mhjb** [comment]
@gdpelican see https://www.loomio.org/d/0lf9Kej7/comment/1156247

**Comment by gdpelican** [comment]
Can someone confirm that going into the JS console and running `Intercom('show') does the thing we want Contact Us to do?

**Comment by mhjb** [comment]
It does

**Comment by gdpelican** [comment]
Kay I'm going to deploy that fix. Give me a few.
