### ISSUE TITLE
Thread placeholder text showing when it shouldn't

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3812]
![image](https://cloud.githubusercontent.com/assets/970124/19707364/98f3f770-9b73-11e6-9b12-d1aa2bfb2c11.png)

I'm a logged in, non-member visitor to [this group](https://www.loomio.org/g/HZxeWwBl/p2p-foundation). I shouldn't see the hint explaining what threads are.

**Comment by gdpelican** [comment]
Currently the logic is to show the threads placeholder if there are less than 4 discussions. I'm pretty sure this is rather wrong (IE, it's assuming you can see the example content and whatnot).

What should the logic be? Tie it to an experience?

**Comment by rdbartlett** [comment]
Whatever the logic is, I think it just needs an extra condition on it: only show it to people who have permission to start a thread.

**Comment by gdpelican** [comment]
Ah okay, easy enough.
