### ISSUE TITLE
Notifications button disappeared 

### ISSUE THREAD

**Issue by natiloomio** [loomio/loomio#3824]
I'm using Firefox and Chrome on Kubuntu.
![Chrome inspector](https://cloud.githubusercontent.com/assets/15793070/19874686/eb4922d6-a02b-11e6-87c4-fcfe98cf88f0.png)
![Firefox inspector](https://cloud.githubusercontent.com/assets/15793070/19874690/f1665a4e-a02b-11e6-86da-dd92e7943ffe.png)

**Comment by mhjb** [comment]
Me too. Wonder what's up with that googleads bizo in the console? 

![image](https://cloud.githubusercontent.com/assets/1380991/19876712/97961ac4-a03d-11e6-9e11-c9924ed425da.png)

**Comment by gdpelican** [comment]
That's because you have a privacy badger or adblocker or something which is preventing google from Big Brothering you.

The error here is that there's a certain notification that's causing the JS in the notifications to error, which explains why you see it and I don't.

**Comment by natiloomio** [comment]
Hi James,  Is that an issue for me as well? I have adblock deactivated for
Loomio.

**Comment by gdpelican** [comment]
I've deleted the notifications which were causing trouble for the two of you. Seems like there's some case where a notification can hang around even after its event is destroyed.
