### ISSUE TITLE
exception with latest master

### ISSUE THREAD

**Issue by fauno** [loomio/loomio#3833]
any idea? btw, is there a public chat channel for loomio? :)

```
App 30558 stdout: NameError (uninitialized constant Group::Subscription):
App 30558 stdout:   app/serializers/group_serializer.rb:110:in `subscription'
App 30558 stdout:   app/serializers/group_serializer.rb:66:in `subscription_kind'
App 30558 stdout:   app/models/current_user_data.rb:3:in `data'
App 30558 stdout:   app/helpers/angular_helper.rb:27:in `app_config'
App 30558 stdout:   app/helpers/angular_helper.rb:6:in `boot_angular_ui'
App 30558 stdout:   app/helpers/uses_metadata.rb:9:in `show'
App 30558 stdout:   app/controllers/application_controller.rb:83:in `user_time_zone'
```

**Comment by gdpelican** [comment]
I was actually just working on a fix for this. Give me a few. :D

**Comment by gdpelican** [comment]
I merged the fix into master; let me know how you get on with it?

To answer your chat question, we had a gitter for a while, but didn't have a ton of activity on it at the time. I'm happy to open it up again if there's an impetus for it.

**Comment by fauno** [comment]
i missed the notification email for this! i'm testing it now.

i just wanted to know how can i chat with the loomio team :O

**Comment by gdpelican** [comment]
https://gitter.im/loomio/loomio is probably the best option for chat, although we're quite responsive to github activity as well.

**Comment by fauno** [comment]
it works!
