### ISSUE TITLE
Text in modals suddenly has random weights

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3841]
![image](https://cloud.githubusercontent.com/assets/970124/19989315/84490e46-a28a-11e6-9a09-696b1114b0cd.png)

Anyone else see this?

**Comment by HSalmon** [comment]
Yeah I've noticed it too.

**Comment by gdpelican** [comment]
Browser, device? Which text fields? Is it intermittent or persistent? Does it go away if you type or remove stuff?

**Comment by mhjb** [comment]
Me too — but I thought it was due to an OSX or Chrome update

**Comment by gdpelican** [comment]
Alright, we only have one font rendering the entire app now, and I think this was related to bootstrap. Going to close for now, please reopen if this is still an issue.
