### ISSUE TITLE
Thread missing from group page

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3845]
I've seen this a bunch of times now, but have no clue how to reproduce. A recent thread is missing from the group page. You can see it in the search results tho:

![image](https://cloud.githubusercontent.com/assets/970124/19996699/54c7d1fc-a2c6-11e6-96fd-27a14e999a3d.png)

**Comment by gdpelican** [comment]
This is a dupe of a bug I've filed under #3623, which I'm in the process of designing a solution for.
