### ISSUE TITLE
Dropping first letter of @mentions

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3851]
Pretty much any time I try to use @mentions, I end up selecting the wrong person because the system skips the first letter after @ while I'm typing. The only way to get it to work is to go back and type each letter verrry slowly. 

![](https://i.gyazo.com/4cff5b7f850be551dd32c12d7e25bc2c.gif)

(I am using Firefox on MacOS)

**Comment by alannallama** [comment]
This time it didn't eat the first letter, but just displayed the wrong names in seemingly a random order. Not sure if it's the same issue or something else.

<img width="262" alt="screen shot 2016-11-17 at 10 49 08 am" src="https://cloud.githubusercontent.com/assets/5498878/20367388/1a7c6574-acb4-11e6-9b3d-5322888906ac.png">

**Comment by gdpelican** [comment]
I've simplified the way we're fetching and displaying mentionables, which should alleviate this jankiness.
