### ISSUE TITLE
Cover photos don't appear for some groups

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3856]
See e.g. group 6xdXIjpb
No error turned up in Firefox console

**Comment by mhjb** [comment]
And group uZx0m9yO; on which Chrome console says 
![image](https://cloud.githubusercontent.com/assets/1380991/20209505/a31d4448-a859-11e6-9dec-73b07f609554.png)

**Comment by gdpelican** [comment]
I can fix these on a case by case basis, but don't think I want to go through and do it for all groups. It won't happen for new groups. Do you know of any other ones that need fixing?

**Comment by mhjb** [comment]
I don't know of others. Do you know what might have caused it? Related to #3809 ?

**Comment by gdpelican** [comment]
Sorta. We started using the `largedesktop` size for the first time in that PR, and seems like that style was never populated for older groups.

Come to think of it, we don't have cover photos for _that_ many groups, so maybe I'll just run the reprocess for groups with cover photos and then we'll be good.

**Comment by gdpelican** [comment]
Alright, I ran this migration; let me know if you see it crop up again.
