### ISSUE TITLE
lots of empty drafts?

### ISSUE THREAD

**Issue by fauno** [loomio/loomio#3863]
while upgrading today i got an exception on the AddIndicesToDrafts migration about a duplicate index, so i went to check on the drafts tables and we have ~1200 drafts, but most of them look like this:

```json
{"comment":{"body":"","attachment_ids":null,"uses_markdown":true,"discussion_id":133}}
```

or this

```json
{"vote":{}}
```

**Comment by gdpelican** [comment]
Drafts are updated to be empty once you submit your existing content. We found that this saves us a little bit of trouble if we need to make a new one (for example, you decide to make another comment in the same thread)

We'll also save an 'empty' draft if you, say, start typing something and then remove it without submitting, which is a little bit nicer than deleting it and having to create a new one once you start typing again.

**Comment by fauno** [comment]
ok... you can close this issue then (i removed the duplicates manually)

-- 
http://utopia.partidopirata.com.ar/
