### ISSUE TITLE
Lintel hangs off right slightly on thread page

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#3868]
Seems like the lintel is being pushed a little right after the mobile thread experience deploy:

![screen shot 2016-11-14 at 6 45 55 pm](https://cloud.githubusercontent.com/assets/750477/20287450/9b36914c-aa9a-11e6-8120-8f37aeb49a3e.png)

**Comment by gdpelican** [comment]
Whoa, maybe I'm crazy, because I can't repro this now. Feel free to close if you can't repro @HSalmon

**Comment by HSalmon** [comment]
I can see this:
<img width="1130" alt="screen shot 2016-11-16 at 10 20 42 am" src="https://cloud.githubusercontent.com/assets/2882097/20324696/618cd3c8-abe6-11e6-9a44-7f4e661aaa9f.png">

The lintel seems to be hanging off the right-hand side. Is this also a problem?

**Comment by gdpelican** [comment]
I'm seeing it too far to the left on mobile, and too far to the right on desktop.

**Comment by gdpelican** [comment]
I've deployed a refactor to the lintel positionining which will hopefully make it less of a thorn in our sides going forward. Keen to hear anyone spots any regressions.
