### ISSUE TITLE
Clicking agree from email does not open modal

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#3870]
regression at some point recently.

When I click a vote button from a proposal email, the thread loads but the vote modal does not open.

**Comment by gdpelican** [comment]
What's the URL it sends you to?

**Comment by robguthrie** [comment]
So the link in the email is:

https://www.loomio.org/ahoy/messages/l1q3QQc8cAslXC1kSeoLAkBpnWpxxsIc/click?signature=1db7dbd6f0554840d26555f8dbfdd5024df84761&url=https%3A%2F%2Fwww.loomio.org%2Fm%2FrARwGl29%3Fposition%3Dyes%26utm_campaign%3Dthread_mailer%26utm_medium%3Demail%26utm_source%3Dnew_motion

Which redirects to:
https://www.loomio.org/m/rARwGl29?position=yes&utm_campaign=thread_mailer&utm_medium=email&utm_source=new_motion

which redirects to
https://www.loomio.org/d/4atGYTui/proposal/rARwGl29?utm_campaign=thread_mailer&utm_medium=email&utm_source=new_motion 
which is the stage the position arg is lost.

Thanks for the clarifying question!
