### ISSUE TITLE
Angry, jumpy character limit warning on position statements

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3874]
This must have changed recently because I just encountered it for the first time...

<img width="570" alt="screen shot 2016-11-16 at 2 54 20 pm" src="https://cloud.githubusercontent.com/assets/5498878/20331853/f30346c2-ac0c-11e6-83fa-c548bb1c9dbd.png">

1) The size of the modal jumps when this message appears, which is distracting (especially because the user experience is to then go edit it shorter and try again, meaning it's jumping back and forth).
2) This text is really angry sounding and off putting (especially in red). This is a facilitation intervention and should be carefully worded and presented as such. I suggest something like "Character limit reached. Short position statements create a succinct summary. If you want to say more, post a comment".

**Comment by mhjb** [comment]
In fact most of a year old… https://github.com/loomio/loomio/commit/e0f45edd7ccced10f62913ef6571f4214794c4f6
