### ISSUE TITLE
Members card is not 100% width on medium screens on thread page

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#3878]
![screen shot 2016-11-16 at 5 31 49 pm](https://cloud.githubusercontent.com/assets/750477/20368570/9f29da28-ac22-11e6-8c09-fc1bd5a7c08e.png)

**Comment by HSalmon** [comment]
I can't reproduce this @gdpelican, what size is that screen?

**Comment by HSalmon** [comment]
I feel like the two column layout should still be visible on that screen...

**Comment by gdpelican** [comment]
Here's another screenshot; I can get it on page load if the page is the right width
![screen shot 2016-11-21 at 9 50 01 am](https://cloud.githubusercontent.com/assets/750477/20487063/043534e8-afd0-11e6-9a34-204e2c76b484.png)

**Comment by HSalmon** [comment]
So it's only on page load?

**Comment by HSalmon** [comment]
I see more problems than that if you resize the window then reload. I'm still having trouble reproducing that particular error though - I wonder if you would be up for taking a stab at fixing it.

**Comment by HSalmon** [comment]
@gdpelican, can this issue be closed now?
