### ISSUE TITLE
My own posts showing up as unread activity

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3880]
<img width="604" alt="screen shot 2016-11-17 at 1 59 51 pm" src="https://cloud.githubusercontent.com/assets/5498878/20372184/43ecbe3a-acce-11e6-9983-292c99e8ddaa.png">

After I post a comment, the thread is turning up in my unread view with my own activity.

**Comment by HSalmon** [comment]
It seems that there's something else going on with unread activity as well:

<img width="791" alt="screen shot 2016-11-22 at 10 17 54 am" src="https://cloud.githubusercontent.com/assets/2882097/20501056/0745c5bc-b09d-11e6-9824-943d9ea10a0f.png">
<img width="658" alt="screen shot 2016-11-22 at 10 17 45 am" src="https://cloud.githubusercontent.com/assets/2882097/20501055/070e7a1c-b09d-11e6-8b5b-57d8f8d3b766.png">

I can't get rid of that thread from my inbox

**Comment by HSalmon** [comment]
Also, just experienced my own posts showing up as unread activity:
<img width="657" alt="screen shot 2016-11-22 at 10 37 08 am" src="https://cloud.githubusercontent.com/assets/2882097/20501671/b302399c-b09f-11e6-8181-0d618087e82e.png">

**Comment by mhjb** [comment]
I'm seeing this too, so is Elizor

**Comment by omouse** [comment]
another confirmation of this bug: I just created a new thread and it showed up as "unread"

**Comment by mhjb** [comment]
I got this today 
![image](https://user-images.githubusercontent.com/1380991/28890096-1d507326-781a-11e7-94bf-fc7cffabfde5.png)

**Comment by gdpelican** [comment]
This should be fixed
