### ISSUE TITLE
"In reply to" is blank when replying to a comment that has been deleted

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3884]
![image](https://cloud.githubusercontent.com/assets/970124/20415738/2b81440c-ad9f-11e6-9b07-5ed9bcf8dc58.png)

Just noticed in [this thread](https://www.loomio.org/d/yXqmkoL2/). 

When you reply to a comment, and then the comment is deleted, your comment will be "In reply to [blank]".

**Comment by gdpelican** [comment]
My hunch is a deleted comment. @natiloomio Do you remember what you were replying to there, and if that comment still exists in that thread?

**Comment by natiloomio** [comment]
hhhmmm not sure, it could've been a comment from matt or rob that was deleted?

**Comment by rdbartlett** [comment]
@gdpelican I just confirmed your hunch

**Comment by gdpelican** [comment]
So what's the intended behaviour here? Drop the parent so it doesn't say 'in Reply To' anymore? Say 'In Reply to [deleted comment]'? Delete the comment entirely? (<- not recommended)

**Comment by rdbartlett** [comment]
Yeah I think when you delete a comment, all it's children should just
become top level comments.

**Comment by gdpelican** [comment]
I've fixed this for new comments; I'm not quite sure how to backport it yet tho.

**Comment by gdpelican** [comment]
Okay this is done for old comments and won't happen for new ones. Closing.
