### ISSUE TITLE
group activation card on subgroup?

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#3886]
I just found the GAC on a subgroup.

I don't think it should be in subgroups, but if it should, then the cover photo detection needs to account for parent having a cover photo.

![image](https://cloud.githubusercontent.com/assets/486367/20465442/04708dc6-afc2-11e6-91f0-7be3dd0617e3.png)

**Comment by gdpelican** [comment]
Seems like a dupe of #3832

**Comment by HSalmon** [comment]
This is fixe in the intro carousel branch

**Comment by robguthrie** [comment]
Thanks
