### ISSUE TITLE
Marketing site janky on Android Samsung Galaxy Tab 8.9 tablet

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3891]
![](http://i.imgur.com/lxPcSJV.jpg)

using default browser

first discovery from our new testing bench… :)

**Comment by mhjb** [comment]
Ah the app's pretty broken too. 

![](http://i.imgur.com/ODgXYLg.jpg)

So perhaps we need an 'upgrade your browser' message for unsupported browsers…

This is a five-year-old device.

**Comment by HSalmon** [comment]
Would you be up for updating this issue to reflect your new discoveries @mhjb? i.e. that we're not supporting this browser?

**Comment by mhjb** [comment]
Sorry — I don't quite understand what you're asking. I think I've opened a conversation; not sure what we should do about this, if anything. One idea is to turn this into a feature request about 'upgrade your browser'.

**Comment by gdpelican** [comment]
Closing as we have a new marketing site that works on tablets as far as I've been able to tell.
