### ISSUE TITLE
attachments can't be deleted or changed when editing thread context

### ISSUE THREAD

**Issue by natiloomio** [loomio/loomio#3892]
it seems like a bug, I didn't manage to change it on a test group. Rob said he could see the attachment and could delete after refreshing the page.

**Comment by HSalmon** [comment]
I can't reproduce this. @natiloomio, have you had further trouble?

**Comment by natiloomio** [comment]
I haven't heard about it again

**Comment by HSalmon** [comment]
Closing for now, can reopen if we get further reports
