### ISSUE TITLE
Margin on proposal card

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3908]
Noticed the extra margin on the proposal card:

![image](https://cloud.githubusercontent.com/assets/970124/20693262/0f3364fa-b642-11e6-9a81-f35e12641fbf.png)

I wonder if maybe this happened when @gdpelican put the loading indicator in?

**Comment by mhjb** [comment]
it got worse on latest deploy, I think … :)

![image](https://cloud.githubusercontent.com/assets/1380991/20768959/dbc011e0-b7a4-11e6-9b60-69334db957ff.png)

**Comment by mhjb** [comment]
@gdpelican assign to me if you can't be bothered tackling

**Comment by HSalmon** [comment]
Is this fixed pending deploy?

**Comment by mhjb** [comment]
@HSalmon looks to be
