### ISSUE TITLE
I should only see the intro carousel once

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#3912]
Love the look of the new intro carousel, however I'm pretty sure it only makes sense for a user to ever see it one time.

I would have thought it would show the first time a new user logs into loomio. Right now it's showing when I view a group, and again when I view another group.

@rdbartlett are you able to confirm that intro carousel should only show once per user, right after login?

**Comment by rdbartlett** [comment]
yep should be shown to all users exactly once.
