### ISSUE TITLE
Display issue with introcarousel

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#3913]
Nati noticed this behaviour with the intro carousel:
![image](https://cloud.githubusercontent.com/assets/486367/20775421/ae2ad93e-b7bf-11e6-9c0e-f346b0af9d12.png)

She's on firefox on ubnutu.

First slide "Robot" appeared normally. When clicking arrow the screenshot shows what happened.

**Comment by gdpelican** [comment]
Sorry, had to redeploy the intro carousel. Should be better now.
