### ISSUE TITLE
Plugin labels untranslated

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3917]
Seen this a couple of times last few days:

![image](https://cloud.githubusercontent.com/assets/1380991/20868210/ce05d378-baba-11e6-91de-306777718541.png)

When I refresh the page, I get the proper labels.

**Comment by gdpelican** [comment]
Hm, I don't really know what to make of this one. The plugin translations not coming through correctly? Can't seem to repro it either.

**Comment by rdbartlett** [comment]
I'm seeing this intermittently. No errors in console.

**Comment by rdbartlett** [comment]
I keep seeing this intermittently. Is there anything I can do to help diagnose?

**Comment by gdpelican** [comment]
I know the answer to this; it's some busy work that I'm going to get to soon.

**Comment by gdpelican** [comment]
I pushed a fix for this and am going to deploy it, hooray!
