### ISSUE TITLE
no indication of session ended

### ISSUE THREAD

**Issue by fauno** [loomio/loomio#3928]
if the session ends (because the cookie expired or was deleted, or you logged out from another machine/browser), the frontend doesn't give you any indication until you reload the site.

for instance:

* log in in your regular browser, leave it open
* log in and then log out from another place
* try to comment or vote, modal pops up as always but the action doesn't complete (modal greyed out and then enabled again, no message)

**Comment by gdpelican** [comment]
Cool. What would your expected behaviour be?

**Comment by fauno** [comment]
it should notify me i should sign in again :)

**Comment by fauno** [comment]
for instance, i had the tab open, so i was just trying to start a new thread, completed the popup form and nothing happened. then i remembered this and reloaded the tab to login again

**Comment by gdpelican** [comment]
This should be working now, and will be working better soon when we upgrade our live update technology. Going to close; let me know if you still experience this.
