### ISSUE TITLE
Thread title overlapped by sidebar and 'start proposal' button cut off

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3931]
<img width="1280" alt="screen shot 2016-12-08 at 7 50 01 pm" src="https://cloud.githubusercontent.com/assets/5498878/21000419/9fbda8fc-bd7f-11e6-80fc-281c678d6550.png">

I'm pretty sure these formatting problems just started with the sidebar update today. This is on Firefox 50.0.1 on a Mac.

**Comment by gdpelican** [comment]
Hm, can't reproduce; it looks fine on my firefox 50.0.2. Maybe a ctrl refresh? Does it happen for all threads?

![screen shot 2016-12-08 at 8 21 11 am](https://cloud.githubusercontent.com/assets/750477/21001187/511557f0-bd1f-11e6-92d1-73c1ea3edd59.png)

**Comment by alannallama** [comment]
You need to scroll down partway until it jumps to just showing the title bar.
I tried ctrl+refresh but it's still happening. Seems to be occurring on all threads for me.

**Comment by gdpelican** [comment]
This is only a problem at 110% zoom. For a temp workaround you can browse with any other zoom level. I'll look at what we can do to account for this.

**Comment by gdpelican** [comment]
It's also a result of a slight mismatch between what Material considers a large screen, and our own custom 'large screen' definition.

**Comment by gdpelican** [comment]
Sorry we're not going to be able to fix this with the current markup. The fix here will be either removing the lintel, or refactoring it so that it's position: absolute rather than position: fixed.

**Comment by alannallama** [comment]
OK. This is happening when I click "zoom > reset" or ctrl+0, so I thought that was 100%. It fixes itself if I zoom out more.

**Comment by rdbartlett** [comment]
FYI this has been broken for me too since the sidebar upgrade. This is on Chrome 55 on OSX. 

![image](https://cloud.githubusercontent.com/assets/970124/22085191/d653123e-de37-11e6-8c70-d9db2ad3ab44.png)

I'm seeing the alignment is off for window sizes from 1280px to 1368px, but it looks good at all other sizes.

@gdpelican do my numbers confirm that this is not worth fixing now, or rekindle the hope that there's a reasonably easy fix?

**Comment by gdpelican** [comment]
We don't have a start proposal button anymore :)

Rob's also cooking up a strategy to get rid of the lintel.
