### ISSUE TITLE
I'm getting comment emails though my group's email settings say 'Important activity'

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3933]
![image](https://cloud.githubusercontent.com/assets/1380991/21001673/a29b6576-bd86-11e6-808a-7202606a9e14.png)

![image](https://cloud.githubusercontent.com/assets/1380991/21001637/7b1f3a72-bd86-11e6-9a30-32b7c6027cef.png)

**Comment by gdpelican** [comment]
I think we set discussions to loud that you've authored.

**Comment by mhjb** [comment]
If so, that's new behaviour; I'm authoring discussions all the time but not seeing this.
