### ISSUE TITLE
[Security hole] Invitation key is guessable/brute forcable

### ISSUE THREAD

**Issue by jpdeplaix** [loomio/loomio#3934]
Hi,

I'm filling this issue on behalf of some friends that recently had an attack using ```secret group```. Some guy got invited on its own it they believe that it due to brute-force attack or low quality key generation.

Could you add a check for ```secret groups``` like the one that is done for ```private groups``` that asks permission to actual group members to add someone to the group ?

Cheers,

**Comment by jpdeplaix** [comment]
Somebody ?

**Comment by gdpelican** [comment]
Hrm, it seems very unlikely that someone was able to brute force an invitation key, especially if they were trying to get into a particular group. It seems more likely that a hacker got their hands on an email or public post or something which had an existing invitation key in it. Do you know if the attacker gained access to a shareable link, or an individual invite token?

We don't currently have different invitation methods for secret vs private ('closed') groups, so still trying to wrap my head around what the suggestion is here.

**Comment by jpdeplaix** [comment]
Ok, we thought that it was not possible to invite people directly in ```private groups```, my bad.
So the proposal is to validate every invited members by current members so that an attacker cannot invite himself into a group without a current member validation.

Concerning the key itself, the invitation key was only shared on an encrypted group chat so it seems unlikely that the attacker go his hand on this. So we think the attacker gained access via the shareable link.

**Comment by gdpelican** [comment]
Hm, yes, if someone has the shareable link, then they can get access to the group. I'd recommend being very careful about where that link is placed if you're concerned about security.

There's likely some additional feature dev we could do around managing, revoking, and reissuing shareable links (and we can do this manually for you if you message contact@loomio.org with particulars), but as far as I can tell this is working as intended, and the likelihood of brute force here is quite low.

Thanks for the report, and please do contact us if you need some additional support around deleting the attacker or changing your shareable link.
