### ISSUE TITLE
Comments have fallen off subscriptions

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3942]
Salespeople used to be able to add comments to subscription records, but can't now.

**Comment by hd719** [comment]
Hello I am new to Open source can I work on this?

**Comment by gdpelican** [comment]
Hey @hd719 , you are welcome to pick this up if you'd like; this is an issue related to the admin Subscriptions page, visible at `/admin/subscriptions` after running

```
User.find_by(username: "<username>").update(admin: true)
```

ActiveAdmin has some functionality for adding comments to models... for example going to `/admin/groups/:id` you can see

![image](https://cloud.githubusercontent.com/assets/750477/25156736/6d26ff00-24d7-11e7-987a-f9d989288a16.png)


So this fix would be making the same thing work for subscriptions.

Have to say this isn't very high on our list of priorities, but happy to accept a contribution if you're willing to do it.

**Comment by hd719** [comment]
Hey @gdpelican I am setting up the development enviroment and when I run `rake bootstrap` I keep getting this error 

```
/Users/HD/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/Users/HD/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_wit
h_call_chain'
/Users/HD/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/HD/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_ch
ain'
/Users/HD/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/Users/HD/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/Users/HD/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 lev
els) in top_level'
/Users/HD/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/Users/HD/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top
_level'
/Users/HD/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_thr
eads'
/Users/HD/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/Users/HD/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
/Users/HD/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exc
eption_handling'
/Users/HD/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/Users/HD/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/Users/HD/.rvm/gems/ruby-2.3.1/bin/rake:23:in `load'
/Users/HD/.rvm/gems/ruby-2.3.1/bin/rake:23:in `<main>'
/Users/HD/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/HD/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Couldn't create database for {"adapter"=>"postgresql", "database"=>"loomio_development"}
could not connect to server: No such file or directory
```

**Comment by hd719** [comment]
@gdpelican 

Hey so I am trying to make my user an admin and whenever I do `User.find_by(username: "default").update(admin: true)` I get `Unknown Attribute "admin" for User` 

```
=> #<User id: 1, email: "default@loomio.org", created_at: "2017-04-24 19:52:04", updated_at
: "2017-04-24 19:59:06", name: nil, deactivated_at: nil, avatar_kind: "initials", uploaded_a
vatar_file_name: nil, uploaded_avatar_content_type: nil, uploaded_avatar_file_size: nil, upl
oaded_avatar_updated_at: nil, is_admin: false, avatar_initials: "DE", username: "default", e
mail_when_proposal_closing_soon: false, authentication_token: nil, unsubscribe_token: "xZ-2M
4JjZHzAzodyzZc2", memberships_count: 0, uses_markdown: false, selected_locale: nil, time_zon
e: "America/New_York", key: "GLDZsaEu", detected_locale: "en", email_missed_yesterday: true,
 email_api_key: "e2e18bc423e3072ec493092da7a8d360", email_when_mentioned: true, angular_ui_e
nabled: true, email_on_participation: false, default_membership_volume: 2, experiences: {},
country: nil, region: nil, city: nil>
2.3.1 :010 > User.find_by(username: "default").update(admin: true)
  User Load (1.5ms)  SELECT  "users".* FROM "users" WHERE "users"."username" = $1 LIMIT 1  [
["username", "default"]]
   (0.2ms)  BEGIN
   (0.2ms)  ROLLBACK
ActiveRecord::UnknownAttributeError: unknown attribute 'admin' for User.
```

-Thank you.

**Comment by hd719** [comment]
Hello any update on this? 

I even tried `User.find_by(username: "default").make_admin!` did not work I got on error saying "undefined method 'make_admin!' for #<User:0x007fce863013d8>

I got the `make_admin!` method from the 

`app/models/membership.rb` 

```
def make_admin!
  update_attribute(:admin, true)
end
```

-Thank you.

**Comment by gdpelican** [comment]
Oh... ack, sorry. The field on user is called `is_admin`, rather than `admin`.

You can check out the current column names in the database in `db/schema.rb`

**Comment by hd719** [comment]
Hey @gdpelican so I was able to make my user an admin, but `localhost:3000/admin/subscriptions` does not work, I get an error saying "No route matches [GET] "/admin/subscriptions" .

-Thank you.

**Comment by hd719** [comment]
hey @gdpelican Any update on this?

**Comment by gdpelican** [comment]
Sorry @hd719 but I'm not able to provide this level of support. I'd encourage you to hack around on the project some and become more familiar with the way routing and rails works.

**Comment by hd719** [comment]
hey @gdpelican I understand, but there is no route defined as `admin/subscriptions` and also I do not see a admins subscriptions option on the admin page. 

![screen shot 2017-05-09 at 7 35 32 pm](https://cloud.githubusercontent.com/assets/20329318/25876998/b34b7f20-34ee-11e7-9328-56f65dc32a08.png)

![screen shot 2017-05-09 at 7 35 19 pm](https://cloud.githubusercontent.com/assets/20329318/25876999/b34c1e26-34ee-11e7-949c-cd78353769ae.png)


I was wondering do you want me to create one and then add comments section to that page? 

-Thank you.

**Comment by hd719** [comment]
Hello @gdpelican  any update on this?

**Comment by hd719** [comment]
Hello @gdpelican sorry for the bother any update on this?

**Comment by mhjb** [comment]
Hey @hd719 did you see GDP's earlier comment: "Sorry @hd719 but I'm not able to provide this level of support."
