### ISSUE TITLE
Make it possible to right-click open new tab in sidebar buttons

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3943]
A user has reported that they can't right-click to choose 'open in new tab' on group names in the sidebar, and I've confirmed it's so.

**Comment by ajay2507** [comment]
Hi, Can I work on this issue.

**Comment by gdpelican** [comment]
Sorry to miss this message, @ajay2507.

The fix here would be to convert the <button> tags in the sidebar to <a> tags, and add an 'href' to match the 'lmo-href' tag.

I _think_ this is okay, but may require some testing to ensure we don't break any intended functionality, like ctrl+clicking those links.

**Comment by ajay2507** [comment]
@gdpelican Thanks for your idea.. I will make this change

**Comment by Erudition** [comment]
Well middle click does that. If no middle button, Ctrl click.

**Comment by juliencarnot** [comment]
@ajay2507 have you made progress on this somewhere? If not, I might give at try. 
There [might be an option to keep the button tags and just add an onclick attribute](https://stackoverflow.com/a/2906611):
```
<button onclick="location.href='http://www.example.com'" type="button">
     www.example.com</button>
```

@Erudition the sidebar menu is using buttons, with no onclick href, so browsers do not recognize a link that could be opened elsewhere, so middle click doesn't work either.

**Comment by ajay2507** [comment]
@juliencarnot  Sorry I missed it and I was busy in some other stuff. May be I am able to do that tomorrow. Is it okay ?. or you can give a try.

**Comment by juliencarnot** [comment]
No worries, go for it, just let me know if you don't find time or give up in a few days!

**Comment by ajay2507** [comment]
sure @juliencarnot. I will let you know.

**Comment by ajay2507** [comment]
@juliencarnot  Can you take this up. I am not finding the time and busy in some stuffs.

**Comment by juliencarnot** [comment]
@gdpelican if there's a better solution to this, any hints are welcome!

**Comment by gdpelican** [comment]
Hey @juliencarnot, my primary concern with the existing PR (#4421) is that we lose the 'ink ripple' animations typically associated with `%md-button`s when we just use the `.md-button` class. I am not certain why this is, but maybe there's an additional helper class we can add to make the `%a` tags behave exactly as `%md-button`s would.

**Comment by juliencarnot** [comment]
@gdpelican I found a solution using ng-href which doesn't require turning buttons into links, keeps the ink ripple effect and allows the right click/open in new tab to work.
I tested in firefox and chromium, it works well, so I updated PR #4421
