### ISSUE TITLE
Undecided member count incorrect on page load

### ISSUE THREAD

**Issue by joshuavial** [loomio/loomio#3946]
When I load a proposal the undecided member count is consistently wrong (specifically in the enspiral members group) and when I click to expand the list it will jump from something like 2 to 9, then when I hide the list again the count is correct.

**Comment by fauno** [comment]
i observed this too yesterday, from 10 to 97

-- 
.oÓ)

**Comment by gdpelican** [comment]
Thanks for the bug report. @robguthrie and I just came up with a fix for this yesterday in our new Polls branch, so this will be accounted for when that gets deployed.

**Comment by rdbartlett** [comment]
Can I add, 'only show undecided panel if there are undecided members' and 'only show 'remind undecided' option while proposal is open'?

**Comment by mdshearer** [comment]
Hey folks, I think the issue I'm getting in Enspiral group is the same as this one... I want to see who is undecided. It shows 3 people. But when I click on "load more" in the proposal section to see who's voted, one of the people who's listed in "undecided" jumps up in to the voted section and then undecided's drop by 1. This person was the second person to vote out of 30. Also, the other day, that "load more" option wasn't working, so I couldn't actually see who hadn't voted.

**Comment by gdpelican** [comment]
I've just fixed the 'Load More' issue, and I believe our undecided counts are now right. Please re-open this issue if you can find otherwise?
