### ISSUE TITLE
Nav: Resources dropdown menu doesn't remain open on hover

### ISSUE THREAD

**Issue by cwilson635** [loomio/loomio#3947]
Dropdown menu doesn't remain open on Chrome browser OS X unless you move the mouse from the button to the actual menu at a quick enough speed.

**Comment by rdbartlett** [comment]
Gosh that is annoying! Thanks for the report @cwilson635 :)

**Comment by heidarmostafa** [comment]
Can you point out which dropdown has the problem? Maybe a screenshot would be helpful.

**Comment by gdpelican** [comment]
It's the 'Resources' dropdown on the home page (http://www.loomio.org). 
![screen shot 2017-03-03 at 7 10 02 am](https://cloud.githubusercontent.com/assets/750477/23520595/97df0d9e-ffe0-11e6-8042-2d143b1f69d1.png)
I can see it on chrome and FF at least:

**Comment by heidarmostafa** [comment]
It can be fixed by changing css under the selector:
```
.header__resources-dropdown-menu {
   top: 50px;
   ....
}
```
to:
```
.header__resources-dropdown-menu {
   top: 40px;
   ....
}
```

**Comment by gdpelican** [comment]
Woof, I finally grabbed this this morning, should be good after deploy.
