### ISSUE TITLE
Give edit permissions over your comments to another user

### ISSUE THREAD

**Issue by agentlewis** [loomio/loomio#3954]
So I have Dyslexia, and though I use spell check programs and Grammarly, I still make mistakes. Also, my stupid Android phone doesn't spell check when browsing to loomio. 

What would be great would be if I could give edit permissions to a couple of peeps I highly trust so that they could fix my spelling for me. 

It's not so bad in smaller groups - but it's pretty frustrating/embarrassing in the larger ones.

**Comment by gdpelican** [comment]
Hm, interesting use case. Not sure if this will make it on the roadmap (we're moving away from developing discussion-related functionality and towards poll-related functionality)

I think it's too complex to add a system for tracking who can edit whose comments, but I might be willing to add a user option like 'allow group admins to edit my comments'

**Comment by agentlewis** [comment]
If that were easy that could be cool. It wouldn't cover all the groups I'm in. But within Root Systems all members are Admins - so that would be perfect.

**Comment by gdpelican** [comment]
As time has gone on, I've soured a bit on the idea that other people can edit your words. I'd be open to this as a custom plugin, but probably not in the main app. Going to close as I'm doing a bit of housekeeping on our issues list.
