### ISSUE TITLE
Tooltips on vote buttons

### ISSUE THREAD

**Issue by MaiaDereva** [loomio/loomio#3956]
Hi! it's not easy for a colorblind people to understand the vote buttons. Is it possible to add tooltips on them?

**Comment by gdpelican** [comment]
Seems like a reasonable request; I'll see if we can add this; thanks for the suggestion.

**Comment by MaiaDereva** [comment]
Thank you for all people concerned @gdpelican :)

**Comment by ajay2507** [comment]
Hi, I am contributing first time to open source project. Can I add this Tool Tip functionality?

**Comment by gdpelican** [comment]
Sorry for the long delay here. I've implemented this and it will go live on the next deploy.
