### ISSUE TITLE
Limit Registration to specific EMail-Domains

### ISSUE THREAD

**Issue by uschreck** [loomio/loomio#3957]
We want to run loomio on a local installation in AWS. The issue we have now is, that the server is open to the world and anyone who knows the url can register an account in our instance. So the we need to limit the registration in any kind. One limit of we think of would be to limit the registration to certain emaildomains.

**Comment by gdpelican** [comment]
Hm, if you were willing to change the code a little you could add a validation to the user's email; something like

```
  validates :email, presence: true, uniqueness: true, email: true, format: { with: '@yourdomain.com', message: "Email must be in the 'yourdomain.com' domain" }
```

**Comment by uschreck** [comment]
Thanks gdpelican; sorry for the dumb question where do I need to add the validator?

many thanks

**Comment by gdpelican** [comment]
Oh, this would be in `user.rb`, and would be instead of the existing line there, which currently reads

```
validates :email, presence: true, uniqueness: true, email: true
```
