### ISSUE TITLE
When I click "show" I can no longer see the link to "remind" undecided people to vote 

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3962]
Before I click Show:

![image](https://cloud.githubusercontent.com/assets/970124/23378495/2b89a6da-fd98-11e6-90d7-45f38a0feeee.png)

Then I click Show, and I lose the Remind option:

![image](https://cloud.githubusercontent.com/assets/970124/23378560/6e5c39f0-fd98-11e6-94d0-81167a576702.png)

**Comment by gdpelican** [comment]
That whole thing will be going away soon I reckon

**Comment by gdpelican** [comment]
Going to close this as we're not using proposals anymore for the vast majority of groups. Still need to write the remind function into polls, though..
