### ISSUE TITLE
question about poll templates

### ISSUE THREAD

**Issue by fauno** [loomio/loomio#3965]
hi, i noticed our commited option naturally goes away when enabling the new poll system.  so i found that by adding it to `config/poll_templates.yml` work, but only for new proposals.  proposals migrated from the previous system only have the old options and the extra ones are not added.  so by taking a quick look at the code i'm guessing the options are created when the poll is loaded, and further loads bring the cached options.  am i correct?

so how could i recover the count from the old system?  taking commited_count and putting it into poll_options would be enough?

**Comment by fauno** [comment]
btw thanks for making adding extra options simpler! <3

**Comment by fauno** [comment]
ok, so far i could add the option and make it appear on the proposal poll, but i'm not sure how to fetch commited_votes_count attribute from the motion and put it on the stance_data, any leads? :)

**Comment by gdpelican** [comment]
Hm, have you tried running `PollService.convert(motions: Motion.all)`? (might be best try it out with a couple motions to start to see if it works)

There's two things here, stance_data and stance_counts; one is a hash like this:

```
{ agree: 5, abstain: 1, disagree: 2, block: 0, committed: 2 }
```

while stance_counts is an array
```
[5,1,2,0,2]
```

(one of these will likely go away, but we use both in different places in the system for now). `convert` looks at the `position_verb` method for each vote on the motion, and converts it over to a Stance, which then gets processed into the stance_data.

Failing that, you might be able to hack your way into something like
```
poll.stance_data[:committed] = motion.committed_votes_count
poll.stance_counts[4] = motion.committed_votes_count
poll.save
```

**Comment by fauno** [comment]
@gdpelican thanks, i went with creating the commited stance and then running `poll.update_stance_data`.

then i realized not every motion was converted into a poll!  on the group with polls enabled there're 106  motions but we just got 17 polls

**Comment by fauno** [comment]
running `PollService.convert(motions: Group.find(1).motions)` fixed it

**Comment by fauno** [comment]
ok, done! `stance_counts` and `stance_data` rely on the order of creation of `poll_options`, so for the polls already converted but missing the option, commited will come last, getting the blocked color on the chart.

https://github.com/piratas-ar/loomio/blob/fff44175070447a5ea3e6ffd8276a9efe4da96e8/db/migrate/20170303164134_add_commited_back.rb
