### ISSUE TITLE
Titles on comment box tabs not rendering correctly

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3970]
<img width="622" alt="screen shot 2017-03-08 at 4 06 07 pm" src="https://cloud.githubusercontent.com/assets/5498878/23688419/60886240-0419-11e7-9ddd-230ddadccee0.png">

Firefox 51.0.1 on Mac OS Sierra

**Comment by gdpelican** [comment]
I've got a fix for this, ref https://github.com/loomio/loomio/issues/3917
