### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by fauno** [loomio/loomio#3973]
Would you be open to maintain a Changelog file?  That way you could communicate downstream about breaking changes, for instance, the change from npm to yarn, node from 4.x to 6.x, etc. :)

**Comment by gdpelican** [comment]
Sorry for the delayed response. We've kept this up at times, and not at others; now is one of those 'others' times. I'm going to start pushing for circa weekly releases with some comms about the changes that are made; it'll be part of the comms strategy we're discussing at the moment.

**Comment by fauno** [comment]
great!

**Comment by fauno** [comment]
and a stable branch maybe? :P

**Comment by lwm** [comment]
http://keepachangelog.com/en/0.3.0/ :)

**Comment by gdpelican** [comment]
Okay, I'm going to start doing this regularly. Check out the initial 1.0 release [here](https://github.com/loomio/loomio/releases/tag/1.0.0).
