### ISSUE TITLE
Cloudflare Captchas Tor Users

### ISSUE THREAD

**Issue by dmytri** [loomio/loomio#3975]
Thanks for making and hosting loomio, one issue our community is having is that Cloudflare forces Tor users to answer a Captcha, which is a problem for us, as many people in our community are Tor users.

Any way to stop this from happening?

**Comment by fauno** [comment]
afaik, _blockflare_ users such as loomio can go to their control panels
and whitelist tor exit nodes:

https://support.cloudflare.com/hc/en-us/articles/203306930-Does-CloudFlare-block-Tor-

(the other option is to offer loomio.org over a tor hidden service :)
