### ISSUE TITLE
New Member Onboarding Flow

### ISSUE THREAD

**Issue by dmytri** [loomio/loomio#3976]
It seems to me like the new member onboarding flow is broken.

1/ I share the url
2/ person requests to join
3/ I approve the request

At this point the person should be a member, but it seems like there is another step in this process that involved an ivitation being sent and the person accepting it.

Is this right? This seem like a confusing flow. Wouldn't be preferable if the person was already a member as soon as I approved it, without needing to then accept an invitation?

Is the second stage intended to confirm the email address? If so, couldn't that be don as part of thr request flow, so that by the time of the approval step the email is already confirmed?

**Comment by gdpelican** [comment]
Ah, they're not a member until they've created an account, which we don't do until they log in with a password or Oauth provider. So the flow as it stands right now is

- User requests to join, which creates a MembershipRequest
- Admin approves the request, which creates an Invitation
- User accepts the invitation, which creates an account for them, and a Membership to the group (We can't create a Membership until the user actually has an account with us.)

We were just discussing this the other day, and have some ideas to improve it, either by displaying approved MembershipRequests with other group memberships, or creating an account and a Membership for the user earlier in the process.

**Comment by dmytri** [comment]
Thanks, currently it is very confusing, and some members are never getting in, some I need to chase down and manually invite, and when a different co-ordinator approves the message, clicking the application notification goes nowhere and doesn't tell me the state of the application.

IMO, user should create an account when they request to join, and the membership to the group should be added when the request is approved.
