### ISSUE TITLE
Meeting time outcome email responses trouble

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4052]
Responses are empty & MJ appears twice. Poll is PXBcQJjh

![image](https://cloud.githubusercontent.com/assets/1380991/25641026/23411a32-2fe6-11e7-86f8-9649a7c14953.png)

**Comment by mhjb** [comment]
Little bit more time poll email trouble (this time in the results email):

![image](https://cloud.githubusercontent.com/assets/1380991/26432495/4a507f70-4150-11e7-9b95-4fd4ef251e5c.png)

**Comment by gdpelican** [comment]
I believe these are now fixed
