### ISSUE TITLE
Nested comments

### ISSUE THREAD

**Issue by aaros-web** [loomio/loomio#4054]
I'm new to Loomio but I found really disturbing that comments are not nested in a thread: wouldn't it be nicer to have a nested structure than have "X replied to Y" (without knowing which message of Y is concerned by the way...)

**Comment by gdpelican** [comment]
It's certainly something we've discussed internally a lot, but isn't on the roadmap at this time. Here are my current list of 'cons':

- A single-threaded conversation more closely mirrors a 'real life' group conversation, and makes it more likely that everyone is presented with all of the information available before making a decision.
- How do you know when you're 'done' reading a threaded conversation? One of the really tough things about reddit is that it's almost impossible to know when you've fully consumed all of the information in a topic (of course, reddit also places much less emphasis on reading _everything_
- There are some hairy technical challenges involved with this, like how do we deal with pagination? What does 'the first 50 comments in a thread' mean now? Can you reply to a reply (multiple nesting?), and if not, what do we do with existing 'reply to a reply's? How do we make it so the user knows what they're replying to? Do we need to support multiple comment boxes, one for each parent comment?

I've also, anecdotally, seen just _tons_ of folks struggle with slack's new threading feature, and FB and reddit (the prime examples of single- and multi- nested threading), both make it feel really impossible to know when you're 'done' with a certain thread.

Could you unpack some more about why you'd like this though? I'd be keen to hear.

**Comment by edilenedacruz** [comment]
Hi @gdpelican. I'm new to open-source contribution and I would love to help with this implementation.

**Comment by gdpelican** [comment]
Hi @edilenedacruz !

I don't have a clear picture in my head of how we'd actually fully implement this feature at present, but there are some steps we can take in this direction. I think the first thing to do would be to make it so that clicking on 'in reply to' scrolls you to the parent comment.

![screen shot 2017-05-27 at 9 08 20 am](https://cloud.githubusercontent.com/assets/750477/26513478/be714496-42bf-11e7-905d-7a6cf3b4edca.png)

There's a `ScrollService.scrollTo` method which takes a selector, which should be able to accomplish this fairly easily. Is that something you'd be interested in taking on?

**Comment by edilenedacruz** [comment]
Hi @gdpelican I apologize for the delay in my response. I was looking over the code and I have zero angular knowledge. I will analyze the code and see if it is something I feel confident tackling on. You said it should be easy so I think we can make it work :)

**Comment by gdpelican** [comment]
A further (more thorough) hint:

In `thread_page/activity_card/new_comment.haml`, there's the bit which displays the `in reply to (author)`:
![screen shot 2017-05-29 at 10 28 19 am](https://cloud.githubusercontent.com/assets/750477/26532625/e4726f44-4459-11e7-8620-ba1201b51ec2.png)

We want to
- take the parentAuthorName off of the translation
- move it into another %a inside a %strong (like with the author)
- When we click on that `a`, we want it to trigger a method on the controller (`thread_page/activity_card/new_comment_item_controller.coffee`), which calls `ScrollService.scrollTo`, and finds the parent comment.

```
%span{translate: "new_comment_item.in_reply_to"}
%strong
  %a{ng-click: "scrollToParent()"}
```
```
$scope.scrollToParent = ->
  ScrollService.scrollTo('#comment-#{$scope.comment.parentId}') # <- this selector is a guess
```

Good luck! :)

**Comment by gdpelican** [comment]
@aaros-web, @robguthrie is working on an implementation of nested comments at the moment, so this is in the pipeline.

**Comment by gdpelican** [comment]
Sooo, we have nested comments now, hooray! They should now be the default view for all threads, although you can also switch back to chronological via dropdown.
