### ISSUE TITLE
Admin 'Create/Edit Category' redirects to port 3000 when rails s -p 8080 is used

### ISSUE THREAD

**Issue by GenericUK** [loomio/loomio#4056]
Hi, I'm trying to get Loomio development install on Ubuntu 16.04 to run on an alternative port.
I have installed everything and it's all working with rails s -p 8080 -e development but when using the admin some of the redirects are still using the default rails 3000 port.

```
Started POST "/admin/categories" for 127.0.0.1 at 2017-05-03 11:34:49 +0100
Processing by Admin::CategoriesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "category"=>{"name"=>"South West", "position"=>"0"}, "commit"=>"Create Category"}
  [1m[36mUser Load (1.0ms)[0m  [1mSELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1[0m  [["id", 1]]
  [1m[35m (0.5ms)[0m  BEGIN
  [1m[36mSQL (48.8ms)[0m  [1mINSERT INTO "categories" ("name", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"[0m  [["name", "South West"], ["created_at", "2017-05-03 10:34:49.973928"], ["updated_at", "2017-05-03 10:34:49.973928"]]
  [1m[35m (12.2ms)[0m  COMMIT
Redirected to http://localhost:3000/admin/categories/1
Completed 302 Found in 295ms (ActiveRecord: 62.5ms)
```

This also happens if you go to http://localhost:8888/admin when not logged in it will redirect to http://localhost:3000/users/sign_in

Happy to post in ActiveAdmin, if you think it's a bug for them.
Thanks

**Comment by GenericUK** [comment]
I see now by changing the port in .env.dvelopment fixes this, also commenting out #CANONICAL_PORT=8080 also works.

Does categories do anything?

**Comment by gdpelican** [comment]
Sorry @GenericUK I'm having trouble parsing this. Did you resolve the issue here?

**Comment by GenericUK** [comment]
Hi @gdpelican sorry for the delay, Yes! editing the .env CANONICAL_PORT fixed the issue. I was then suggesting if whether the CANONICAL_PORT option is required, as it breaks the `rails s -p` port option. Sorry the question about 'what categories does' is off topic, I was just wondering if it has been implemented.

**Comment by gdpelican** [comment]
Ah, categories is a previous dev artifact that we can probably remove.

CANONICAL_PORT (and its more-oft-used companion, CANONICAL_HOST) is used to construct absolute urls for our asset host so that the emails (or slack messages, FB posts, what have you) we send out can construct an absolute URL to point back to the instance you're running. Since sometimes these things run in jobs and aren't necessarily attached to a web request, `request.host` / `request.port` wouldn't work for this case.

Some googling points to using `Rails::Server.new.options[:Port]` for this, but it doesn't work on heroku, where we get this instead:
```
require 'rails/commands/server'
Rails::Server.new.options[:Port] # => 3000
Rails::Server.new.options[:Host] # => '0.0.0.0'
```

**Comment by GenericUK** [comment]
Cool! Thanks for looking at it.

**Comment by GenericUK** [comment]
Hi James @gdpelican 

Sorry to bring this up again, considering it's been closed.

I have Loomio running on VPS using foreman or heroku local to start it on port 3000, I am then using Nginx proxy_pass. It all works fine but I still have the redirect issue where the CANONICAL_PORT is added after updating a record in the admin area (e.g admin>users>edit>update user). I can get around this by setting CANONICAL_PORT to 80 even though foreman starts on port 3000. Is this the correct solution and do you see it causing any problems with things run in jobs as mentioned in your last reply.

Thanks
Mark

**Comment by gdpelican** [comment]
Hey @GenericUK I've just pushed a fix which will redirect to a path, rather than a full URL, for the admin users actions. See if that fixes your redirect issue? Does this redirect problem happen only in the admin panel, or have you noticed it for other routes as well?

**Comment by GenericUK** [comment]
Cool! Thanks

I have only noticed it in the admin so far, it also happens on edit>update group
