### ISSUE TITLE
Add a comment button labels do not always render correctly

### ISSUE THREAD

**Issue by booleanvalue** [loomio/loomio#4062]
The Edit and Preview buttons do not always display correctly as per image:

![screenshot](https://cloud.githubusercontent.com/assets/576513/25829802/d5a3b6a6-34ac-11e7-90e0-9dd04dce3be5.png)

I am using Chrome 57 on OSX and can replicate this on an irregular basis.

**Comment by gdpelican** [comment]
I have fixed this; it'll be gone by the next deploy. :)
