### ISSUE TITLE
Users not uploading profile pics

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#4064]
Some UX feedback (hope I'm posting in the right place).

I just started a new group I'm facilitating. Six out of six people who joined did not upload profile photos (even though I specifically asked them to). This has a negative effect at this critical starting moment when I'm trying to get them engaged.

I'm trying to get them to now, but as a facilitator I really wish profile photos were pushed strongly in the signup process because it's really tough getting people to do it after the fact.

<img width="574" alt="screen shot 2017-05-10 at 11 05 56 am" src="https://cloud.githubusercontent.com/assets/5498878/25876435/52059358-3571-11e7-9a96-f9a9d74747f9.png">

I suggest considering whether "upload profile pic" should be part of the initial name and email signup page. Or at least assign random animal pics or something so we can tell people apart :)

**Comment by robguthrie** [comment]
Thanks @alannallama. Are you able to ask your users, on what platforms do they already have profile pictures which they'd be happy to use with Loomio? Or do they have files on their computers already, or would they be happy to take a picture as they sign up?

**Comment by alannallama** [comment]
I can try to ask them at the next meeting, but it will be several weeks. My
guess is they almost all have facebook, most would be able to upload a
picture from their device, and would also be OK taking a pic on the spot.
They are not really tech savvy women, many in their 50s. None have asked
for help because they tried putting up a photo and couldn't - I think
they're just very busy and will skip any steps that's aren't strongly
emphasised in the signup process.

**Comment by gdpelican** [comment]
Also our change picture form doesn't look too enticing atm:
![screen shot 2017-05-11 at 9 59 26 am](https://cloud.githubusercontent.com/assets/750477/25928780/9a8a8948-3630-11e7-8c70-0db87258e2ed.png)

We're rewriting the auth flow now, which will emphasize third party sign in, which will pull logos. If we still see people signing up with email a lot we can put in an option to upload a photo prominently on account creation easily.

**Comment by alannallama** [comment]
Great! I think a prominent upload photo option would be a real improvement,
if it fits with the changes you're already implementing.

**Comment by gdpelican** [comment]
Alanna (and anyone else interested) I made you a video! :D
https://www.youtube.com/watch?v=Fn5UwFh32sU

**Comment by alannallama** [comment]
Looks awesome! I like where you indicated you'd add the photo option as
well. I hope we'd see an increased rate of profile photo uploads with that
change.

(Side note: I'm wondering why Loomio still needs to authenticate the email
when you're signing in with a third party? Wouldn't your email linked to
Facebook etc already be authenticated? I think with other tools I've done
third-party sign in for it just lets me straight through.)

**Comment by gdpelican** [comment]
It's like that this at this moment because you can change your email address there to associate with an existing account, and so if it was just 'Log In' there you could simply change the email and gain access to that account.

Rob and I just had a little jam on this though and I think we can improve it so that if your new account email address matches your facebook email address, then you can just log in automatically

**Comment by gdpelican** [comment]
Going to close this for now and track whether more users signing in with oauth means more users with profile photos.
