### ISSUE TITLE
Upgrade prompt formatting broken

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#4075]
<img width="663" alt="imgur-2017_05_15-10 28 22" src="https://cloud.githubusercontent.com/assets/5498878/26038294/69b6cd8c-3959-11e7-9d1a-406400e8ae9a.png">

MacOS Sierra on Chrome Version 58.0.3029.96 (64-bit)

**Comment by gdpelican** [comment]
This is now fixed
