### ISSUE TITLE
Proposal not closing

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#4076]
<img width="379" alt="screen shot 2017-05-15 at 11 08 20 am" src="https://cloud.githubusercontent.com/assets/5498878/26038545/e6c61c92-395e-11e7-816f-e9238d404313.png">

This should say "closed".

**Comment by alannallama** [comment]
Huh actually it's more than that - the menu still has the option to close the proposal, and there's not option to add an outcome, so the system still thinks the proposal is open it seems.

**Comment by alannallama** [comment]
It eventually closed about an hour after the closing time. Now it's acting normally.

**Comment by robguthrie** [comment]
Thanks for reporting this @alannallama. I'll close it for now
