### ISSUE TITLE
Issues with the 'proposal closed' email

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#4088]
I've noticed a few issues with a recent 'proposal closed' email I received.

1) The email arrived 48 hours after the proposal actually closed (I think it's supposed to go out at the time it closes - I'm posting this on 17 May and the closing time was 15 May).
2) The group logo image is broken.
3) It's telling me to set an outcome when an outcome has already been set.

<img width="643" alt="screen shot 2017-05-17 at 12 59 56 pm" src="https://cloud.githubusercontent.com/assets/5498878/26134186/e8479f7a-3b00-11e7-8042-51071cc3184a.png">

**Comment by alannallama** [comment]
I also got a 'proposal started' email just now, two days after the proposal started (for a different proposal). The group images is also broken in that.

**Comment by gdpelican** [comment]
Hey Alanna,

All of these are related to a clog in our email pipeline which has now been fixed. Can you forward the proposal closed email to me (if it's not sensitive), so I can fix the group logo?

**Comment by gdpelican** [comment]
Alright, group logos should start appearing now, pending deploy later today. Thanks for the report!
