### ISSUE TITLE
Notification (in-app & email) slow to arrive

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4089]
Comment made on Monday evening, notification arrives Wednesday afternoon: 
![image](https://cloud.githubusercontent.com/assets/1380991/26134717/af7913c8-3b04-11e7-8f50-b74e22755bd2.png)

**Comment by gdpelican** [comment]
Yes, we had a clog in our email jobs queue, but should be resolved going forward. Sorry for the crap experience. <3
