### ISSUE TITLE
Poll counting one person's vote multiple times when they change it

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#4102]
See example below. Susan tried to change her vote, but the system ended up counting her multiple times instead. There are 7 people voting, but 9 votes recorded.

<img width="328" alt="screen shot 2017-05-24 at 10 48 25 am" src="https://cloud.githubusercontent.com/assets/5498878/26379697/bc0db804-406e-11e7-840e-18c3343a8bd2.png">

**Comment by gdpelican** [comment]
Looks like Susan is voting as a visitor those second two times; IE, she's not actually logged into her account when voting.

**Comment by gdpelican** [comment]
One fix for this might be to disable the 'Anyone can participate' option, which will force participants to be an identified member of the group to vote.

**Comment by alannallama** [comment]
@gdpelican I have just changed this group to Secret. It was on Closed, and I thought that meant only logged in users could see content?? A bit worried about privacy now if anyone can come along and participate in a Closed group. Maybe I'm misunderstanding?

**Comment by gdpelican** [comment]
The fix we're about to deploy here is to default polls within groups to _not_ be anyone can participate (before all polls defaulted to anyone can participate). You can turn it off for existing ones in the 'share' modal for the poll.

Anyone can participate means that there exists a shareable link that people can visit, to view content. If you haven't shared that link anywhere (presumably not), no one will be able to follow it. But it's likely better if we just don't create the shareable link at all for groups with private content.
