### ISSUE TITLE
Incorrect helper text when starting decision

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#4105]
I raised a "check" in a thread, and I think the notification help text is incorrect and confusing. It says "people who have voted will be notified", but no one has voted since this is a new "check". I hope it notified all the members of my group - did it? There was a previous decision in this thread, but it was a "time poll" so there was no voting.

<img width="454" alt="screen shot 2017-05-24 at 2 42 23 pm" src="https://cloud.githubusercontent.com/assets/5498878/26384753/75193682-408f-11e7-95b2-7ca21d38125e.png">

I tested by going into another thread with no previous decisions, and got the same issue.

<img width="500" alt="screen shot 2017-05-24 at 2 44 48 pm" src="https://cloud.githubusercontent.com/assets/5498878/26384805/b9ee58c8-408f-11e7-8d8f-c04a288fd4cc.png">

I also note it says "you will receive results when this *poll* closes", but this is a proposal, not a poll.

**Comment by gdpelican** [comment]
This should be resolved now
