### ISSUE TITLE
Totals on time poll incorrect

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#4111]
Unless I'm totally misunderstanding the purpose of the numbers in the "total" row on the time poll, they seem to be incorrect. I assume they're meant to indicate how many people said they were available on that date?

<img width="351" alt="screen shot 2017-05-25 at 10 32 54 pm" src="https://cloud.githubusercontent.com/assets/5498878/26446920/4b20657e-419a-11e7-94e8-eb1d9a328896.png">

**Comment by gdpelican** [comment]
This is now fixed.
