### ISSUE TITLE
Proposal vote buttons missing

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#4112]
No options for Yes/No/Abstain/Block are appearing for me.

<img width="400" alt="screen shot 2017-05-26 at 12 23 18 pm" src="https://cloud.githubusercontent.com/assets/5498878/26475846/50a00a3a-420e-11e7-8352-d96903131aee.png">

**Comment by alannallama** [comment]
I reloaded a few times and then the options appeared and worked normally (phew). That was odd.

**Comment by gdpelican** [comment]
This should be fixed now
