### ISSUE TITLE
Activation panel: start new discussion thread unticked, though I have

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4127]
![image](https://cloud.githubusercontent.com/assets/1380991/26604892/eff3b0d0-45df-11e7-8e7c-b0bf6eb544c2.png)

**Comment by gdpelican** [comment]
The logic is that that's checked when there are more than 2 discussions in the group (since there are two example discussions created). Did you delete one of the example discussions?

**Comment by mhjb** [comment]
Ah — I did delete the original ones and made two more. Edge case probably.

**Comment by mhjb** [comment]
Could change the rule to at least one discussion with author != 5964, if you could be bothered

**Comment by gdpelican** [comment]
Yep, I wanted to avoid an extra query there (we serialize out groups _a lot_, and they have tons of information tacked to them already), since we're serializing out the counts of discussions in a group anyway. I agree it could be more robust, but Good Enough™
