### ISSUE TITLE
check poll counters are meaningless when anyone with link can participate option is selected

### ISSUE THREAD

**Issue by pravi** [loomio/loomio#4137]
When anyone with link is allowed to participate, percentage and x out of y is meaningless.

Example poll: https://www.loomio.org/p/84SYRuBe
433% of members have stated their position (91/21). It should just say 91 persons participated and mention anyone with link can participate.

https://www.loomio.org/p/wz2i5PKm

**Comment by pravi** [comment]
Also the actual number of people votes yes is 60, but the count there shows 85.

**Comment by gdpelican** [comment]
I've just written some code yesterday to account correctly for visitors in
the count denominator, which will be deployed soon.

The stances look like there are 85 actual latest votes there, although some
of the given names seem like duplicates. So it seems like folks are voting
as visitors, coming back to change their vote, and being counted as new
participants.

I don't really want to leave a cookie for every poll, so likely the thing
we'll do here is update an existing stance if the new visitor's email
matches an existing one. I'll open a separate bug for that and close this
one once the visitor count fix is deployed.

**Comment by gdpelican** [comment]
Alright, I've added support for counting visitors in the denominator, and for linking to existing visitors on the stance if the email is the same. These fixes will go in the next deploy. Thanks for the report!

**Comment by pravi** [comment]
I think if you are reluctant to set a cookie, you should ask confirmation via sending a unique url to the email, else people can easily change other people's stance if they know their email.
