### ISSUE TITLE
Modal open but shortcut keys let other modals swap in

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4156]
If I'm on a modal like

![image](https://user-images.githubusercontent.com/1380991/27015195-73f72d00-4f5c-11e7-9ab8-5b9c09c5dd4c.png)

… and I've no field focused, if I hit one of the shortcut keys a new modal is swapped in (e.g. if I type g I get Start new group). 

Suggestions:

* make the top text box of each of the decision tools have the focus when the modal opens
* turn off shortcut keys when a modal is open

**Comment by gdpelican** [comment]
I've made it so that letter hotkeys don't execute when a modal is already open, pending deploy
