### ISSUE TITLE
Pressing "Back" on poll modal reveals template variables

### ISSUE THREAD

**Issue by gollmar** [loomio/loomio#4160]
When creating a new poll from the "Decision tools" box on the dashboard:
* The Back button is active, though there is no previous page/dialog
* When the user clicks Back, the header showing Poll type and related messages are replaced with what is presumably the name of an unfilled template variable

![loomio_back_button](https://user-images.githubusercontent.com/1475108/27128719-b714dc32-50cd-11e7-8322-d044069e2d20.png)

**Comment by gdpelican** [comment]
Thanks for the report; this is now fixed in master and will go live on the next deploy.

**Comment by gdpelican** [comment]
(In the interest of the easiest possible fix, I have made the back button work as it does when starting a new poll, rather than removing it for the case where you open the start poll form from the decision tools card.)
