### ISSUE TITLE
Undecided count and list wrong on check email

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4163]
Undecided count should be 5. (Note Bridget C has two accounts, so no bug there)

![image](https://user-images.githubusercontent.com/1380991/27206241-48b8813a-528a-11e7-89ee-8c6dde0c5a69.png)

on the web version it's a bit wrong too, in that while the number is right it only shows the two BC accounts (even when I click LOAD MORE): 

![image](https://user-images.githubusercontent.com/1380991/27206250-619ce4f2-528a-11e7-856d-1831fb7f8aeb.png)

**Comment by mhjb** [comment]
Here's another — this time from the Yesterday on Loomio email (should list 4 responses): 
![image](https://user-images.githubusercontent.com/1380991/27355850-84722292-5660-11e7-9f40-33a6f1f55a03.png)

**Comment by gdpelican** [comment]
I'm in the process of revamping the way we do undecided counts a bit, but I'm not confident this is fully fixed yet. Will close when that changes.

**Comment by gdpelican** [comment]
I _believe_ our counts should be patched up now. Please reopen if you see more weirdness
