### ISSUE TITLE
TAGS in Loomio

### ISSUE THREAD

**Issue by ckiltolier** [loomio/loomio#4167]
Hi !

I'm wondering : What is the use of the TAGS in Loomio ? I can't find any documentation about it, and I cant find the use of it in my group. Has somebody here the answer ?

Thank you !

**Comment by gdpelican** [comment]
Hey @ckiltolier , tags were an experimental feature which we recently turned on for all groups. Here's how it works: https://youtu.be/sX_vXCLziVI

 (I'll likely make a more thorough HOWTO about this once we've settled a bit more on the functionality and use case)

tl;dw:
- Coordinators of a parent group may create tags for that group
- These tags attach to discussions and allow for categorizing similar threads together, and provide context at a glance for what a particular thread might be about.
- There is also a `/tags/:id` page which lists all of the threads associated with a particular tag.
- Once Tags have been created, any member may apply or remove them from threads

**Comment by ckiltolier** [comment]
DAMN I missed the tags icone in the threads. Thank you so much for this fast made video ! ;)

This is a nice add.

I'm wondering, do we have an option in our group to make non-admin be able to create tags ?

Hope there will be some way of automatically filter the thread to access the liked tagged thread first ;)

Thank you !
