### ISSUE TITLE
Can't leave group

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4168]
![image](https://user-images.githubusercontent.com/1380991/27264476-87eb4f0e-54d3-11e7-967b-5ca490f38ae6.png)

**Comment by gdpelican** [comment]
Are you a member of a subgroup of that group?

**Comment by gdpelican** [comment]
We show the parent group because otherwise it would look like 'Internet Party International' was a subgroup of 'Help Bot's Space' in the groups list. What would make this more clear?

**Comment by mhjb** [comment]
Oh sorry! I am a member of the subgroup. Hadn't realised I was. A link on social media turned out to be an invitation link to the subgroup and I hadn't realised it.

**Comment by mhjb** [comment]
Oh! I can't leave the (sub)group. Here's a console error if it's of use:

![image](https://user-images.githubusercontent.com/1380991/27268803-35ae80de-5506-11e7-88b3-10749577a5e7.png)

**Comment by gdpelican** [comment]
This is now fixed
