### ISSUE TITLE
Timepoll option delete bug

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4175]
![image](https://user-images.githubusercontent.com/1380991/27522001-a60a5e32-5a76-11e7-9950-581614a6eddb.png)

Clicking the X on any option deletes the last time option, not the clicked one.

**Comment by gdpelican** [comment]
Thanks for the report. That is h*cking weird and I will fix it soon.

**Comment by gdpelican** [comment]
Alright, I've got a fix for this and it will go in the next deploy.

**Comment by mhjb** [comment]
You're great
