### ISSUE TITLE
Past dates should not be included in time slot options

### ISSUE THREAD

**Issue by renziver** [loomio/loomio#4176]
<img width="712" alt="screen shot 2017-06-27 at 8 36 50 am" src="https://user-images.githubusercontent.com/13497174/27566146-c38bc4b0-5b15-11e7-9f23-8be6a6bbedd7.png">

<img width="340" alt="screen shot 2017-06-27 at 8 52 22 am" src="https://user-images.githubusercontent.com/13497174/27566177-013ad99a-5b16-11e7-89dc-00be1eeeed41.png">

just a minor issue on adding time slots option, calendar should automatically mute past dates on its option.

**Comment by gdpelican** [comment]
I've fixed this in latest, thanks!
