### ISSUE TITLE
Time poll counts (wildly) inaccurate 

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4181]
![](http://i.imgur.com/bvako0w.jpg)

**Comment by gdpelican** [comment]
Link me plz?

**Comment by mhjb** [comment]
poll is ZrTC0Epz

**Comment by mhjb** [comment]
(stuck high priority on it with the rationale that it's core functionality broken)

**Comment by gdpelican** [comment]
Whoa... I can't see this behaviour, at it looks ok to me in the database as well
![screen shot 2017-06-30 at 10 46 58 am](https://user-images.githubusercontent.com/750477/27713810-84bf47a2-5d81-11e7-891a-e415baae7fb1.png)

Is it still misbehaving? Did the counts always appear off or only intermittently?

**Comment by mhjb** [comment]
odd!

After refreshing still looks like the below on the thread page (same counts show up on the poll page):

![image](https://user-images.githubusercontent.com/1380991/27714002-87c14a9e-5d82-11e7-84f9-6cb74934b160.png)

**Comment by mhjb** [comment]
here's another 

![image](https://user-images.githubusercontent.com/1380991/27886649-27400cd8-6231-11e7-8778-e6d471ea8930.png)

(iqhEofl6)

I've a feeling it happens after I change my 'vote'

**Comment by gdpelican** [comment]
This should now be fixed.
