### ISSUE TITLE
Dot vote option labels want to wrap

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4182]
![image](https://user-images.githubusercontent.com/1380991/27757783-4f179bc0-5e5a-11e7-8e47-99ff3925fa7c.png)

1Ed3Hcmu

**Comment by gdpelican** [comment]
We've gotten this feedback a few times now, and no one's been happy with the response 'just use shorter option names', so I'd like to fix this properly.

Here's what I came up with:

![screen shot 2017-07-09 at 7 56 05 pm](https://user-images.githubusercontent.com/750477/27992148-c1b426b2-64e0-11e7-8c05-1b91203fe05b.png)

Which I think looks ok, if not stellar.
