### ISSUE TITLE
"Cancel Reply" breaking TAB+ENTER to post

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#4185]
If you click reply to someone, type out a comment, and then hit Tab then Enter to post, it tabs to "cancel reply" instead of "post".

<img width="607" alt="screen shot 2017-07-03 at 7 19 34 pm" src="https://user-images.githubusercontent.com/5498878/27781991-bb403688-6024-11e7-9a53-61dd8f5bb8c8.png">

**Comment by gdpelican** [comment]
This has been fixed and will go in the next deploy. Thanks for the report!
