### ISSUE TITLE
Support for Fractional Choice of Law

### ISSUE THREAD

**Issue by mediaprophet** [loomio/loomio#4191]
In the schema.org mark-up community i've raised this issue for SEO https://github.com/schemaorg/schemaorg/issues/1662 principally (whilst also being considerate of machine-readable ontology, et.al. as may otherwise be discovered via tools such as http://osds.openlinksw.com/ or sites such as http://lod-cloud.net/ )

the consideration of 'fractional choice of law' is that different contributors of different jurisdictional areas may wish to contribute to a problem pertaining to their own 'citizenship' that is different to another. therein; the means to notate 'choice of law' is a means to associate requests (and affiliate requests) to the means of advocacy within any specified area. 

I figured the concept of 'fractional' might work best with a graph, as to support the concept of agreement of participants throughout multiple areas 'ruled by law' for any particular subject.

**Comment by gdpelican** [comment]
Hi Timothy,

Sorry, but I cannot understand this. Is thus a feature request? Could you
explain more simply what it is you're trying to do?
