### ISSUE TITLE
Privacy issue: Secret Groups not very "Secret" when moving threads.

### ISSUE THREAD

**Issue by stellarmagnet** [loomio/loomio#4192]
When I move one thread that had proposals from GROUP A instead to "secret" GROUP B, it is still visible to GROUP A. 

Initial conditions: have two groups with differing members -
- GROUP A: has members Bob, Sally, Joe
- GROUP B: has members Bob, Sally, James
- Bob creates a thread in GROUP A. This thread had proposals in it. 

Steps to reproduce:
- Bob now wants to move this thread from GROUP A to GROUP B, as a way to change the decision makers on the topic (as agreed upon by the team). 
- Problem: The proposal's decisions are still being displayed in the "Recent decisions" side panel for GROUP A even though that group is no longer it's parent. People that are in GROUP A and are not in GROUP B can still view these threads.

**Comment by gdpelican** [comment]
Hi @stellarmagnet 

Can you provide me with the URL of the discussion or decision in question, so that I can investigate?

**Comment by gdpelican** [comment]
Haven't been able to repro or get additional information about this one; closing for now. Feel free to reopen with further repro steps or an example.
