### ISSUE TITLE
Links not automatically linking in discussion context

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#4196]
www.something.com is not auto-linking in discussion context 

http://www.something.com does though

**Comment by prabhakar267** [comment]
@rdbartlett I would like to take up this issue if it is still up for grabs.

**Comment by rdbartlett** [comment]
Thank you!

**Comment by prabhakar267** [comment]
@rdbartlett I am having some issues in understanding the flow. Could you please help me or tag someone who can help me in this issue?

**Comment by rdbartlett** [comment]
Sure thing :)

Here you can see a screenshot of the issue:

![image](https://user-images.githubusercontent.com/970124/28360747-502b8fa4-6c6e-11e7-8680-d121c90674ae.png)

As a user, I expect that typing `www.google.com` in plain text would be converted into `<a href="http://www.google.com">www.google.com</a>` . 

This used to be the case, but there's been some recent change that means only strings that start with `http` are being formatted as links.

**Comment by wlisrausr** [comment]
Is this issue already fixed? I would like to take it as my first contribution to an open source project @rdbartlett

**Comment by gdpelican** [comment]
I don't believe this is fixed yet, feel free to take it on @wlisrausr

**Comment by wlisrausr** [comment]
Sure. Thanks @gdpelican

**Comment by JustusFT** [comment]
Hi, is this issue still looking for a fix? I'm a first-time contributer and would like to help. @rdbartlett

**Comment by gdpelican** [comment]
This is marked as 'easy win', but it's nnnot easy, heh. :)

You're welcome to give it a go if you like; you'll likely need to dive a bit into angular-marked (https://github.com/Hypercubed/angular-marked) or further into marked itself (https://github.com/chjj/marked) [these are the libraries that we use to render markdown], to figure out why `https://www.loomio.org` is autolinked, but `www.loomio.org` is not. It's likely a regular expression that needs an update somewhere down the line.

**Comment by extremelypenguin** [comment]
hey, i'd like to work on this issue if its still open. If my thinking is correct, it would be a pretty easy issue -

it would be something like:

if (link.slice(0, 3)!= "http" || link.slice(0, 3) != "https){
    link = "https" + link
} 

in what file is the code for link generation located?

**Comment by gdpelican** [comment]
Alright, this now works for me on prod, and I believe has for some time. 🗡 !
