### ISSUE TITLE
Changes required in documentation

### ISSUE THREAD

**Issue by prabhakar267** [loomio/loomio#4201]
While setting up the system for development, I found the following things missing or incorrect in the documentation.

[```setup_environment.md```](https://github.com/loomio/loomio/blob/master/docs/en/development_handbook/setup_environment.md)
 - In **Ubuntu system setup**, ```postgresql-9.4``` shows this error : ```Unable to locate package postgresql-9.4``` in Ubuntu 14.04 LTS (solution: https://askubuntu.com/questions/633919/how-install-postgresql-9-4).

[```quickstart.md```](https://github.com/loomio/loomio/blob/master/docs/en/development_handbook/quickstart.md)
 - Before Step 2 (Run the bootstrap task), I had to install ```bundler ``` by running the command ```gem install bundler``` followed by installing all the dependencies ```bundle install```
(Again for which I had to install a few gems like ```sqlite3``` using ```apt-get install libsqlite3-dev``` and ```gem install sqlite3```)

/cc @gdpelican

**Comment by gdpelican** [comment]
Would you be willing to submit a PR for these changes @prabhakar267 ?

**Comment by prabhakar267** [comment]
@gdpelican sure I will do it. There are a few steps missing regards the database setup as discussed with @robguthrie 
I will do all the changes in one PR
