### ISSUE TITLE
Can't load undecided members on proposal

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#4204]
I'm on a poll page https://www.loomio.org/p/TKUiJ51j

I click "show 24 undecided". It reveals the heading "Undecided Group Members (24)" but doesn't show me any of the members. I click "Load more" and nothing happens.

**Comment by rdbartlett** [comment]
However, when I'm on the thread page, it works

**Comment by rdbartlett** [comment]
When I'm on the thread page, if I click "show undecided", I get the first 8 undecided members, but can't load more.

**Comment by gdpelican** [comment]
This should now be fixed, yay!
