### ISSUE TITLE
New activity in one of my threads is never marked as unread

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#4207]
There's a thread in one of my groups that is having a lot of ongoing activity, but it never turns up in my inbox. I switched on all email notifications, so I get a message whenever someone participates so I know it is active, but it's not in inbox. When I see the thread preview on the group page or dashboard, it says there is no unread activity.

How can I help debug this one?

**Comment by mhjb** [comment]
Perhaps related to #4222

**Comment by gdpelican** [comment]
This should be resolved with the nested comments overhaul
