### ISSUE TITLE
Pricing page broken

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4212]
![image](https://user-images.githubusercontent.com/1380991/28236168-d64c1c6a-6972-11e7-8fcf-9c5d82ed256a.png)

**Comment by mhjb** [comment]
broken again 
![image](https://user-images.githubusercontent.com/1380991/28847981-4e242534-7765-11e7-8c12-e23cc87c346b.png)

**Comment by gdpelican** [comment]
This should be fixed now, thanks for the report!

**Comment by mhjb** [comment]
still failing at the mo but maybe waiting for deploy
