### ISSUE TITLE
rake plugins:fetch is broken

### ISSUE THREAD

**Issue by toupeira** [loomio/loomio#4215]
Looks like https://github.com/loomio/loomio/commit/9c38ed5b362cc3dbb98141d8e4b806d0f6d62f97 broke this (/cc @robguthrie), running `rake plugins:fetch` outputs these errors for each plugin:

```sh
rm: cannot remove 'plugins': Is a directory
ln: failed to create symbolic link 'plugins/fetched_plugins': File exists
```

The plugins are correctly fetched in `fetched_plugins`, but the `plugins` folder remains and contains a broken symlink `fetched_plugins`:

```sh
$ ls -l plugins/
total 0
lrwxrwxrwx 1 mak mak 15 Jul 15 17:18 fetched_plugins -> fetched_plugins
```

Not sure what the intent is exactly, but since Git supports symlinks maybe the easiest option would be to commit the `plugins` symlink and remove `Plugins::Fetcher#link`?

**Comment by gdpelican** [comment]
Thanks for the report, this should now be resolved.
