### ISSUE TITLE
Votes panel in Dotvote includes stances where latest != true

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#4217]
I'm looking at an epic dot vote poll, lots of participation. I found a two entries for Ants, coz he changed his mind. His latest vote is at the top of the list, and his original one is down the bottom (hidden behind the Load More button).

**Comment by rdbartlett** [comment]
I think the count is also including the old vote.

**Comment by rdbartlett** [comment]
Also seeing this in the poll closed email (see two votes from Susan)

![image](https://user-images.githubusercontent.com/970124/28771536-262715d6-75db-11e7-91e6-50be13890c9b.png)

**Comment by robguthrie** [comment]
Hi @rdbartlett we've deployed a fix for this. Thanks for the helpful report.
