### ISSUE TITLE
Members of this group not seeing unread threads

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4222]
Unread threads for subgroup Bp2zLshy don't turn up in inbox or Yesterday on Loomio. This happens for me and at least one other member of the group.

**Comment by mhjb** [comment]
On the same group, I have a thread that does keep turning up in the inbox, even though there's no new activity:

![image](https://user-images.githubusercontent.com/1380991/29336671-a6967a02-8262-11e7-922e-36b4d7ec441b.png)
---

![image](https://user-images.githubusercontent.com/1380991/29336696-bf271e0a-8262-11e7-829d-02ec4d712be2.png)

**Comment by gdpelican** [comment]
I believe this has been solved with proper paginating of inbox / group threads.
