### ISSUE TITLE
Profile page does not live-update so user thinks avatar update failed

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#4223]
I'm supporting a user at the moment, they got stumped on this issue. 

When I select Change Picture on the Profile page
And I upload a new picture on the Change Picture modal
I expect to see the new picture on the Profile page

Currently I have to reload before I see that the picture upload was successful.

**Comment by rdbartlett** [comment]
Ok it is worse than I thought:

When I select Change Picture on the Profile page
And I upload a new picture on the Change Picture modal
My new picture successfully uploads but I get no visual feedback
And if I click "Update Profile", it resets my profile picture back to the original one

**Comment by gdpelican** [comment]
This is now fixed!
