### ISSUE TITLE
Context panel losing newlines

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4225]
![image](https://user-images.githubusercontent.com/1380991/28740352-c830a818-7457-11e7-9bb4-e5e18aedd925.png)
 = 
![image](https://user-images.githubusercontent.com/1380991/28740346-bd53e7b6-7457-11e7-8ced-98b8d2706288.png)

**Comment by gdpelican** [comment]
Yep this is the intended functionality of markdown; two spaces between lines adds a <p> tag to break lines.

**Comment by mhjb** [comment]
true! weird
