### ISSUE TITLE
Important error while using chrome

### ISSUE THREAD

**Issue by felipeolcav** [loomio/loomio#4241]
I don't know if this happens in other browsers, but i've got this problem while using google chrome with linux, windows, mac and even android. It happens abroad, on Loomio.org as on a self install of loomio.

![fireshot capture 2 - recent i loomio - https___www loomio org_dashboard](https://user-images.githubusercontent.com/5359738/29053408-576b0d00-7bc6-11e7-95cc-3de1db734caa.png)

More commonly, it happens after opening loomio from a link, from whatsapp, telegram or email.

The console message:

[www.loomio.org-1502158722533.zip](https://github.com/loomio/loomio/files/1206733/www.loomio.org-1502158722533.zip)

![captura de tela 2017-08-07 as 23 21 17](https://user-images.githubusercontent.com/5359738/29053573-42470158-7bc7-11e7-906c-147977af1076.png)

**Comment by gdpelican** [comment]
That console error is actually expected; it's saying that you don't have permission to access a dashboard (which you don't, as a logged out user).

Seems like the only thing going wrong here is that translation strings aren't loading, which I won't be able to repro on Loomio.org.

You mentioned it's a self-hosted install; are there any changes or modifications to that install that might be causing this behaviour?

**Comment by felipeolcav** [comment]
Actually, it happens before login and it's in the self-hosted install, but also on Loomio.org.
If you look at the URL in the second screenshot, you will see I was visiting loomio.org. 

I tried to repro in other browsers and seems that it's working fine in firefox and safari.

**Comment by gdpelican** [comment]
Seems likely to be related to your settings in Chrome.
Can you find the `/translations?lang=<locale>` API call and tell me what the locale is? Also, can you confirm that that API call is returning `null`?

**Comment by felipeolcav** [comment]
> Seems likely to be related to your settings in Chrome.
Maybe, but I made tests using different devices and not only with my google account.

> Can you find the /translations?lang=<locale> API call and tell me what the locale is? Also, can you confirm that that API call is returning null?

Sorry, but I didn't find it, would you mind to tell where?

**Comment by gdpelican** [comment]
Try the 'network' tab in Chrome.
![screen shot 2017-08-08 at 5 17 45 pm](https://user-images.githubusercontent.com/750477/29057307-8beb2456-7c5d-11e7-8f43-b85ef002730a.png)

**Comment by felipeolcav** [comment]
Hi, here it is:

https://www.loomio.org/api/v1/translations?lang=pt

And yes, the API call is returning null

![captura de tela 2017-08-08 as 12 23 35](https://user-images.githubusercontent.com/5359738/29079777-72c115c2-7c34-11e7-9990-10dcc1ea0909.png)

**Comment by gdpelican** [comment]
Great, I'll have a fix for this shortly. In the meantime you can fix manually for yourself by visiting the 'Edit Profile' screen and selecting Portuguese from the language dropdown.

**Comment by gdpelican** [comment]
Alright, this is fixed pending the next deploy.

**Comment by felipeolcav** [comment]
Great @gdpelican 

Thanks
