### ISSUE TITLE
'Show Undecided' listing all users, even one who have voted

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#4243]
<img width="331" alt="screen shot 2017-08-09 at 9 30 32 am" src="https://user-images.githubusercontent.com/5498878/29095605-865b3bce-7ce5-11e7-9f40-93ee221bf164.png">

The number of undecided is showing up correctly (2) but then it's listing all group members instead of just those two.

**Comment by gdpelican** [comment]
This should now be fixed.
