### ISSUE TITLE
Major frontend memory leak due to ment.io

### ISSUE THREAD

**Issue by jvilk** [loomio/loomio#4247]
Loomio's angular frontend has a major memory leak due to [unpatched memory leaks in the `ment.io` library](https://github.com/jeff-collins/ment.io/pull/138). As a result, it leaks multiple megabytes of memory every time users browse across a few pages.

### Experiment setup

* Fresh Loomio development installation (from Git; version 1.8.66 in commit e6f96ac92881e9b0621236661cad23c1d2444c33)
* Default account with initial default posts.

### Methodology

Perform the following tasks with an unmodified version of Loomio, and Loomio with the ment.io leak fixes from the pull request:

* Log in to Loomio as `default@loomio.org`.
* Refresh `/dashboard` page to begin a fresh session with the app.
* Click on the "How to use Loomio" post.
* Perform the following loop 3 times:
  * Click on "Fun Group 1" in the menu.
  * Click on "How to use Loomio" post
  * Click on the hamburger icon to open the menu.
  * [Take a heap snapshot.](https://developer.chrome.com/devtools/docs/heap-profiling#basics_snapshot)
* For each snapshot:
  * Click on the dropdown and select the *statistics* view.
  * Subtract *System Objects* from the *Total*; this is Loomio's controllable heap size.
    * (As far as I can tell, System Objects correspond to internal Chrome state with no clear direct link to your application's behavior. They can add considerable noise to the graphs.)

### Result

As you can see in the graph, ment.io leaks *multiple megabytes of memory* every time the user navigates to a few pages:

![loomio_mentio_leaks](https://user-images.githubusercontent.com/1141042/29183072-2bece5bc-7db6-11e7-85ef-b7fa3dc818e5.png)

### Suggested Action

Fork ment.io and apply the fix in the pull request, or bug the ment.io developers to merge that pull request.

**Comment by deutrino** [comment]
Is this still a known problem? Perhaps it would explain why Loomio becomes progressively slower on Firefox Mobile over the course of a session, occasionally crashing my entire phone. :|

**Comment by jvilk** [comment]
Loomio is still using `ment.io` and `ment.io` has not been updated with a fix. So, this is still a problem, and could potentially be causing your issues.
