### ISSUE TITLE
Loomio Frontend Impacted by Minor AngularJS Memory Leak

### ISSUE THREAD

**Issue by jvilk** [loomio/loomio#4249]
As I document [in this issue over at AngularJS](https://github.com/angular/angular.js/issues/16135), Loomio is impacted by a small memory leak in AngularJS caused by its dependency, `angular-translate`.

The memory leak amounts to ~344 bytes per page navigation. There is a [pull request to fix the issue](https://github.com/angular/angular.js/pull/16161), which should hopefully ship with the next version of Angular.

**Comment by gdpelican** [comment]
Thanks for the report. I'm going to close this as it's not in our codebase, but good to be aware of it, and I'll apply some pressure to that PR if need be.
