### ISSUE TITLE
Proposal outcome notification links to the wrong place

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#4258]
I got a notification that Michael has set a proposal outcome. It is linked to `https://www.loomio.org/p/Vr402fg5?set_outcome=true`, which means I see a modal asking me to set the outcome. Seems like an easy fix for a fairly significant UX hiccup.

![image](https://user-images.githubusercontent.com/970124/29361012-e276b910-8285-11e7-99cd-64cf98cc8d65.png)

**Comment by gdpelican** [comment]
Alright, I've fixed this one and it will go live in the next deploy
