### ISSUE TITLE
Double activity item for new time poll

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4261]
![image](https://user-images.githubusercontent.com/1380991/29435236-4a0b12b8-83fa-11e7-9ebd-f6a8c68b0553.png)

The first and fourth items seem to be duplicates. (I did vote twice.) After I started this poll I shared it, so perhaps that's related to the fourth item. 

The screenshot also shows an example of #3880.

**Comment by gdpelican** [comment]
This should now be fixed. :D
