### ISSUE TITLE
z-heights on search input and results

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#4270]
Since the bootstrap clear-out, the z-heights have changed on the search input and results. Now the input is always higher than the navbar, and results are displayed underneath it.

![image](https://user-images.githubusercontent.com/970124/29661562-b90bbaea-88c4-11e7-9a45-238e9c2e19b9.png)

Aesthetically, it looks "off" to me, and from a UX perspective, having the results lower than the navbar made me wonder if I was missing the top result.

I would expect the input on the same plane as the navbar, and the results to be on the same plane or above it.

**Comment by gdpelican** [comment]
This is fixed and will go in the next deploy.
