### ISSUE TITLE
Advanced group settings not working completely properly

### ISSUE THREAD

**Issue by felipeolcav** [loomio/loomio#4273]
Hi,

I'm testing the advanced group settings and I noticed it's not working completely properly.  

I followed these steps:

- edit group settings;
- advanced settings;
- set off "Members can start proposals.";

![captura de tela 2017-08-25 as 00 50 30](https://user-images.githubusercontent.com/5359738/29698932-7231f1fa-892f-11e7-93d1-76d9b37eb7c9.png)

- invited a new member without coordinator role;

![captura de tela 2017-08-25 as 00 49 53](https://user-images.githubusercontent.com/5359738/29698923-5e228684-892f-11e7-95e7-e00125a7e2a0.png)

- new decision call to action button is still there;

![captura de tela 2017-08-25 as 00 51 51](https://user-images.githubusercontent.com/5359738/29698963-9c4a02de-892f-11e7-96e0-d155db92a1bb.png)

- user still can create a decision;

![captura de tela 2017-08-25 as 00 52 18](https://user-images.githubusercontent.com/5359738/29698984-c37ec29a-892f-11e7-93f8-2135c488cf5d.png)

- to vote as well:

![captura de tela 2017-08-25 as 01 02 35](https://user-images.githubusercontent.com/5359738/29699193-262ed532-8931-11e7-804b-87486e838757.png)

![captura de tela 2017-08-25 as 01 02 19](https://user-images.githubusercontent.com/5359738/29699199-2ff265c0-8931-11e7-9bb7-0d8758e7672c.png)

All other features seems to work very properly :)

**Comment by gdpelican** [comment]
@robguthrie What are your thoughts here? I know we've discussed discontinuing support for some of these options..

**Comment by robguthrie** [comment]
My thoughts are that we need to support those settings. There are plenty of people who want them, until we work out another way of doing the same level of configurability with less "if statements" (ie: only guest group members can participate) we need to support them.

**Comment by gdpelican** [comment]
Alright, I've updated our polling modules to handle these permissions properly now, will go live in next deploy.
