### ISSUE TITLE
Some old images seem to have disappeared

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4276]
See https://www.loomio.org/d/1dhKcpXt/ux-r-d-resources-card

![image](https://user-images.githubusercontent.com/1380991/29841942-6adcbf0e-8d5b-11e7-8566-b474bdd83645.png)
![image](https://user-images.githubusercontent.com/1380991/29841945-6f691450-8d5b-11e7-81f1-69362ec2d513.png)

**Comment by robguthrie** [comment]
Thanks for the report and the great mockup!

Fixed now
