### ISSUE TITLE
Loomio[.org] intermittently displays login modal when attempting to view a public or closed group

### ISSUE THREAD

**Issue by wfdd** [loomio/loomio#4287]
Sometimes when you're not logged into Loomio and attempting to view a public or closed group 
the login modal window is shown.  It cannot be dismissed and obscures the page underneath. I wish I could be more specific but I cannot reliably reproduce this; though I've experienced it as have other people in [our group](https://www.loomio.org/g/h1BjgZMm).

**Comment by gdpelican** [comment]
The login modal should appear whenever you're attempting to visit a resource you don't have access to. In the case of a closed group, it's very possible that there are some discussions (marked public) which you can visit, while other private ones will trigger the login modal.

Could you provide me a URL to a page that pops the login modal when you're not expecting it to?

**Comment by wfdd** [comment]
See https://www.loomio.org/g/h1BjgZMm.  In a private window try clicking on the invitation link in the header then refreshing the page - that seems to do it.  The URL is the same as it was but now it asks you to log in, you can't interact with the group and you can't close the modal box.

**Comment by gdpelican** [comment]
Yes, this is actually as design. If you click on an invitation while logged out, it puts you in the awkward position of having access to a group, but not having a Loomio user account.

To resolve this, we force login for users with a pending invitation, since you need a Loomio account to be part of a group.

**Comment by wfdd** [comment]
That kinda makes sense - you probably didn't anticipate that someone would place the invitation link in the description.  Anyway, I haven't been able to reproduce this thru regular browsing, so I'm putting it down as a fluke...
