### ISSUE TITLE
When you have multiple proposals/checks etc in a thread, the voting activity is not informative

### ISSUE THREAD

**Issue by stellarmagnet** [loomio/loomio#4289]
Example:
I have a thread and it has >1 checks.

It says "Giulio Prisco voted..." and then whatever his vote was. I do not actually know what he voted on since there are multiple checks in this thread (unless I looked at the results). I suggest a minor enhancement to make the activity useful to the end-user. Have the text instead say:

```
< user> voted on the check <title>
```

This effects all decision types - checks, proposals, etc.

![image](https://user-images.githubusercontent.com/2584493/30048287-5ddee52a-91ca-11e7-8d90-463f80c94c34.png)

**Comment by robguthrie** [comment]
Fair call. Thanks for reporting it. I've just made a PR for a fix. #4291

**Comment by robguthrie** [comment]
ok we've fix this. Thanks
