### ISSUE TITLE
[feature] Display voting results for a check in the "Check" card, without requiring the logged in user to vote

### ISSUE THREAD

**Issue by stellarmagnet** [loomio/loomio#4290]
Scenario:
I am looking at a thread, and it has multiple checks. I want to see what the results are for the check before I make my decision. 

For our coops use case: I am experimenting with using the "Check" feature to help find coordinators to work on tasks, so usually one volunteer is good enough. With this enhancement, it would be easier to see which tasks have a coordinator and which don't - so then the team members can volunteer on the remaining tasks.

Enhancement: Display the existing voting results in the "Checks" card in the right panel. This is how Proposals and other objects already work (it shows what the current progress is) so I assume that the Checks should also display the current progress without me voting.

This feature enhancement I am describing above will be important and complementary to this other issue for an enhanced usability (#4289)

![image](https://user-images.githubusercontent.com/2584493/30048787-b692b622-91cc-11e7-9ccf-84b7267dc900.png)

**Comment by gdpelican** [comment]
Ah, this is just an oversight on our part; I've fixed and it will go live with the next deploy. (Now we will display the 'Show Results' button the way we do for the other poll types). Thanks for the nudge.
