### ISSUE TITLE
[Feature Idea] Comment people votes  reasoning on proposals

### ISSUE THREAD

**Issue by felipeolcav** [loomio/loomio#4296]
Hi,

I don't no if you ever discussed this or even if it's easy or hard to code, but I consider that it would be very nice if one can comment other people votes reasoning. Besides helping to clarify the positions people stand, it could help people to build common understanding about the questions and decisions to make. It's truth that it always can be used for trolling, manipulating or other not so good reasons, but, in the other hand, I think that exchanging opinions is a necessary way to achieve better decisions.

**Comment by gdpelican** [comment]
Yes, we've considered this. @robguthrie is working on a nested event structure which will make it easier for us to handle this; once that's a little bit more mature I'm happy to revisit this as an option (although... we'll have to discuss it some more once it's a possibility; I feel like there are lots of pros and cons)
