### ISSUE TITLE
When editing a long comment, action buttons are not clearly visible and are out of the box

### ISSUE THREAD

**Issue by stellarmagnet** [loomio/loomio#4303]
When editing a long comment, action buttons are not clearly visible and are out of the box.

Browser: Version 60.0.3112.113 (Official Build) (64-bit) on Mac OS X
See screenshot:

![image](https://user-images.githubusercontent.com/2584493/30417351-42b7c7aa-98e4-11e7-96b8-f3db58ab6769.png)

**Comment by gdpelican** [comment]
@stellarmagnet Is this still an issue for you? I haven't been able to repro. Which browser are you using, safari?

**Comment by gdpelican** [comment]
This should now be resolved. Thanks for the report.
