### ISSUE TITLE
In Firefox typing a new comment causes entire page to jump up and down with each character typed

### ISSUE THREAD

**Issue by simonv3** [loomio/loomio#4306]
# Steps 
1. I am using Firefox 55.0.3
2. Open a long thread and scroll to the bottom to start typing.
3. Type more than 4 lines of text.
4. Enter a character. The input box jumps up and down really quickly. Enter another character, the input box jumps up and down again. 
5. As you type faster your browser starts freezing up.

# Expected
I expected to be able to type something longer than 4 lines in a thread without my screen jumping up and down.

Thanks for the awesome software! Aside from this issue it's been great :)

**Comment by juliencarnot** [comment]
Might be related to [AngularJS Material](https://material.angularjs.org/latest/), several similar bugs have been filed in [Angular Material issues](https://github.com/angular/material/issues/3070), maybe the issue was already there in v1.x of the framework?

**Comment by robguthrie** [comment]
tracking this via #4743
