### ISSUE TITLE
Clicking "resend invitation" reloads all resend buttons on the page

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#4310]
When I click resend on one invitation, all the resend buttons do a 'reload' animation. This is confusing because I wasn't sure if that meant they all got resent? I hope not, because if so I just resent to 63 people 63 times. I assume since each invitation has its own resend button it only applies to that one.

<img width="242" alt="screen shot 2017-09-20 at 12 52 23 pm" src="https://user-images.githubusercontent.com/5498878/30621989-c3ef793a-9e02-11e7-9211-3557128950a8.png">

Sidenote: it would be awesome to have a "resend all" option.

**Comment by gdpelican** [comment]
This has been fixed and will go live in the next deploy. Thanks for the report!
