### ISSUE TITLE
Proposal closed_at timestamps

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#4319]
On a thread, when I hover over the started_at, I get an accurate timestamp. So "9 months ago" reveals itself to be "Monday, 19th December at 7:43am".

On a proposal, when I hover over the closed_at timestamp I expect the same behaviour, but I'm stuck with "7 months ago".

**Comment by JonathanWThom** [comment]
Hello, I'd be happy to take a crack at this if no one else is already working on it.

**Comment by gdpelican** [comment]
Yes, please do! :D

**Comment by gdpelican** [comment]
Thanks to @JonathanWThom !
