### ISSUE TITLE
Wrong activity item on proposal edit

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#4320]
I started a proposal. Then I voted. Then I changed it to 'anyone with link can participate' (as a hacky way to get the direct link to the proposal). Then I changed it back. I got 3 'proposal started' items in the activity feed:

![image](https://user-images.githubusercontent.com/970124/31047878-5e154436-a60a-11e7-9378-4461de4df927.png)

**Comment by gdpelican** [comment]
This will be fixed with the next deploy
