### ISSUE TITLE
Attachment button breaking TAB+ENTER to post comment

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#4324]
If you type a comment and hit TAB+ENTER, it opens the attachment option, instead of posting, which is the expected behaviour.

**Comment by juliencarnot** [comment]
Tab will focus on next button (which is the add an attachment button) and enter will open it, just as it does here on GitHub. The attachment button has an aria-label for accessibility. If it were to be skipped in tab navigation, how could tab navigation/assistive technologies' users add an attachment before posting?

**Comment by gdpelican** [comment]
I'm with Julien on this one; I don't want special or unexpected rules about what tab does in the interface, and CMD + ENTER will work just as well to post a comment without having to click.
