### ISSUE TITLE
results are backwards in ranked choice email

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#4328]
Here's what it says in the app:
![image](https://user-images.githubusercontent.com/486367/31209750-c1c94bca-a9e9-11e7-8f54-2b5f1339568b.png)

Here's what it says in the email:
![image](https://user-images.githubusercontent.com/486367/31209760-cecc3a58-a9e9-11e7-960a-cd3a77537672.png)

Seems like it would be cool to also include bar graphs as seperate lines like in poll.

**Comment by robguthrie** [comment]
@gdpelican if you have capacity it would be great to have you fix this and the stance backwards issue, as the client is looking at testing broadly next week.

**Comment by gdpelican** [comment]
This should now be fixed

**Comment by gdpelican** [comment]
On second thought, let me take another look at this tomorrow. I've made a bunch of fixes related to poll option ordering, but this may still be an issue.

**Comment by gdpelican** [comment]
I believe this is fixed; happy to re-open if we trip on it again

**Comment by juliencarnot** [comment]
reproduced today on loomio.org :

in app:
![in app](https://user-images.githubusercontent.com/3848493/32796115-09acbfaa-c96e-11e7-985a-883988b23034.png)

in e-mail:
![in email](https://user-images.githubusercontent.com/3848493/32796138-1a627de4-c96e-11e7-9fbb-434e5aa899ee.png)

**Comment by juliencarnot** [comment]
Maybe this should be reopened to keep track of it...

**Comment by robguthrie** [comment]
This is still an issue

**Comment by gdpelican** [comment]
I've fixed this, pending deploy :)
