### ISSUE TITLE
ranked choice display bug

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#4339]
![image](https://user-images.githubusercontent.com/486367/31597017-93621e62-b2a2-11e7-8604-9e4408eea977.png)

I can circle back and fix soon if you'd rather not

**Comment by gdpelican** [comment]
I see an easy fix for truncating the long titles, but a quick look didn't yield a way to break them into multiple lines the way we do for dot votes / polls. Which is the right fix here?

**Comment by robguthrie** [comment]
I think we want them to all work the same way. so I'd +1 investigating how to break lines.
