### ISSUE TITLE
Proposal - votes not registering

### ISSUE THREAD

**Issue by genekeyssociety** [loomio/loomio#4343]
We have just taken a Proposal vote in a subgroup in which three votes cast have not registered. This has happened once in another sub-group

**Comment by robguthrie** [comment]
Hi. At this stage I don't have enough information to understand what's going on. Can you provide some screenshots or describe what you expected to see In contrast to what you did see? Thank you

**Comment by genekeyssociety** [comment]
Thanks for quick response. Three people reported that they had used the vote button and cast their votes, but their votes did not show up in the outcome. I'll see if I can get any more info.

**Comment by gdpelican** [comment]
Going to close this as we don't have enough information to determine what's going on. Happy to reopen with some further info.
