### ISSUE TITLE
"Learn more about email settings..." is not translatable and link points to english documentation even if it exists in the user's language

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4345]
"Learn more about email settings..." link at the bottom of https://www.loomio.org/email_preferences has 2 problems for localization:
* The text string is not translatable in Transifex: https://www.transifex.com/rdbartlett/loomio-1/translate/#fr/main-app-loomio-10?q=Learn%20more%20about%20email%20setting
* The link is pointing to https://loomio.gitbooks.io/manual/content/en/keeping_up_to_date.html even though I'm using French language for Loomio, and the manual page has a French translation ( https://loomio.gitbooks.io/manual/content/fr/keeping_up_to_date.html )

**Comment by robguthrie** [comment]
Thanks for the report!

I've added a PR for the first part so you can see how it's done.

For the second part we need a function which takes a Loomio user locale and returns the appropriate help locale. 

current help locales are: ar, en, pt, zh, es

So we need to convert en-GB or whatever to one of these, then inject it into the help url.

**Comment by juliencarnot** [comment]
Thanks for the PR, I had a look at it.

For the second part, I guess the function already exist for the Help link (currently at the bottom of the sidebar ;-) ), because when switching language in my profile, the link is changed to the right locale. By the way, fr help is partially translated too.

**Comment by gdpelican** [comment]
Check out `user_help_service.coffee` for where we currently put locale-specific links.

I'd like to do some work at some point to throw this in a YAML file so it's a bit more configurable.

**Comment by juliencarnot** [comment]
Maybe we should wait for this, if [all doc is merged in Loomio School](https://github.com/loomio/loomio-school/issues/10#issuecomment-341295485), it will be easier to apply a single rule.
