### ISSUE TITLE
Move user info and user menu from sidebar to navbar for a simpler & scroll-less sidebar

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4346]
I find the sidebar to be cluttered and impractical, with a scroll bar on decent sized screens even if you're not a part of many groups:
![existing interface](https://user-images.githubusercontent.com/3848493/32100511-5beb5820-bb14-11e7-8436-9b175f0c0871.png)

I think it would be much simpler if all the user-related display and options were moved to a menu tray in the navbar, at the top right corner after the notifications (which are personal to the user), where a lot of tools and apps put the user settings and log-out links:
![proposal with user menu in navbar](https://user-images.githubusercontent.com/3848493/32100512-5c0b7038-bb14-11e7-84a0-21f080664014.png)

This way, the focus is more on the discussions and groups in the sidebar, and depending on how many groups the median user is participating in, some of the freed space could be used for additionnal features (favorite/pinned labels for example?).

**Comment by robguthrie** [comment]
Great mockup and I agree with your assessment of the sidebar, thank you.

**Comment by robguthrie** [comment]
We're likely to remove muted threads. I'd like to experiment with removing subgroups. I'd also like to investigate what a threads sidebar might look like. IE: like a mail client view of Loomio.

**Comment by juliencarnot** [comment]
You're very welcome. 

Not sure I'd have proposed to remove muted threads, but I do agree that subgroups use-cases are hard to grasp and navigate around, especially now that tagging can help organize discussions in themes/topics.

And regarding a threads sidebar, I'd be curious to see mockups or examples of mail client UIs that could inspire this change. I can't really think of an mail client UI that would keep as much focus and space for discussions and I often find sidebar+panes UIs confusing...

**Comment by gdpelican** [comment]
I agree with the thought of putting additional user-related stuff like editing the profile under a user dropdown.

Thanks for the mockup; we'll definitely be taking a good hard look at the sidebar in the near future. I've written a simplified sidebar, but it's dependent on some functionality a bit down in the pipeline (namely starting discussions independent of groups), so we'll revisit once we get there.

**Comment by juliencarnot** [comment]
See https://www.loomio.org/d/mhPKAUgl/interface-change-the-user-dropdown
