### ISSUE TITLE
Feature request: Alpine docker container

### ISSUE THREAD

**Issue by djcf** [loomio/loomio#4347]
Hi there, is it possible for a Dockerfile for alpine linux to be created? Alpine-based containers have several advantages over regular containers, principally size. Perhaps using `ruby:2.3.5-alpine3.4
`. Thanks in advance!

**Comment by robguthrie** [comment]
Hi @djcf. Are you running Loomio on a box with very little space or bandwidth? The choices so far have just been about familiarity and popularity - the most scarce resource around here is developer time.

Would you like to clone the repo, change the base reference in the Dockerfile, do a build (`docker build .`) and report back?

**Comment by robguthrie** [comment]
Happy to re open this, but we don't have any space concerns with the current setup, so please try using it yourself and report back.
