### ISSUE TITLE
"Preview" button and "No content to display" in forms are not translatable

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4350]
These two strings [can't be found in Transifex](https://www.transifex.com/rdbartlett/loomio-1/translate/#fr/main-app-loomio-10?q=preview) and are not translatable.
Here they are in context:
![capture du 2017-10-28 23-53-31](https://user-images.githubusercontent.com/3848493/32138945-f7029f3e-bc3c-11e7-8ee6-1a416a3ae4f1.png)
![capture du 2017-10-28 23-52-56](https://user-images.githubusercontent.com/3848493/32138944-f6deab38-bc3c-11e7-85ea-311cddbb401b.png)

I had a look in loomio/angular/core/components/, but I couldn't find the module in which the string should be replaced.
Thanks @uportalis for noticing this in #3898

**Comment by gdpelican** [comment]
You'll want to submit a PR with translations to https://www.github.com/loomio/loomio_content_preview , as these strings are present in a plugin which isn't handled by Transifex currently.

**Comment by juliencarnot** [comment]
Thanks @gdpelican for pointing to that plugin. 

I see that loomio_reactions , loomio_onboarding and loomio_tags are needing translations too. I'd be glad to make a PR for French translations, but it might be a better solution to manage them in new resources in Transifex, as it would prevent the problem to appear for other languages, even less technical translators, and to keep track of new or modified strings.

If this is not possible, I'd suggest listing all the yaml files github URIs that need to be translated in the translation tutorial and a quick explanation about how to translate and PR them or where to e-mail them if the translator doesn't want to install/learn Git.
