### ISSUE TITLE
add a good wysiwym editor for Markdown

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4367]
The subject has been discussed before, both on [Loomio Community](https://www.loomio.org/d/jNlAyLp1/improved-formatting-with-markdown) and [GitHub](https://github.com/loomio/loomio/issues/2742), and there seems to be a consensus that Markdown is great for "power-users", but not so easy for beginners, and that a simple visual editor would allow more participants to structure their contributions or add links to interesting materials. I'm sure a decent-sized and well equiped text-area box will have impact on the quantity and quality of contributions in a group.

It looks like there are lots of solutions, some packaged for angular, such as [angular markdown editor](https://www.npmjs.com/package/angular-markdown-editor) (see [demo](https://www.npmjs.com/package/angular-markdown-editor)). Maybe worth investigating again?

**Comment by robguthrie** [comment]
Yep. There are a number of people who would agree with you on the advanced user thing.

I've been really keen on [Prosemirror](https://prosemirror.net/) because of it's well thought out design - it can be used as a collaborative editor (should we want to introduce a wiki/pages), and it can render out to markdown or a number of other formats. 

It's just been released at 1.0 and I really think it would be an excellent candidate for Loomio.

**Comment by robguthrie** [comment]
There is an angular prose mirror repo floating around, but it's dead. It does give the outline for how to integrate it as a wysiwyg markdown editor though. 

It's a major piece of work, but worth investing in IMO

**Comment by juliencarnot** [comment]
Stumbled upon this repo, [ng-prosemirror : An angular.js wrapper for ProseMirror.](https://github.com/RonB/ng-prosemirror), would it be a good starting point on this?

**Comment by robguthrie** [comment]
I'm a very big fan of Prosemirror, it's my favourite option for editing and looks very well designed.
The promise of collaborative text editing as a side benefit seems like a possible game changer for Loomio for some groups.

Low risk and effort to experiment with.

I've checked out and tried ng-prosemirror but it does not work immediately with our version of Angular.

I really want to give it another go.

**Comment by juliencarnot** [comment]
Great, let me know if I can be of any help testing this, just helping group members to share more structured thoughts more easily was exciting enough, I didn't realize the potential for replacing our external etherpads too but that would be amazing!

**Comment by robguthrie** [comment]
this is now live in loomio 2.0.

embedding iframes with etherpads is available
and collaborative real time editing will be coming in 2020
