### ISSUE TITLE
add loomio_content_preview, loomio_reactions, loomio_onboarding and loomio_tags locales to transifex resources

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4369]
These 4 modules have language files but are not listed as resources in Transifex:
- loomio_content_preview,
- loomio_reactions,
- loomio_onboarding
- loomio_tags

In order to help translators of all languages to achieve full localization in a single interface and keep track of changes, it would be great to add them as translatable resources in Transifex.

**Comment by robguthrie** [comment]
I've deleted loomio_reactions as we don't actually use it.

I'll add the others as resources to transifex shortly. 

Thanks!

**Comment by robguthrie** [comment]
Ok I've added these resources now. Thanks again!
