### ISSUE TITLE
Initial Sign in to Loomio e-mail is sent in English, even when the user completed account creation in another locale

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4372]
Steps to reproduce:

1. Go to Loomio with a browser language set to fr, the homepage is translated in French
2. Create an account, the form is translated in French 
3. Confirm and check your e-mail: the Sign in to Loomio email is all in English (I checked, the strings it contains are translated in [server.fr.yml](https://github.com/loomio/loomio/blob/master/config/locales/server.fr.yml))

Not the best experience for a non-english speaking member!

**Comment by robguthrie** [comment]
@juliencarnot I think this is fixed now! Would you mind confirming this is the case?

**Comment by juliencarnot** [comment]
Confirmed, thanks!
