### ISSUE TITLE
Improve progressive web app capabilities and performance on mobile

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4373]
Loomio feels a bit slow on Android, both in Chrome and Firefox beta. I ran a test in Lighthouse in Chromium and here are the results I got on /dashboard:
- Progressive Web App 45%
- Performance 32%
- Accessibility 86%
- Best Practices 63%

See [Lighthouse Report loomio org.pdf](https://github.com/loomio/loomio/files/1438533/Lighthouse.Report.loomio.org.pdf) for details

Regarding performance, it seems than on mobile, avatars are loaded in their large size (170×170px) instead of medium on desktop, just to be displayed in 50×50px if the iPhone 6+ simulation developer tools is right, and that the dashboard always loads a 20ko 800×75px  /img/mute.png that I've never saw in the GUI...

There are a some low hanging fruits in manifest.json, for example to allow browsers to prompt user to pin the app on their phone (I couldn't find the manifest.json source in Loomio repos), and probably a lot of work to investigate offline support and improve pure performance but it seems that [some progressive web apps experience great results](https://developers.google.com/web/showcase/).

**Comment by robguthrie** [comment]
Thanks @juliencarnot. We're aware of the poor perf issues (we mostly blame Angular 1.x), it's going to take a pretty dramatic change to fix, which we're not prepared to undertake this year.

The manifest.json does exist but as a controller in rails. It does need a few fixes.

I think we can migrate to a better, progressive framework, but we've decided to do our best (in terms of UX, features) with the one we have, get more established, then revisit the problem.

**Comment by juliencarnot** [comment]
Understood, thanks for taking the time to explain the situation and the plans!

**Comment by juliencarnot** [comment]
For what it's worth, after tweaking the manifest.json, Lighthouse now says a working service worker on /dashboard is the last thing preventing Chrome from prompting the user to add to home screen:

> User will not be prompted to Install the Web App
> Failures: Service worker does not successfully serve the manifest's start_url.

I had a look at it and get that the missing part is https://github.com/loomio/loomio/blob/master/public/service-worker.js (see [pull/3323 comments](https://github.com/loomio/loomio/pull/3323), but I'm not sure what it should include, even after reading a few articles on the subject (got lost in caching for offline opportunities, which might also help to deliver a faster mobile experience even with the current framework).

**Comment by robguthrie** [comment]
I'm so grateful for this help @juliencarnot! 
We've had these issues pointed out before but I didn't have the space to sort it out... however I'm pretty sure there is a bit more work to get this to boot from cache.

We need to re-request bootdata, and it's worth noting that lokijs our client side database supports an offline/save to client function.

I've started a service-worker.js but I've not actually tested it in lighthouse or to boot the app. I'm just giving it a kick.

**Comment by juliencarnot** [comment]
Thanks, it looks like a great start, caching these resources should really improve performance!

Running offline could be a great feature for users on-the-go or even to be able to check info in group when the group occasionally meet in person in that basement meeting room with no wifi.

I'm not familiar enough with the offline-world, the codebase and the stack to push this further, but I'd be happy to help testing!

**Comment by juliencarnot** [comment]
#4529

**Comment by gdpelican** [comment]
We're looking much better on lighthouse these days, although performance is still an issue (and likely will be until we're able to upgrade our frontend stack)

![screen shot 2018-05-30 at 5 47 47 pm](https://user-images.githubusercontent.com/750477/40701471-1d8cbaac-6432-11e8-9e88-1ef3b6e23db3.png)

Closing this for now, feel free to open more specific issues as they crop up.

**Comment by gdpelican** [comment]
Heh, a second run of lighthouse makes us look even better:
![screen shot 2018-05-30 at 5 53 59 pm](https://user-images.githubusercontent.com/750477/40701580-916d3b72-6432-11e8-87d2-8038d693d5b7.png)
