### ISSUE TITLE
Allow group names to wrap inside the sidebar, rather than truncating them 

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4374]
On my screen, a group name is truncated after 19 characters.
![nowrap](https://user-images.githubusercontent.com/3848493/32354534-646bed5a-c02a-11e7-8237-6db0da500899.png)

This is very short and if wrapping wasn't prevented by css, this group name could be displayed with no problems:

![wrappingnormal](https://user-images.githubusercontent.com/3848493/32354651-edc9a330-c02a-11e7-860d-ad094ea5c061.png)

Of course, max length of a group name is 255 characters, which would be problematic:
![255 group name wrapping in sidebar](https://user-images.githubusercontent.com/3848493/32354668-00876cc8-c02b-11e7-9f72-9867ff74813b.png)

But I'd say it would still be (more) usable and most probably a coordinator would soon come up with a shorter name for the group... If a group does need a reasonably long name, I don't see why the interface should hide half or more of it.

**Comment by gdpelican** [comment]
This looks great, thanks! And we'll take a look in the near future around shortening the maximum length of a group name - I don't see why anyone needs the length of not one but _two_ tweets to name their thing.
