### ISSUE TITLE
allow visitor/user to switch language and see the translation coverage

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4375]
Right now the home page language is set from browser preferences (which users are not always aware of - think locked down or borrowed computers). A user can set the interface language in her profile, but there are a lot of choices and only few offer a complete or significant coverage.

Maybe we could offer a language switch/dropdown (ranked by translation coverage and displaying the % of translated strings (or a graphic indication of the translation coverage) both in app (enhance the one in the profile edit page) and on the home page.

The coverage indication could also be a good way to find new translators rather than dropping existing (non empty) translations : I guess seing that your preferred language has 25% of translations done is more encouraging than starting from scratch.

**Comment by robguthrie** [comment]
we're paying people to keep our main languages translated, as open source contributions rarely keep up with the changes made at product level.
