### ISSUE TITLE
I keep occasionally seeing the old Tag icon

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#4384]
And I don't get why..

![image](https://user-images.githubusercontent.com/486367/32403480-7ffb8154-c19f-11e7-9ee1-e4f99dda342b.png)

**Comment by robguthrie** [comment]
I thought it had been moved to the action dock.. or am I mistaken?

**Comment by gdpelican** [comment]
Somewhere along the way we removed the line pointing to the correct tags
branch. I've merged that branch to master so it'll fix itself on the next
deploy.
