### ISSUE TITLE
Facebook discussion link unfurling is broken

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#4390]
![image](https://user-images.githubusercontent.com/486367/32412423-39bd7004-c25c-11e7-916e-178dc69b2f62.png)

**Comment by gdpelican** [comment]
Hey @robguthrie is this a link to an Enspiral thread per chance? I believe Enspiral's a secret group, so we don't serve it with OpenGraph data.

**Comment by robguthrie** [comment]
Oh righty! I wonder if we want to think about how to make private links unfurlable.

At the very least, we could say something like "Join this discussion on Loomio"
