### ISSUE TITLE
Loomio believes I reside in Athens though I've never specified my location

### ISSUE THREAD

**Issue by wfdd** [loomio/loomio#4391]
![location mov](https://user-images.githubusercontent.com/8489551/32414500-483841fe-c220-11e7-9186-24cbefaaf76b.gif)

**Comment by gdpelican** [comment]
Yes, we detect location based on browser information that's sent over on initial request (and have done so for a long time). Location can be overridden with anything you like if you'd like this information to not be visible.

**Comment by wfdd** [comment]
I think it's actually some consolation that Loomio believes I live in a place I've not visited in nearly two decades if the developers here think it acceptable to leak people's location.

**Comment by robguthrie** [comment]
Hrrmm I wonder what others think.

I'm open to not revealing user location without permission... seems kind of invasive in some situations.

The location is guessed from IP address and it sucks pretty bad. Which made me think it would be "ok"

We _could_ ask the user's browser for their location when they click the location field, using html5 geolocation: https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation

So one scenario is that we don't reveal the guessed location to users (we use it for basic analytics). We offer to geolocate users from the profile page, and allow users to override the result string.

**Comment by juliencarnot** [comment]
I'd say reset/leave it blank if the user did not choose to disclose a location in the text input of the profile page. Using html5 only would give results that are ranging from unusable if you're on a desktop with an ISP not disclosing ip address locations but a network node 300km away, or creeping exact with Chrome/Google maps' streetview SSID geolocation or from a mobile.

I noticed that in a group that's supposed to be local, virtually all users appear to be from cities far away, sometimes in different European countries (of course, they're not). That's "ok" from a privacy point of view, but useless for users and for the platform. If you really need this data for analytics, I hope you don't trust the reports... 

In my view,  potential geolocation uses for Loomio, such as finding a nearby group containing a keyword (this would imply that groups can have a location), or setting up a subgroup for geographical region should remain on a user opt-in base, and will require storing structured geodata and support approximation for privacy, so I'd leave that out of the scope until there's a real case for it.

**Comment by juliencarnot** [comment]
By the way, I just noticed these info on my account in the JSON bootData: `"location":"La Pesse, France","city":"Frankfurt am Main","region":"Hesse","country":"Germany"`

I've set the location on my profile page, but the ip geolocation city/region/country (a mere 600km across the border...) doesn't get updated or superseded, and there is no GUI to edit these. This is problematic, I think this issue should be reopened and discussed.

**Comment by robguthrie** [comment]
yep I agree! 

just to set expectations.. it might be a week or 2 before we revisit this stuff.. we're working really hard on finishing some big features and need a bit of focus right now, but happy to return to this soon.

**Comment by gdpelican** [comment]
We've now removed this 'feature', so that location only appears if you've set it yourself.
