### ISSUE TITLE
no "Voters may add options" option for ranked choice polls

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4399]
For polls, dot votes and time polls, the decision creation and edition forms offer the option to let voters add options before voting/replying, but the ranked choice poll form doesn't.

Is it because of a technical limitation or was it forgotten?

**Comment by gdpelican** [comment]
Hm. Seems a bit dodgy, but it also does seem like an oversight. I'll throw it in and see how we go. At some point we'll want to store these options in poll_templates.yml so they're easy to turn on and off and we don't miss something like this again.

**Comment by gdpelican** [comment]
Fixed and will go with the next deploy.
