### ISSUE TITLE
Time picker 'new time slot' calendar widget shows next month when you click the down arrow

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4402]
… so I always have to scroll back by a month 
![image](https://user-images.githubusercontent.com/1380991/32638729-93898f2e-c625-11e7-97d9-f0ccfb962b94.png)

For bonus points:
'Preview' is miles away from the Details field that it relates to
![image](https://user-images.githubusercontent.com/1380991/32638857-0d8a7be4-c626-11e7-8c3f-64d120f59603.png)

and Meeting duration doesn't remember your choice when the rest of the form is saved as a draft (can't remember the Loomio term for that).

**Comment by juliencarnot** [comment]
Not reproducing the month shift in Firefox or Chromium.

And not sure why the preview button should be moved in that modal only...

**Comment by mhjb** [comment]
Helps?
![](http://g.recordit.co/UlOHAH1KqA.gif)

**Comment by juliencarnot** [comment]
That's strange, it shows some of next month then focuses on the current month in less than a second:
![datepicker](https://user-images.githubusercontent.com/3848493/32776264-46eff198-c932-11e7-8fd5-18f7691fa062.gif)

**Comment by mhjb** [comment]
No - the focus on the current month is me scrolling up.

**Comment by juliencarnot** [comment]
Got that, that's why I'm not reproducing the issue: no scroll needed for me!

**Comment by mhjb** [comment]
This is working properly for me now.
