### ISSUE TITLE
every page in the app loads 250ko+ of JSON "bootData", including all marketing locales + inline newrelic tracking code

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4403]
Not exactly sure if this is a bug or a feature, but viewing the source code in my browser, I noticed that  15ko of JS tracker from newrelic (see `<script type="text/javascript">(window.NREUM||(NREUM={})).loader_config={...`) and that a 250ko+ of JSON (see `<script>window.Loomio = {"bootData":{"memberships":[{...`) are loaded as inline code on every page of the app once you're logged in.

Wouldn't it help performance and limit both your and our bandwidth costs if these could be loaded as external scripts, separately from the page, and potentially cached by the browser instead of being resent on each page the user access?

Looking at the JSON content, I noticed that ALL of the existing marketing resource translations are included with the plugin loomio_org, which seems very strange in the app, which doesn't use most of these strings (and never every language at the same time!). Browsing the homepage and marketing pages before log in does not load any of these locales as inline JSON...

**Comment by robguthrie** [comment]
hrrrmm.. thanks for noticing!

Point by point:
- New relic helps us keep track of performance of the app. It's unlikely to be removed right now.
- We can't cache records in bootData, and they are required present before the app boots.
- we can cache translation strings, but have not yet configured that. we need to introduce a version number in the path and set the http headers in the response to allow caching. 
- We include marketing translations because the choose_plan_modal uses the same translations as the front page.
- It's a bug that there are other languages included and that is the first thing we should try to resolve here.

Once again.. thanks @juliencarnot I'm really noticing how great it is to have another person helping James and I.

**Comment by robguthrie** [comment]
Also we don't need to send over all the timezones, and they could be cached.

**Comment by juliencarnot** [comment]
Thanks for the quick and detailed feedback, happy to be able to help on this great project, thanks for bearing with my questions!

* Ok, it appears that new relic requires inline js in head. Maybe it could be placed at the end of the head so that important resources start loading before it.
* Ok for bootData, I assumed some of it was necessary to be generated before the boot and not cachable on the server side or cdn, but what about local/browser cache? I seems that some of this data will remain identical for all my session, if it were served as an external json instead of inline, and invalidated upon update so that the browser would fetch it when needed, it could reduce data exchanges.
* For translation strings, I wonder if it wouldn't be worth to duplicate the needed strings in client.xx.yml, so that the string are served from https://www.loomio.org/api/v1/translations?lang=xx as they are for client strings. I'm not sure if Transifex would pick and update duplicate strings or suggestion translations across resources as it does within a single resource, but even if it doesn't, it might be worth the hassle for translators if it reduces bandwidth significantly.
* Agreed, it would be a lot less data if only the current locale is included
* Yep, timezones labels are pretty stable in time I guess ;-)

**Comment by gdpelican** [comment]
We just need to not serialize out the translations with the plugins; the fetched translations should have everything we need. I'll fix this today.

**Comment by juliencarnot** [comment]
Just noticed that it seems app.min.css is loaded twice, once by html and once by js...

![image](https://user-images.githubusercontent.com/3848493/35095660-9737258c-fc49-11e7-96ea-d4f2d1b38934.png)

**Comment by gdpelican** [comment]
As far as I can tell, this is a bug with firefox and doesn't happen a) with
chrome, or b) with the network tab closed.

https://stackoverflow.com/questions/41529386/multiple-get-requests-for-the-same-css-file-in-firefox-inspector
https://bugzilla.mozilla.org/show_bug.cgi?id=1306892

**Comment by gdpelican** [comment]
I'm going to close this as it's wandered off topic and isn't a specific bug. I plan on the PWA work mitigating quite a bit of our 'too much data' issues, in that I'm addressing duplicated data in that branch, and that the service worker will cache static files like this quite well.
