### ISSUE TITLE
Groups on the explore groups pages should be ordered by recent_activity_count, but recent_activity_count is 0 for all groups

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4404]
The [explore page template](https://github.com/loomio/loomio/blob/master/angular/core/components/explore_page/explore_page.haml) sets the group list to be sorted by : orderBy: '-recentActivityCount', but it looks like they are in fact sorted by group members count: it seems all the groups I belong to have a recent_activity_count of 0...

This display implies that Loomio is for big groups, and doesn't let new users see how Loomio can be used by the smaller groups they are part of.

Do you already have metrics for measuring engagement/use of Loomio by groups? I think that a ratio of amount of activities in the last 90 days / group members count, or maybe the ratio of votes&answers to decisions in the last 90 days / group members would probably help showcasing groups with 20 engaged persons making the most out of Loomio, and if there are several groups matching a search, to check out the most lively ones first. It would also have the advantage to have a more dynamic top 20, with young groups getting a bit more exposure.

**Comment by robguthrie** [comment]
Thanks for the prompt and the thoughtful ideas.

Explore page was completely out of sight and mind for us. Nice to be given a little reminder and an easy opportunity to make it better.

**Comment by robguthrie** [comment]
Hrrm.. actually, can you come up with another equation for active groups? recent_activity_count/memberships_count is problematic when there are few members. maybe we include a minimum memberships count?
Also I think big groups probably should rise to the top easily.

**Comment by juliencarnot** [comment]
No worries, I know how easy it is to focus on some features of a project and forget about some others! I can try to come up with a better formula and to run it on a sample of groups to preview the changes, but just to make sure that we are on the same page:
* Can we update recent_activity_count daily or weekly and set it to the count of all activities (ie all discussions creations, poll creations, comments, reactions, votes) in the group (and its subgroups) for the last 90 days, or would this be too costly in compute time/performance?
* Do we agree that we want to display groups based on their activity rather than their size? In other words, should a group of 20 averaging 45 activities per member over 90 days be shown before a group of 800 averaging 3 activities per member over 90 days. If not, I think we should offer different sorting modes in a dropdown  (by member count, by name and by activity for example).
* Do we agree that groups using polls and not just discussions should get a better rank than "forum only" groups?  I feel that if we want 'explore' to give a better idea of what Loomio really is about (decision tools and not only discussion space), this is critical...

I think this adjusted explore page should become a menu item on the Homepage/marketing site, as it can already be accessed without an account. It could be a real asset for SEO (as far as I can see, public groups' description are not indexed in search engines at the moment, they could be a good way for people interested in group subjects to discover Loomio) and for onboarding ("hum, these features sound interesting, but do groups like mine really manage to use them?" or "oh, there's an open group on a subject I'm interested in, I'll ask to join and see how it works and participate, before trying to start my group").

**Comment by robguthrie** [comment]
1. Yes we can do *something* daily, but it needs to result in a single value we end up saving in recent_activity_count. We could also do something around user_sessions_count in the same time period.
2. I think a dropdown choice between these ordering systems will be appreciated.
3. Seems  a little advanced at this stage.. I'm keen to find out what's there.

I agree it could be interesting and help explain the value of Loomio and generate search juice. I also think a popular/trending discussion view of content might be interesting.

**Comment by juliencarnot** [comment]
1. Great could this something be the 'sum of all discussions creations, poll creations, comments, reactions, votes) in the group (and its subgroups) in the last 90 days'? I think this would be the first step to have some real world data to crunch in the equation. I've started thinking about it and the formula will probably also use the following existing and already set fields:

- polls_count
- closed_polls_count
- discussions_count
- memberships_count

2. Agree, and it looks like a feature I could try to add if you want me to.

3. Yes, it would be interesting to see. 

Is there a better way of generating data for dev than set up groups from gui and edit their counts in the db?

About the "popular/trending discussion view", do you mean a view/sort option in the group thread list or an explore active public threads page?

**Comment by juliencarnot** [comment]
I tried to add the sort-order dropdown [in my fork](https://github.com/loomio/loomio/compare/sort-explore-by-group-activity-and-size...juliencarnot:sort-explore-by-group-activity-and-size), which worked pretty well with ng-select but was ugly, and doesn't work with md-select (see commits comment for more). Not requesting a pull at this stage, but sharing my work in progress if it helps or if you can fix it.
BTW, the options are just examples, the final list should probably be 3 criterias with asc and desc, so 6 entries and not 8.
