### ISSUE TITLE
Impossible to click on the text (to edit it) when using Android

### ISSUE THREAD

**Issue by Vanecx** [loomio/loomio#4408]
Hello,
When I type an answer in a thread, I'm unable to click on the text, which makes it impossible to edit it without deleting the characters until reaching the part I want to edit.

I'm using Android 7.0 and someone else reported the same issue on Android 7.1.1

Thanks for the great tool :)

**Comment by gdpelican** [comment]
This should now be fixed with the latest version of angular material.
