### ISSUE TITLE
text overflow in poll results on firefox

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#4415]
![image](https://user-images.githubusercontent.com/486367/32741699-04e97682-c90c-11e7-9e2b-6ac66c9e0965.png)

**Comment by juliencarnot** [comment]
Humm, so the option.name is altered by [barTextFor](https://github.com/loomio/loomio/tree/master/angular/core/components/poll/common/bar_chart/poll_common_bar_chart.coffee), replacing white spaces by non-breakable spaces:

```
$scope.barTextFor = (option) ->
      "#{$scope.countFor(option)} - #{option.name}".replace(/\s/g, '\u00a0')
```
replacing `{{barTextFor(option)}}` by `{{option.name}}` fixes the issue:
![capture du 2017-11-14 12-15-07](https://user-images.githubusercontent.com/3848493/32777196-82a0e8ac-c935-11e7-9efe-166e1b9b6302.png)

These use barTextFor:

- core/components/poll/dot_vote/votes_panel_stance/poll_dot_vote_votes_panel_stance.coffee
- core/components/poll/dot_vote/votes_panel_stance/poll_dot_vote_votes_panel_stance.haml
- core/components/poll/common/ranked_choice_chart/poll_common_ranked_choice_chart.coffee
- core/components/poll/common/bar_chart/poll_common_bar_chart.coffee
- core/components/poll/common/bar_chart/poll_common_bar_chart.haml

Is there a good reason to use these functions? Should we remove them in all these files?

**Comment by robguthrie** [comment]
this happens on loomio 2.0.. sadly
