### ISSUE TITLE
"Add resource" in threads: URL vs. local file mixed-up? needs clarification

### ISSUE THREAD

**Issue by bamstam** [loomio/loomio#4419]
![screenshot-2017-11-16 loomio](https://user-images.githubusercontent.com/9203888/32888256-f48c8d3a-cac6-11e7-8ee1-ad8fcf3c2a70.png)

The two options seem to be mixed-up, currently "Link to websites and tools" allows selecting a local file and "Upload documents and files" allows entering a URL.

**Comment by gdpelican** [comment]
Oops, sorry about the switch-up! This is now fixed.
