### ISSUE TITLE
Gold features/upgrade menu is not shown correctly on Firefox and Chromium

### ISSUE THREAD

**Issue by bamstam** [loomio/loomio#4420]
Gold features/upgrade menu is not shown correctly and cannot be scrolled down on Firefox and Chromium; the buttons to select the desired plan may not be visible

Also important with regard to **translations** and varying text lengths

Firefox 57.0:
![firefox](https://user-images.githubusercontent.com/9203888/32961300-f062204a-cbbf-11e7-85ea-a6a9a3566060.png)

Chromium 62.0:
![chromium](https://user-images.githubusercontent.com/9203888/32961319-fdcb3ffa-cbbf-11e7-8dbe-6d6292557789.png)

**Comment by gdpelican** [comment]
This should be fixed now; needed to re-add scrolling to that modal. Thanks for the report. :)
