### ISSUE TITLE
Time poll outcome email problem

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4423]
I just closed a time poll (ILFOmYJe), choosing not to announce it, and not to send a calendar invite. I don't know whether my group members received an email about it, but I did:

![image](https://user-images.githubusercontent.com/1380991/33034817-e8225398-ce8d-11e7-857a-7b40b862b141.png)

**Comment by gdpelican** [comment]
Meeting polls have the 'author_receives_outcome' option set to true, meaning the author always receives a copy of the outcome when it's created.

@robguthrie can you remember why we did this?

**Comment by robguthrie** [comment]
I think it's supposed to be "author receives outcome if an email is going out" ie author_recieves_outcome && announcement

**Comment by gdpelican** [comment]
Okay, I've updated this so the author only receives an email from an announcement (this will be more clearer with the next iteration of notifications work as well.) Closing this now :D

**Comment by mhjb** [comment]
You're great
