### ISSUE TITLE
can't see new document management feature on loomio.org

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4426]
I can see the add resources feature in dev (the resources are not saved though) but not on loomio.org:
* the attachment icon is no longer shown on discussions or decisions forms
* on comments forms, it still only offers to pick a local file.
* I can see the  'View Attachments' on the group page, but not the add resource button the empty resource lists mentions

Seems like the deploy did not succeed for me. Tested in Chromium and Firefox, caches flushed, with two different user accounts.

**Comment by juliencarnot** [comment]
@gdpelican [It looks like I'm not the only one having this issue](https://www.loomio.org/d/JWeaygGj/uploading-resources). I can give you access to my demo account on loomio.org if it helps to reproduce, e-mail me or ask Rob for my phone number.

Would be happy to add info to the user-manual, but for now I can't create the screen captures.

**Comment by juliencarnot** [comment]
Still reproducing this on both my main and demo accounts...

**Comment by gdpelican** [comment]
This should now be updated; let me know if you see further issues with the document management . :)
