### ISSUE TITLE
document management: display resource update/edit date

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4427]
The resource list could show last edit/upload date for resources in the title tooltip of the link to the resource or next to the filesize, so that group members can see if there is a new version I should check.

Does a resource update show up in new activity/notifications (couldn't test with my accounts, sorry!)?

**Comment by gdpelican** [comment]
We show the uploaded date on the management page, but not with the document list... seems like a reasonable request though. I'll put this on the list of things to improve with documents.

**Comment by gdpelican** [comment]
We've added an upload date to the document list, pending deploy. This will likely iterate some more over time.
