### ISSUE TITLE
Make search more usable (search results page, sort/filter, boolean)

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4428]
Taking discussion to a written medium has a great value for groups, as it allows to keep track of discussions and decisions and to make it easier for a newcomer to catch up and avoid launching a new debate for nothing, but this requires easy access to these contents. After a few months of use, Loomio is not only a decision making suite, it becomes a *de facto* knowledge management solution.

When searching, you only get 5 results in the search tray, and the results are not very legible with the group name having almost the same font than the result title, and a date appearing only on desktop.

I think search results would deserve a real modal or even a page, which would allow to display all results, and maybe choose sorting by date (original post or last activity?), by relevance (if keyword is in title rather than in a comment, etc.), by active, closed or all decisions, by group, by tags, with pagination?

Bonus points for boolean operators support ;-)

**Comment by gdpelican** [comment]
I'd be more than happy to accept a PR for some of this functionality, but search isn't on our immediate roadmap right now :)

**Comment by mhjb** [comment]
Should it interest, @juliencarnot — here's a design for search I did a couple years ago: https://www.youtube.com/watch?v=4xhG_9BnNZQ

**Comment by robguthrie** [comment]
search is MUCH better in loomio 2.0. article about improvings coming soon
