### ISSUE TITLE
attaching file to comment shows 2 attachement icons

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#4433]
Attaching a file to a comment shows it twice, and it appears twice in the activity card, deleting one of them deletes both. @gdpelican fyi.

**Comment by mhjb** [comment]
looks like a duplicate of #4425

**Comment by BenDawes** [comment]
https://github.com/loomio/loomio/pull/4438

**Comment by mhjb** [comment]
I think this is fixed now.
