### ISSUE TITLE
Deleted comment not totally deleted until refresh

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4434]
![image](https://user-images.githubusercontent.com/1380991/33253057-96110c70-d3a6-11e7-8647-7e63cea4462e.png)

**Comment by gdpelican** [comment]
This should be resolved; thanks for the report.

**Comment by mhjb** [comment]
Soz — still doing it

**Comment by gdpelican** [comment]
Sorry, can't repro this. Please provide repro steps, browser, and examples.

**Comment by mhjb** [comment]
(Latest Chrome on OSX High Sierra)

New thread:

![image](https://user-images.githubusercontent.com/1380991/33931309-7c060c58-e054-11e7-915d-513ad8f4cf7c.png)

Edit context:

![image](https://user-images.githubusercontent.com/1380991/33931324-87374bdc-e054-11e7-83e6-37bdbdbfcb62.png)

Click delete icon on activity icon:
![image](https://user-images.githubusercontent.com/1380991/33931366-a67f307c-e054-11e7-86cb-ecb78a6a0a1d.png)

**Comment by gdpelican** [comment]
Sorry, but that is very much not the bug described in this issue. I'll make a note to fix this though.
