### ISSUE TITLE
Past decisions showing up blank

### ISSUE THREAD

**Issue by ntnsndr** [loomio/loomio#4439]
On at least two groups, I'm getting this behavior:

* Under "Previous decisions" on the sidebar, I click "See all: (X) decisions" (BTW, why is the number in parentheses?)
* I come to a page. The circle spins a bit, but no decisions come up. It says "Displaying 0 of X decisions." X appears to be the correct number of total decisions.
* Nothing changes if I switch to "(All polls)." (Again, not sure why the parentheses need to be there.)

Glitch?

**Comment by gdpelican** [comment]
Thanks for the report; this should be fixed now, pending deploy.
