### ISSUE TITLE
Can't sign in with Google

### ISSUE THREAD

**Issue by nmella** [loomio/loomio#4447]
Hi there,

I am testing Loomio in a local deploy. I configure Google credentials, but when trying logging with Google I  got error:

translation missing: es.Could not connect to google!

![2017-12-03_21-31-05](https://user-images.githubusercontent.com/5648244/33531838-be134d76-d871-11e7-9d8f-9fdac043ec18.png)

What might be wrong ? Thanks for your help !

Nicolas

**Comment by gdpelican** [comment]
Hi Nicolas,
Sorry for not having a more description error message there. I'd happily accept a PR to improve it.

Have a go at putting a 'byebug' in `Clients::Request#perform!`, and seeing what google's responses to your API calls are. 
```
# app/extras/client/request.rb
def perform!(options = {})
  # see what the value of 'json', or 'url', or 'params' is here
  byebug
  ...
end
```
