### ISSUE TITLE
Closing/archiving discussions

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4450]
Following [discussion on Loomio Product Dev](https://www.loomio.org/d/ZxhcqojW/feature-request-more-standard-moderator-tools), after a good number of threads on the same subject:
* https://www.loomio.org/d/HaE6ux1C/archiving-discussions
* https://www.loomio.org/d/yBkedAWw/archiving-discussions
* https://www.loomio.org/d/H8XTRsv7/archiving-and-not-deleting
* https://www.loomio.org/d/gEjqlDi7/subgroups-for-archiving-threads-

"Loomio is really missing the ability to mark discussions as closed, or completed, so that someone arriving at the front page can see what's current and what's in the past."

Basic feature would include:
* adding a close/archive and open/"unarchive" option in the context menu for discussions for coordinators
* filtering out closed/archived discussions from Recent discussions dashboard

More advanced features could include:
* adding an indicator/icon for open/closed on search results (see related #4428), muted and unread threads 
* adding a view for closed/archived discussions in the sidebar

Not sure if members should be able to add comments/decisions to closed/archived discussion (maybe a closed discussion can resurface without a coordinator reopening it, if so it might be useful to continue the existing thread).

**Comment by gdpelican** [comment]
I've just started on an implementation of this; stay tuned.

**Comment by gdpelican** [comment]
Okay, we have an initial implementation of this out there; I'll close this now and accept future enhancements as they come.
