### ISSUE TITLE
Visiting a long thread makes me load the whole thing before getting to the one new comment

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4451]

**Comment by robguthrie** [comment]
I'm super keen to get more information somehow. We now have a jump to dropdown, which allows you to jump to the beginning , unread, or end  of a thread.

Was the thread completely unread, some unread, or all read?

**Comment by robguthrie** [comment]
and did you see the dropdown box? 

I think there might be two problems.. people don't know about the new box, and the thread isnt doing the right thing in the first place, eh?

**Comment by mhjb** [comment]
~9 month old thread (this one: YNwXTk5a), almost entirely read comments, with three unread at the end. I got tired of scrolling after a while, found the dropdown, and switched from 'Unread' to 'Latest', which jumped me to the real bottom of the thread. Visiting the same thread again now I have no problems.

I don't understand what the difference between Latest and Unread is.

Also just got this — related?
![image](https://user-images.githubusercontent.com/1380991/33743414-99a6cd7a-dc11-11e7-874f-ced2ee669ef4.png)

**Comment by mhjb** [comment]
Oh of course — Unread might differ from Latest when there are nested comments.

**Comment by gdpelican** [comment]
Yeah that 'id' bug I've seen a time or two, and is quite bad. Let's try to
get that one soon?
