### ISSUE TITLE
Groups list out of order

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#4456]
Siblings Korero is a subgroup of Bartlett and Baird Family Business, but is showing up in the sidebar groups list as a subgroup of Salmons Demo Group. I guess the list is being alphabetised without paying attention to the parent / sub hierarchy.

**Comment by gdpelican** [comment]
Screenshot me?

**Comment by rdbartlett** [comment]
![screenshot_20171210-174254](https://user-images.githubusercontent.com/970124/33956719-4f1decc4-e0a4-11e7-8a75-e4ae91f4c614.png)

Most of the subgroups are in the right place, there's just a few out of whack.

**Comment by gdpelican** [comment]
That group should now be fixed. I'm also going to put in a fix to remove the full_name column so it doesn't get out of whack.

**Comment by rdbartlett** [comment]
I'm also seeing [this](https://www.loomio.org/g/2b4dQZvU/purposive-collective) as a subgroup of [this](https://www.loomio.org/g/l6QsLChc/platform-cooperative-consortium)

**Comment by gdpelican** [comment]
I've deployed a fix which should keep this from happening in the future. Thanks for the report!

**Comment by agentero** [comment]
Hi James,

Not sure why I am getting these messages, but please usubscribe me.

Thanks and happy programming.

Best,

Luis Pino

**Comment by gdpelican** [comment]
Hey @agentero,

I don't think I have any control over your notification settings, maybe check out your [notification settings](https://github.com/settings/notifications) on github, or unwatch this repository?
