### ISSUE TITLE
New activity items empty until refresh

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4470]
Just after I did the edits:
![image](https://user-images.githubusercontent.com/1380991/33928761-ec395aec-e04b-11e7-9afa-beae84cd8586.png)

After I refreshed the page:
![image](https://user-images.githubusercontent.com/1380991/33928781-fd4cbb30-e04b-11e7-9b45-23354c1dd9bf.png)

**Comment by gdpelican** [comment]
I believe @robguthrie fixed this yesterday, so this should be fixed pending deploy

**Comment by robguthrie** [comment]
I think that your refresh was the fix @mhjb. The change was a bit rough because it breaks the view for clients who don't reload (server started returning data in a new shape), but from then on it should be working fine.
