### ISSUE TITLE
Thread-attached google doc falls off after editing context

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4471]
Repro steps:
* 'Attach' a google doc to a thread
* Edit the context (leaving the attachment alone)
* Google doc link has disappeared

**Comment by gdpelican** [comment]
Sorry, can't repro this one. Attachments should appear in the context box and be editable and removeable from there.

**Comment by gdpelican** [comment]
Ah, nevermind, I've got it. Will be fixed soon.

**Comment by gdpelican** [comment]
This is now fixed.
