### ISSUE TITLE
Can't leave groups easily

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#4477]
From Chelsea,
When I remove myself from a parent Loomio group, but I'm still a coordinator of a sub-group (and sometimes the only coordinator of that subgroup), I then cannot leave the parent group OR delete the subgroups. I think for this case there should be a blocker pop up or something that says "You are a coordinator of a subgroup, if you want to leave all parts of {name of parent group] please remove yourself from subgroups first" or something

**Comment by gdpelican** [comment]
Do you think it's fair to say that memberships#destroy on a parent group should downgrade memberships to non-coordinator for subgroups (which will then throw a validation error if you can't do that)?

**Comment by robguthrie** [comment]
yea, I think leaving a parent group should make you leave all the subgroups and it should ask if you're sure. wow. this is such a dumb problem to have.

**Comment by gdpelican** [comment]
We did this with the announcements branch, now leaving a parent group removes you from the subgroups as well.
