### ISSUE TITLE
line break mid word

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#4478]
![image](https://user-images.githubusercontent.com/970124/33966217-aba4dcea-e0c3-11e7-9654-8a24342d4de7.png)

I've noticed lately some linebreaks are being inserted in the middle of words. I think it is only affecting links?

**Comment by rdbartlett** [comment]
Let's think about it out loud together. This is strikes me as an ugly fix
to a common problem.

**Comment by BenDawes** [comment]
I think it'd be reasonable to set a width-based upper limit, under which the line break just goes before the entire link, and above which the visible text is truncated with either an ellipsis in the middle or at the end (so the above would either be @micha...smith or @michaelel...). My preference is for the former.
