### ISSUE TITLE
Unused translations?

### ISSUE THREAD

**Issue by ariasuni** [loomio/loomio#4490]
It seems that many strings are not used in Loomio, like:

- https://github.com/loomio/loomio/blob/master/config/locales/client.en.yml#L486
- https://github.com/loomio/loomio/blob/master/config/locales/client.en.yml#L597
- https://github.com/loomio/loomio/blob/master/config/locales/client.en.yml#L376

At least, I can’t find in all the source code where this keys are used.

Is there some strings to remove?

**Comment by gdpelican** [comment]
Closing this for now, but further down the road when we have a little spare resourcing I'm happy to consider an audit of our unused translation strings; my guess is that we have many, but not overwhelmingly many of them.
