### ISSUE TITLE
New attachments form issues

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4491]
1. The upload box falls off the bottom of the page:
![image](https://user-images.githubusercontent.com/1380991/34584878-5278df4a-f202-11e7-90b9-a0857cf0434d.png)

2. and it looks like you can upload multiple files, but when I drag two files onto the box, only one uploads.

**Comment by gdpelican** [comment]
This should be fixed pending deploy. I'm not planning on supporting multiple file drag and drop right now (so I've updated the language), but if I hear about it more I'd consider it.
