### ISSUE TITLE
Time poll didn't send calendar invites to email participants

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4495]
I'd emailed three people a shareable link to a threadless time picker poll (XdExwbG3). They all voted. I closed the poll, and received a calendar invite myself, but none of the other three participants did. It made for a great deal of irl meeting time confusion. 

I really want to introduce people to Loomio by using time pickers instead of Doodle, but I feel like I can't really quite trust it at the moment :'(

**Comment by gdpelican** [comment]
Sounds like the outcome wasn't announced to the group. Announcements are
coming soon, which will hopefully make this a less 'wth just happened'
experience.

**Comment by mhjb** [comment]
I just tried again, this time with two dummy accounts (e.g. 'myemail+1@gmail.com'). I got two please verify emails (which I actioned), two welcome emails (from Intercom). I closed the poll, and shared an outcome. The outcome modal included this stuff:

![image](https://user-images.githubusercontent.com/1380991/34966726-accdcf82-fac2-11e7-9ec5-ee59eebab488.png)

… so it looks like announcements are here, rather than coming soon…?

**Comment by robguthrie** [comment]
I don't feel confident in this stuff either, we have some work to do, and it's related to thread first loomio.

**Comment by mhjb** [comment]
Thanks @gdpelican . Am I right in thinking there's a bug there? In the difference between "4 people will be notified" and the reality of 1 person receiving a calendar invite?

**Comment by mhjb** [comment]
FYI — this is still happening. Yesterday, combined with my own incompetence, it contributed to confusion about the time of our own board meeting. The meeting organiser thought that Loomio had sent meeting invites out with the poll outcome (as it says it does). Feels like a fairly big bug to me, in a workflow that not so long ago was pitched as a potentially really significant one for introducing new people to the value of Loomio.

**Comment by rdbartlett** [comment]
Yeah it just happened for me too. I know there's a feature in dev to fix this, but in the meantime I wonder about just commenting out the line about sending a calendar invite? Currently seems like it is doing more harm than good to tell the user you've sent a cal invite when you haven't.

**Comment by gdpelican** [comment]
Announcements should fix this bug (given that you've specified the right folks to announce to when sending out an outcome); let me know if you encounter this again.

**Comment by mhjb** [comment]
I've just sent an outcome for a time poll including a calendar invite. I'm hoping its been sent to people (I've asked them to confirm); but I haven't received an invite myself. It could just be that emails are running behind a bit at the moment…?

**Comment by mhjb** [comment]
Thanks Rob; no I wasn't; though I did choose 'Members of thread' when I set the time poll outcome; and I am a member of that thread…

**Comment by robguthrie** [comment]
I think it's normally weird to send yourself a notification, however for outcomes, it seems reasonable that the author wants a copy themselves. We've talked to a few users now who also feel this way.

@gdpelican how about, for outcomes, the audience_for method includes the author?

**Comment by gdpelican** [comment]
Hm, I think I disagree with this approach; I'd rather not pollute the idea of 'you don't notify yourself of stuff with announcements'.

The author should already be getting a calendar invite due to `Events::OutcomeCreated` including `Events::Notify::Author`, which should send an `outcome_created` email to `outcome.author`... I think we want to fix whatever bug may be in that pipeline.

**Comment by robguthrie** [comment]
Arr right, thank you for checking that! I agree! I'll look into it shortly.
