### ISSUE TITLE
Comments moving around in feed

### ISSUE THREAD

**Issue by aerugo** [loomio/loomio#4509]
In a thread in my Loomio install, a comment (by Christophe, "Yes, I had misunderstood...") moves around when I click "Load 5 responses". After loading more responses, position of the comment has shifted in the feed, now appearing further down in the history.

**Comment in right place:**
<img width="643" alt="screen shot 2018-01-30 at 18 00 54" src="https://user-images.githubusercontent.com/7785081/35579740-a0929326-05e7-11e8-8f1b-1590b0e927f7.png">

**Load more responses:**
<img width="668" alt="screen shot 2018-01-30 at 18 00 48" src="https://user-images.githubusercontent.com/7785081/35579742-a0bb2872-05e7-11e8-9527-792ab252c7d6.png">

**Comment in wrong place:**
<img width="666" alt="screen shot 2018-01-30 at 18 00 30" src="https://user-images.githubusercontent.com/7785081/35579743-a0d878a0-05e7-11e8-8590-ce6a0d23b3ad.png">

**Comment by robguthrie** [comment]
Hi @aerugo, sorry you're having issues.

We have a debug mode that helps understand what's going on. Open your browser javascript console and type `Loomio.debug = true` give the screen a wriggle or click and it should display a bunch of ugly debug info on the page, please repeat the copy paste with this mode enabled and I reckon the problem will be much clearer.

Thank you!

**Comment by aerugo** [comment]
Can't reproduce the exact same screenshots because there have been comments since then, but I can get a similar behaviour.

**This is the comment showing in the right place when I jump straight to it:**
<img width="608" alt="screen shot 2018-01-31 at 00 34 27" src="https://user-images.githubusercontent.com/7785081/35597396-8bf903b4-061e-11e8-9de7-50e202b06099.png">

**Same comment showing up in wrong place after I click "Load previous responses"**
<img width="608" alt="screen shot 2018-01-31 at 00 33 40" src="https://user-images.githubusercontent.com/7785081/35597399-9233a342-061e-11e8-969a-6568095f449b.png">

**Comment by robguthrie** [comment]
Thank you! Ok.. I think I've discovered the issue and am building a new "stable" image. You should be able to docker-compose pull a fixed image in about 30 minutes from now. Hope it fixes it!

**Comment by aerugo** [comment]
Thanks a lot! Will pull the latest update next time I do maintenance.

**Comment by aerugo** [comment]
I can confirm that this is now fixed, thanks a lot!
