### ISSUE TITLE
Attachments panel sorting mysterious

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4512]
Top of attachment page looks like this:
![image](https://user-images.githubusercontent.com/1380991/35667162-782e0aae-0791-11e8-9d53-4e131f7dc8f4.png)

Attachment panel looks like this:

![image](https://user-images.githubusercontent.com/1380991/35667173-8224027a-0791-11e8-8431-70b8b09deeca.png)

Seems like it should be the most recent items that should be shown in the attachment panel.

**Comment by gdpelican** [comment]
This is fixed pending deploy, big thanks to @Space-Ed for this one.

**Comment by mhjb** [comment]
I just added an attachment to a thread in this group (eh8mAZFD), but it failed to show up in the attachments panel: 

![image](https://user-images.githubusercontent.com/1380991/36766014-d23d69ce-1c98-11e8-907e-37acdb10a61e.png)

The newest attachment is called 'Pre-app meeting notes'

**Comment by robguthrie** [comment]
@Space-Ed this may be something you can sort out for us. :)

**Comment by Space-Ed** [comment]
is there any way to reproduce this problem?

**Comment by gdpelican** [comment]
I can confirm this bug; it's a result of the `documents#for_group` call not ordering by created_at descending. I'll take this one actually; the easiest repro will be with a prod database running locally.

**Comment by mhjb** [comment]
FWIW this remains an issue. To my mind it renders the Attachments panel almost useless (except that it provides a link to the Attachments/Documents page).

**Comment by gdpelican** [comment]
This should now be fixed with the latest deploy.
