### ISSUE TITLE
can't log-out of Loomio and some users can't log in

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4514]
When clicking on log out in the user drop-down menu, my dashboard is reloaded and I'm still logged in.

A user from one of my groups had to reply to a discussion by email, stating he couldn't log in and that some other users he had reached by other means could not log in either.

**Comment by juliencarnot** [comment]
Can't reproduce now, sorry if this was a false alert.

**Comment by gdpelican** [comment]
I appreciate the report; I've rolled back to a previous version for now
while I diagnose why this is happening.

**Comment by gdpelican** [comment]
This has been resolved. :)
