### ISSUE TITLE
poll notification emails are not completely translated

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4518]
![image](https://user-images.githubusercontent.com/3848493/36021153-3319fef6-0d85-11e8-9041-17bc5add9e1a.png)

status is not translated and date does not use the moment-locale:

> Closed 10:02am - Friday 9 Feb 2018 

Options for a proposal are not translated:

> Agree -
> Abstain -
> Disagree -
> Block -

**Comment by gdpelican** [comment]
This has been fixed pending deploy
