### ISSUE TITLE
Create a new account issue

### ISSUE THREAD

**Issue by sonofghandi** [loomio/loomio#4520]
Received an email invite.

Attempted to create a new account using Facebook info.

Was interrupted during the process, and my laptop auto-restarted for updates before I could resume.

I am now trapped at a place where any time I try to go anywhere with anything loomio, I get the pop-up to "create account" or "Already have a Loomio account? Enter your email address to link this account to yours" with my name already at the top of this pop-up and my Facebook avatar pictured, yet clicking "create account" does nothing, clicking the Facebook avatar does nothing, and putting in my email informs me I have no account.

Used your site's "contact us" official online form.  Used your site's listed "contact us" email.  Messaged your organization via Facebook.  Contacted multiple employees listed on LinkedIn in tech/customer service.  Have received no acknowledgment that I have been heard.

Please advise.

**Comment by gdpelican** [comment]
I've responded to this privately.
