### ISSUE TITLE
keyboard shortcut to post comment should only submit the currently active form

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#4521]
I am typing a comment in reply to a subthread
I hit cmd+enter to post
The comment gets posted in the subthread
And the comment form in the parent thread gives me a warning "comment cannot be empty"

I believe cmd+enter is attempting to submit all comment forms on the page, rather than just the one I am focussed on

**Comment by gdpelican** [comment]
Fixed pending deploy

**Comment by rdbartlett** [comment]
Thanks @gdpelican -- I think it also triggers the vote-submit action

**Comment by gdpelican** [comment]
Okay now I've fixed this in a way that should be more robust going forward.
