### ISSUE TITLE
Discussion items out of order

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4530]
discussion key: wDd8LgzJ
![image](https://user-images.githubusercontent.com/1380991/36226915-28e455fe-1234-11e8-9dc4-3e536704d0e3.png)

**Comment by gdpelican** [comment]
Sorry, could you explain a bit more what you're seeing here?

**Comment by robguthrie** [comment]
For thread rendering issues please open developer console and type `Loomio.debug = true` then wiggle the page/click something and debug info will show up.

**Comment by mhjb** [comment]
@gdpelican that screenshot shows the last three discussion items: one from 5 months ago, then 3 months ago, then 2 years ago. The thread order is 'Latest'.

@robguthrie here you go:

![image](https://user-images.githubusercontent.com/1380991/36228095-11f444e0-1238-11e8-942a-ac5207b90cd3.png)

**Comment by robguthrie** [comment]
all fixed in loomio 2.0
