### ISSUE TITLE
Poll form: Sub-label consistency

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4543]
Minor quibble: the first label caption in the below screenshot describes what will happen when the checkbox is ticked; the second describes what will happen if the checkbox is not ticked.
![image](https://user-images.githubusercontent.com/1380991/36349144-1348309a-14e5-11e8-9fe8-e3dd613dc213.png)

**Comment by robguthrie** [comment]
Arr.. helpful to have this quibble shared. I think the sentence should say
what will happen in the current state.

**Comment by gdpelican** [comment]
The announcement checkbox is going away, and the others conform to this
standard.
