### ISSUE TITLE
validation message not clearing when fixed

### ISSUE THREAD

**Issue by Space-Ed** [loomio/loomio#4562]
When I run into an validation error that presents a message I expect that message to disappear when the problem is fixed as I have done here. 

Perhaps this is actually a feature request of a more general validation messages should be reactive to form changes not only submit. 

![validation message not clearing](https://user-images.githubusercontent.com/6799598/36873985-1f2d4c3c-1e0f-11e8-96b5-864deb11d7d4.png)

**Comment by gdpelican** [comment]
Sure. We can fix this by calling `model.setErrors({})` whenever we know the message is no longer valid

So, in this instance, putting
```
@setErrors({})
``` 
on line 154 of poll model, after we've pushed the new poll option name, should fix this.

**Comment by gdpelican** [comment]
I believe this is now fixed.
