### ISSUE TITLE
Formatting on 404 page looks broken

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#4563]
<img width="995" alt="screen shot 2018-03-05 at 10 44 50 am" src="https://user-images.githubusercontent.com/5498878/36950959-52d49f04-2062-11e8-9c10-56ae7b570d43.png">

This is in Firefox 58.0.2 on Mac.

**Comment by gdpelican** [comment]
This should now be fixed pending deploy. Thanks for the report!
