### ISSUE TITLE
Inaccurate notification timestamps

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#4567]
![image](https://user-images.githubusercontent.com/970124/36957016-5893c972-2096-11e8-8b95-399ea81b1afc.png)

I *think* what is happening here is that I have a live network connection, then I get a new notification which arrives with a timestamp of "a few seconds ago". Then I keep my browser open, maybe I close the laptop lid. Then a few hours later I open the notifications again and the old item is still timestamped "a few seconds ago".

**Comment by rdbartlett** [comment]
This is still happening for me. So I closed my laptop lid overnight. Open it up and there are 3 notifications, all time stamped "right now":

![image](https://user-images.githubusercontent.com/970124/48185660-0798e580-e336-11e8-97f9-e471140932fb.png)

Then I reload the page and the real time is shown:

![image](https://user-images.githubusercontent.com/970124/48185711-3020df80-e336-11e8-9f76-7b5b5df2210a.png)

This is not a major, just wanted to flag it up in case there's an easy solution.

**Comment by robguthrie** [comment]
not relevant/a problem for loomio 2.0
