### ISSUE TITLE
New subgroup auto-populating last subgroup text

### ISSUE THREAD

**Issue by MichaelatLoomio** [loomio/loomio#4571]
When starting a new subgroup, the field text is already filled in with text from an existing subgroup.  And similar behavior is happening with New Group (the software is remembering the last text I drafted?).  It should go back to a fresh screen, yes?

![image](https://user-images.githubusercontent.com/36490055/37116461-446dd0ea-22b3-11e8-947e-9f360e9daff2.png)

**Comment by gdpelican** [comment]
This should now be fixed.
