### ISSUE TITLE
"New Decision" button 

### ISSUE THREAD

**Issue by LifestylesLoomio** [loomio/loomio#4573]
On a group's main profile page, it would be great to have a NEW DECISION button to start a decision. Currently a user has to click on Decisions on the main sidebar, and then the NEW DECISION button is available. It could be placed in the top right corner of "Current Decisions" window, as shown below.

![new decision](https://user-images.githubusercontent.com/37197107/37182979-ba2acb78-22e8-11e8-8312-9f345256bcd5.JPG)

Thanks!

**Comment by seoulstice** [comment]
Hello! I am a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thank You!

**Comment by gdpelican** [comment]
We now have a shiny new decision button on the group page. Hooray!
