### ISSUE TITLE
Glitch in reaction attribution when not logged in

### ISSUE THREAD

**Issue by modulistic** [loomio/loomio#4580]
When I am not logged in, [this answer](https://www.loomio.org/d/LDS3ON5a/mailserver-refuses-connection-from-inside-loomios-containers/4) has a :clap: reaction, which reads "You" (although the hover tooltip shows the right attribution):

![anonymous_visitor](https://user-images.githubusercontent.com/1902456/37246402-bf1028c4-24a8-11e8-9d9c-dca4765b51ae.png)

When I log in, I see the right attribution besides the :clap::

![logged_in](https://user-images.githubusercontent.com/1902456/37246403-bf3080e2-24a8-11e8-826a-5a28a8be6410.png)

**Comment by gdpelican** [comment]
Thanks for the report; seems like something we can fix.

**Comment by gdpelican** [comment]
Cool, I've fixed this and it will go live with the next deploy.
