### ISSUE TITLE
inbox does not show all unread until I load the recent page.

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#4586]
When I first load inbox I see this:
![image](https://user-images.githubusercontent.com/486367/37314814-16c78076-26bb-11e8-8be6-aa9245f72b31.png)

Then I click recent threads then go back to inbox and I see this:
![image](https://user-images.githubusercontent.com/486367/37314830-284e2fb6-26bb-11e8-8ce1-72cfef476770.png)

(other thread titles not shown for privacy reasons)

I guess the scope of inbox is smaller than recent, but I can't quite understand how.

**Comment by robguthrie** [comment]
All the unreads are very new

**Comment by gdpelican** [comment]
I wonder if any of the unread threads are closed? The only noticeable difference between the inbox and dashboard queries that I can see are

- Inbox shows just last 6 weeks, dashboard allows for older threads
- Inbox shows closed threads, dashboard does not (reason for this being that the only other way to see activity in closed threads is to click into closed and view the threads there... something you'd almost definitely never do)

...come to think of it, that's backwards and wouldn't describe this behaviour, unless maybe we're not live updating discussion closed events or something.

**Comment by robguthrie** [comment]
not applicable anymore. thanks
