### ISSUE TITLE
Threads not loading, move thread fixes temporarily

### ISSUE THREAD

**Issue by aerugo** [loomio/loomio#4588]
We're having a lot of spooky problems with this thread: https://talk.theborderland.se/d/y4GVswoJ/budget-guidelines-for-dream-grants-2018

For some users, sometimes, comments don't load. It's intermittent and is sometimes fixed temporarily by moving the thread to another group. After a while, the problem can reappear or appear for another user.

Only lead I have is that it might possibly have to do with comments being replied to after they've been deleted, but I've not tried to verify that suspicion.

**Comment by robguthrie** [comment]
Hrrm, I think the best way to dig into that is to start capturing your error messages, can you send me an email rob@loomio.org and I'll send you back some ENV's so that your errors are reported to us... If you're willing.

**Comment by aerugo** [comment]
FYI, I managed to see it happen and caught a console log:

<img width="554" alt="screen shot 2018-03-14 at 01 49 28" src="https://user-images.githubusercontent.com/7785081/37377417-105be762-272a-11e8-968e-109a5a0e547f.png">

In this case, it did not help to move the thread back and forth, but it has worked in the past.

**Comment by gdpelican** [comment]
Would you be willing to dig into this one @robguthrie ? It'll be a nested comments bug around a comment getting deleted but its children sticking around or not updating their tree values correctly. We've seen it several times before, and it b0rks the whole thread associated with it, so I reckon it's got some priority.

**Comment by aerugo** [comment]
In the meantime, is there some manual quick fix I could use to fix the thread? Like manually changing fields through the console or something?

**Comment by gdpelican** [comment]
Have a go at this:
```
d = Discussion.find("<discussion_key")
d.items.where(parent: nil).map { |event| event.update(parent: event.eventable.parent_event) }
```
then, if that doesn't work for some reason, try this
```
d = Discussion.find("<discussion_key>")
d.items.where(parent: nil).update_all(discussion_id: nil)
```

**Comment by aerugo** [comment]
No, that's not it apparently. 

`irb(main):030:0> d = Discussion.find(102)
=> #<Discussion id: 102, group_id: 21, author_id: 256, created_at: "2018-02-21 13:25:01", updated_at: "2018-03-14 09:18:27", title: "Budget Guidelines for Dream Grants 2018", last_comment_at: nil, description: "I would like to start a Discussions about the curr...", uses_markdown: false, items_count: 48, closed_at: nil, private: false, key: "y4GVswoJ", iframe_src: nil, last_activity_at: "2018-03-14 09:18:25", last_sequence_id: 0, first_sequence_id: 0, salient_items_count: 0, versions_count: 11, closed_polls_count: 0, pinned: false, importance: 1, seen_by_count: 79, ranges_string: "2-2,5-6,8-9,11-25,27-54">
irb(main):031:0> d.items.where(parent: nil).map { |event| event.update(parent: event.eventable.parent_event) }
=> []
irb(main):032:0> d.items.where(parent: nil)
=> #<ActiveRecord::AssociationRelation []>`

**Comment by aerugo** [comment]
Have you seen anything useful come from the sentry ENVs we set up?

**Comment by robguthrie** [comment]
Sorry for the delay, I've been away.

I've come to the same conclusion. Seems like it's something like that is the problem.

Maybe this works?
``` 
e = Event.find(2715)
e.update(parent: e.eventable.parent_event) 
```

**Comment by robguthrie** [comment]
Or maybe try
 
```
e = Event.find(2715)
e.update(parent: e.eventable.parent_event || e.discussion.created_event)
```

**Comment by aerugo** [comment]
Yes @robguthrie! That first command worked. Thanks a lot!
Now fixed for that particular thread.

**Comment by aerugo** [comment]
Oh, nope. Problem is back. It got fixed for a while, then it came back. Still only affects certain users.
New error in the console now.

<img width="554" alt="screen shot 2018-03-18 at 21 46 00" src="https://user-images.githubusercontent.com/7785081/37570885-fff07a12-2af5-11e8-9371-47de911f5f5c.png">

**Comment by robguthrie** [comment]
oh ok then! And now I see we already have something for this.

```
d = Discussion.find('y4GVswoJ')
Event.where(discussion_id: d.id).each {|e| e.ensure_parent_present! }
```

I'm sorry I forgot about that command until now!

Hopefully that sorts it out.

**Comment by aerugo** [comment]
Didn't solve it, sending you a log printout over email.

**Comment by gdpelican** [comment]
This has been fixed with flying colors! 🍏 🔴 💙
