### ISSUE TITLE
Time poll issues

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4597]
Three small issues with the time poll. 

* This poll (bT0l281I) is a groupless, 'anyone with the link' poll; so the text '100% of members have stated their position (2/2)' is not really relevant or accurate (it'll always be 100% and Loomio can't know how many people are involved). 
* There's a dangling VOTES heading at the bottom of the card
* The vote ordering dropdown is far from the content it orders (is it useful at all on a time poll?)

![image](https://user-images.githubusercontent.com/1380991/37571090-eab04ee0-2b5c-11e8-8e70-602b49ea72d9.png)

**Comment by mhjb** [comment]
Same poll — a more serious issue: we couldn't find a time that suited everyone, so I edited the poll to add some more options (and delete some no longer relevant ones). Upon saving, two of the people's votes disappeared.

**Comment by ntnsndr** [comment]
Another Time Poll problem: I submitted a vote to a poll which allows voters to add options, but then wanted to change my vote by adding some new options. Whereas I was able to add options during my first vote, I wasn't able to do that when I attempted to change my vote. This seems like an arbitrary restriction, from a user perspective.

**Comment by robguthrie** [comment]
closing this as it's super out of date now
