### ISSUE TITLE
Fails to load resource: angular.bundle.js

### ISSUE THREAD

**Issue by zenny** [loomio/loomio#4602]
Hi,

Getting a blank page in port 3000 after following the installation tutorial at https://github.com/loomio/loomio/blob/master/docs/en/development_handbook/setup_environment.md

Browser reports 'fails to load resource: angular.bundle.js' It reported to fail to get from http://localhost:4002/client/development/angular.bundle.js 

Any inputs appreciated.

Cheers,
/z

**Comment by robguthrie** [comment]
Oh no. First thing to check:
Are you running `gulp dev` from the `client` folder?

**Comment by gdpelican** [comment]
I'm 99% sure this is a result of `gulp dev` not running. Check out here for some docs on getting a dev environment running:

https://github.com/loomio/loomio/blob/master/docs/en/development_handbook/quickstart.md

Closing now :)
