### ISSUE TITLE
Reminders not sent; no error or confirmation given

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#4615]
In some groups (but not in others), when I click "Remind" on an undecided voter, I get the loading spinner for a second, but then no confirmation if it succeeded or failed. 

In console I see:

![image](https://user-images.githubusercontent.com/970124/38272051-39d2a76c-37dc-11e8-9ba5-09c436969c81.png)

**Comment by gdpelican** [comment]
Looks like a permissions error; could you provide the key of the poll in
question?

**Comment by rdbartlett** [comment]
don't know how to find the poll key per se, but it's the only poll on this
discussion `0HpMLSZv`

**Comment by gdpelican** [comment]
Alright, thanks. Looks like we're showing the remind button to folks who are unable to remind; should be just the poll author and group admins who can do that.

I've fixed and it will go live with the next deploy. Thanks!!! <3

**Comment by rdbartlett** [comment]
What's the logic of restricting this feature? As a group member, I can
manually @mention people to remind them about the proposal. The Remind
button makes it much quicker and easier for me to do it, which seems like a
useful act of facilitation. (I just did this in an important decision in
Enspiral Members, where the author and admins are both busy.)

**Comment by gdpelican** [comment]
I'm not married to it, but I also don't want to change anything as we rethink our notification system (this will turn into an announcement-related function really soon).

I'd imagine the original reasoning was that mentions are 'public' within the group and so it's quite obvious to everyone who is sending notifications to whom, whereas remind is a bit more behind the scenes and thus perhaps more prone to misuse in a large group of people. I'd posit that, in this argument, if you're going to be trusted with facilitating the group, you probably want to be a coordinator of the group (although I'm super open to ways we can allow non-coordinators to facilitate effectively, and this might be one of them.)

**Comment by rdbartlett** [comment]
Fair enough, happy to leave it as is for now :)
