### ISSUE TITLE
Case of poll option altered

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4618]
In the app, the poll option is capitalised thusly:
![image](https://user-images.githubusercontent.com/1380991/38472065-62ce58fa-3bce-11e8-8943-975f8625477d.png)

In the email notification to me (the poll creator), it's all been lowercased apart from the first letter:
![image](https://user-images.githubusercontent.com/1380991/38472074-82f98c80-3bce-11e8-9cbc-2cc41ac82772.png)

**Comment by gdpelican** [comment]
Alright, I've patched this one up in latest, pending deploy.
