### ISSUE TITLE
moving individual posts to the correct thread or to a new thread if misposted

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4634]
As a facilitator, options are very limited to organize and keep discussions on focus. And in diverse groups, it would be a shame to delete contributions and ask some members who contribute rarely to repost a comment as a discussion, inducing the idea that they failed at contributing to the group.

Following discussions in [this thread](https://www.loomio.org/d/ZxhcqojW/feature-request-more-standard-moderator-tools), here is a user story :

1. A coordinator (facilitator) in group A notices that a comment in discussion ZxhcqojW contains interesting ideas, but that they are not directly linked with discussion ZxhcqojW
2. Instead of deleting and ask the comment author to post in a new discussion, the coordinator uses the "Move to another discussion" option in the comment dropdown menu
3. A modal with a select labelled "Move to" offering a "a new discussion" thread and last active discussions (with a way to filter them)
4. if the coordinator chooses:
* the "a new discussion" option, he then chooses a title and if the comment should be used as context or types another context, then submits the modal.
* an existing discussion, validating the modal adds the post as comment to the discussion
  * if there are existing comments, the user is prompted to choose a parent comment it should be nested.
5. The initial comment does no longer appear, and is replaced with a "a comment has been moved to [this thread](https://)" message. This allows any member to follow up the discussion there, and to still use links from email notifications. If there were nested comments to the moved comment, they have been moved to and are either  children of the comment or first comments if the original comment has been used as context.

This feature could be open to the original poster if all members can edit their posts.

This leaves out the cases where a new discussion should be created in a subgroup or where only part of the comment should be moved to a new discussion (duplication and edit to keep first part in original discussion and last part in a new discussion?).

**Comment by robguthrie** [comment]
Wonderful feature description. Thank you!

**Comment by gdpelican** [comment]
The first iteration of this is now live; you can now fork comments into a new thread by clicking on the 'fork' action in the action dock. Let me know how you get on with this? :)

**Comment by juliencarnot** [comment]
Thanks for the progress on this! 

On loomio.org, I couldn't complete the process, I get a 403 error on https://www.loomio.org/api/v1/discussions/fork when submitting the modal then nothing happens.

Do you intend to allow moving a post or a comment to an existing discussion too, or do you consider the feature complete?

**Comment by juliencarnot** [comment]
@gdpelican  : I don't get the 403 error in my dev environment but still get it on loomio.org. Let me know if I can help debugging.
