### ISSUE TITLE
Reply by email fails, contact page is down

### ISSUE THREAD

**Issue by alexgleason** [loomio/loomio#4635]
Hi, at first I didn't want to make a GitHub issue because this affects loomio.org, but the contact page on loomio.org is also down.

When replying by email to a thread, it tells me that my message could not be sent:

Delivery Status Notification (Failure)
mailer-daemon@googlemail.com

**Comment by robguthrie** [comment]
Thanks for the report.

Reply to discussion by email is working for me. 
Could you forward the full error message to rob@loomio.org please?

I've tested loomio.org/contact via a logged out user and that works too. Were you logged in when using the contact system?

**Comment by alexgleason** [comment]
Thanks Rob, just forwarded you the email.

The contact page seems to be working fine for me now. Reply by email hasn't worked for several days for me.

**Comment by robguthrie** [comment]
It seems you're replying to notifications@loomio.org.. which is not correct. Your email client should be replying to the REPLY-TO address we include in the email header, which includes information needed to shuffle the message back into the group.

**Comment by alexgleason** [comment]
Ohhhhh wow, thank you for figuring this out! That makes sense and you are exactly right.

For reference this is happening to me on the stock Android AOSP client (which is now somewhat abandoned) so that is probably why. I've just tried a different email client and it did work; totally my email client's fault.

Thanks again for solving this.
