### ISSUE TITLE
Don't offer announce form if making no changes to a discussion

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#4646]
Just like with an edit of a thread, we should display a "who do you want to notify about these changes" modal after editing a proposal.

(i also reckon we should include the don't notify button here)

**Comment by gdpelican** [comment]
Hm, this is the current and intended behavior, although we don't display it if you haven't changed anything. Can you provide steps to repro where you'd expect the announce form to show up but it doesn't?

**Comment by robguthrie** [comment]
Oh sorry. I did not look into the code, I just noticed that it did not show
when I did not modify anything. That's good. Can we introduce the same
behaviour (don't show notify) on thread edit?

**Comment by gdpelican** [comment]
Alright, I made that change.
