### ISSUE TITLE
Move thread dialog broken

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4649]
thread: BWAz9qZf

![image](https://user-images.githubusercontent.com/1380991/39678184-17bf44d6-51dc-11e8-9e6b-bd88f74355e0.png)

no errors in console

**Comment by gdpelican** [comment]
Looks like it's offering guest groups as options there; I'll issue a fix
shortly. In the meantime, you should be able to scroll down to see the rest
of the groups, which should include groups you can actually move the
discussion to.

**Comment by gdpelican** [comment]
This should now be fixed; let me know if you continue to see this behaviour?
