### ISSUE TITLE
Calendar email timezone wrong + some email design suggestions

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4664]
I invited myself to a time poll. In the app, all the times are '6:00pm' (presumably NZT), but in the email, they're '6:00am' (UTC)
![image](https://user-images.githubusercontent.com/1380991/39837809-9a08409a-542b-11e8-8943-1c1bed2e4178.png)

I wonder if this email could also do with a little more love — it's to a not-yet-Loomio user. Thoughts:

* It might be nicer for the subject to say 'Matthew Bartlett invited you to participate in a time poll: ', 
* and for a little bit of word padding to happen around the group name and discussion, e.g. the email could start with "Matthew Bartlett has invited you to participate in a time poll in the discussion **Meetings & minutes** in the Loomio group **Test group**."
* Instead of "Closing 8:00pm - Friday 11 May 2018", near the Vote button it could say "You have until 8pm, Friday 11 May to participate in this time poll"
* It might also be sensible to have a little explanation of Loomio — like Doodle does

![image](https://user-images.githubusercontent.com/1380991/39838968-e3a4b172-542e-11e8-87af-3b775a28e9d6.png)

**Comment by robguthrie** [comment]
Thanks for the detailed help.

The default timezone for invited users should be the author's timezone, but that may have been lost in the last feature upgrade.

I like all your suggestions and will try to implement them shortly.

**Comment by mhjb** [comment]
Thanks x3 :)
