### ISSUE TITLE
Attempting to demote myself as coordinator gives error

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4683]
![image](https://user-images.githubusercontent.com/1380991/40037266-8854c72c-5860-11e8-8a7c-95b928b1749e.png)

**Comment by gdpelican** [comment]
Thanks for the report. Are you the only admin of this particular group?

**Comment by mhjb** [comment]
No - it's the loomio members group

**Comment by gdpelican** [comment]
Cool, this is actually related to that group being deleted and restored not so long ago. I've updated the counts for that group and demoted your coordinator status, and am pretty confident this isn't affecting  groups which weren't deleted

**Comment by mhjb** [comment]
tnx :)
