### ISSUE TITLE
Can't mention someone I just invited to join thread

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4686]
d: I1J2R6r9
I started a thread in a group & invited one other Loomio member + one other person by email (fun!)

The Loomio member instantly got added to the Thread members panel — which seemed odd; seems like they should perhaps have to agree to join it first.

<img width="410" alt="screen shot 2018-05-16 at 11 25 35 am" src="https://user-images.githubusercontent.com/1380991/40088604-e04557c6-58fb-11e8-998a-4ef9381f34e5.png">

Though they're listed in that panel, they don't turn up in the at-mentionable list.

**Comment by gdpelican** [comment]
This should be fixed with @robguthrie 's recent mention work.
