### ISSUE TITLE
Group appears to have no members

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4697]
g:3SzvElZb
It's a long established group and should have perhaps ten members in it, but the Group members panel looks like this today:

![image](https://user-images.githubusercontent.com/1380991/40582465-f685162e-61cb-11e8-81e7-8410ed5e1373.png)

**Comment by mhjb** [comment]
This was one of them groups that got deleted & restored a few weeks back…

**Comment by gdpelican** [comment]
I'll update this count in the DB for you later today

**Comment by mhjb** [comment]
Most appreciated :)

**Comment by gdpelican** [comment]
This should now be done for that group
