### ISSUE TITLE
Mention dropdown shows heaps of people not in group

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4703]
![image](https://user-images.githubusercontent.com/1380991/40809358-5ee2995c-657e-11e8-876d-2cff7e1a278f.png)

If I pick any of the people not in the group, it resolves to '@undefined'.

**Comment by gdpelican** [comment]
This one should be fixed pending deploy.

Note that having people appear who aren't in the group is now the intended behavour :)

**Comment by mhjb** [comment]
That's quite an exciting development. 

However it feels a bit tricky to not give any hint that people will be added… what if I pick the wrong person, don't notice; and they gain inappropriate access to content? Could it pop up a confirmation modal when you hit POST? Would also be cool to at that point learn whether someone is being added only to the present thread or to the group.
