### ISSUE TITLE
High priority: cannot start a group

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#4705]
Repro steps:

Logged in user. Open 'new group' modal. Set to closed. In advanced settings, deselect everything apart from editing comments and voting on proposals. Click Start Group. Modal fails silently. Console says `angular.bundle.min.js:1 POST https://www.loomio.org/api/v1/groups 403 ()`

**Comment by robguthrie** [comment]
Thanks for the report. Seems that you can't start a group unless 'members can start threads' is ticked. I'm going to look into it tomorrow morning.

**Comment by gdpelican** [comment]
This is now fixed.
