### ISSUE TITLE
403 on fork - unable to create a new thread from my comment

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4712]
Sorry this is a duplicate of https://github.com/loomio/loomio/issues/4634#issuecomment-389414972 , but as the issue was closed before testing the feature and there's no answer over there, here it is:

On loomio.org, I couldn't complete the forking process (moving one of my comment to a new thread, within a group I'm not an admin of), I get a 403 error on https://www.loomio.org/api/v1/discussions/fork when submitting the moda then nothing happens:

![image](https://user-images.githubusercontent.com/3848493/41099031-935b18a6-6a5d-11e8-8155-cd944c0d4e65.png)

**Comment by conatus** [comment]
Forking also doesn't appear to work for me.

Console throws this when I enter into fork mode and click on fork.

<img width="1375" alt="screen shot 2018-11-24 at 14 30 09" src="https://user-images.githubusercontent.com/317734/48969380-ad667880-eff5-11e8-965d-929ce482bd41.png">

**Comment by patcon** [comment]
Getting the same 403 on a self-hosted instance launch Fall 2018 (v1.8.663)

**Comment by robguthrie** [comment]
Hi fiends. I'm only willing to support the latest code (and efforts to upgrade to it). Please update your instances then report back.
