### ISSUE TITLE
invitations to new threads fill up notification tray while already accessible in the sidebar

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4713]
see https://www.loomio.org/d/WmcJB5lR/new-feature-invite-people-directly-into-a-thread-or-decision/53 for background:

When I'm "invited to join a discussion", regardless if the discussion is in a group I belong to or not, I get a navbar notification for a new discussion, which I already can see and access through "Unread threads (xx)" in the sidebar... 

The navbar notification tray quickly fills up with notifications I don't need, because I'll find the unread or recent discussions in the sidebar.

I'd prefer to remove notifications in the navbar tray, at least if the "discussion I'm invited to" is in a group I belong to, so that the notifications tray stay useful...

**Comment by robguthrie** [comment]
I understand the problem. Thanks for helping us work it out.

I hesitant to change the app's behaviour of notifying people, I want to change how people use the app.

It wasn't the original intention that people would use the invite form to invite everyone to every discussion. The intention was to prompt users to notify people who are specifically involved or invite external people into the thread. In the case where you just want to start a discussion within your group, and see who shows up, it's not intended that you invite everyone (or even anyone).

We need to to a better job of warning people when they invite a large number of people, and educating them about how discussions will show up as unread, and in the daily email without the extra step of notifying people.

Im thinking of a message like:
Everyone in your group can see this thread. Use this form to notify specific people immediately, or invite external people into the thread.

**Comment by juliencarnot** [comment]
Ok, that makes a lot more sense once it is explained (and the documentation is really lacking on this now...). Honestly, I had no idea this was the way to do it and I guess I'm among the most change-aware "power users", so I'm not surprised people are confused. 

In that case the wording needs to reflect that not inviting people (which looks a lot like the new wording for the previous notifying members option for long time users) will still notify them as they chose to be notified (for every new discussion or in daily e-mail), and that skiping the invitation won't let them in the dark. And I'd probably remove the obvious option to invite every group member if this is not the intended use...

**Comment by robguthrie** [comment]
I've been thinking about this a lot, thanks for raising it.

Here's my thinking:

- When you just want to get a person's attention, the most natural way is to mention them. So you don't need this form for that.
- For _most new threads_ (eg: in Loomio Community), we don't want people to send notifications, and certainly not to lots and lots of people. The right people will see it without that extra noise.
- For _important threads_ where the information is ready to go out, this is a great way to ensure your message is received especially by nontechnical or infrequent users.
- For _proposals_ it's often appreciated to send notifications as they often have importance worthy of a notification and need good engagement. Edits, just sometimes, but I don't hear of people having an overuse issue when editing. However often you want to be able to select a subgroup of people who's vote is important.

We also want the app to feel familiar and behave predictably.

Some ideas:
- If you notify more than x people, pop a warning message which says this is very noisy and should only be used in exceptional situations.
- We display some kind of education screen before the form asking something like "Is this an important announcement or just another thread? Would you like to invite special guests into the thread?"

What do you think?

**Comment by juliencarnot** [comment]
From my experience with group e-mailing, it sounds very risky to rely on the poster to decide what is important and worth notifying. People have a tendency to believe what they think is important to others (yay social media) and anyways participants will have different tolerance thresholds for notifications/email traffic.

What I really liked about Loomio is that each participant decide how and when they get the info, pull from the web when they have a moment or push and daily or immediately by mail, rather than drowning in e-mails and notifications. I still believe this is how you foster participation, by letting participants chose how they participate, and not by letting a participant or even a coordinator decide what is worth bugging everybody with.

From this point of view, I'd say the notification pane should be removed in new/edit modals for discussions or decisions that belong to a group. And I'm not even sure I'd put the notification checkbox back in the new discussion or decision modal, considering the participants choose how they are or are not notified. For a groupless discussion or decision, I'd keep it as it is (except for the ability to notify only one full group, in which case it should have been posted as a group discussion).

Adding explanations or warnings will make the app more complex to use and will be ignored by some of the participants, so I wouldn't choose that path. But maybe this topic would deserve a design proposal to be debated and why not a decision in the product development group?

**Comment by robguthrie** [comment]
not actioning anything here just now. it did make me think though.
