### ISSUE TITLE
Feature request: allow source markdown to be exported from closed decisions etc.

### ISSUE THREAD

**Issue by wu-lee** [loomio/loomio#4714]
I just had a mild awkward moment with the social.coop Loomio groups, wherein I had made a proposal on a sub-group, which closed, and I wanted to move it to the main group, starting with the text of the original proposal.

I found I can't get at the source of the proposal when it's closed, so I couldn't re-edit it easily. (There were a lot of links and so on I didn't want to re-create).

In the end I re-opened the decision, edited it, copied the source, cancelled the edit, and then close it again.

It would be nice if this were easier.

Thanks!

**Comment by robguthrie** [comment]
Will take this onboard. Ideally we'll have both export json and download report functions on threads and polls. The json is something you can import into another loomio instance and the report is something you can open in a spreadsheet or browser.

**Comment by robguthrie** [comment]
the new export discussion feature will cover this use case fairly well
