### ISSUE TITLE
Loomio.org detecting I'm logged in, redirecting to /dashboard, blank white page

### ISSUE THREAD

**Issue by strypey** [loomio/loomio#4715]
I'm not sure if this is the appropriate place to report this issue, but since I can't get into Loomio, I'm not sure how else to do so. When I navigate to loomio.org, it detects I'm logged in, and redirects to /dashboard as normal. But nothing appears, just a blank white page.

I first noticed this issue today, but I haven't tried logging into the web app for a while, maybe even a week or two? So I don't know exactly when it started.

EDIT: Eek! Just realized I gave no system info! Bad bug reporter, bad!

OS: Trisquel 7 GNU-Linux (based on Ubuntu 14.04)
Browser: ABrowser 60.0.1 (based on 32-bit Firefox)

EDIT: Browser plug-ins:
* NoScript 10.1.8.2rc4
* uBlock Origin 1.16.2
* 1-Click YouTube Video Downloader 4.0.92

Hardware: https://www.coactivate.org/projects/disintermedia/bishop

I've just downloaded some system updates, so I'm going to reboot, and see if that improves things. I'll let you know.

**Comment by strypey** [comment]
Updated and rebooted. Still got a white screen :-< Is there anything I can do to test why it's not working that might help you folks fix it?

**Comment by robguthrie** [comment]
And, could you please try with another browser and report those results? Thanks for your patience!

**Comment by strypey** [comment]
@robguthrie 
> Could you please open your javascript console and screenshot or copy paste any errors from there?

See:
[new-normal-window.txt](https://github.com/loomio/loomio/files/2086660/new-normal-window.txt)

> And, could you please try with another browser and report those results?

I tried with NetSurf. I crashed immediately as soon as I entered Loomio.org and hit enter ;) Do you have any other browsers in mind that don't depend on proprietary software?

Curiously, I tried opening Loomio is a new private window, to get a tidy JS console report. The page came up as normal. I logged in. The /dashboard page displayed as normal.
[new-private-window.txt](https://github.com/loomio/loomio/files/2086650/new-private-window.txt)

**Comment by strypey** [comment]
I did suspect NoScript initially, but it works with NoScript in the private window. Loomio.org was set as "trusted" in NoScript in both windows when I took those JS console outputs. With NoScript set to 'disable restrictions for this tab, and with it completely disabled in the Add-ons Manger, Loomio.org in the normal window still gives the same white page.

**Comment by robguthrie** [comment]
Hrrrm. Some googling on those errors tells me they are benign and it's something else that's the problem. However without other errors we have nothing to go on. Do I have your permission to generate a login token and test logging in as you?

**Comment by strypey** [comment]
Go hard brother!

**Comment by robguthrie** [comment]
Hrrm. I'm able to login as you with a login token perfectly, it loads up in both FF and Chrome. 

So, it's something to do with browser choice or settings. I have had some other reports but I don't have enough info to follow it up yet.

**Comment by robguthrie** [comment]
Hi Strypey, If you use Firefox, does it work?

**Comment by strypey** [comment]
ABrowser is essentially an unbranded FF, less a few things (the proprietary Adobe EME module) and with a few tweaks to reduce the tracking surface and plug up other security flaws in vanilla FF. So I suspect not.

> I have had some other reports but I don't have enough info to follow it up yet.

what hardware/ OS/ browser are the people making these other reports using? Is it all people on GNU-Linux? Is it all people with older hardware? Figuring out what the people with the same issue do and don't have in common might help us narrow it down?

**Comment by strypey** [comment]
OK, I just downloaded some new updates, and it's fixed! If anyone else is reporting the same problem I was having, who uses GNU Linux, get them to do a system update (and make sure they've updating all their add-ons too), and see if that helps.

**Comment by robguthrie** [comment]
Ok. Good it working now!
