### ISSUE TITLE
admin panel simple features to add

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#4716]
User page:
link to visits from that user so we can see what browser etc they use.

**Comment by robguthrie** [comment]
Group page

I would like to easily see exactly what the settings are. I'd like them to be displayed in a similar order to how they are on the group settings form

**Comment by robguthrie** [comment]
link to be able to see emails sent to a user and if they're read or not.

**Comment by mattkeenan** [comment]
Be able to add / remove users of a group from the admin panel
