### ISSUE TITLE
inbox is missing threads

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#4720]
I've been experiencing this for a long time now... 

Currently if I load the inbox I get no results, but if i load dashboard I can see unread threads.

![image](https://user-images.githubusercontent.com/486367/41290889-0ee59cb2-6e46-11e8-8ab7-baaf370f323c.png)
![image](https://user-images.githubusercontent.com/486367/41290902-1c8ca644-6e46-11e8-8421-fd266a30a26e.png)

dashboard:
![image](https://user-images.githubusercontent.com/486367/41290932-351b305e-6e46-11e8-942d-1252edef5e54.png)

I think it might just be displaying threads which i have a discussion reader for..

**Comment by gdpelican** [comment]
How did this fix go? I have to admit never experiencing this

**Comment by robguthrie** [comment]
no good. still a big problem for me.

**Comment by robguthrie** [comment]
I'm also seeing that threads I've been invited into directly are not showing on my recent/dashboard page.

**Comment by mgodlewski** [comment]
@robguthrie, I can't see any reference to a fix, are you sure this issue is closed ?

**Comment by robguthrie** [comment]
Thanks for catching this. I'll reopen and look into it.

**Comment by robguthrie** [comment]
this is a duplicate of #4586
