### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by loydjayme25** [loomio/loomio#4723]
Good day, about the enhancement of the project. I am willing to submit my design for logo and icon.
and also, making your github repo prettier.

**Comment by robguthrie** [comment]
Ooo I'm excited to see what you've done. Changing our logo would be a very big deal but I'd love to know what you've done and start a conversation about if we want to adopt it. Would you be happy to contribute your designs under the AGPL?

**Comment by loydjayme25** [comment]
@robguthrie there is no problem sir, i am happy to work on my designs under AGPL .

**Comment by loydjayme25** [comment]
i made two kind of design, whats your pick ? 
if you have any suggestions, pls don't hesitate to comment. Thank you !

![proposals](https://user-images.githubusercontent.com/37318022/41344616-229f0fba-6f34-11e8-94cc-ceb22e8465fa.png)

**Comment by loydjayme25** [comment]
Color changes

![2](https://user-images.githubusercontent.com/37318022/41344770-839a0d38-6f34-11e8-84ad-305973dc5b80.png)

**Comment by robguthrie** [comment]
Wow. It's really cool. this is great work.

I love the return to linked letters for the brand name. have you seen our old logo with the linked letters? It was originally made out of string then photographed and turned into a vector image. ![](https://loomio.gitbooks.io/manual/content/en/index.html)

What's your inspiration for the fan like image? Can you tell me more about that?

I just want to reiterate that this is really cool, but we are in no position to adjust our brand in the short term, but I am enjoying this conversation and think this could influence future decisions.

**Comment by gdpelican** [comment]
I'm personally digging the direction of the text change; I think it's a nice medium between the current top-of-app text (which seems quite corporate to me), and the previous 'stringy' one (which is a bit tough to instantly parse, and has a feeling of 'looseness' about it).

**Comment by loydjayme25** [comment]
My intention of making the logo is to make the name clearer to read, the current logo was cool and i like it. the " i " in the loomio can be look as e or i, so that was my purpose of creating the logo. Clear and equal, to attract more user/project. thank you @robguthrie

**Comment by robguthrie** [comment]
closing this as it's very old now. Thanks anyway.
