### ISSUE TITLE
ranked choice in missed yesterday still a little wrong

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#4724]
logging for myself to fix tomorrow:
![image](https://user-images.githubusercontent.com/486367/41311121-4b614134-6e7b-11e8-9774-38c5d8c18f6c.png)

**Comment by robguthrie** [comment]
@gdpelican this is making my head hurt a little. It looks like we have some duplication in our responses view code. Are you able to have a crack at removing the broken duplication so it does not display ranked choice stances incorrectly?

No problem if you'd rather not and too busy. Just thought I'd ask

**Comment by gdpelican** [comment]
I'll take a look tomorrow, sorry for the delay.
