### ISSUE TITLE
network protocol violation

### ISSUE THREAD

**Issue by TulsaMidtowner** [loomio/loomio#4740]
Unable to login to Loomio 
See only blank screen at the above URL, with error message in Firefox as follows: 

> Corrupted Content Error
> 
> The site at https://www.loomio.org/profile has experienced a network protocol violation that cannot be repaired.
> 
> The page you are trying to view cannot be shown because an error in the data transmission was detected.
> 
>     Please contact the website owners to inform them of this problem.

Running Firefox 60.0.2 (64-bit) on Ubuntu
Am a new user of Loomio (few months experience with it only)
The problem has persisted for a few days now.
No other thread with "network protocol violation" seems to exist on GitHub.

There does not seem to be anyway to reach Loomio outside their platform.
The feedback form doesn't work (same error msg displayed as above)

**Comment by robguthrie** [comment]
My guess is that something on your network is modifying your web pages.. maybe your ISP or your employer. 

I don't think this is a Loomio bug, I'm sorry to say (for your sake).

**Comment by TulsaMidtowner** [comment]
Thanks for the reply robguthrie.  It turns out it was a conflict with the NoScript add-on in Firefox.  NoScript whitelisting for this Loomio website isn't available.  But disabling NoScript (turning off script-blocker in Firefox) fixes the problem, allowing login to Loomio and use of their service.

**Comment by robguthrie** [comment]
Great news!
