### ISSUE TITLE
unable to post comments, edit and participate in poles/vote tools etc. 

### ISSUE THREAD

**Issue by rmnkwrt** [loomio/loomio#4745]
when pushing the post or vote button the whole comments or vote window stays grayed out... then after like one minute it gets back to like it was before and nothing changed

![grafik](https://user-images.githubusercontent.com/40860758/42324621-eaa7ae32-8063-11e8-9b70-1c1bd2d485eb.png)

![grafik](https://user-images.githubusercontent.com/40860758/42324728-413f7478-8064-11e8-8278-059fdc4a65dd.png)

why is that? anybody has an idea?

**Comment by robguthrie** [comment]
I'm resolving this via our normal customer support channels
