### ISSUE TITLE
Performance: load much bigger chunks of a discussion at once

### ISSUE THREAD

**Issue by deutrino** [loomio/loomio#4749]
This comment is chiefly about mobile performance though I am sure there are implications for desktop. After poking around a bit I see that the dev team is aware of poor performance on mobile and that excising Angular may be necessary to change that. Okay.

In the meantime is there a way to do away with the following maddening ux on large threads:

1. Navigate to thread.
2. Scroll down to what appears to be the end of the thread.
3. A throbber suddenly appears - assuming you scrolled to the right zone in the page, that is. Overshoot or undershoot and nothing happens until you scroll back to the zone where Loomio detects the need to load more comments. At any rate, if you're lucky, the throbber appears relatively quickly, but sometimes it doesn't.
4. After an often considerable delay, the throbber is replaced by a small handful more comments. 
5. Repeat steps 2-4 ad nauseam. If the thread has a bunch of comments and you somehow know you want one at the end, you're in for several minutes of this (or you just give up, which is the problem I see happening with many users in the org where I'm exposed to loomio, due to ux issues)

If there is not a very good reason to load threads piecemeal like this, it may be good to drop the approach, as it's terribly inefficient - roundtrip after roundtrip to request each tiny dribble of comments, meanwhile my phone is getting hot to the touch and the battery is draining almost visibly. 

This is an instance hosted at loomio.org btw, so somebody running it on a particularly slow server can be removed as a variable. I'm running Firefox Mobile on Android.

**Comment by deutrino** [comment]
I just came back to the Loomio github to look thru the issues and see if anybody was complaining about this on desktop as well (actually, I didn't remember offhand that I'd submitted this issue, clearly it's a pain point though). The model of having to click 9000 times to "load more" is incredibly irritating. I can't even get Loomio to spit out a list of users in a group without having to click "load more" over and over and over and OVER. This is an antipattern. It's bad on desktop and completely insufferable on mobile. Please provide a way to shut it off and load all the content at once.

**Comment by robguthrie** [comment]
much much better comment loading in loomio 2.0
