### ISSUE TITLE
Loomio not loading on Android

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4757]
I'm finding Loomio.org/dashboard won't load for me on my Android 5.1 with Chrome, though it does work on the built-in browser. In Chrome I see a blank screen with the Loomio grey in the background.

**Comment by robguthrie** [comment]
@mhjb is this still happening for you?

**Comment by mhjb** [comment]
Yes

**Comment by mhjb** [comment]
All working again, thank you.
