### ISSUE TITLE
Crashing in my browser

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#4844]
In my normal browser (latest Chrome on macOS), when I visit loomio.org/dashboard I just get a blank screen. Same result with all extensions disabled.

![image](https://user-images.githubusercontent.com/970124/44855941-7a1d8300-ac6c-11e8-9307-1aa03ea8d2d2.png)

Then I go incognito and it works normal, no errors in console.

Any hints how I can help debug this?

**Comment by rdbartlett** [comment]
I blew out my cookies and that fixed it. 

Happy to close this unless someone thinks there's something worth investigating.

**Comment by robguthrie** [comment]
Hrrmm I wish I knew more, but gonna close until more info comes up. Thanks anyway.
