### ISSUE TITLE
I don't know what to do with time poll outcome statement

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4862]
Not a bug, just a bit of UI uncomfortableness: I use time polls a lot, and I never know what to do with the (required) outcome statement. What I want to say always seems to be covered by the other fields.

![image](https://user-images.githubusercontent.com/1380991/45119189-c574eb80-b1ae-11e8-9076-a62d55e1f8c6.png)

**Comment by robguthrie** [comment]
i'm closing this as until another person complains
