### ISSUE TITLE
broken trackpad scrolling in comment edit boxes

### ISSUE THREAD

**Issue by mike-hales** [loomio/loomio#4888]
Scrolling works fine in comment-creating boxes. But when editing a posted comment, continuous scrolling by trackpad doesn't work, can only be achieved with cursor keys, line-by-line.
This occurs in Firefox 61.0.2 and Safari 11.1.2, MacOS 10.13.6

**Comment by robguthrie** [comment]
You're right, thanks for the report. We'll look into it.

**Comment by robguthrie** [comment]
fixed now

**Comment by mike-hales** [comment]
great. thank u
