### ISSUE TITLE
Invite to vote sending anyone with a link can participate

### ISSUE THREAD

**Issue by DamonClark** [loomio/loomio#4903]
I don't know if this would be a considered a bug or a new feature request. It just seems a little odd to me how the functionality on the Invite to Vote window works. In cases where a user would like to only use the anyone with link can participate feature but not specifically invite people by email or name. 
The send button appears to be disabled:

<img width="484" alt="invite to vote" src="https://user-images.githubusercontent.com/940055/45917222-957d4780-be40-11e8-8952-2469a5bd1cdc.png">

I would expect that the send button should still be enabled, and the text should be changed to the word done.

Another oddity to me is when you start adding people to invite and the sending anyone with a link checkbox disappears. In cases where a user would want to invite people and also allow anyone with a link to access. I think it is a little unclear if this is possible. 

<img width="483" alt="invite_to_vote2" src="https://user-images.githubusercontent.com/940055/45917335-c78fa900-be42-11e8-9c9d-0e6083ee49fb.png">

I would expect that the anyone with a link can participate check box remains on the window to make it obvious that this is still enabled/disabled.

**Comment by robguthrie** [comment]
see Loomio 2.0, it's resolved this issue.
