### ISSUE TITLE
Error clicking email links when logged into wrong account

### ISSUE THREAD

**Issue by alanna** [loomio/loomio#4932]
I have different Loomio accounts for different jobs/groups. I got an email notification while logged into the other Loomio account. I clicked "view it on Loomio" in the email, and got this error. I logged out of Loomio, and then into the other account and tried again, and it went through. 

<img width="821" alt="screen shot 2018-10-11 at 10 57 53 am" src="https://user-images.githubusercontent.com/5498878/46768619-62deb480-cd45-11e8-883a-9dfdcbf00883.png">

I understand why it doesn't show the content when logged in as the wrong user, but I think this error message could be more informative. Maybe something similar to when you try to view a Google doc with a different account, like "You don't have permission to view that. You're logged in as xxxx@xxx.com. Switch accounts?"

**Comment by robguthrie** [comment]
Thank you! What a great suggestion. We're preparing a roadmap now and I'll scoot this to the top.

**Comment by robguthrie** [comment]
I think this is resovled now.
