### ISSUE TITLE
interpolation issue on thread page

### ISSUE THREAD

**Issue by data-doge** [loomio/loomio#4965]
when i go to the thread page, in the upper right-hand corner i see:

<img width="485" alt="screen shot 2018-11-01 at 11 47 53 am" src="https://user-images.githubusercontent.com/7520103/47862931-92289480-ddcc-11e8-9aef-16c99703cdcc.png">

**Comment by data-doge** [comment]
i don't recall this being an issue yesterday

**Comment by gregorykan** [comment]
fixed 👍
