### ISSUE TITLE
Styling tweak on notifications

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#4978]
If you don't have a fast network connection, when you open the notifications panel it looks like this:

<img width="1280" alt="screenshot 2018-11-05 at 7 52 37 am" src="https://user-images.githubusercontent.com/970124/47982409-e9ca4700-e0cf-11e8-8bc8-3c1d5f545a02.png">

Some of the avatars haven't loaded yet, so those line items are out of alignment with the ones who have avatars already. Then once the network transaction is complete, they all jump into line.

I wonder if there is a tiny fix that would stop the jumping? E.g. specify the width of the avatar container so it stays the same size before and after the image has loaded. I appreciate this could be very easy, or annoyingly complex.

**Comment by robguthrie** [comment]
Thanks mate. Will do
