### ISSUE TITLE
missing translation issue on `poll_common_edit_modal`

### ISSUE THREAD

**Issue by data-doge** [loomio/loomio#4984]
steps to reproduce:

1. edit poll
2. announcement modal pops up
3. translation path shows instead of copy (see screenshot)

<img width="482" alt="screen shot 2018-11-07 at 2 27 36 pm" src="https://user-images.githubusercontent.com/7520103/48155640-707e5000-e299-11e8-9b8d-a7ef971e4dce.png">

possible that https://github.com/loomio/loomio/blob/master/client/angular/components/poll/common/edit_modal/poll_common_edit_modal.haml#L8 should be
```rb
%span{translate: "announcement.form.poll_{{poll.pollType}}.title", ng-switch-when: "announce"}
```

**Comment by robguthrie** [comment]
fixed
