### ISSUE TITLE
New Decision button disappeared

### ISSUE THREAD

**Issue by lorelei1** [loomio/loomio#4994]
Hi! We at giveth use loomio a lot and have over the course of the past week (maybe longer) have been losing the new decision button. First, it was gone on Griff's account, but present on mine so he made it from mine, and now it's gone from my view as well. 
I think before it was here, in the top right of the decisions box just like in the threads box.
<img width="640" alt="screen shot 2018-11-09 at 9 13 49 pm" src="https://user-images.githubusercontent.com/38163206/48285958-71afa880-e464-11e8-9934-8635ed4e15ef.png">

it's also nowhere to be found when i click on the decisions page from the sidebar. 
<img width="1119" alt="screen shot 2018-11-09 at 9 17 52 pm" src="https://user-images.githubusercontent.com/38163206/48286185-2a75e780-e465-11e8-89ec-532b39da4a35.png">

**Comment by lorelei1** [comment]
OHH. Awesome! I'm very intrigued by these possibilities. It makes a lot of sense now that you explain it, but definitely wasn't intuitive for me as a user. (Maybe I am just used to the old ways). It would be amazing if there was some simple banner "Every Decision now starts with a Thread" or something to that effect :)

**Comment by robguthrie** [comment]
Good idea. Thank you for understanding! We'll be releasing a new tour/demo video soon (ie: in the early new year) and hopefully this gives people a much better understanding of using Loomio effectively.

**Comment by marxistvegan** [comment]
> Hi,
> 
> Sorry you're missing the button.
> We've removed this button as it was causing users to arrive in confusing situations .. related the following issues:
> 
>     * Decisions started without a thread don't appear on the dashboard (so we had multiple people who could not find their decisions)
> 
>     * There is no way to have a discussion "about" the proposal, which is necessary to the loomio process.
> 
>     * There is no sequence that multiple proposals can exist within
> 
>     * New users were not sure what the recommended way to use Loomio was (it's to have a discussion before you start making proposals).
> 
> 
> We have a new UX for decision making coming in the next month or so, and it will double down on the thread being necessary to the decisions workflow.
> 
> We'll make it so you you can start a thread with a decision about as easily as a decision alone, we're really excited about it - I'm sorry to be removing something you're used to, but I feel it's necessary to move the product forward.

Though this is a good idea in part a number of people were more familiar with the past practices as there were discussions that happened offline and a decision was proposed. I think this as an option would be helpful alternative.

**Comment by rdbartlett** [comment]
Nathan [says](https://twitter.com/ntnsndr/status/1070822833389895680) 

> "is it no longer possible to create a poll independent of any group from the "Decisions" (/polls) screen? I wanted to create a time poll..."
