### ISSUE TITLE
Aragon wants to pay you to make your tools available to DAOs

### ISSUE THREAD

**Issue by GriffGreen** [loomio/loomio#5008]
Aragon has an amazing Nest program and your tooling is so great! It would be amazing if DAOs using their platform had access to these tools.

Yes... they could just go to your website... but then they would have to do a second vote in their application to actually have it be binding.

Imagine if you could have the results of a loomio decision actually result directly into hiring someone, or giving a raise, or modifying a value statement (In a few months DAOs will be able to run github repos), or making any other decision that can be digitally enforced (especially cryptocurrency decisions).

The Nest Program which would give you the funding for each voting module you implement: https://github.com/aragon/nest

This is on that seems like it's just waiting for you to apply:
https://github.com/aragon/nest/issues/49

But you can take a lot of what you have done already and my team could help design a smart contract around it and I bet almost each type of poll could get its own grant, or we could put together a test poll so we can see how it all goes together.

Thoughts?

**Comment by robguthrie** [comment]
Thanks for the kind suggestion. We are not seeing a demand from our customers for this kind of thing, and as we're trying to make our (open source) company cashflow positive we're following the customers right now.

However it might be a good opportunity for someone new (or not in the core team) to learn about Aragon + Loomio and be paid at the same time.

@gdpelican maybe you're interested or know someone?

**Comment by GriffGreen** [comment]
Ooooo yeah! That would be great, I'm not picky on who does it, altho i hope who ever does sets aside some sort of donation to your team for the foundational work. I am just one customer that wants to see it happen. I also happen to be able to help make it happen and find funding for it to happen ;-)

**Comment by gdpelican** [comment]
Hm, I think I'm interested in an initial conversation in this direction. @GriffGreen would you be willing to reach out to schedule a time? D-1r4ajezbps@maildrop.cc

**Comment by gdpelican** [comment]
@GriffGreen Thought I'd check back in about this; is this still a thing you're interested in helping build?
