### ISSUE TITLE
Reactivate account flow is broken

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#5039]
I was unable to reactivate my account recently; I got an oddly styled email
<img width="648" alt="captura de pantalla 2018-12-03 a la s 11 13 41" src="https://user-images.githubusercontent.com/750477/49345643-aa057800-f6ec-11e8-815a-dd71c0e5082f.png">

which took me to this screen
<img width="602" alt="captura de pantalla 2018-12-03 a la s 11 13 53" src="https://user-images.githubusercontent.com/750477/49345649-b558a380-f6ec-11e8-8387-89ecd9d43af0.png">

But clicking 'Log in as James' dropped the 'Sorry but we were unable to log you in' error
<img width="568" alt="captura de pantalla 2018-12-03 a la s 11 13 56" src="https://user-images.githubusercontent.com/750477/49345653-c1446580-f6ec-11e8-8fd9-76c5b181ad02.png">

Entering the code also didn't work for me.

**Comment by gregorykan** [comment]
hey @gdpelican, we couldn't reproduce this unfortunately. seems like your account is back?

will fix the formatting of the email tho!

**Comment by gdpelican** [comment]
Sorry, but this is definitely broken. Here's a screencast of what happened this time:
https://www.useloom.com/share/2ab2d1a2b3dc416a927beefabf720ecd
