### ISSUE TITLE
Bot - Support for matrix/Riot bot

### ISSUE THREAD

**Issue by geleeroyale** [loomio/loomio#5066]
First of all - YOU GUYS ROCK! I love loomio and think it is essential to modern decentralized governance. With this issue, I dare make a feature request: It would be awesome to have more team-chat platforms (especially open source ones) supported with notification bots.

*I have a very practical reason to ask this:*
Our community went away from Slack to Riot.im - we have decent bridging - but because all essential information in the Slack bot seems to be transported in payload and the bot itself has an unchangeable(?) username - it is not even clear that the message is from loomio.

![image](https://user-images.githubusercontent.com/317685/49840575-3e8a6d00-fdb4-11e8-93bc-c37bf367b734.png)

I am aware that this is an issue that comes from our bridging of Slack/Riot, but I still wanted to tell the loomio team, because I think many people would benefit from a tight riot/loomio setup - we found Riot is quite a good hub to integrate all kinds of other chat messengers via bridging.

**Comment by robguthrie** [comment]
Hi, nice to hear from you.

2 questions:
- What would you like to see in the text over the bridge?
- Would you like to see each comment and vote come through the slack bot?

**Comment by geleeroyale** [comment]
The most useful would be a **link to the proposal** and a mention that this comes from loomio (which could be expressed by the name of the bot)

Your suggestion with comments and votes is interesting - it would definitely be nice to have more control over the bot settings, as this is something that might want to be set per sub-group

**Comment by robguthrie** [comment]
I'm closing this, it's a great idea, but this issue won't make it more likely to happen. welcoming any contributions
