### ISSUE TITLE
Thread marked as read even when logged in on wrong account

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#5085]
Here's what happened:

* Clicked 'view on Loomio' link in email
* Loaded page, but I was logged into wrong account
* Saw 'you don't have permission to do this'
* Logged out and then in on right account
* Looked for unread discussion, but it wasn't there because it had been marked as read

Maybe it was just a fluke, but if it's marking threads read when not allowing you to read them (as it should if you're not logged into the right account), then that's a problem.

**Comment by robguthrie** [comment]
I think the explanation is normal behaviour.
Loomio will mark things you read via email as read, and I think that's what's happened here.

Thanks for your continued support with making Loomio better!
