### ISSUE TITLE
Use local to display hour in "meeting time" polls

### ISSUE THREAD

**Issue by mgodlewski** [loomio/loomio#5164]
Hi,

Today, the hour in the poll are displayed in [12-hour clock time convention](https://en.wikipedia.org/wiki/12-hour_clock) which is common in several English-speaking nations.
In other countries, this convention is poorly known which leads to misunderstanding.
It'll be convenient to display hour in 24-hour  clock time convention based on group preference or client request header.

Regards,

Mathieu

**Comment by robguthrie** [comment]
Thank you for suggesting this.

The easiest thing to do right now is the change the default format to be most broadly understood.
Then a per user setting seems good after that.

Am I correct in assuming that a format like below is internationally understood?

2019-01-20 16:00

Which I'd line break like so:
2019
01-20
16:00


Also for day of the week and month, does a 3 letter abbreviation like 'Fri' and 'Mar' translate well?

**Comment by mgodlewski** [comment]
You're suggestion seems good to me for a better international understanding of hour.

For day of the week and month, the 3 letter abbreviation doesn't translate very well (for example, in french, Friday translation is "Vendredi").

I've seen in [angular documentation](https://docs.angularjs.org/api/ng/filter/date) there is some format that are "localizable formats", such as "shortTime" for time or "fullDate" for dates.
Do you think they can be easily in loomio ?

**Comment by robguthrie** [comment]
dates and times are in 24h international date formats in loomio 2.0.

No complaints so far.
