### ISSUE TITLE
threads not deleting within reasonable time (or at all?!)

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#5188]
@robguthrie @gregorykan @iainkirkpatrick sorry for the big ping but the issue I mentioned to Rob a couple of days ago - that threads I delete do not get deleted - has persisted for quite a long time now... in the group linked below I have deleted (perhaps twice now) some threads if not early yesterday actually the day before yesterday: https://www.loomio.org/g/Az2KfDEj/demothe lag in threads getting deleted is troublesome in the first place. I was in an activation call just yesterday and helping the customer clean up their group as they prepared for group-wide launch, and we tried to delete their Test thread and it did not go away, causing me to have to explain technical stuff (how deleting threads is background process, in layperson terms as best i could without drawing too much attention) and I know y'all well know that the customer isn't interested in that but wants to know it's working... also I am worried that this person's Test thread will persist for days, and they're inviting group members as soon as Monday NZT; here's that group: https://www.loomio.org/admin/groups/foIEupat

**Comment by robguthrie** [comment]
Thanks @coopchange - I'm aware of the problem and working on it as I can.

This bug has been introduced by a change in the way paper_trail gem works.. it's trying to write updates when we're destroying records, which causes the destroy to abort.

**Comment by robguthrie** [comment]
I best acknowledge both problems. Thanks for the feedback on the delayed delete. I'll remove it as I don't think it's necessary.

**Comment by robguthrie** [comment]
I've fixed both issues, deploying now. Thanks for the reporting @coopchange
