### ISSUE TITLE
@mentions malfunctioning - not getting a drop down (and maybe unable to tag people period?)

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#5190]
Earlier today I was unable to tag you @robguthrie ; only Chelsea Robinson would pop up. Now I'm not sure I can tag anyone (was trying to tag someone in subgroup of Enspiral)

_@gregorykan i think Michael mentioned you're off today but in case I'm mistaken..._

**Comment by robguthrie** [comment]
this has been fixed!
