### ISSUE TITLE
Can't get from proposal page to thread that gave rise to it

### ISSUE THREAD

**Issue by smoyth** [loomio/loomio#5199]
Is it just me, or is there no way to go from a proposal to the thread that it came out of?

The link must be there in the DB because if you go to the thread page, the proposal is listed there...

Is this an intentional design choice? My group has taken to always including the thread link in the proposal, but that seems hackish...

Thanks for such a great tool!

**Comment by smoyth** [comment]
UPDATE: A colleague showed me you can click on the thread title like this:

![image](https://user-images.githubusercontent.com/702320/52284773-13934400-2933-11e9-9b31-83e14d0f518d.png)

Can I suggest perhaps some kind of styling that shows the title is distinct from the group name? I tried clicking "that link" but it took me to our group page because I clicked 'sassafras' instead of 'qualified ...', because the styling makes it appear as one big link. Could do underline on hover maybe?

**Comment by robguthrie** [comment]
Thanks for the feedback. 

We're currently rewriting the client interface, and this breadcrumb will get clearer as a result. Additionally we'll soon be linking to polls within threads (with the thread page opened up in the right place) rather than linking to poll pages directly.
