### ISSUE TITLE
plugins.yml file doesn't exist by default, and doesn't accept gitlab

### ISSUE THREAD

**Issue by simonv3** [loomio/loomio#5200]
Hey!

So far we've been working with the plugins structure and it seems to be great! We've got a small [identity provider plugin](https://gitlab.com/dsausa/loomio-auth0/) written for Auth0 that works pretty well. 

We noticed though that the `plugins.yml` file - referenced in both the `lib/plugins/README.md` and in the documentation's how to write plugins - doesn't exist by default, should we just create it? Additionally we've noticed that this plugins file only accepts repositories on GitHub - is there something we're missing here that would let us fetch from Gitlab?

**Comment by robguthrie** [comment]
plugins.yml is unnecessary, the documentation is out of date. 

Generally we don't want to be using config files much, as it's not very 12 factor.

Loomio will load any plugins it finds in it's plugin folders, unless you've excluded them out via ENV with DISABLED_PLUGINS

So no, don't add a plugins.yml - it's the past.
