### ISSUE TITLE
Set up identity providers to be read from ENV variables

### ISSUE THREAD

**Issue by simonv3** [loomio/loomio#5203]
As noted here: 

https://github.com/loomio/loomio-deploy/issues/39#issuecomment-460795332

the providers in `config/providers.yml` should probably be moved to be read from an ENV variable rather than this list in a config file. 

It would probably be a case of switching this to load from the env rather than the yaml:

https://github.com/loomio/loomio/blob/7765b4ddb2cd96bb53aa373cc23c7fe239421b27/app/models/identities/base.rb#L10

**Comment by robguthrie** [comment]
closing as we have't done anything about it and are unlikely to
