### ISSUE TITLE
invite to subgroup not working

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#5211]
on /g/YMgAIeSm

group page loads without console error
click Invite to group
paste in email address... no response
remove last character of the address... it gives me the option to send to this (now incorrect) address
put the last character back in... no response

so rich@loomio.org doesn't work, but rich@loomio.or does.

**Comment by robguthrie** [comment]
Hi pal, thanks for the report.

Current theory: you're trying to invite someone already in the group, and the system is doing a bad job of explaining that.  Can you confirm the email you're adding isn't already a member?

**Comment by rdbartlett** [comment]
ah-hah, yep can confirm that behaviour.

**Comment by GriffGreen** [comment]
<img width="881" alt="screen shot 2019-02-23 at 6 29 49 pm" src="https://user-images.githubusercontent.com/14945613/53289808-3038d400-379b-11e9-9ae7-5be78af161a5.png">

This might not fit the original post but it definitely fits the title.

The Sharing link for the subgroup doesnt work

**Comment by GriffGreen** [comment]
The link came up after i invited someone

**Comment by robguthrie** [comment]
hi @GriffGreen - sorry for the delayed response. I've just fixed this error - thank you so much for reporting it!
