### ISSUE TITLE
Comment notification taking me to wrong thread position

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#5217]
Not sure precisely of the behaviour yet, but I have been confused by this a few times recently. 

Latest example, I got a notification that Michael replied to my comment. I click the notification, and it takes me to the wrong point in the thread, I needed to scroll back up the thread to find the right spot. 

I'm trying to debug this but I'm confused by the different url schemas. The notification links to https://www.loomio.org/d/7NoVU1rd/comment/1923293, but when I "copy link" on the comment I get https://www.loomio.org/d/7NoVU1rd/designing-a-new-marketing-website/46

**Comment by rdbartlett** [comment]
Many of the comment notifications are working correctly. I think this bug is happening when the notifying comment is in a subthread, and the parent comment has a bunch of top-level comments before and after it. I.e. when there are more comments on the page, sometimes it lands me in the wrong place.

**Comment by robguthrie** [comment]
We're going to leave this problem until new vue client is released. Thanks for reporting.
