### ISSUE TITLE
long press stolen- breaking tabbed browsing

### ISSUE THREAD

**Issue by QJKX** [loomio/loomio#5227]
Often I like to open links in the background in new tabs.

With Firefox on Android I do that by long pressing a link, which pops up a browser context menu, then choosing "Open Link in New Tab".

In loomio on the "Explore groups" page, long-pressing opens the link instead of yielding the browser context menu, so I can't open a group in a new (background) Tab.

Thank you for sharing your work as floss.

**Comment by robguthrie** [comment]
Thanks for reporting this too. Again this will be fixed with the move from Angular.js to Vue.js

Thanks for your help.
