### ISSUE TITLE
"Sign in to Loomio" doesn't scroll on Firefox on Android

### ISSUE THREAD

**Issue by QJKX** [loomio/loomio#5228]
Hi
On screens like "Sign in to Loomio" Firefox for Android (on mobile) covers half the screen with an on screen keyboard (as expected). The keyboard covers the submit button.
I would expect to be able to scroll the visible page with the keyboard remaining up with the usual swipe, but it doesn't work.

To log in it's necessary to close the keyboard which will confuse some users (I've never had to do that with any other site).

**Comment by robguthrie** [comment]
Thanks for reporting this. I can reproduce the problem on FF for iOS. We have not have not had bug reports from users about this, saying it's a critical problem, yet.

We're currently rewriting the Loomio client in a new front end framework which will probably remove this problematic behaviour altogether. Fingers crossed.
