### ISSUE TITLE
Time for a new release, maybe?

### ISSUE THREAD

**Issue by utkarsh2102** [loomio/loomio#5249]
Hey,

The last stable release (1.9.0) was out in June 2017 and the last patch update was out in March 2018. Since then, there have been more than 1530 commits to the project.
Perhaps, we could do a new release?
A minor release if not major?
Or a patch release if not minor?

**Comment by robguthrie** [comment]
Hi, thanks for asking. I had no idea people looked at the release version.

I guess we should make monthly releases and detail what has changed.

**Comment by utkarsh2102** [comment]
@robguthrie, yes, please.
That'd be great! :D
I am planning to package loomio for Debian repositories and it'll be great to have updated package there! :D
I am willing to help, if needed.
Let me know the same.

**Comment by robguthrie** [comment]
I do appreciate your support, but, I'm not so sure about a Debian package of Loomio. 

I don't think we have good processes to support people who setup systems based on the packages. For instance, database migrations or changes to the software stack (eg: when we added a redis server) would just break existing deb package based installations.

**Comment by utkarsh2102** [comment]
> I don't think we have good processes to support people who setup systems based on the packages. For instance, database migrations or changes to the software stack (eg: when we added a redis server) would just break existing deb package based installations.

Why d'you think it would break it?
We have been dealing with complicated packages like gitlab, diapsora, etc.
I think we can give it a shot, no? ;)

**Comment by utkarsh2102** [comment]
@robguthrie, I hope we can do a bi-monthly release or something now?  
If so, we can close this issue, too.  

Another thing, we could perhaps role out `Loomio 2.0.0`? Presently it is `1.9.0`.

**Comment by utkarsh2102** [comment]
Meaning, there are 499 commits since the last release.  
I think it's time for a release now?  
And if it looks sensible, you could perhaps roll out 2.0.0.

**Comment by robguthrie** [comment]
I think we'll roll out 2.0.0 when the vue client is formally released. I've made a new github release today. Is that what you're looking for?

**Comment by utkarsh2102** [comment]
Sweet, thanks! :D

**Comment by utkarsh2102** [comment]
@robguthrie, 780+ commits since the last release.
Could you please make a release asap, whenever possible?

**Comment by robguthrie** [comment]
@utkarsh2102 - They're mostly for the unreleased new client interface we're working on. I'll make a new release anyway.

**Comment by utkarsh2102** [comment]
@robguthrie, a lot of dependencies were bumped since the last release.  
Thus need a new release to sync that up. Would be great if you could do that asap.

**Comment by robguthrie** [comment]
Thanks for explaining. Done.

**Comment by utkarsh2102** [comment]
Great, thanks :D
