### ISSUE TITLE
minor formatting bug on Invite To Group form

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#5260]
I started a new group, then the Invitation modal opens immediately. Just noticed the formatting on the bottom of this form is a bit weird, extra margin created by this empty element called `<md-dialog-actions>`

![image](https://user-images.githubusercontent.com/970124/54109706-ab2afd00-43df-11e9-9635-3c4a07117dbb.png)

**Comment by robguthrie** [comment]
fix it. thanks pal
