### ISSUE TITLE
Unable to edit context

### ISSUE THREAD

**Issue by eduard-k** [loomio/loomio#5261]
We use the free trial version of Loomio with a limit of 5 threads. All 5 threads are already created. 

When I try to edit the context of the existing thread, a message appears.
<img width="511" alt="2019-03-11 17 47 28" src="https://user-images.githubusercontent.com/7514378/54137706-ca994880-4426-11e9-9962-05a5f3a60239.png">

Is this the bug or the context can't be edited in the free version?

**Comment by robguthrie** [comment]
Oooh! it's a bug - Thanks for reporting it. Fix on it's way.
