### ISSUE TITLE
Unable to invite to standalone polls

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#5265]
I'm setting up a standalone meeting poll and I'm unable to invite anyone to it :(

![Captura de pantalla 2019-03-13 a la(s) 8 10 46 p  m](https://user-images.githubusercontent.com/750477/54259917-31a43200-45cc-11e9-8fdb-0062116599ee.png)
![Captura de pantalla 2019-03-13 a la(s) 8 10 53 p  m](https://user-images.githubusercontent.com/750477/54259918-31a43200-45cc-11e9-92dc-ccc22f1abfbf.png)
![Captura de pantalla 2019-03-13 a la(s) 8 11 35 p  m](https://user-images.githubusercontent.com/750477/54259919-31a43200-45cc-11e9-80c8-708a10daa1a0.png)

**Comment by robguthrie** [comment]
Yikes. I fix it and add an e2e tomorrow. Thanks for reporting

**Comment by robguthrie** [comment]
This is fixed now. Thanks for the report. Sorry for the delay.
