### ISSUE TITLE
Package Loomio for Debian?

### ISSUE THREAD

**Issue by utkarsh2102** [loomio/loomio#5283]
Hey,

There are a good number of people using and loving this software.
Why not package it and ship it as a package in Debian?
There are more than 51k packages available there, already. A lot of FOSS enthusiasts are already using Debian and it'd be a great idea to have this software packaged there. Because why not? :D

**Comment by robguthrie** [comment]
I'm concerned that OS provided packages tend to fail to provide a good experience for software such as Loomio for the following reasons:

- Loomio is dependent upon many pieces of software and this set of dependencies will grow. Docker-compose makes this seamless. OS packages tend to be out of date and unsupported by upstream.
- Running a successful Loomio server requires smooth upgrades of all the software at once, regularly.
- I personally provide user support to people running Loomio via the docker based system, I would not be willing to support people with OS provided packages as I don't use them myself. If we never had the packages then they would not have to waste that time using an unsupported installation method.

The existing loomio-deploy repo provides full instructions for how to manage and maintain a server, an os provided set of packages would not provide such documentation.

How you install Loomio should be really well documented and provide adequate support. I've seen people lose their group data from a poorly maintained loomio server before, and I don't want to see that happen again.

I really appreciate that you're trying to help, thank you, but I wonder if you realize how much this project changes and the requirements that puts on a package maintainer.

**Comment by utkarsh2102** [comment]
Hi @robguthrie,

> Loomio is dependent upon many pieces of software and this set of dependencies will grow. Docker-compose makes this seamless.

I heartily understand that. We, at Debian, package every dependency separately. If any of these dependencies grow, we'll update it separately, as per the upstream codebase :)

> OS packages tend to be out of date and unsupported by upstream.

We, at Debian, try to keep up with everything. However, there comes a time when some of the  dependencies are not maintained anymore. In such a case, we `embed` that particular dependency inside the main package. In this case, it'd be Loomio. So that the main package runs smoothly as it should, without any problem.

> Running a successful Loomio server requires smooth upgrades of all the software at once, regularly.

Agreed. This is with every other application. There might be, say a bug fix or a security update in the upstream, then we update the package as per the upstream codebase.

> I would not be willing to support people with OS provided packages as I don't use them myself.

This is fairly a valid point. Thus, we, at Debian, are here to help and take this forward.
I am a user of Loomio and a Debian Maintainer. I, along with some other Maintainers and Developers, are going to take care of the package with the best possible way and thus want to take this forward.

> The existing loomio-deploy repo provides full instructions for how to manage and maintain a server, an os provided set of packages would not provide such documentation.

Well, we, being developers, understand how hard it gets to work with any application/software without the availability of the proper documentation. Thus, after Loomio is successfully packaged, we could perhaps write the documentation of the for the same :D 

> I wonder if you realize how much this project changes and the requirements that puts on a package maintainer.

I do. Hence, we, as a team, are willing to take this forward. Few Debian Developers and contributors will be working on packaging this software. We, sometimes, might need help from y'all in fixing some tests, etc. I hope you'd be available for the same? And thus we all could successfully package this to Debian? :D

**Comment by robguthrie** [comment]
Ok thanks for the thoughtful reply. Let's give it a go.

I might need some help or suggestions about how to properly version manage this repo to support your downstream work.

**Comment by utkarsh2102** [comment]
That's great to hear, @robguthrie :D 

For a visual representation, I'm attaching the workflow we'll follow:

![Loomio](https://user-images.githubusercontent.com/31288318/55366175-2ece9a00-5505-11e9-8e2f-a5edd06b0dcf.png)


As shown, we'll be completing this in three phases.
- The first phase would be to package all it's dependencies and sub-dependencies separately, for better maintainance ahead. We'll be needing help there, in maintaing compatibility of the gem versions.
- The second phase would be to package Loomio and make a clean package out of it (won't be installation, but would build fine) and to write a maintainer's script for configuration and maintainance of Loomio and to ensure it's smooth installation in the third phase.
- The third phase would be to integrate the script, bridge the left over stuff and finally fix the test failures (if any) and thus making it installable on Debian machines.

Let me know what you think about the same?

**Comment by robguthrie** [comment]
Oh geee! I just worry that I'm going to break this and I won't want to take any responsibility for that, but also I will not want people to be left in the lurch. 

Our dependencies change regularly. The tiptap branch (for example) is an entire rewrite of the frontend, during the beta period there are two package.json's, one for the (stable) Angular.JS client and one for the (beta) Vue.js based client.

We also have a plugin system which people use to change words/phrases and functionality within the app. The only documented way to run a plugin on a production server is with docker-compose. 

We also have great documentation and default configuration files for ENV's etc. How will those be managed?

In the future, I plan on changing the plugin system to adopt Rails Engines, which would actually make your job simpler, as each plugin looks like a gem from that point on.. but it's another example of change, and how it's nice to be able to know that I can support people running production instances if they follow the officially supported system, but I'm probably going to upset people not doing that. 

If someone wants to run Loomio, then I fear that making the packaging preference for debian a priority over the developer supported option of docker-compose would be a regretable prioritization - and anyone with strong OS preferences would be better running from source/git rather than using packages anyway. 

I've used linux distros for a huge chunk of my life, and I have to strongly believe that big applications like Loomio are much better distributed as containers, and packages are better for little apps.

A couple of other questions:
- Will these packages depend upon postgresql, redis etc too? 
- Does debian provide packages for ruby gems and node modules too? do you intend to use those?

I have supreme respect for your willingness and enthusiasm to do this, but I also don't want users to have a bad time when the project changes at the speed of my development but the packages don't keep up or migrate well. Also if people come asking for support and I say that I'm only supporting docker-compose based servers, will that be ok?

With much kindness and thanks for reading,
Rob

**Comment by utkarsh2102** [comment]
> I just worry that I'm going to break this and I won't want to take any responsibility for that.

I understand. Don't worry, let's give it a shot, no? :D
We've been dealing with complex packages, like diaspora, gitlab, etc, for a while now.

> Our dependencies change regularly. The tiptap branch (for example, which today has been merged into master) is an entire rewrite of the frontend, during the beta period there are two package.json's, one for the (stable) Angular.JS client and one for the (beta) Vue.js based client.

We'll look for stable releases and keep updating the package as per the upstream changes.
We might have to package a few new modules or gems or might even drop the existing ones, but that is fine. We've been doing that for a while. I'd say, if we have people to take that up, then why not try it as well? :D

> We also have great documentation and default configuration files for ENV's etc.

Configurations are often done with the help of the maintainer's script. And as for the documentation, I plan on including it and even write one for the package as well, after completing the packaging, though.

> If someone wants to run Loomio, then I fear that making the packaging preference for debian a priority over the developer supported option of docker-compose would be a regretable prioritization.

Let's just say you don't have to.
You could keep providing support for `docker-compose` as you've been doing.
Alternatively, we try to get Loomio available as a separate Debian package, too. Don't make it official yet, maybe? If that's what you want?

> Will these packages depend upon postgresql, redis etc too?

If needed, sure! Many packages depend upon postgres and redis. Adding them is not a problem at all.

> Does debian provide packages for ruby gems and node modules too? do you intend to use those?

Yes, a good amount of gems and modules are provided by Debian. I maintain a few of them myself. You can check the packages I maintain [here](https://qa.debian.org/developer.php?login=guptautkarsh2102@gmail.com). Moreover, to get a complete list of gems maintained under the Ruby team, check [this](https://qa.debian.org/developer.php?email=pkg-ruby-extras-maintainers%40lists.alioth.debian.org) and to get a complete list of modules maintained under the JavaScript team, check [this](https://qa.debian.org/developer.php?email=pkg-javascript-devel%40lists.alioth.debian.org).
We, at Debian, maintain all these packages and keep them updated as and when needed/required.
A lot of packages are added and removed, depending upon the requirements and the needs.

> I have supreme respect for your willingness and enthusiasm to do this, but I also don't want users to have a bad time when the project changes at the speed of my development but the packages don't keep up or migrate well.

Again, you could keep providing the support for `docker-compose`, officially. And on the other hand, we try to get this in the apt repositories in the best possible shape. Don't make it official, if you're not that sure? Let's say it's more of an experiment, not hindering your project in any way.

> Also if people come asking for support and I say that I'm only supporting docker-compose based servers, will that be ok?

Yes, that is perfectly fine! :D

**Comment by robguthrie** [comment]
Hi, Ok with all of this understood - I'm happy and grateful for you to proceed. Thanks for being so enthusiastic about Loomio.

**Comment by pravi** [comment]
Hi @robguthrie just adding some comments. We maintain gitlab in debian and they have monthly releases and security updates for 3 months (how often loomio gets a new feature release and how long do you provide security support? I guess not faster than gitlab). We are currently on latest security release 10.8.9 on debian unstable. You are right, it is not fit for the existing distro models, we are trying hard to change that to have fast paced apps with more relaxed rules. This is still a work in progress. As for dependencies, we sometimes do embed dependencies if we can't package them natively and even do a direct npm/yarn install. In gitlab, we embed rails 5.1 as debian already moved to rails 5.2 and the entire node modules are pulled via yarn install. Though we still want to package them natively, but that does not stop us from giving updated packages to our users. We are able to provide smooth upgrade experience with gitlab and I hope we can do the same for loomio as well. See https://tracker.debian.org/gitlab for how frequent we update gitlab package and how good our response to security issues are.

**Comment by pravi** [comment]
Just to add, we have been running git.fosscommunity.in for many years on debian packages. Though well supported version have to be pushed through a personal repo outside debian, we hope to integrate this with debian some day (big changes take a long time to happen officially). See https://wiki.debian.org/gitlab for the documentation.

**Comment by pravi** [comment]
Debian Popularity Contest (it is opt-in so does not show the actual figures) shows 79 users for gitlab https://qa.debian.org/popcon.php?package=gitlab

**Comment by robguthrie** [comment]
Righto, thanks for the update!
