### ISSUE TITLE
e-mail notification username translation missing

### ISSUE THREAD

**Issue by bennlich** [loomio/loomio#5285]
![Screenshot from 2019-03-31 23-22-45](https://user-images.githubusercontent.com/704368/55307430-5f7ed880-540c-11e9-96e2-8c05306d7fa4.png)
This only appears to be a problem in the e-mail notification. When I load the thread in the web app, the user's name renders correctly.

Thanks for all that you do :)

**Comment by robguthrie** [comment]
Thanks for reporting. That's no good. I'll look into it now. What's your loomio username?

**Comment by robguthrie** [comment]
Has this happened on any other emails? Have you had many?

It's really hard for me to understand how this is possible.

**Comment by bennlich** [comment]
I've never noticed it before, but this might have been the first time they've commented on a thread I'm on.

3 hours after the post above, I received a second notification, this time with the correct username. I'm not sure if they changed their username in the interim. Here's the user page: https://www.loomio.org/u/mux

I'll cc them and see if they have any ideas.

**Comment by bennlich** [comment]
I asked him and he said his name was set to "Translation missing" in his profile. He was somehow able to reset his name, which fixed the issue.

**Comment by robguthrie** [comment]
he said his name was set to Translation missing? Wow.

This has to be the strangest bug report I've seen in a long time. 

Could you please forward the original buggy email to me? rob at loomio org

Thank you.
