### ISSUE TITLE
Home page translation trouble in español

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#5307]
<img width="1012" alt="Captura de pantalla 2019-04-05 a la(s) 14 55 44" src="https://user-images.githubusercontent.com/750477/55599240-429f2800-57b3-11e9-8647-deb80b376d12.png">

Taking off the 'w-150' class seemed to make it a bit better...

**Comment by robguthrie** [comment]
thanks for reporting this. fixed now
