### ISSUE TITLE
Thread members not live-updating

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#5310]
In a comment in a thread in a subgroup, I at-mention a member of the main group. I then check the Thread Members panel, but their name does not turn up there — until I refresh the page.

**Comment by scw248** [comment]
Hi @mhjb, has anyone tackled this issue yet?

**Comment by robguthrie** [comment]
hi @scw248 - nobody has taken this on yet, however we probably won't fix it because we're working on a new front end client which is nearly ready for beta testing.

**Comment by scw248** [comment]
Hi @robguthrie, no problem.  Just thought I'd ask, but thank you for letting me know!
