### ISSUE TITLE
Showing users 'last online' time in anonymous voting leaks identity

### ISSUE THREAD

**Issue by ana0** [loomio/loomio#5347]
Loomio ui shows the 'last online' time of a user and also the time of a vote, meaning anonymous votes can be de-anonymized by close attention to when they come in.

**Comment by robguthrie** [comment]
Thanks for reporting this. The last online time is the time when a user last loaded their user interface/refreshed an app page. I'm not sure what action we'll take about this right now.

**Comment by robguthrie** [comment]
Thanks for bringing this up. 
I've removed last seen at from the information we share to users for now.
