### ISSUE TITLE
Recent change in client build script breaks deploy with docker-compose

### ISSUE THREAD

**Issue by ludat** [loomio/loomio#5362]
Now when the client builds it tries to `rm -rf public/client` and that may not be possible if that directory is mounted by docker (which is the case in [loomio-deploy](https://github.com/loomio/loomio-deploy/blob/master/docker-compose.yml#L41)), since this directory can't be build starting de app fails completely.

This is the commit  where this change was applied https://github.com/loomio/loomio/commit/c985f81d26125e3ac5cb1f62c0ddc7ec08815a54#diff-a467a6afd3a8d709d11779a090ba5249R6

I don't know the internals of loomio enough to make a PR but if you point me in the right direction I can make the change and create a PR.

Thanks for creating such a wonderful product :smiley:

**Comment by robguthrie** [comment]
Hello, thanks for the heads up. I've changed the rm line to be `rm -rf public/client/*` which should resolve the problem I reckon.

Sorry for the hassle, and thank you so much for using and contributing to Loomio!

**Comment by ludat** [comment]
yep, I think that should solve it, thanks for the quick response :smile:
