### ISSUE TITLE
loomio not working on Chromium

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#5372]
I get blank screen (below address bar) and inspector shows: https://www.dropbox.com/s/qx9ue6wj5bvtfq9/Screenshot%20from%202019-04-18%2010-34-13.png?dl=0

anything I should try (cache etc)? @robguthrie

**Comment by robguthrie** [comment]
yes, please try hard refresh, shift + refresh

**Comment by robguthrie** [comment]
John did hard refresh help?

**Comment by coopchange** [comment]
Yes looks good now. Everything seems to be functioning fine though FWIW/FYI I do see this come up in the inspector as I load pages:

> dashboard:1 Error while trying to use the following icon from the Manifest: https://www.loomio.org/ (Download error or resource isn't a valid image)
