### ISSUE TITLE
Comment replies no longer loading after forking

### ISSUE THREAD

**Issue by aerugo** [loomio/loomio#5431]
I forked a whole bunch of comments out of a conversation into a new thread.
Some of these were in threads. After the forking, many of the nested comments could no longer be loaded. See this thread: https://talk.theborderland.se/d/L2FfYGlM/comment/13757

**Comment by aerugo** [comment]
Ok, I fixed this particular thread now through the console. Turns out that not all discussion_id's had been updated. Running this fixed the problem:

`
d = Discussion.find('L2FfYGlM')
Event.where(discussion_id: d.id).each {|e| e.children.each { |c| c.update(discussion_id: d.id) }}
`

Some bug is hiding in the fork code though. My guess is that it might not update the discussion_id for children that are hidden when you do the fork.

**Comment by robguthrie** [comment]
I'm thrilled you we're able to fix it! Nice job.

I wonder if the fork process took too long and rack-timeout killed it..
