### ISSUE TITLE
New messages not shown in Inbox?

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#5504]
I received some email notifications about new replies to my comment. I didn't open the emails. I went to the Unread Threads page on Loomio. I see I have Loomio notifications that match the email notifications, but the Loomio inbox doesn't have those threads marked as unread:

![image](https://user-images.githubusercontent.com/970124/58535337-0524ad00-81ee-11e9-9a05-488d4cceacf4.png)

**Comment by robguthrie** [comment]
not applicable for loomio 2.0
