### ISSUE TITLE
"__ has requested to join..." but then no requesrt

### ISSUE THREAD

**Issue by jonschull** [loomio/loomio#5559]
Lately I've been getting membership requests in my email.  

When I click on View Request "there are no pending requests".  (Also the requester is not listed among members, so I know they haven't been approved by someone else).

I inquired about this in the forum and got no response.

**Comment by robguthrie** [comment]
That's a real mystery to me. Nothing in the previous requests list either? Is this on loomio.org? If so, email contact@loomio.org with your group url and I'll look into it.
