### ISSUE TITLE
Fails to load on openSUSE Firefox 66.0.3

### ISSUE THREAD

**Issue by lynxlynxlynx** [loomio/loomio#5577]
This is a tumbleweed machine, so for a while I just ignored that loomio stopped working, since I don't need it often and it still works fine on a different linux machine. The symptoms have been there for about a year, so if it's a regression, it's not recent.

I cleared the cookies and forced a refresh, but it still doesn't load. The console has these warnings and errors:

> Loading failed for the <script> with source “https://www.loomio.org/client/1.8.759/angular.bundle.min.js”. dashboard:42:1
> Loading failed for the <script> with source “https://hello.loomio.io/js/”. dashboard:1:1
> **Failed** to load ‘https://hello.loomio.io/js/’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.
> Service worker event waitUntil() was passed a promise that rejected with 'TypeError: Cache got basic response with bad **status 404** while trying to add request https://www.loomio.org/client/1.8.748/angular.min.css'.

Manually opening those urls of course works. From the network tab I can see the unrendered response is that I don't have js enabled, which is of course not true and likely just a consequence of the missing files. Of addons I only have Privacy badger, but also on the working machine. Either way, whitelisting loomio.org didn't change anything.

Trivially reproducible for me at https://www.loomio.org/dashboard.
https://www.loomio.org itself loads (only fails angular.min.css), but that's not useful, since login immediately redirects to the first.

**Comment by robguthrie** [comment]
no way to reproduce this and no other reports of errors, closing for now. thank you
