### ISSUE TITLE
User-completion is invertedly case-sensitive

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#5698]
I just tried to compose a message by writing "I think @Rob…" and then stopped, because Loomio (2.0 beta 75) told me there were no matching users.
![Screenshot_2019-08-05 Loomio](https://user-images.githubusercontent.com/195073/62437307-c1729480-b796-11e9-8d2d-27434c26b1dc.png)
I was confused. And only after I tried "@rob…", then it would offer the user "Rob…".
![Screenshot_2019-08-05 Loomio(1)](https://user-images.githubusercontent.com/195073/62437334-d6e7be80-b796-11e9-9335-6c9c618d1548.png)
I think that the matching should be case-insensitive, but definitely not "reverse-sensitive", i.e. having to type lower-case to match an upper-case name.

**Comment by robguthrie** [comment]
I just saw these issues come through yesterday. I had no idea you had been posting them! Sorry!
Going to go through and address them all today. 

We've been doing this work [within Loomio](https://www.loomio.org/d/xOocrpB1), which gives us the dog-fooding experience and is (IMO) more fun, but I'm happy work in here too.

Thanks for reporting this. Fix being deployed now (landing in v263).
