### ISSUE TITLE
Unread notifications count and item highlighting

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#5722]
I just opened Loomio to see that I have (2) notifications, because a "2" was displayed in a blue circle on top of the bell.

As soon as I clicked the bell, however, the 2 went away, and I was left with a list of notifications that all looked the same, i.e. the 2 unread ones were not visually distinguishable from the previously read ones:

![image](https://user-images.githubusercontent.com/195073/62496872-63918b80-b82e-11e9-81db-d4b7aa9e100f.png)

It would be really nice if the (2) stayed, and the actually unread notifications were highlighted, e.g. using a blue (or whatever) background. I think Github does this.

And then, when I read one item in there, the (2) should become a (1), and two items should remain visually distinguishable, like in this mockup, after I just read the second item in the list.

![image](https://user-images.githubusercontent.com/195073/62497552-70af7a00-b830-11e9-9727-ed369705371d.png)

**Comment by robguthrie** [comment]
I think the behaviour has improved. The notification (2) goes away on click, but the unread notifications will be highlighted until you close the dropdown.
