### ISSUE TITLE
What about ActivityPub / Federation?

### ISSUE THREAD

**Issue by 360fun** [loomio/loomio#5785]
would be interesting consider to federate **Loomio** through [ActivityPub](https://the-federation.info/protocol/activitypub) to the [Fediverse network](https://fediverse.network/)? 😄  🌳 

PS
like **MoodleNet** and other projects are doing: [watchlist-for-activitypub-apps](https://gitlab.com/fediverse/fediverse.gitlab.io/wikis/watchlist-for-activitypub-apps)

**Comment by robguthrie** [comment]
maybe this can happen one day, we'll need to convert to uuids but that's not impossible. until then, closing this issue

**Comment by 360fun** [comment]
😻

**Comment by aschrijver** [comment]
**FYI**: I just [described a vision](https://meta.discourse.org/t/132624/40?u=aschrijver) for Discourse as-if it were built from the ground up with federation support, called **"Community has no boundary"** and which would turn Discourse from a stand-alone product into Discourse-as-a-Fabric. It may be inspiring to **loomio** to consider these possibilities too. Also adopting a compatible federation design would allow `loomio <----> discourse` community integration.

I've also posted this comment to **forem** who have an open AP issue: https://github.com/forem/forem/issues/317#issuecomment-752359165

**Comment by RokeJulianLockhart** [comment]
https://github.com/loomio/loomio/issues/9527#issue-1584741757
