### ISSUE TITLE
Doesn't list invited people

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#5839]
I just started a thread on Loomio 2 beta 155, and invited a couple of people. Now I see no record of these invitations anywhere. Given similar tools I've used in the past, I expected to see a list of invited people under "Participants", visually separated so as to make it obvious that they have not joined yet. As it is, I have no way to verify that the invitations have been cast, and nothing prevents me from re-inviting the same people, which probably spams them…

**Comment by robguthrie** [comment]
sorted now.
