### ISSUE TITLE
<button title=""> not properly expanded

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#5840]
At least the `<button>`s underneath thread summaries and posts don't get their `title` HTML attributes expanded properly, e.g.:

```
<button type="button" class="v-btn v-btn--flat v-btn--icon v-btn--round theme--light v-size--default action-dock__button--edit_tags" title="$t(action.name || 'action_dock.' + name)">
```

The `$t(action.name || 'action_dock.' + name)` in there is shown verbatim in the tooltip when hovering over any of the buttons.

**Comment by robguthrie** [comment]
fixed in next release. Thank you.
