### ISSUE TITLE
Read counter disagrees with empty inbox

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#5849]
(I saw #1805 and #3093 and #3127, but since they are all years old, I decided to create a new issue, also as this applies to Loomio 2 beta 164)

See screenshot: the inbox is said to be empty, but there's an unread counter on the unread threads.

![image](https://user-images.githubusercontent.com/195073/64480880-d377a500-d224-11e9-845d-10be5d32afa2.png)

**Comment by robguthrie** [comment]
I think this is all fixed now
