### ISSUE TITLE
User mention highlights break text character kerning/flow

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#5851]
This is surely a low priority issue, but if you look at the following screenshot:

> ![image](https://user-images.githubusercontent.com/195073/64496331-02128000-d2f8-11e9-8fd1-7aaf88bb5504.png)

then you will notice how there's unnecessary (and arguably wrong) space between the end of the name I'm mentioning, and the comma to follow.

Is the padding needed? Is the background highlight even needed? Wouldn't just a different text colour do just fine?

**Comment by madduck** [comment]
Just noticed that the same applies to inline code snippets \`using backquotes\`, which is the `same on Github`, actually. I personally think just using a monospace font without a background highlight would be better.

Maybe this issue is instead a call for an alternate stylesheet? I'll write the stylesheet if you provide the UI to select it :)

**Comment by robguthrie** [comment]
I've simplified the styles on mentions and code blocks. Thank you!
