### ISSUE TITLE
Add a "Compact display" user preference

### ISSUE THREAD

**Issue by mgodlewski** [loomio/loomio#5976]
The actual display is user friendly but doesn't allow a view on large set of subjects / replies.

It could be great to propose a "compact display" as a user preference to get more subjects / replies displayed on a screen.

**Comment by robguthrie** [comment]
Yea, agree. Also, I'm not much of a fan of double line list items used as the main list, so I'd like to try uncomplecting it on desktop. Next time we go around that block we'll also include batch selection for actions.

**Comment by robguthrie** [comment]
we won't be doing this. Thanks anyway
