### ISSUE TITLE
Messages posted by slack bot include HTML Tags

### ISSUE THREAD

**Issue by outsmartin** [loomio/loomio#6055]
Hi,

all our messages posted to slack include html tags inside of the description.

Example:

```
</p><p>One interesting approach I found is shown in the article below:</p><p><a href="https://startupandrew.com/posts/how-firebase-interviewed-software-engineers/" target="_blank">https://startupandrew.com/posts/how-firebase-interviewed-software-engineers/</a> </p>
```
Expected:

Clickable link? and No `<p>` tags surrounding the text.
We are using the dockerized version of loomio. 

Thank you very much for the efforts!

**Comment by robguthrie** [comment]
Oh, thanks so much for reporting this problem! We'll get around to sorting it out shortly

**Comment by robguthrie** [comment]
I think this has been fixed! https://github.com/loomio/loomio/commit/2a907f5af12f214155b081ce267cb3527cdaf5a3
