### ISSUE TITLE
Ability to pin sidebar doesn't work anymore

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#6061]
I had my sidebar pinned ever since I started using Loomio 2. Today, I played around a bit and unpinned it. Since then, I cannot get it to repin. Hitting that button has no effect, and the sidebar will remain hidden behind the burger menu.
![image](https://user-images.githubusercontent.com/195073/68467741-9f981a80-027b-11ea-92ac-f5db07e208aa.png)

**Comment by robguthrie** [comment]
I wonder if this is happening just when your browser window is not big
enough. Can you confirm the window is maximised?

**Comment by madduck** [comment]
Indeed! I just decreased the font size, and now it's pinned again, although now I also cannot discern any difference between pinned and unpinned, i.e. I cannot unpin it.

**Comment by robguthrie** [comment]
we've sorted this out too
