### ISSUE TITLE
Comments display intermittent in Loomio 2.0

### ISSUE THREAD

**Issue by strypey** [loomio/loomio#6084]
As mentioned in [this comment in the Loomio 2.0 bugs thread](https://www.loomio.org/d/xOocrpB1/loomio-2-0-report-bugs-and-issues-here/609), comment threads are sometimes not displaying for me. For example, I clicked on a notification to see the reply by @robguthrie to my other comment there (about the problem with the 'notify users' pop-up), I got a page with the Context Box, but no comments. Navigating to another page, and then clicking the back button, I can now see Robert's reply.

I'm looking at Loomio.org using Firefox 68.0.2 64-bit (ABrowser distribution), on Ubuntu 16.04 64-bit (Trisquel 8.0 distribution).

**Comment by robguthrie** [comment]
I've done a lot of work on the thread render over the last 2 days. Could you please re test this bug for me? thank you.

**Comment by robguthrie** [comment]
I think this is fixed. If you find otherwise, feel free to re open it.

**Comment by strypey** [comment]
On 2019-11-20 22:10, Robert Guthrie wrote:
> I've done a lot of work on the thread render over the last 2 days.
> Could you please re test this bug for me? thank you.

I haven't struck this again since you said on the Loomio bugs thread
that you thought it was fixed.  Great work! As I said there, I'll let
you know if I strike it again :)
