### ISSUE TITLE
bug: opening a second proposal clones the first proposal

### ISSUE THREAD

**Issue by igor47** [loomio/loomio#6105]
to reproduce:
1. start a thread
1. create a proposal -- i gave my test one the title `proposal 1` and details section `details 1`
1. create another proposal -- it will have "details" section auto-set to `details 1`, but will have a blank title
1. add a title to the second proposal (`proposal 2`), and edit the details to be `details 2`
1. click `start` -- the second proposal will be created with title `proposal 1` and details `details 1`
1. you can do it again; the third proposal will have `details` set to `details 2`, but if you click `start` the end result is again `proposal 1` and `details 1`

i did this in our loomio group, here: https://www.loomio.org/d/mYLJiPrx/test-thread-please-ignore if that helps debugging. my browser is firefox 70 on osx mojave.

this looks like a JS error; looking at the network console the `POST` request seems to be incorrect (this post should have had `proposal 4` and `details 4`):
<img width="535" alt="Screen Shot 2019-11-26 at 5 05 26 PM" src="https://user-images.githubusercontent.com/200575/69684873-16505880-106f-11ea-857c-d5e2ef61ad95.png">

**Comment by robguthrie** [comment]
are you on loomio 1.0 or loomio 2.0? (does the app boot with a orange
loomio logo in the center or a blank screen?)
This sounds like a known bug with the old js client.

**Comment by igor47** [comment]
loomio 2.0.34

**Comment by robguthrie** [comment]
Thanks for taking the time to report this to us! I've been able to reproduce the issue and have a fix on the way.

**Comment by robguthrie** [comment]
fixed now
