### ISSUE TITLE
Docker start script failing on old jobs:work command

### ISSUE THREAD

**Issue by pjsier** [loomio/loomio#6134]
While trying to run the `docker-compose` setup in the loomio-deploy repo I ran into the following error:

```
loomio-worker  | rake aborted!
loomio-worker  | Don't know how to build task 'jobs:work' (See the list of available tasks with `rake --tasks`)
loomio-worker  | /usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
loomio-worker  | /usr/local/bin/bundle:30:in `block in <main>'
loomio-worker  | /usr/local/bin/bundle:22:in `<main>'
loomio-worker  | (See full trace by running task with --trace)
```

It looks like the `jobs:work` rake task was recently replaced with Sidekiq, but docker_start.sh hasn't been updated yet. I'm happy to put in a PR for this if it would be helpful, thanks!

**Comment by robguthrie** [comment]
Hi thanks for noting this, I've just pushed the fix to master. Running sidekiq rather than jobs:work now.
