### ISSUE TITLE
Raw HTML and Markdown strings in explore page group descriptions

### ISSUE THREAD

**Issue by pjsier** [loomio/loomio#6140]
Possible duplicate of #3033, but on the current explore page it looks like multiple group descriptions are displaying as raw HTML or Markdown strings:

<img width="519" alt="Screen Shot 2019-12-09 at 9 30 32 AM" src="https://user-images.githubusercontent.com/8291663/70448945-bee6bb00-1a66-11ea-80dd-f5e88039c9a0.png">

<img width="520" alt="Screen Shot 2019-12-09 at 9 30 39 AM" src="https://user-images.githubusercontent.com/8291663/70448957-c27a4200-1a66-11ea-9163-f5f9a23678dc.png">

It looks like this was initially fixed in #3801, but might have been lost in later changes. If you want to address it the same way as in that PR I'm interested in putting in a PR that checks `discussion_format` and sanitizes the input based on whether it's HTML or Markdown

**Comment by robguthrie** [comment]
Hi @pjsier your offer of making a PR sounds great. Please go ahead if you wish. Thank you!
