### ISSUE TITLE
attachment button is not visible in small screen

### ISSUE THREAD

**Issue by pravi** [loomio/loomio#6182]
![loomio-mobile-portrait](https://user-images.githubusercontent.com/708222/71617604-d9353400-2be1-11ea-9b28-05ea3894f7eb.png)

Works in landscape mode but it is not intuitive

![loomio-mobile-ladscape](https://user-images.githubusercontent.com/708222/71617669-1b5e7580-2be2-11ea-8f7b-e10a8cbd1f3b.png)

The remaining options should come on the next line instead of getting cut.

**Comment by robguthrie** [comment]
Thanks for your feedback. We'll move the attachment icon more to the left as it's more important, and on small screens move the other buttons into a drop down menu.

**Comment by robguthrie** [comment]
Will be sorting this issue out in the next couple of days. Re open if I'm a liar.
