### ISSUE TITLE
Show polls where my vote is still missing

### ISSUE THREAD

**Issue by erdmenchen** [loomio/loomio#6222]
I tried Loomio in the free trial and very much like, what it does and how it works.
However after a bit of use, I am missing a filter for the current open polls, where my vote is still missing.

I want to see a list of open polls, where my vote is still missing, so that I can reach theses faster.
Currently I can filter polls only status (open/closed) and the various types.

Maybe it would be enough to just mark the polls, where I already voted, so that they are more distinktive from the polls, where my vote is still missing.

Or just add the filter option "Not voted yet" to the status drop down.

**Comment by robguthrie** [comment]
Hi @erdmenchen Thanks for the feedback!

There is an icon on the bottom corner of proposals which says if you have voted or not, but this is not present on other poll types.

I think your idea is good and I'll see if we can implement that in the dropdown, and extend the icon to all polltypes.

**Comment by robguthrie** [comment]
we have a filter for "needs vote" now!
