### ISSUE TITLE
Sent to wrong place in thread on loading

### ISSUE THREAD

**Issue by aerugo** [loomio/loomio#6239]
In long threads, the 2.0 Vue client sometimes drops you off at the wrong place when you've clicked a notification. This is a bit hard to reproduce consistently, but what happens is:

* Get a notification for a new reply in a long thread and click it
* Get sent to the thread 
* First you will see the comment you came for but as the thread completes being rendered, your view of the thread is pushed around so that you end up somewhere else
* When you try to find the comment you came for again, the highlighting has faded so you no longer know what the new comment was

This has been reported by a few people, [like here](https://talk.theborderland.se/d/QsP3rJc0/public-beta-of-loomio-2-0-now-on-talk-/77).

**Comment by robguthrie** [comment]
Thanks for letting me know, I'll see what I can do to improve things.

**Comment by robguthrie** [comment]
We have updated this so that it should land in the right place after loading has finished more often than before.. however a better fix is still in the works (and I mean, it's actually being worked on)

**Comment by robguthrie** [comment]
Plus, we've improved load times, so the effect will be less severe.

**Comment by robguthrie** [comment]
this does not happen much, if ever now. also we have another thread page in the works which will never do it, by design.
