### ISSUE TITLE
adding option to a poll is broken

### ISSUE THREAD

**Issue by igor47** [loomio/loomio#6258]
i click "add another option" on a poll, and get the pop-up with options listed and the chance to enter my new option.

i enter a new option, and push enter. the UI claims my option has been added, but it does not appear among the other options in the poll.

in the console, the error:
```
NotFoundError: Node was not found chunk-vendors.0565af58.js:25
    hide index.ts:123
    r helpers.js:71
```

**Comment by robguthrie** [comment]
@gregorykan can you please look into this one? Thank you

**Comment by gregorykan** [comment]
Hi @igor47,

I've tried this myself and have been unable to reproduce this problem. Would you mind sending an email to contact@loomio.org with a link to the particular discussion/poll?

Thanks!
