### ISSUE TITLE
[feature request] Edit source in markdown editor

### ISSUE THREAD

**Issue by EliotBerriot** [loomio/loomio#6260]
## What is the issue I'm facing?

The new UI of Loomio is shipped with a new WYSIWYG markdown editor.

While I tend to dislike WYSIWYG editors because they sometimes have an unexpected behaviour when you want to perform advanced (or not so advanced) text edition, I understand this is mostly a matter of personal preference, so this is not what I want to discuss here.

However, being a heavy Loomio user for more than a year, there is one crucial things I was able to do with the previous editor I cannot do now. As part of my workflow, I do a lot of collaborative edition on CodiMD (an online markdown editor). When the writing/review process is done, I used to copy-paste the markdown text in a Loomio post for publication and voilà!

This is not working anymore, as shown on the video below. My understanding is that the new editor interprets the markup as it's copy-pasted, yielding unpredictable results, and removing most of the structure (e.g titles and tables).

The only workaround I found was to copy the source as HTML and paste it in Loomio's `contenteditable` tag in the editor, which is slow, error prone, and inaccessible to most people.

## Demo of the issue

![loomio-copy-paste](https://user-images.githubusercontent.com/1970915/73435780-946bfc80-4349-11ea-88f3-f95587eae368.gif)

## What is my suggested solution?

I'd like to have a "see/edit source" button in the editor toolbar. Cliking on this button would switch the editor in a different mode, and let you edit the markdown source directly, without any rendering.

This would solve the specific issue  I have (copy-pasting markdown content from a third-party source), but also help with other annoying issues, when one of the the WYSIWYG editor bugs prevent you from doing something (editing a link, or code block, quote, etc).

It would also give an easy way to copy a message or a part of a message from Loomio to somewhere else.

This is not strictly required, but it would be a nice bonus if the editor could remember what mode it's in, so I don't have to switch it for every new comment or thread. I really don't need the preview.

Thank you for your consideration, let me know if I can clarify anything.

**Comment by robguthrie** [comment]
I'm happy to provide a markdown mode for the editor. The wysiwyg mode is actually HTML, and supports features markdown does not, but conversion between the two formats is possible, and we can indeed add a MD button that gives you such an experience.

This just comes down to prioritization

**Comment by robguthrie** [comment]
@EliotBerriot I've made a start on this feature.. i'll keep pushing it along when I have the motivation

**Comment by robguthrie** [comment]
done!
