### ISSUE TITLE
Time poll would be easier with days displayed

### ISSUE THREAD

**Issue by jnicho02** [loomio/loomio#6277]
When participating in a time poll it is a pain to only see the date and not the day of the week.

<img width="699" alt="Screenshot 2020-02-04 at 2 06 41 pm" src="https://user-images.githubusercontent.com/83251/73751733-9c67da00-4757-11ea-8788-70371c34518b.png">

...or did I miss a setting somewhere?

**Comment by robguthrie** [comment]
Thanks for saying so..  I'll add something soon

**Comment by robguthrie** [comment]
I've updated this just now:
<img width="328" alt="image" src="https://user-images.githubusercontent.com/486367/79504800-89428600-8087-11ea-8fef-09fc86f26878.png">

Thanks for your feedback and patience!
