### ISSUE TITLE
Are "delete thread" actions soft deletes? Any option to permanently delete?

### ISSUE THREAD

**Issue by chmac** [loomio/loomio#6369]
I'm looking at some GDPR compliance stuff and trying to remove some content from a Loomio site. I've had a quick look at the code and I see this:

https://github.com/loomio/loomio/blob/8bb8463ca39c0d643db2e015e28b51be8803362c/vue/src/shared/services/thread_service.coffee#L175-L189

Plus this commit:

https://github.com/loomio/loomio/commit/e02a1e8b1e18ab520ca52f2b14416bbf6e43d5a2

And I'm guessing that Loomio uses a soft-delete approach, maybe even [this one](https://github.com/jhawthorn/discard). First question, is it true that threads are soft deleted in Loomio?

Second question, is there anything that would assist with GDPR compliance in 100% removing a user's data?

**Comment by robguthrie** [comment]
It's soft delete (for ui responsiveness) then immediate real delete as a background job:
https://github.com/loomio/loomio/blob/master/app/services/discussion_service.rb#L13

Users can delete their own accounts and it will remove all personally identifying data.
