### ISSUE TITLE
url simplified with the group name

### ISSUE THREAD

**Issue by Meldane** [loomio/loomio#6382]
Hi,

First of all, thanks for your work on Loomio, that's a great tool.

I try to encourage as many groups and associations to use Loomio, but one of the main difficulty is to **not be able to have a memorable homepage for the group**.

I use Framavox.org servers and the homepage will be something like that www.framavox.org/g/xyXXZZxyx123xix
It would make such a difference if it could be www.framavox.org/nameofthegroup or www.framavox.org/chosenshortername

Then we could advertise the url as the main website address for the group...

**Is it something that could be possible to implement in the future ?**

**Comment by robguthrie** [comment]
That's is a feature we currently have. It's called the group handle.

https://help.loomio.org/en/user_manual/groups/settings/#group-handle
