### ISSUE TITLE
feature request: hide votes until poll closes

### ISSUE THREAD

**Issue by igor47** [loomio/loomio#6402]
we want to vote on something (like a candidate who is applying for a position) where we are hoping to get everyone's opinion, unbiased by the group consensus. however, if we open a poll, those voting later can see the votes of those who voted earlier, which might bias them.

would be great if one of the options when opening a poll, like the option to make votes anonymous, was to hide votes until the poll closes. i thought about "until when you vote" but you still have the ability to change your vote.

**Comment by robguthrie** [comment]
Thanks for getting in touch, I agree, this would be a really useful feature to have, and we'll be working on it in the coming months, stay tuned. I'll update this issue when there is news.

**Comment by robguthrie** [comment]
we have this feature! I'm not sure quite when we added it, but a good long while ago now.
Cheers!
