### ISSUE TITLE
Login not possible. Bug on the website?

### ISSUE THREAD

**Issue by aschrijver** [loomio/loomio#6511]
I tried logging in by email both on Android and Linux (Ubuntu 18.04) and the 'Create Account' button is dysfunctional.. it does nothing. Both times I tried this using the latest version of Firefox for these respective platforms.

**Comment by robguthrie** [comment]
Hi Arnold,

Is this on your own host, or on loomio.org?

If your own host, can you check the docker-compose logs? It's likely an
email issue.

**Comment by aschrijver** [comment]
It is on Loomio..

**Comment by aschrijver** [comment]
There was another issue from mobile - maybe related - where, if you the login popup (cross on right-hand side) then you get to the UI for logged in users (so without actually having logged in). When clicking Profile on the menu - logically - a stuck load screen is all what happens in the main menu.

![Screenshot_20200426-151149_Firefox](https://user-images.githubusercontent.com/5111931/80321139-11105900-881b-11ea-82f7-2e79526870c1.jpg)

**Comment by robguthrie** [comment]
Yes, I have a fix in the works for the sidebar issue. Should be sorted early next week.

However I'm still shocked to hear that you are having create account issues! This is a nightmare inducing scenario for me!.. It could be the Google Captcha though.. do you have blockers running?

**Comment by aschrijver** [comment]
Oh, I must be really stupid, because I forgot my Privacy Badger and uBlock Origin I have active at both places. Sorry for that 😳 but they just never give me trouble and thus are out of my sight.

Disabling both, and I am now logged in. Now to figure out which cookie to enable. There are maybe too many of them on Loomio I kindly suggest (am very strict with them on my system, and as admin of [Humane Tech Community](https://community.humanetech
com) also not a fan + avoiding tech monopolies, like Google, as much as I possibly can).

**Comment by robguthrie** [comment]
There is a cloudflare cookie and a loomio session cookie. You only need
those to use Loomio without issue, after you have an account.

The CAPTCHA is only necessary for account creation. It's a necessary evil
for us, unfortunately.

**Comment by aschrijver** [comment]
Thank you! I came upon another good captcha provider the other day via Hacker News. Commercial company, but more privacy-focused and not an ads moloch.

https://www.hcaptcha.com/

It was actually Cloudflare that made the switch to it. See: https://news.ycombinator.com/item?id=22812509

**Comment by robguthrie** [comment]
Oh, cool. Looks interesting!
