### ISSUE TITLE
Improvement: versioning, mainly for the docker images

### ISSUE THREAD

**Issue by kbcasagrande** [loomio/loomio#6522]
We use dockerized loomio/loomio, but pointing direct to a given image digest(e.g. loomio/loomio@sha256:ebc62647ef230799d9226f8ed0816574ab075b23c5dc2fb7153bc651730248cb) due to the absence of numbered versions and because using for example the tag stable we wouldn't know actually which code version would be running; There's also the possibility of breaking changes being introduced into the stable image tag that we'd note only in case it breaks our loomio stack;

So what I suggest is loomio to apply the release versions also for docker image tagging;

**Comment by robguthrie** [comment]
Thanks for your patience on this, as you've suggested, we're introducing semantic versioning and automatically building docker releases from this from now, beginning with v2.1.10.

**Comment by kbcasagrande** [comment]
Thanks so much @robguthrie !
