### ISSUE TITLE
Unable to log out in Chrome

### ISSUE THREAD

**Issue by alanna** [loomio/loomio#6551]
[Here's a screen capture](https://i.gyazo.com/2e53a4bf84c7f982c865519c0b48db7c.mp4) 

It just takes me back to my logged in dashboard. I tried disabling ad blocker and everything but no change. Version 81.0.4044.138 on Mac.

This is all I see on console:
![Screen Shot 2020-05-18 at 2 39 15 PM](https://user-images.githubusercontent.com/5498878/82169376-6a007800-9915-11ea-9a40-5f337788a315.png)

I was able to log out with Firefox.

**Comment by robguthrie** [comment]
Sorry about this. 

There has been some changes in how we store cookies. I've done my best to make sure we can backwards compatibly remove cookies stored in the old format, but there are a few situations where I can't fix the issue and this is one of them.

I believe if you delete all cookies for *.loomio.org within chrome, next time you login, you'll be able to log out.

Here is a video for how to do this, without deleting other cookies

https://www.loom.com/share/69c27537cad24313870c4cc0f8519cf8
