### ISSUE TITLE
Clicking on profile photos in daily email gives 404s

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#6555]
![image](https://user-images.githubusercontent.com/1380991/82268361-ebfaaa80-99c2-11ea-8f8e-dc6b0e00acc2.png)

(fwiw: I don't actually want to go to the user's profile anyway, but to their comment)

**Comment by robguthrie** [comment]
thanks for reporting this

**Comment by robguthrie** [comment]
have removed link for user avatar in mailers
