### ISSUE TITLE
Dark theme, theming

### ISSUE THREAD

**Issue by koalp** [loomio/loomio#6571]
I think it would be nice to be able to have a dark color scheme for loomio.

And it may be even better if it follow the new [prefers-color-scheme css media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) to take into account to the user's browser preference.

**Comment by robguthrie** [comment]
This is in the works, but paused while I fix bugs and work on higher priority issues.

**Comment by robguthrie** [comment]
Dark mode has been in Loomio for a while now. Thanks
