### ISSUE TITLE
"not yet invited" showing as "-1" people

### ISSUE THREAD

**Issue by alanna** [loomio/loomio#6575]
<img width="594" alt="Screen Shot 2020-05-25 at 11 48 26 AM" src="https://user-images.githubusercontent.com/5498878/82767795-417cfe80-9e7e-11ea-94a4-1ae253c1fd1a.png">

This seems odd to me but maybe I just don't understand what it's supposed to indicate?

**Comment by robguthrie** [comment]
It's a bug, thanks for reporting it. I'll its on the to-fix list

**Comment by robguthrie** [comment]
replaced with new notificaiton stuff now.
