### ISSUE TITLE
Condorcet method poll

### ISSUE THREAD

**Issue by alanpoulain** [loomio/loomio#6612]
Today there is the ranked choice poll to make a good democratic decision.
The [Condorcet method](https://en.wikipedia.org/wiki/Condorcet_method) is an alternative to this method.
The voting stays the same, only the counting method changes.
It could be great to have an option to enable it for the ranked choice poll.

**Comment by BakedCrossiant** [comment]
maybe [Schulze method](https://en.wikipedia.org/wiki/Schulze_method) instead?

**Comment by robguthrie** [comment]
We'll consider this if there is sponsored development, or someone contributes the code. Closing this issue for now.
