### ISSUE TITLE
"x of y have voted" vs. "seen by z" confusion

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#6617]
![image](https://user-images.githubusercontent.com/195073/83742420-7f172e00-a6ad-11ea-9812-d7c887daec84.png)
The thread has been seen by 6, but only 2 *out of 3* have voted. Out of which 3? Why not out of 6?

**Comment by robguthrie** [comment]
The total number of voters is the number of people you invite to vote. You can see who has been invited to vote on the poll page.

**Comment by madduck** [comment]
This makes no sense to me, sorry. I did not invite anyone to the poll itself. I did invite 7 people to the thread, and by now, all 7 have seen the thread. I had added the poll shortly after starting the thread, and correlating the seen timestamps, that was before anyone saw the thread.

I did not specifically invite anyone to the poll, let alone 3 people. I can only assume that those 3 people are the 2 who have voted already, plus myself, who has not yet voted.

Why would people who were invited to the thread (including one usually sitting next to you) see the thread, but not vote, or not be counted towards the total number?

**Comment by robguthrie** [comment]
Your feedback recently has been helpful.

Yep, you're right about how the count comes to be.

It's not the final state of things, we're moving towards a model where you subscribe to a thread and that group of people will automatically get votes generated for polls started. This work also touches on the other stuff you have raised recently.

**Comment by robguthrie** [comment]
this is all much better now. closing
