### ISSUE TITLE
Enable admin-editing of comments

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#6629]
With email-to-thread sending signatures to Loomio threads, but probably also in other use cases, it would be very useful for admins/moderators to be able to edit others' posts to remove these extra lines, in an effort to keep the discussions clean. Please consider making this possible.

**Comment by robguthrie** [comment]
Thanks for the request, it's quite easy and will slide it into the jobs stack near the top.

- Group setting for "admins can edit other user's comments"
- Show edit function for admins in dropdown
- Add editor to the Revision History panel.

**Comment by robguthrie** [comment]
Happening with #6641

**Comment by robguthrie** [comment]
this is done
