### ISSUE TITLE
After selecting a tag, all tags appear highlighted

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#6630]
Without any tags selected, the "all" item appears highlighted:
![image](https://user-images.githubusercontent.com/195073/84227185-d434c300-ab37-11ea-8cb4-be6411cefba5.png)

If I selected the "meta" tag, then all tags (including "all") seem to be highlighted:
![image](https://user-images.githubusercontent.com/195073/84227132-b9624e80-ab37-11ea-898b-641b591bf9e6.png)

**Comment by gregorykan** [comment]
Thanks Martin! I'm deploying a fix for this now.

cc: @robguthrie
