### ISSUE TITLE
Ability to fold sub-threads

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#6631]
Every now and then, participants of thread go off on a tangent. I am aware that I can delete these tangents, or move them to a thread of their own. However, sometimes that just isn't appropriate. Sometimes what would be better would be to "fold" those subthreads such that they don't occupy vertical screen estate by default, but users can still easily expand their placeholder to check out what happened "beneath".

This should at least be available to admins and thread owners, but I actually don't see a reason why normal participants shouldn't be able to do this.

**Comment by robguthrie** [comment]
You can fold threads now.
