### ISSUE TITLE
Option to disable the ability to create polls without threads

### ISSUE THREAD

**Issue by leoluk** [loomio/loomio#6645]
Is there a way to prevent the creation of "loose" polls that aren't tied to a thread?

We always want threads such that proposals can be discussed and the current UX is confusing to new members.

**Comment by robguthrie** [comment]
Hi @leoluk, if we, rather than adding another group setting ("allow stand alone polls" or similar), how about we just make an "Add poll to thread" function.

How does that sound?

**Comment by robguthrie** [comment]
yes, you can start polls without threads now.
