### ISSUE TITLE
Add sign-in link to 'not permitted' screen

### ISSUE THREAD

**Issue by alanna** [loomio/loomio#6646]
![Screen Shot 2020-06-15 at 9 57 57 AM](https://user-images.githubusercontent.com/5498878/84605102-d491dd00-aeee-11ea-8c27-d7762445ed11.png)

This screen tells me to sign in, but doesn't have a link for me to do so. I figured out how to get out of here and go sign in, but I could imagine some users getting stuck. I got here by clicking a link to a thread from an email notification.

**Comment by robguthrie** [comment]
Alanna, can you email me a link where this is happening for you? Thank you!

**Comment by alanna** [comment]
Sorry I can't get it to do it again now... :/

When I went back and did it again it reloaded the page fine and I was signed in.

**Comment by robguthrie** [comment]
We've made changes that I'm confident will have fixed this issue now. Thanks for reporting it Alanna.
