### ISSUE TITLE
Reactions to thread are nowhere visible

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#6663]
I was just told that someone reacted thumbs-up to my thread, but as you can see from the screenshot, the reaction is not actually shown. It's also not behind the notifications list. I even logged out and back in, but it's just not visible.
![image](https://user-images.githubusercontent.com/195073/85189777-039cba00-b306-11ea-9940-4917e5991146.png)

**Comment by robguthrie** [comment]
this is fixed now. thanks for reporting it
