### ISSUE TITLE
No response to reports of critical security issues

### ISSUE THREAD

**Issue by leoluk** [loomio/loomio#6665]
Is contact@loomio.org the correct contact address to report security issues to?

Members of our organization have reported two separate, critical security issues and haven't received a response, so we want to make sure they didn't get lost in a spam filter.

**Comment by robguthrie** [comment]
Hi Leo, yes it is, we're working on a response right now. Thank you

**Comment by leoluk** [comment]
Thanks! Feel free to delete this issue
