### ISSUE TITLE
Missing thread

### ISSUE THREAD

**Issue by alanna** [loomio/loomio#6710]
I was looking for the "June 2020 board meeting" thread, but it does not appear on the list of threads in the subgroup:
![Screen Shot 2020-07-03 at 11 41 35 AM](https://user-images.githubusercontent.com/5498878/86417838-5d4bae00-bd22-11ea-92bf-34034f24e883.png)

However, when I search for it, it does come up:
![Screen Shot 2020-07-03 at 11 41 25 AM](https://user-images.githubusercontent.com/5498878/86417872-748a9b80-bd22-11ea-8970-4d3ccc78527f.png)

**Comment by robguthrie** [comment]
thanks for reporting this, I'll look into it shortly

**Comment by robguthrie** [comment]
Hi Alanna,

From what I can see.. The thread you're looking for is actually kept in the other board group, but search is confusing because it shows results from any subgroup.

**Comment by alanna** [comment]
As you can see in the screenshot, there is a June meeting thread in each of the two groups. The subgroup name is under the thread name in the search results there. But when you look at the list of OSC board subgroup threads, it's not listed. The URL is https://www.loomio.org/d/CnFPxIS6/june-2020-board-meeting.

**Comment by gregorykan** [comment]
Hey again @alanna 

Finally figured it out lol. That thread is CLOSED! If you filter by "closed" (to the left of the search box), you'll see it there.

Hmm might be useful to indicate the thread status in the search results...

cc: @robguthrie

**Comment by alanna** [comment]
Ahhhhh thank you! That explains it.

>
