### ISSUE TITLE
Closed time poll does not display results nor a "view results" button

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#6746]
<img width="773" alt="image" src="https://user-images.githubusercontent.com/18379380/87356431-2abd7300-c5b6-11ea-8d64-9206f083de71.png">
@robguthrie

**Comment by robguthrie** [comment]
Thanks John. Just a friendly reminder that URL's are always appreciated along with screenshots. Even if you email them to me direclty.

**Comment by robguthrie** [comment]
I'm unable to reproduce/see the problem, @coopchange. The poll in question is displaying the outcome and results for me.
