### ISSUE TITLE
Log in to Firefox Loomio pulls up my user account but with no groups associated

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#6748]
It's very strange; I'll show you in the office tomorrow, but basically it looks like a user account with no groups nor threads nor polls... "Welcome! You are not a member of any groups yet..."

In my /profile everything looks as I would expect it.

Has happened to me twice
- one time i tried to go to loomio.org/admin on my phone, it prompted me to log in, and i got that behaviour
- more recently I was successfully using loomio in firefox, and then (within some 24-48 hours) I tried to jump back in but i was logged out; logged in twice (from a direct link to a group, and then from loomio.org) and still couldn't find any groups

@robguthrie @gregorykan

**Comment by robguthrie** [comment]
issue seems to be local browser bug fixed by restarting firefox
