### ISSUE TITLE
Bad string in email notification subject

### ISSUE THREAD

**Issue by alanna** [loomio/loomio#6760]
I closed a proposal and set an outcome, and the email came through looking like this:

<img width="947" alt="Screen Shot 2020-07-20 at 11 46 55 AM" src="https://user-images.githubusercontent.com/5498878/87888134-e2eb8f80-ca7e-11ea-9de6-6ef133621c0a.png">

The rest of the email was fine.

**Comment by robguthrie** [comment]
Thanks for reporting this, deploying a fix now.
