### ISSUE TITLE
Bigger editor area

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#6763]
Loomio is a place to aggregate information and knowledge to aid teams to make decisions. Having rich formatting available, as well as inline images and tables is great for this.

I find it at odds with this that the `textarea` input field for a thread's context, as well as comments to a thread are essentially 2 lines only:
![image](https://user-images.githubusercontent.com/195073/87997690-e6981880-cb49-11ea-907e-7fa92ce9688a.png)
The field will grow as you enter newlines, but just seeing the small vertical space strikes me as uninviting, and impedes my creative juices, to the point that I usually start with just hitting enter a few times to create the space I need to think and pour meaning into words.

It's the same with comments to a thread.

Would it be possible to make the context field maximum vertical size from the start, and add a few lines to the comments fields?

**Comment by robguthrie** [comment]
Does not apply any more. Edit grows to content size, and you can open edit screens in new tabs.
