### ISSUE TITLE
Open thread not updated with replies

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#6771]
I have a thread open and was just told about a reply by email, but I cannot see the reply until after I reload Loomio. Could replies/updates be pushed to the page DOM?

**Comment by robguthrie** [comment]
Pages should indeed be live updated, sometimes the websocket connection
drops and does not resume.. noted and will look into it.

**Comment by robguthrie** [comment]
Thanks for the push on this, I've done a quick review of message_bus vs ActionCable, and am switching out our current live update system (ActionCable) for message_bus, I expect this will make reconnection (and sync) much more reliable. Should be live next week, and then hopefully we'll have a good foudation for a more realtime, reliable app.

**Comment by robguthrie** [comment]
fixed
