### ISSUE TITLE
Search broken on Firefox

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#6772]
Literally anything I search (in, say, loomio.org/enspiral) returns "No results" even after hard refresh.

@robguthrie

**Comment by robguthrie** [comment]
Yikes. Thanks for reporting it.. deploying fix now

**Comment by peicheng87** [comment]
I tried searching in Chinese, search result also seemed to be broken.
Some Chinese words were tested: "紓壓", "唱歌", "衣服". I'm sure these words should be in some threads, but search result was empty.

**Comment by naresh97** [comment]
Still an issue for me, tested on:
- Firefox 85.0 on Ubuntu 20.04
- Firefox 84.0.2 on Windows 10

Tested on my own Docker deployment, as well as on https://www.loomio.org/explore

The groups briefly flash, before the disappear, showing no results.

**Comment by phleba** [comment]
> Still an issue for me, tested on:
> 
>     * Firefox 85.0 on Ubuntu 20.04
> 
>     * Firefox 84.0.2 on Windows 10
> 
> 
> Tested on my own Docker deployment, as well as on https://www.loomio.org/explore
> 
> The groups briefly flash, before the disappear, showing no results.

I have the same issue, with Firefox under Linux, Android and Chromium under Linux. Navigating to my instance or https://www.loomio.org/explore briefly shows all (?) public (?) groups, then quickly forwards to https://www.loomio.org/explore?order=memberships_count where nothing is shown and searching does not work. E.g. searching for the existing group "Loomio Community" returns only the prompt 
"Can't find the group you're looking for? If a group's privacy is set to 'secret', it won't appear here."

**Comment by coopchange** [comment]
I wasn't getting _no_ results, but I was having trouble searching for a thread "[Reporting back from Activation Calls](https://www.loomio.org/d/6hdiJcQF/reporting-back-from-activation-calls)" on Android Firefox – tried both "Reporting" and "Activation" from the[ relevant parent group](https://loomio.org/loomio-cooperative) with no luck
