### ISSUE TITLE
no voting on proposal is unfinished, improve or remove

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#6796]

**Comment by coopchange** [comment]
Moved this off of ## Under consideration (in Product Roadmap doc)

**Comment by robguthrie** [comment]
Hi @scroll, I'm pleased you found it useful! Thanks for saying so.

There was something about it which seemed to fail to meet expectations. I would like to bring it back in some form, as a "Request for questions and feedback" is such a useful stage of proposal creation.

I think the biggest problem was people seeing the proposal, but then there was no "call to action", it felt unfinished and confusing. Maybe we need to explain the state of the proposal and that comments and feedback are requested

**Comment by robguthrie** [comment]
No voting is removed, finally. Templates provides a better UX.
