### ISSUE TITLE
Time Poll meeting durations dont have any affect AFAIK and 90min isn't available

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#6809]
from Zero Waste Europe:
> i'm creating a time poll and I cannot choose a time slot length of 90 mins? It either has to be 1 or 2 hours, is there anyway around this?
https://support.loomio.org/scp/tickets.php?id=7328

from me:
I don't think there's any practical way that this duration selection shows up? Maybe it does in the outcome?

**Comment by coopchange** [comment]
Oops @robguthrie I also meant to bring up this one alongside the other timepoll things

**Comment by coopchange** [comment]
that last bit that is,
> I don't think there's any practical way that this duration selection shows up? Maybe it does in the outcome?

**Comment by robguthrie** [comment]
sorted now
