### ISSUE TITLE
thread rendering - thread doesn't load

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#6830]
I've seen this a couple of times with this same thread so I'll just bump it here (i think it was formerly documented in 2.0-bugs-loomio-thread)

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/18379380/89834528-24231b00-dbb7-11ea-9a29-6eb19c2fafb5.png">

This is the Wellington Office thread in Loomio Co-operative group

**Comment by robguthrie** [comment]
fix on the way with new thread renderer
