### ISSUE TITLE
Export poll broken

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#6865]
@robguthrie I'm getting really weird export from the most recent check poll in this thread: https://www.loomio.org/d/eOJgZqV5/this-august-omg-we-re-enspiraling-generously-online-monthly-gatherings-final-tuesdays

please export and compare; Anne-Marie, for example, checked yes but the export doesn't make that clear/ makes it seem not the case

**Comment by robguthrie** [comment]
i think export is ok now. thanks anyway.
