### ISSUE TITLE
Semi-urgent: Starter thread is missing link to 5 ways to use threads

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#6888]
@robguthrie just saw that there's some issue with the starter thread, which is supposed to link the text "5 ways to use threads" to the article help.loomio.org/en/guides/5_ways_to_use_threads/

interestingly, when i go to edit that thread it's in markdown and – editing it in markdown – it won't seem to take the link for some reason (see  screencaps:

_I open the editor and add the text_
<img width="1006" alt="Screen Shot 2020-08-28 at 1 01 53 PM" src="https://user-images.githubusercontent.com/18379380/91513786-45b32f00-e939-11ea-94dc-56360ad3dbd6.png">

_Here it's having some error in the preview; when I save it I see the same thing, ie, the markdown doesnt convert to an embedded ilnk_
<img width="1007" alt="Screen Shot 2020-08-28 at 1 01 44 PM" src="https://user-images.githubusercontent.com/18379380/91513833-64b1c100-e939-11ea-9d1b-d3252767b75f.png">

**Comment by coopchange** [comment]
@robguthrie to clarify, currently the starter thread is just missing that link (as far as i can see)

**Comment by robguthrie** [comment]
deploying fix now, thanks for reporting it
