### ISSUE TITLE
Collaborative editing: A couple issues today on FF

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#6901]
I'll leave them as comments on this ticket, with time stamps of the screenshots denoted in case things have changed

**Comment by coopchange** [comment]
my name tag appears twice:
Screen Shot 2020-09-04 at 11.15.16 AM
<img width="584" alt="Screen Shot 2020-09-04 at 11 15 16 AM" src="https://user-images.githubusercontent.com/18379380/92196825-45c8a700-eec4-11ea-98ad-418cb4ea7177.png">

**Comment by coopchange** [comment]
Hard to see the text behind someone's name (I didn't manage to get a screenshot of this, I guess)

**Comment by coopchange** [comment]
@robguthrie similar to the first comment, but additional behaviour – when i draft a reply it drafts a comment at the same time; probably no surprise that posting the reply and returning to the page my comment (the same text I posted as reply) is saved

**Comment by robguthrie** [comment]
thanks, keep em coming

**Comment by coopchange** [comment]
comments (or, at least, replies) I've already posted are saved as draft comments, and now with folded comments it takes some checking to see if I actually posted it or not
cc @robguthrie

**Comment by robguthrie** [comment]
@coopchange I don't understand, sorry. Either record or show me when I'm in the office today?

**Comment by coopchange** [comment]
Couldn't reproduce; will try to capture if I find it again (latter-most bug that is)

**Comment by coopchange** [comment]
Reproduced the last bug i documented here, I've already (clearly) posted this reply, I refreshed and then the text is still in the reply box:
2020-09-09 at 7:11pm
<img width="1391" alt="Screen Shot 2020-09-09 at 7 11 01 PM" src="https://user-images.githubusercontent.com/18379380/92667449-11d80080-f360-11ea-911d-d5d4347e072f.png">

**Comment by coopchange** [comment]
you probably already caught this but the screencap helpful (date: 09-07 at 8.59.25 PM)

<img width="671" alt="Screen Shot 2020-09-07 at 8 59 25 PM" src="https://user-images.githubusercontent.com/18379380/92667880-4c8e6880-f361-11ea-8117-889cdff6bdbc.png">


related to a former issue noted in this channel ([this comment](https://github.com/loomio/loomio/issues/6901#issuecomment-686882588)), here I'm typing reply and comment being typed on as well

**Comment by coopchange** [comment]
Another instance of the reply i just posted showing up as saved draft, in case it adds any helpful error messages/ clues/ etc (again, may be related to #6926)
<img width="1374" alt="Screen Shot 2020-10-09 at 8 45 03 AM" src="https://user-images.githubusercontent.com/18379380/95707813-0e190000-0cb7-11eb-865c-b6af0b003768.png">

**Comment by robguthrie** [comment]
thanks, good to see, will sweep these issues up next week.
