### ISSUE TITLE
Formatting tools hiding the comment form on mobile

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#6905]
Android, FF, beta enabled
![Screenshot_20200904-155054](https://user-images.githubusercontent.com/18379380/92335475-5018ba00-f0eb-11ea-8ddd-b5ad27f0dda1.png)
![Screenshot_20200904-155035](https://user-images.githubusercontent.com/18379380/92335479-573fc800-f0eb-11ea-8381-5b8d2a4e9174.png)

**Comment by robguthrie** [comment]
Hi John. this is why the collapse (<) button exists. I don't really have
another solution.
