### ISSUE TITLE
[beta thread renderer] pinned item from dropdown doesn't work

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#6912]
https://www.loomio.org/s/jGAmNiWe
<img width="791" alt="Screen Shot 2020-09-09 at 10 09 36 AM" src="https://user-images.githubusercontent.com/18379380/92532550-a2411300-f284-11ea-8bfa-de20c2e591c9.png">

same thing happens clicking either of the pinned items from the dropdown in this thread ^

**Comment by robguthrie** [comment]
yes, it's just not done yet, thanks for making an issue, but maybe just one thread on beta feedback? it's changing so quickly and I'm aware of lots of it.

**Comment by robguthrie** [comment]
actually, if you're happy to do a thread per thing, then be my guest
