### ISSUE TITLE
reply form hidden on FF (desktop)

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#6920]
It may be unclear to user how to reply as they only see the formatting buttons and not sure the collapse button brings it the distance... maybe just something to listen for though as I remember this isn't an easy one from your reply to same-similar issue for mobile, #6905 

09-09 at 11.43.47 AM

<img width="921" alt="Screen Shot 2020-09-09 at 11 43 47 AM" src="https://user-images.githubusercontent.com/18379380/92667630-8d39b200-f360-11ea-90b4-75f35babe799.png">

<img width="935" alt="Screen Shot 2020-09-09 at 11 43 57 AM" src="https://user-images.githubusercontent.com/18379380/92667621-8a3ec180-f360-11ea-9ec7-35345c7dcbdb.png">

**Comment by robguthrie** [comment]
fixed
