### ISSUE TITLE
[thread renderer] applying a link leaves the link form open and empty

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#6938]
in this screenshot, the link has just successfully been applied but the modal looks like it failed, ie, when i escape from the modal the hyperlink was successful,
![Screenshot from 2020-09-15 12-13-19](https://user-images.githubusercontent.com/18379380/93150580-acb05080-f74d-11ea-893c-f19797da7982.png)

**Comment by robguthrie** [comment]
resolved now. thanks
