### ISSUE TITLE
'Add time slot' didn't fire it the first time i clicked it for 9:30 option

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#6941]
![Screenshot from 2020-09-11 11-00-57](https://user-images.githubusercontent.com/18379380/93153203-dc168b80-f754-11ea-9c0d-9c552777c67b.png)

error log:
![Screenshot from 2020-09-11 11-01-03](https://user-images.githubusercontent.com/18379380/93153218-e6d12080-f754-11ea-97af-c6efecba396d.png)

**Comment by robguthrie** [comment]
fixed
