### ISSUE TITLE
subgroup tick boxes are not working

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#6944]
I reproduced user's issue, the one I just cc'd you into, (or at least a similar bug) by inviting my demo-account to two subgroups at the same time, from a subgroup.

1. I invited my john@loomio.org account to Demo > [Test 1](https://www.loomio.org/demo-test1/) and Demo > [Test 2](https://www.loomio.org/g/xqOGTtJK/members) from the Invite modal of Test 1 subgroup
 - john@loomio.org already was member of Demo
2. john@loomio.org received invitation for Test 1 but not Test 2

**Comment by coopchange** [comment]
Leon's issue: https://support.loomio.org/scp/tickets.php?id=7857

**Comment by robguthrie** [comment]
this is fixed now
