### ISSUE TITLE
Anonymous voting - Vote creator can see who voted or not

### ISSUE THREAD

**Issue by JeffLeFoll** [loomio/loomio#6949]
Hello, 

When creating an anonymous vote, the creator of the vote can still see who voted or not via the notification tab because the notification displaying "Anonymous participated in : ..." is displayed with the profile picture of the person who just participate.

In the notification tab, the profile picture should be replaced by an anonymous place holder.

**Comment by robguthrie** [comment]
yikes, I'll sort that out. thank you

**Comment by robguthrie** [comment]
ok this has been fixed for past data and now in the future too. Thanks for letting me know. My apologies for this!

**Comment by JeffLeFoll** [comment]
Awesome ! Thank you very much !
