### ISSUE TITLE
[collab editing] thread context changes will not save (but remain saved as draft when i reopen editor)

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#6950]
https://www.loomio.org/s/9LhA1pTk
https://www.loom.com/share/79caadd9f43f4f0188a7359e32cdb5bd

^ I have another more extensive video reproducing the first time I encountered it, but I think you'll find it really fast to reproduce (here's that link anyways: https://www.loom.com/share/d411baf3e5d24fdcb66bf5978802b253?t=45)

**Comment by robguthrie** [comment]
fixed
