### ISSUE TITLE
[collab editing] several words disappeared after ???

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#6975]
Sorry I don't have more 'reproduce this' notes, but I do think I've experienced it twice at this stage. TBH I think I was typing, paused for a second without changing the focus or clicking etc., and then two words ("ora koutou") disappeared... _maaybe I hit enter for a line break or two but yeah sorry don't remember._

Here's what my console read:

<img width="1320" alt="Screen Shot 2020-09-29 at 2 39 15 PM" src="https://user-images.githubusercontent.com/18379380/94504052-60443500-0264-11eb-9bba-be332d7c1a6b.png">

**Comment by robguthrie** [comment]
closing collab editor stuff, we're not looking at this level of detail yet, thank you though
