### ISSUE TITLE
[collab editing] momentary lapse of being able to edit a thread (socket connecting stall (out)) and loss of content

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#6976]
@gregorykan saw this happen live... maybe you already fixed it Greg?

<img width="1306" alt="Screen Shot 2020-09-29 at 10 50 48 AM" src="https://user-images.githubusercontent.com/18379380/94504203-bb762780-0264-11eb-9dfa-544b6281efcf.png">

I saved it, and I believe Greg you did too, but several bullets were lost when I got back to the thread (and maybe some more error messages of use... was hard refreshing along the journey to this from the first time I had issue of double-cursor (see #6977) saved and returned to the thread, went back into edit but socket didn't connect, and then this following screenshot was reloading the thread at that point)

<img width="1331" alt="Screen Shot 2020-09-29 at 10 51 08 AM" src="https://user-images.githubusercontent.com/18379380/94504308-f4ae9780-0264-11eb-9202-d47a80a47218.png">

**Comment by robguthrie** [comment]
closing collab editor stuff, we're not looking at this level of detail yet, thank you though
