### ISSUE TITLE
[collab editing] I suddenly appear twice, and my text cursor starts moving around

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#6977]
<img width="1324" alt="Screen Shot 2020-09-29 at 10 48 50 AM" src="https://user-images.githubusercontent.com/18379380/94504103-8538a800-0264-11eb-8e7e-e6352960b65b.png">

this was followed by the bug #6976

**Comment by robguthrie** [comment]
closing collab editor stuff, we're not looking at this level of detail yet, thank you though
