### ISSUE TITLE
[thread renderer] "-3 more" collapse button, and comment does not appear if beta is disabled

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#6984]
Neither "-3" nor "3" collapse buttons do anything.

MOK tried to comment and @mention me and it showed up in another thread (I've emailed @gregorykan a full report about this and I'll leave him to bring you/Rob across it)

https://www.loomio.org/s/cfYSG45b
<img width="1325" alt="Screen Shot 2020-10-01 at 5 06 44 PM" src="https://user-images.githubusercontent.com/18379380/94767378-adf9a280-0408-11eb-83c8-1c7e568a1b0f.png">

**Comment by robguthrie** [comment]
fixed i think
