### ISSUE TITLE
Time poll: 90 minute meeting-duration is showing as an additional/duplicate 2 hr option

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#6986]
Additionally, we have a [wish from ZWE](https://support.loomio.org/scp/tickets.php?id=8040) for 2.5, 3.5 hour meetings

<img width="1323" alt="Screen Shot 2020-10-02 at 10 50 06 AM" src="https://user-images.githubusercontent.com/18379380/94867227-522d2900-049d-11eb-8b6d-69548bfd7083.png">

**Comment by robguthrie** [comment]
fixed!
