### ISSUE TITLE
Small issues in the time poll design

### ISSUE THREAD

**Issue by alanna** [loomio/loomio#6996]
![Screen Shot 2020-10-06 at 1 29 51 PM](https://user-images.githubusercontent.com/5498878/95145783-a7887380-07d8-11eb-9128-3dd5441fb3f4.png)

1. Europe and London aren't actually in the same time zone (1 hour different)
2. There are two `2 hour` options for meeting length. I was trying to schedule a 90 minute meeting and wasn't able to select that. Could this be changed to a `minutes` number field the user can set more flexibly? Or for MVP, maybe change one of the 2 hour options to a 90 minute one?

**Comment by robguthrie** [comment]
Thanks @alanna, fixed the duration list just now, we'll deploy the fix in the next hour.

The timezones are defined by an upstream organization, however if that just said "London" (ie: we just drop the first part before the /) then would that make sense?

**Comment by alanna** [comment]
Yeah sure if it's actually London time then that should be fine. Thanks!

>
