### ISSUE TITLE
Received outcome notification for a subgroup I'm no longer a part of

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#6997]
<img width="1401" alt="Screen Shot 2020-10-06 at 2 08 43 PM" src="https://user-images.githubusercontent.com/18379380/95150114-fc7db700-07e3-11eb-9867-d95b908ebb96.png">

I recently removed myself from a subgroup of Enspiral (called "Europe" I believe)

Copy/pasting the link of the in-app notification: https://www.loomio.org/p/Nc2zLy7A

**Comment by robguthrie** [comment]
should be fixed with new notifications
