### ISSUE TITLE
[Beta] Michael deleted this poll in 'production' but still shows up for me in 'beta'

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#6998]
<img width="1398" alt="Screen Shot 2020-10-06 at 3 00 26 PM" src="https://user-images.githubusercontent.com/18379380/95150480-be34c780-07e4-11eb-9bfc-81acc36f9342.png">
https://www.loomio.org/s/4pQORif2

and now back in production:
https://www.loomio.org/d/4pQORif2
<img width="1401" alt="Screen Shot 2020-10-06 at 3 01 38 PM" src="https://user-images.githubusercontent.com/18379380/95150563-eae8df00-07e4-11eb-915e-69bb72a205fa.png">

**Comment by robguthrie** [comment]
fixed
