### ISSUE TITLE
Unable to comment due to "Connecting to socket server …"

### ISSUE THREAD

**Issue by alanna** [loomio/loomio#7007]
The comment box at the bottom of threads isn't loading for me. It just says "Connecting to socket server …" Refreshing doesn't help.

![Screen Shot 2020-10-08 at 10 44 25 AM](https://user-images.githubusercontent.com/5498878/95391449-94e67980-0953-11eb-8502-117fef5e5421.png)

**Comment by alanna** [comment]
Tried logging out and in again and tried in another browser - no dice, same issue.

**Comment by robguthrie** [comment]
sorry about this, turn off beta features to work around this for now.

**Comment by alanna** [comment]
Ah great, that works. Thanks!

>
