### ISSUE TITLE
[collab editing] socket server doesn't connect

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7021]
seems a touch different – but maybe it's not – from #6976

<img width="1440" alt="Screen Shot 2020-10-12 at 11 43 20 AM" src="https://user-images.githubusercontent.com/18379380/95700500-a7d6b200-0ca3-11eb-8b4d-e89a0c281229.png">

**Comment by robguthrie** [comment]
thanks, yes aware of it, wont fix until we get private threads merged. FYI
it breaks quite often but is reset after 10 minutes.

**Comment by coopchange** [comment]
cool i'll close this as i accidentally missed Alanna's same issue anyways which will help other early adopters (given your replies)
