### ISSUE TITLE
Can't turn off notifications

### ISSUE THREAD

**Issue by alanna** [loomio/loomio#7048]
I've switched off both the global and group level notifications, but they keep coming to my inbox.

<img width="916" alt="Screen Shot 2020-10-27 at 4 38 06 PM" src="https://user-images.githubusercontent.com/5498878/97254416-3128df80-1873-11eb-999d-b8f94efb9938.png">
<img width="596" alt="Screen Shot 2020-10-27 at 4 39 39 PM" src="https://user-images.githubusercontent.com/5498878/97254441-3d14a180-1873-11eb-9740-c60e064fb940.png">
<img width="933" alt="Screen Shot 2020-10-27 at 4 38 49 PM" src="https://user-images.githubusercontent.com/5498878/97254435-39811a80-1873-11eb-83a8-50a4474f6ec5.png">

**Comment by robguthrie** [comment]
Noted, I'm just closing up a big change and will check in on this then, thank you for the info and apologies for the nuisance

**Comment by robguthrie** [comment]
Hi @alanna. We've rewritten notifications in Loomio, again. I believe this will solve them problem here. However,  If this problem persists, please re open this ticket and I'll fix it good.

**Comment by alanna** [comment]
I'm still getting notifications even though I turned them off for everything. I logged in and out and reloaded and stuff.

**Comment by robguthrie** [comment]
Arrrhg, sorry! I'll look into this real soon.

**Comment by robguthrie** [comment]
Just looking at your emails there, it might be that it's only proposal
closed notifications that are coming through eh?

**Comment by robguthrie** [comment]
I mean, in the timeframe since Loomio 2.5 was released (last week or so).

**Comment by robguthrie** [comment]
Hi @alanna, I've looked into this, and ensured that these notification emails you received will not happen again. They were one of 2 kinds that ignored user settings, sorry!

**Comment by alanna** [comment]
All good! Thanks!

**Comment by alanna** [comment]
I'm still getting email notifications - has the fix not been merged yet or is it something else?

**Comment by robguthrie** [comment]
yikes, can you forward it to me? rob at loomio.org
