### ISSUE TITLE
iOS (safari?) "permission denied" upon entry every time (can access it through workaround though)

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7059]
IOS - error [object Response] You do not have permission to do this - every time I open on my iPhone, need to select the menu and then it works

The below message from customer repeat and add details:

**iOS / Android** The IOS start error occurs 100% of the time, plus access is important as many of our people work in the field with their phones being their key tool for work. Having an external badge notification is important. An email notification goes part of the way but if there is a lot of activity then there could be a lot of emails. Also out in the field work is carried out without internet access, many apps allow data entry which is then synced when back online

I'm going to send some more details, including the above, via an email @robguthrie

**Comment by coopchange** [comment]
Note: the link XXXXXX starts https://www.loomio.org/saml_providers/auth?group_id=XXXXXX

**Comment by coopchange** [comment]
Oops sorry I've conflated two issues here; editing and starting another issue for the latter, the one on desktop

**Comment by robguthrie** [comment]
sorry, I can't use this report. single-instance bugs specific to a customer would be better directly emailed or within our private loomio group I Think
