### ISSUE TITLE
Unable to reply to comments on mobile

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#7060]
Just tried to reply to a comment using Firefox on Android, but I am not shown any buttons to interact with comments — no reply, no reactions. I can reply at the bottom of the thread, but not to an individual message. The screenshot below shows a couple of posts, as well as the expanded menu.

![image](https://user-images.githubusercontent.com/195073/97643980-f6f75200-1aad-11eb-8e77-70991f2f2daf.png)

**Comment by robguthrie** [comment]
Hi @madduck can you email me the link to the thread where this is happening? Thank you.

**Comment by madduck** [comment]
I cannot reproduce this anymore. Must have been due to the meteor shower causing wrong polarity of the neutron flow.
