### ISSUE TITLE
404 page not found for a specific subgroup (customer has found workaround to get there) SAML in the link 🤔

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7061]
**404 Page not Found** I had the 404 Page not Found error in my browser Macos 10.15.7 Browser, it happened a couple of times in a row yesterday when opening one specific subgroup from the Subgroup menu

- https://www.loomio.org/saml_providers/auth?group_id=XXXXXX at 12:15PM
- Later when selecting a Thread from my Home page is was able to select that Subgroup
- Screenshot - I took a screenshot but must have done so to the Clipboard - but it will most likely recur

He said he was sometimes using [Flotato,](https://www.flotato.com/) a tab manager that allows you to open a web-page from your Dock, but not all the time... maybe that's part of the issue? I asked him and it seems he's not totally clear on it

**Comment by coopchange** [comment]
broke this out from #7059

**Comment by coopchange** [comment]
I responded to customer with the following
Sometimes 404 Page not Found

    Can you try navigating directly to the correct link for the subgroup you mention? The true link should be https://loomio.org/XXXXXXXX and also https://loomio.org/SUBGROUP_HANDLE navigates you to the same place.
    We will work to respond expediently to this; thanks for the URL. I am curious if Flotato was involved given that there is "SAML" in the URL you provided.

See the osTicket link i sent you for those links, Rob, (sorry for the extra pings for this one; a bit tired today)

**Comment by robguthrie** [comment]
FYI @coopchange, I'm unable to action this because I have no idea of the group in question.
This was in OSTicket at at some point.. can you help me find that? or email me the group url?
