### ISSUE TITLE
Odd results when removing voter from check poll

### ISSUE THREAD

**Issue by eteb3** [loomio/loomio#7072]
We have one user invited to vote who hasn't signed up for Loomio yet. She normally shows as _invited user (@gmail.com)_

I decided to remove her as a voter from a check poll by clicking
_5 voters > overflow ... at user's name > remove from check_

As expected, **number** of voters shown reduced to '4 voters'.

Unexpected, **list of voters** showed all five original invitees AND unregistered voter's email address was unmasked.

Display auto-refreshed from -> to
_invited user (@gmail.com)· Trustee -> firstname.lastname@gmail.com · Trustee_

When I manually refreshed the page, things were as expected: user no longer listed on list of voters.

![git2](https://user-images.githubusercontent.com/11834131/98395225-dc941a00-2053-11eb-86b3-f787a920a3f0.jpg)

**Comment by robguthrie** [comment]
Thanks for reporting this, a fix for removed/revoked votes showing up is on the way today.

The email address showing up is ok, sometimes we supply the email address when you are the admin of the group or poll and the user has no name yet.

**Comment by eteb3** [comment]
Thanks, Rob. 

Keep up the good work, all of you - Loomio is the best!

**Comment by robguthrie** [comment]
this is fixed now!
