### ISSUE TITLE
"Show notifications" – my gut reaction was that it made me think something else than "Notification history"

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7076]
I vote don't fix what ain't broken! And we've talked to a lot of customers about Notification History.

Open to chat it further, and obviously you own the decision but do please lmk

**Comment by coopchange** [comment]
^ @robguthrie

**Comment by robguthrie** [comment]
yea, I think we can change this without ruining anyone's day.

Also changed was "Edit revision history"... making them similar: See edits, See notifications.

Lemme run with this, I think it's important to try using simpler/shorter more consistent words.
