### ISSUE TITLE
Can't extend duration of time poll (May be user error)

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7088]
https://www.loomio.org/d/AOMKNXWB/comment/2362369
<img width="721" alt="Screen Shot 2020-11-11 at 9 21 05 AM" src="https://user-images.githubusercontent.com/18379380/98729155-5b47d900-23ff-11eb-8638-5e7e839b0766.png">

**Comment by robguthrie** [comment]
@coopchange there is a "reopen" function for a closed time poll:
<img width="817" alt="image" src="https://user-images.githubusercontent.com/486367/98729837-5b94a400-2400-11eb-9363-e3b65bddce7a.png">

Also I note that even after voting, I can edit the poll and extend the closing date.

I'd love to know what Frans experience was, is she on github?

**Comment by coopchange** [comment]
@francesca-sp maybe you didn't reopen the poll before trying to extend the duration?

hope you don't mind that I pasted your innocuous comment here (open to that feedback ofc!)
