### ISSUE TITLE
Deactivated alt account showing in tag suggestions

### ISSUE THREAD

**Issue by alanna** [loomio/loomio#7090]
We had a user added to our group under a certain email, who then created another account for herself using another email, so we had two of her. I removed the inactive account from the group, but when I try to tag her, both accounts pop up and it's impossible to tell which one is correct.

![Screen Shot 2020-11-11 at 1 03 06 PM](https://user-images.githubusercontent.com/5498878/98748489-a8877300-241e-11eb-976c-0c57369ff8e5.png)

**Comment by robguthrie** [comment]
Oh dear. Will fix it this afternoon for you

**Comment by robguthrie** [comment]
Oooookay, just deployed a fix for this. Thanks and apologies!
