### ISSUE TITLE
Poll in subgroup is not listed in Polls tab of parent group

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7099]
Started a poll in loomio.org/demo 's subgroup, "Board", from the poll tab. Can't find it in parent group poll tab.

<img width="1067" alt="Screen Shot 2020-11-16 at 8 50 35 AM" src="https://user-images.githubusercontent.com/18379380/99195165-f28aa300-27e8-11eb-97d7-4b6548342337.png">

<img width="1064" alt="Screen Shot 2020-11-16 at 8 50 53 AM" src="https://user-images.githubusercontent.com/18379380/99195169-f74f5700-27e8-11eb-837c-948078837fff.png">

**Comment by robguthrie** [comment]
thanks, fixed
