### ISSUE TITLE
Invite people to vote – as non-admin – gives spinny wheel and an error upon pressing "invite"

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7101]
@robguthrie 

Maybe I'm not allowed (I'm not an admin, in this picture):

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/18379380/99195324-e3f0bb80-27e9-11eb-9adc-e3a54553b1e9.png">

**Comment by robguthrie** [comment]
closed and fixed. thanks
