### ISSUE TITLE
Threads don't mark as read

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7114]
FWIW: I've been in to clear these threads twice and was still getting unread marks; seems like maybe 3rd time was the charm:
https://www.loomio.org/d/02rG1U86/v2-5-release-noticing-and-bugs-?p=10

(also curious to see socket.io connect while beta disabled... maybe just cos i haven't hard refreshed recently?)

**Comment by coopchange** [comment]
@robguthrie just getting your attention here – if it bug replicable beyond me (firefox 82) I'm realizing via my experience that it might be a bit grr for users

**Comment by robguthrie** [comment]
thanks. I'll look into it next

**Comment by robguthrie** [comment]
i think this was due to the background job system being overloaded. reopen if it happens again. thanks

**Comment by coopchange** [comment]
Experiencing this again; just returned to see your reply twice today: https://www.loomio.org/d/LbDqIx68/workers-wall-

**Comment by coopchange** [comment]
@robguthrie it doesn't appear i can reopen

**Comment by coopchange** [comment]
I've emailed you three more I've read but continue to be unread along with a screen cap of my console Rob

**Comment by robguthrie** [comment]
I think I may have found the root cause of this and fixed it. interested in hearing if you notice it from now on.

**Comment by coopchange** [comment]
This is still occurring. I think I've had a number of incidents in the past couple weeks. I'll try and post another, but one for now (link below)
_Reproduction steps:_
1. opened thread
2. read all comments (1)
3. posted my own comment
4. later I opened the group page and saw it was unread (1)
5. when i entered the thread it showed the comment _previous_ to mine as the unread one (yellow fading)

I'll look for more! I didn't manage to capture the log/console this time apologies

https://www.loomio.org/d/Qn0aoRbu/deciding-in-isolation-a-report-about-using-loomio-pre-and-post-covid-in-a-german-collective

**Comment by coopchange** [comment]
<img width="1425" alt="read_still_unread" src="https://user-images.githubusercontent.com/18379380/110732901-e9d34680-8289-11eb-8ccb-a5f07d0b6fb5.png">

one other example I'd not posted yet, from 20th Jan.

**Comment by coopchange** [comment]
And a recent one from today, where I believe the tab had not stayed on Loomio, I think I opened the tab today... 
I read Rahul's message (see below) last week, but there was an unread mark on the thread, and when I opened the thread his comment was highlighted in yellow:
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/18379380/111083281-a28ed380-8571-11eb-9890-780d6c76041c.png">
https://www.loomio.org/d/eUQXEY2S/mosaic-s-blog-post-finding-the-best-online-tools-for-the-job-

**Comment by coopchange** [comment]
Should I continue dropping examples here @robguthrie ? Had a clear one today with hard refresh still showed as read. The Board Collateral thread; have screencap on request

**Comment by robguthrie** [comment]
no, I think I've got a picture of it. I'll look into this issue soon. Thank
you.
