### ISSUE TITLE
work in progress poll email is missing translation

### ISSUE THREAD

**Issue by data-doge** [loomio/loomio#7116]
steps to reproduce:
- make work in progress poll
- emails sent out
- subject contains `[group name] translation missing: en.poll_mailer.subject.poll_edited_wip`

unrelated, check this out: https://newyork.craigslist.org/mnh/fuo/d/new-york-unique-pig-couch-must-pick-up/7232296274.html

**Comment by robguthrie** [comment]
Wow, what a couch! Thanks for sharing.

Next release will fix this issue.. I think it's better to just use regular
poll_mailer strings for WIP polls, leave that info for the inside of the
email

**Comment by robguthrie** [comment]
sorted
