### ISSUE TITLE
grey box (single repeatable grey box item)

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7120]
https://www.loomio.org/d/57MAOR3b/newsletter-or-email-design-examples
<img width="1380" alt="Screen Shot 2020-11-24 at 1 12 11 PM" src="https://user-images.githubusercontent.com/18379380/100029965-53545400-2e57-11eb-89e2-9ec0da310fa2.png">

**Comment by robguthrie** [comment]
fixed!
