### ISSUE TITLE
 npm ERR!  git://github.com/loomio/router.git not found

### ISSUE THREAD

**Issue by battosai30** [loomio/loomio#7129]
Hi,

Trying to set up a dev env, I got this error on npm install in client/vue

```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/loomio/router.git
npm ERR! 
npm ERR! fatal: remote error: 
npm ERR!   Repository not found.
```

And I can't say that it's wrong, I can't find it xD

Regards

**Comment by robguthrie** [comment]
You're both right! Where did you find these outdated instructions?

**Comment by battosai30** [comment]
I'm trying to setup an Alpine (not Docker ;) ) env.

 I just followed the manual : https://help.loomio.org/en/dev_manual/setup_dev_environment/

It happens on npm install in client/vue

**Comment by robguthrie** [comment]
I've updated the instructions. I think you're cloning robguthrie/loomio,
which isnt right. Clone loomio/loomio

**Comment by battosai30** [comment]
Oh yeah it's better know xD

Thanks !
