### ISSUE TITLE
embedded video does not appear in email notification (from 'invite to thread')

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7133]
https://www.loomio.org/d/3yYqZpaE/finding-our-first-book-study-time-sand-talk-by-tyson-yunkaporta-
<img width="863" alt="Screen Shot 2020-11-28 at 6 21 18 AM" src="https://user-images.githubusercontent.com/18379380/100472883-f94adb80-3141-11eb-922c-35c4fbead66b.png">

**Comment by robguthrie** [comment]
I fixed this last night.
when was this notification sent?

**Comment by coopchange** [comment]
2020-11-28 at 6.21.18 AM was when i took the screen cap; it would have been shortly before unless i misremember

**Comment by robguthrie** [comment]
I sent you a test, lemme know when you see it :)

**Comment by robguthrie** [comment]
I've also sent the test to myself and confirmed its fixed.
