### ISSUE TITLE
Seen By and Notification History disagreeing

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7137]
https://www.loomio.org/d/U4SaVCqj/key-messages-per-customer-segment

<img width="317" alt="image" src="https://user-images.githubusercontent.com/18379380/100560020-577de700-3319-11eb-92de-ca41df0ff089.png">

but this shows differently

<img width="543" alt="image" src="https://user-images.githubusercontent.com/18379380/100560082-8a27df80-3319-11eb-8eff-b6a0af1aa010.png">

**Comment by robguthrie** [comment]
thanks!

**Comment by robguthrie** [comment]
cant see this happening anymore, reopen if you do
