### ISSUE TITLE
Results appear before any voting (eg, in Polls) in noisey way that doesn't help

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7176]
This is the same behaviour as the time poll... obviously with less benefit associated with leaving it the way it is:
<img width="767" alt="image" src="https://user-images.githubusercontent.com/18379380/102038491-46120000-3e2c-11eb-941f-0a88301350ec.png">

**Comment by robguthrie** [comment]
yep, fair call, thanks for logging it

**Comment by robguthrie** [comment]
fixed now, thanks john
