### ISSUE TITLE
Results flickering in & out of sight post-vote

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7280]
Sorry I don't have time to recreate this (happened in a training).

My best sense of steps to recreate are:

1. Create & start poll
2. Submit a vote
3. Scroll around as if you were showing someone the decision and how you can edit your stance

— you should encounter behavior like the results disappearing possibly reappearing

**Comment by robguthrie** [comment]
thanks, its this on poll page or thread page, if thread page, beta or main?

**Comment by coopchange** [comment]
Thread, main

**Comment by coopchange** [comment]
I believe this is related, where you should be able to see not only my "yes" vote but also the text of my "reason"
<img width="1310" alt="Screen Shot 2021-01-11 at 12 49 34 PM" src="https://user-images.githubusercontent.com/18379380/110733400-c066ea80-828a-11eb-86ee-147b76f9187e.png">
It appears this would have appeared after this particular edit in the edit log, which is also funny looking:
<img width="633" alt="image" src="https://user-images.githubusercontent.com/18379380/110733638-2c495300-828b-11eb-8f74-2bc5d40be91a.png">
https://www.loomio.org/d/XcSJLk5e/members-retreat-at-summer-fest-2021-12th-february-


I may have recreated it just now, although it's hard to know for sure if it is or isn't operating as intended (the following check poll only has "yes" as an option):
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/18379380/110733463-e1c7d680-828a-11eb-916d-5dd747db6987.png">
https://www.loomio.org/d/rmGlZJpH/native-tree-and-card-for-joshua-in-remembrance-

**Comment by robguthrie** [comment]
fixed
