### ISSUE TITLE
when importing loomio-data.json: "Unkown attribute error (unknown attribute 'secret_token' for stance)

### ISSUE THREAD

**Issue by puschmie** [loomio/loomio#7298]
I'm getting the above error when trying to import a json file with the loomio data from a different instance. We are moving servers and therefore I'm trying to move our loomio aswell. At first I thought it was an issue of versions. But even after upgrading the old installation I still get the same error. When I delete the secret_token attribute from all stance objects I can import, but when I log in with the admin user I'm not part of the group, but can see all discussions. No way to find the group either since it is private.
Could someone please provide me with some more info on importing data from another loomio instance? following the steps in the documentation doesn't seem to cut it. 
Thank you!!

**Comment by robguthrie** [comment]
Hi Pushmie,

I think I'm aware of an issue that might be affecting you. I may need to make a migration and add secret_token to stances.

Are you exporting data from loomio.org to your own server?

Are you able to post a bit more of the error output, or if it is sensitive info, send it to rob at loomio? (dot org)

**Comment by puschmie** [comment]
Hey Rob!
No I'm just moving servers, had loomio running in a temporary setup for about a month and know I'm moving to a more permanent setup.

This is the error output:

Traceback (most recent call last):
        7: from (irb):1
        6: from app/services/group_export_service.rb:60:in `import'
        5: from app/services/group_export_service.rb:60:in `each'
        4: from app/services/group_export_service.rb:63:in `block in import'
        3: from app/services/group_export_service.rb:63:in `map'
        2: from app/services/group_export_service.rb:63:in `each'
        1: from app/services/group_export_service.rb:66:in `block (2 levels) in import'
ActiveModel::UnknownAttributeError (unknown attribute 'secret_token' for Stance.)

On a sidenote: before updating the old instance I also got the same error about the motion_can_be_edited attribute of groups, but that went away after updating. 
Thanks!

**Comment by robguthrie** [comment]
I've just updated master to include secret_token on stance, if you upgrade both instances you should be able to bring the data between them. Sorry about this, it's been a curious issue for a while so good to straighten it out.
Good luck!

**Comment by puschmie** [comment]
Thanks for your quick action!
I still get the error though. I guess it's because I'm using loomio-deploy. I only see your commit on loomio. Any chance to get the fix over there?

**Comment by robguthrie** [comment]
Oh yea, switch from :stable to :latest within your docker-compose.yml (2
places, worker and app)

**Comment by puschmie** [comment]
aahhh, thank you so much, it worked a treat.
actually the tag is set through .env :)

**Comment by puschmie** [comment]
Hey Rob,
I only now realized, that I have some more issues.
The data from the import shows up fine and I can login with my old username. All Threads and comments are there. So far so good..
But when I (or any other user for that matter) try to start a new thread or post a comment nothing happens on the frontend. 
The logs print out the following: 
`loomio-app     | app/services/discussion_service.rb:19:in `create'
loomio-app     | app/controllers/api/v1/discussions_controller.rb:13:in `create_action'
loomio-app     | app/controllers/api/v1/discussions_controller.rb:7:in `create'
loomio-app     | app/helpers/locales_helper.rb:8:in `use_preferred_locale'
loomio-app     | source=rack-timeout id=1d546355-475c-4773-8e89-e8152a9220b9 timeout=15000ms service=139ms state=completed
loomio-app     | source=rack-timeout id=2417bb45-279b-411e-8c8b-1b7b3b766d82 timeout=15000ms state=ready
loomio-app     | method=POST path=/api/v1/discussions format=json controller=API::V1::DiscussionsController action=create status=500 error='ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "discussions_pkey"
loomio-app     | DETAIL:  Key (id)=(4) already exists.
loomio-app     | : INSERT INTO "discussions" ("group_id", "author_id", "created_at", "updated_at", "title", "description", "key", "description_format", "content_locale") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"' duration=77.60 view=0.00 db=33.03`

Seems like there is an issue where loomio tries to start unique id's from the same start id or seed or something like that??
Is this a known issue? Is there anything I can do to get around this?
Thanks a ton!

**Comment by robguthrie** [comment]
Hi @puschmie,

I think you'll need to reset your redis database.
try 
`docker-compose run app rails c`
then
`Redis::Objects.redis.flushdb`
then exit and try starting another discussion

**Comment by puschmie** [comment]
it still returns the same error output. 
When I start thee rails console I get this warning: 

`Redis#exists(key)` will return an Integer by default in redis-rb 4.3. The option to explicitly disable this behaviour via `Redis.exists_returns_integer` will be removed in 5.0. You should use `exists?` instead.
Loading production environment (Rails 5.2.4.4)

could that have something todo with it?

**Comment by robguthrie** [comment]
Nope, that warning is ok. Actually, I'm crazy, the redis container does not persist anything anyway. Sorry!

The problem is the importing of records has not incremented the primary key sequence of the table.
So to fix this for you, we need to login to the postgres server and reset the primary key sequences, then, more generally I need to make that happen automatically after import.

The following is to get a postgresql console.
```
docker exec -ti loomio-db su - postgres -c 'psql loomio_production'
```

then run the following..
```
SELECT SETVAL('public.active_storage_attachments_id_seq', COALESCE(MAX(id), 1) ) FROM public.active_storage_attachments;
SELECT SETVAL('public.active_storage_blobs_id_seq', COALESCE(MAX(id), 1) ) FROM public.active_storage_blobs;
SELECT SETVAL('public.ahoy_messages_id_seq', COALESCE(MAX(id), 1) ) FROM public.ahoy_messages;
SELECT SETVAL('public.attachments_id_seq', COALESCE(MAX(id), 1) ) FROM public.attachments;
SELECT SETVAL('public.blacklisted_passwords_id_seq', COALESCE(MAX(id), 1) ) FROM public.blacklisted_passwords;
SELECT SETVAL('public.comments_id_seq', COALESCE(MAX(id), 1) ) FROM public.comments;
SELECT SETVAL('public.default_group_covers_id_seq', COALESCE(MAX(id), 1) ) FROM public.default_group_covers;
SELECT SETVAL('public.discussion_readers_id_seq', COALESCE(MAX(id), 1) ) FROM public.discussion_readers;
SELECT SETVAL('public.discussion_search_vectors_id_seq', COALESCE(MAX(id), 1) ) FROM public.discussion_search_vectors;
SELECT SETVAL('public.discussion_tags_id_seq', COALESCE(MAX(id), 1) ) FROM public.discussion_tags;
SELECT SETVAL('public.discussions_id_seq', COALESCE(MAX(id), 1) ) FROM public.discussions;
SELECT SETVAL('public.documents_id_seq', COALESCE(MAX(id), 1) ) FROM public.documents;
SELECT SETVAL('public.events_id_seq', COALESCE(MAX(id), 1) ) FROM public.events;
SELECT SETVAL('public.group_identities_id_seq', COALESCE(MAX(id), 1) ) FROM public.group_identities;
SELECT SETVAL('public.group_surveys_id_seq', COALESCE(MAX(id), 1) ) FROM public.group_surveys;
SELECT SETVAL('public.groups_id_seq', COALESCE(MAX(id), 1) ) FROM public.groups;
SELECT SETVAL('public.login_tokens_id_seq', COALESCE(MAX(id), 1) ) FROM public.login_tokens;
SELECT SETVAL('public.membership_requests_id_seq', COALESCE(MAX(id), 1) ) FROM public.membership_requests;
SELECT SETVAL('public.memberships_id_seq', COALESCE(MAX(id), 1) ) FROM public.memberships;
SELECT SETVAL('public.notifications_id_seq', COALESCE(MAX(id), 1) ) FROM public.notifications;
SELECT SETVAL('public.oauth_access_grants_id_seq', COALESCE(MAX(id), 1) ) FROM public.oauth_access_grants;
SELECT SETVAL('public.oauth_access_tokens_id_seq', COALESCE(MAX(id), 1) ) FROM public.oauth_access_tokens;
SELECT SETVAL('public.oauth_applications_id_seq', COALESCE(MAX(id), 1) ) FROM public.oauth_applications;
SELECT SETVAL('public.omniauth_identities_id_seq', COALESCE(MAX(id), 1) ) FROM public.omniauth_identities;
SELECT SETVAL('public.outcomes_id_seq', COALESCE(MAX(id), 1) ) FROM public.outcomes;
SELECT SETVAL('public.poll_options_id_seq', COALESCE(MAX(id), 1) ) FROM public.poll_options;
SELECT SETVAL('public.poll_unsubscriptions_id_seq', COALESCE(MAX(id), 1) ) FROM public.poll_unsubscriptions;
SELECT SETVAL('public.polls_id_seq', COALESCE(MAX(id), 1) ) FROM public.polls;
SELECT SETVAL('public.reactions_id_seq', COALESCE(MAX(id), 1) ) FROM public.reactions;
SELECT SETVAL('public.saml_providers_id_seq', COALESCE(MAX(id), 1) ) FROM public.saml_providers;
SELECT SETVAL('public.stance_choices_id_seq', COALESCE(MAX(id), 1) ) FROM public.stance_choices;
SELECT SETVAL('public.stances_id_seq', COALESCE(MAX(id), 1) ) FROM public.stances;
SELECT SETVAL('public.subscriptions_id_seq', COALESCE(MAX(id), 1) ) FROM public.subscriptions;
SELECT SETVAL('public.tags_id_seq', COALESCE(MAX(id), 1) ) FROM public.tags;
SELECT SETVAL('public.translations_id_seq', COALESCE(MAX(id), 1) ) FROM public.translations;
SELECT SETVAL('public.usage_reports_id_seq', COALESCE(MAX(id), 1) ) FROM public.usage_reports;
SELECT SETVAL('public.user_deactivation_responses_id_seq', COALESCE(MAX(id), 1) ) FROM public.user_deactivation_responses;
SELECT SETVAL('public.users_id_seq', COALESCE(MAX(id), 1) ) FROM public.users;
SELECT SETVAL('public.versions_id_seq', COALESCE(MAX(id), 1) ) FROM public.versions;
SELECT SETVAL('public.webhooks_id_seq', COALESCE(MAX(id), 1) ) FROM public.webhooks;

```

**Comment by robguthrie** [comment]
then \q to exit and try creating a discussion again

**Comment by robguthrie** [comment]
finally, for my and others reference, I generated the SQL above with the code available here: 
https://wiki.postgresql.org/wiki/Fixing_Sequences

**Comment by puschmie** [comment]
yes rob you're a genius! thank you so so much for your effort here!

and in general: thank you for making loomio available for self-hosting and even supporting us like this. we are a small community supported agriculture project in Vienna/Austria and loomio helps us SO much in reducing meeting time by discussing and making decisions asynchronously. We are really grateful for this tool being available to us for just the cost of the server we run anyways. Unfortunately we can't really give back to you financially, but if you need something like a testimonial or help with feedback or testing I'd be super glad to help out!
Thanks again for your really important work!
cheers
jonas
