### ISSUE TITLE
Feature request: survey poll

### ISSUE THREAD

**Issue by alanna** [loomio/loomio#7301]
[If this isn't the right place to put feature requests, just let me know]

It would be really useful to have a poll type that's like a survey, where you define questions and are asking people to respond by a specific date. For MVP, this could be a single customisable line of text and a text box. If you wanted to get fancy you could have multiple questions.

In terms of a user story, I'm sort of hacking this right now in a thread where I'm asking board members to suggest potential new board members, using a check and saying "click yes and write your suggested people's names as your comment" but it would be nice to have a poll type designed for this kind of situation. I can imagine a lot of other use cases, like "what would you like on the agenda for the next meeting?" and "Have a go articulating what our mission statement could be" etc.

**Comment by robguthrie** [comment]
Fine to request features here.

I assume answers would be length limited? Would you want to combine other answer types too, aside from text responses, like a series of multichoice polls tied together in a survey?

**Comment by alanna** [comment]
Yes length limited would be fine, if there's a technical or design requirement there. Maybe allow the poll creator to set the length limit, with an absolute maximum set by Loomio?

I think other types of survey questions are already pretty well covered by the other poll types (e.g. multi-choice is basically a regular poll), and if I needed the complexity of a fully featured survey tool, I could imagine just using Google forms or Survey Monkey, and putting the link in a check saying "Have you filled out the survey?". That would be a decent workaround. 

I'm specifically interested in a text box with a deadline, and making it streamlined enough to integrate the responses into an ongoing thread. But if you think there's a need for a more fully featured survey option, I could meet the need I have with that.

**Comment by robguthrie** [comment]
oh, it's not that I'm arguing for something more complex, I'm just
wondering if this is similar to other feature requests which have been
introduced to me as a survey poll.

So this is more like, a poll, without any choices, just a reason field?

**Comment by alanna** [comment]
Hello! just wanted to come back and bump this because my groups keep wanting it. Often times we simply have a question for everyone and need an answer in the form of a text box they fill out by a certain date. 

> So this is more like, a poll, without any choices, just a reason field?

Yep! All the same features as a poll (title, deadline, details), and the response is just a text box people fill out, with no choices.

As an example, right now we've asked all the sociocratic circles in our org a question (How would XYZ change affect your area of work?) and we need their response by a certain date. We're trying to hack Loomio for this using a poll with only one possible response, but it's a bit ugly and confusing to do it this way.

**Comment by robguthrie** [comment]
Thanks for the reminder. I'll try to add this in our upcoming release

**Comment by robguthrie** [comment]
Hi @alanna - with the latest Poll template feature we included a Question round poll type. 

https://help.loomio.com/en/user_manual/polls/poll_templates/index.html

You'll find it under "Settings" when starting a new poll, and you can unhide it to make it available for users in your group.
