### ISSUE TITLE
Tags upgrade, minor stuff

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7348]
Just making a space for minor noticings; trying to practice with 'em more these coming weeks

**Comment by coopchange** [comment]
Click on a tag, the letters I had typed in stay and try to prompt another tag (seems like i just clicked somewhere else and it went away)
https://www.loomio.org/d/YymVGCsd/
<img width="1414" alt="Screen Shot 2021-02-19 at 2 41 59 PM" src="https://user-images.githubusercontent.com/18379380/108445222-e1a66d80-72c0-11eb-9b44-5897b8896c04.png">

**Comment by robguthrie** [comment]
fixed
