### ISSUE TITLE
Loomio Explore : Public groups first load, then disappear

### ISSUE THREAD

**Issue by phleba** [loomio/loomio#7381]
Hey, as mentioned in a otherwise unrelated and closed issue #6772 by someone else and me there is the problem of not being able to explore public groups.

E.g. browsing my own /explore or https://www.loomio.org/explore will load public groups but after loading of the web page is done, they all disappear for me. Only the search bar and sorting options remain. Typing anything in the search bar yields no results. 

Tested on Linux with latest Firefox and Chromium. Tested with two other team members here. 

P.s. Don't know if this helps but the Browser console reports around the time all groups vanish

`XHR GET https://www.loomio.org/api/v1/groups/count_explore_results? [HTTP/2 304 Not Modified 570ms]`

**Comment by chaotika** [comment]
We have the same problem with the lThe problem here seems to be that /api/v1/groups?per=50&order=memberships_count answers with an empty JSON: {"groups":[],"meta":{"total":0}}

When i block the endpoint the groups somehow appear.

I don't know if this is a problem with loomio or our local setup. The instance on loomio.org does not seem to have this problem so i am a bit confused about this.

**Comment by chaotika** [comment]
seems to be fixed in current master branch commit f33ed92e75de59910c1bda565edbda3bf2cf69ce

**Comment by phleba** [comment]
Yes it appears to be fixed! Closing this issue, thanks.
