### ISSUE TITLE
"Change plans" buttons on certain plans may not be working

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7401]
EG, Enspiral's loomio.org/upgrade/2 (screencap below) – the buttons don't work _and_ the "charge of $loading" doesn't load (it looks awesome when it does work tho 👏 )

Similar behavior for any of the groups that are free & active (that I have access to anyway)

Loomio Co-op's is working fine

<img width="827" alt="Screen Shot 2021-03-11 at 3 30 42 PM" src="https://user-images.githubusercontent.com/18379380/110726792-ea1a1480-827e-11eb-9e65-d8e75e10d3dd.png">

**Comment by coopchange** [comment]
oh on all of them though there is this typo: 
> plus sales tax if **applicicable**

**Comment by robguthrie** [comment]
Yep, that'll happen for groups without chargify subscriptions. It's on my radar

**Comment by robguthrie** [comment]
closed
