### ISSUE TITLE
New banner photo does not show until exiting the Edit group settings modal

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7402]
but you may be able to see it in the background, as in the second example:
<img width="1397" alt="Screen Shot 2021-02-11 at 9 13 58 AM" src="https://user-images.githubusercontent.com/18379380/110731452-3701e900-8287-11eb-85f9-cf0a2cc482c4.png">
<img width="1080" alt="Screen Shot 2021-03-11 at 4 29 38 PM" src="https://user-images.githubusercontent.com/18379380/110731464-3a957000-8287-11eb-8266-15bcc0bb29c8.png">

**Comment by robguthrie** [comment]
fixed
