### ISSUE TITLE
Thread unread due to my own reply

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7403]
This was back on 10th February – didn't seem pressing so only posting now, soz...

I documented in part as I've been on the watch for stuff that might support you to figure out #7114 which continues to be part of my experience that I think is enough of a stutter to be worth fixing

I took some screenshots but better for me just to say I replied, was back in the group page and saw it unread and "last active 1 minute ago", and so I went back into it thinking there was a reply to my reply - [in this thread](https://www.loomio.org/d/fTUPveVM/process-templates-brainstorm) - and saw that it was showing some older things as unread for a second or third time, and that there was nothing new... I think that's the point at which I captured the log:

<img width="1415" alt="Screen Shot 2021-02-10 at 4 08 39 PM" src="https://user-images.githubusercontent.com/18379380/110732067-4f263800-8288-11eb-9f00-ed3ce11b5ace.png">

**Comment by robguthrie** [comment]
fixed
