### ISSUE TITLE
When I first propose and vote, the pie & my vote are not displayed

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#7415]
Immediately after proposing and voting:
<img width="815" alt="image" src="https://user-images.githubusercontent.com/1380991/111081897-58562400-856a-11eb-8660-45cd32d24ba8.png">

After refreshing:
<img width="802" alt="image" src="https://user-images.githubusercontent.com/1380991/111081915-6c9a2100-856a-11eb-8900-0779501b3192.png">

**Comment by chaotika** [comment]
seems to be fixed in current master branch commit f33ed92e75de59910c1bda565edbda3bf2cf69ce

**Comment by robguthrie** [comment]
no, i think this is still happening, it's kind of tricky to reproduce. I
will look again today

**Comment by robguthrie** [comment]
I've fixed this bug now!
