### ISSUE TITLE
Edit thread requires two clicks

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7439]
Encountered this a few times now, clicking **edit** and then having to click it again – sometimes the current page scrolls to another position upon the first click.

<img width="1338" alt="Screen Shot 2021-03-23 at 3 21 30 PM" src="https://user-images.githubusercontent.com/18379380/112091924-496f1180-8bfb-11eb-9f16-4d0f0474a812.png">
https://www.loomio.org/d/0Qle1Ejg/quick-start-guides-per-segment

**Comment by robguthrie** [comment]
Thanks for reporting, I'll look into it soon

**Comment by robguthrie** [comment]
closed (i think it's fixed)
