### ISSUE TITLE
Search on Recent Threads not working properly

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7448]
not pulling up the appropriate results

Here's a general example:
You can see "a new thread" with an open decision in first screencap, and then see how "new thread" will not pull it up in the second
<img width="1433" alt="Screen Shot 2021-03-26 at 4 10 22 PM" src="https://user-images.githubusercontent.com/18379380/112572101-56377380-8e4e-11eb-92b1-afe53fe605e9.png">
<img width="1440" alt="Screen Shot 2021-03-26 at 4 10 44 PM" src="https://user-images.githubusercontent.com/18379380/112572109-59326400-8e4e-11eb-84a6-849e3c01639f.png">

Invite-only example (2 screencaps)
<img width="1433" alt="Screen Shot 2021-03-26 at 4 10 22 PM" src="https://user-images.githubusercontent.com/18379380/112572139-66e7e980-8e4e-11eb-86f3-e36bad43a683.png">
<img width="1440" alt="Screen Shot 2021-03-26 at 4 10 05 PM" src="https://user-images.githubusercontent.com/18379380/112572173-7b2be680-8e4e-11eb-9ed7-d788f6482e2c.png">

**Comment by robguthrie** [comment]
I've fixed a bug with searching recent threads just now. thanks john.

**Comment by robguthrie** [comment]
searching is fixed
