### ISSUE TITLE
Searching invite-only threads

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7449]
Looking for this thread [Musing on Muses…](https://www.loomio.org/d/javW2BGP/musing-on-muses-reply-draft)
I don't get anything:
<img width="1378" alt="Screen Shot 2021-03-26 at 4 19 53 PM" src="https://user-images.githubusercontent.com/18379380/112572549-3eacba80-8e4f-11eb-821f-d4690196bfba.png">

maybe this is just related to bug #7448

**Comment by robguthrie** [comment]
searching is fixed now
