### ISSUE TITLE
Add Options to active Time Poll

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7451]
Can't add options; button to save at the end of the process is greyed out:
<img width="1426" alt="Screen Shot 2021-03-29 at 11 34 22 AM" src="https://user-images.githubusercontent.com/18379380/112770387-12797f80-9083-11eb-843b-5dd08bb55f8a.png">

https://www.loomio.org/d/FHUkJRsx/gatherings-wg-coordination

**Comment by coopchange** [comment]
@robguthrie second occurrence: https://www.loomio.org/d/rAXqUHI6/tech-support/57

**Comment by coopchange** [comment]
friendly reminder about this @robguthrie still bugging here's a poll to exp it with:

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/18379380/113814709-2aa97700-97c6-11eb-865b-ece45f953fcb.png">
https://www.loomio.org/p/WexOYSad/test

**Comment by robguthrie** [comment]
righto, thanks for the reminder, fixed now (deploying currently)
