### ISSUE TITLE
Unread showing as read (Other user started a new thread, I never opened it, it does not appear unread)

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7476]
Not sure how to replicate, sorry. To expand on the issue title:

There was a new thread (your roadmap thread in our Loomio Co-op group) that I'd never opened or read, and when I came across it it appeared as read. I couldn't think of a reason why this would be. It already had several replies to it by the time I became aware of its existence today.

Mentioning it as this is the second time I believe this has occurred to me, just in case it helps / to look out for.

This screenshot likely won't help, but just in case:
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/18379380/114110424-8f321680-992b-11eb-93a7-592958cd6e59.png">

**Comment by coopchange** [comment]
Looking at that screenshot, there's another one that I've never visited at all "Interesting enquiry about anonymous comments", even to this point, that I also have never opened.

**Comment by robguthrie** [comment]
thanks, is this a window you leave open, or was it loaded fresh?

**Comment by coopchange** [comment]
The firefox window is left open

**Comment by robguthrie** [comment]
closed due to being very old
