### ISSUE TITLE
Search returning false "no results" from group page (thread) search

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7480]
<img width="1403" alt="Screen Shot 2021-04-13 at 3 52 09 PM" src="https://user-images.githubusercontent.com/18379380/114494384-6635bc80-9c70-11eb-8f5b-0f8b7497e082.png">
https://www.loomio.org/demo-agm-2020/?q=report

https://www.loomio.org/demo-agm-2020/ and loomio.org/demo 

searching report in the polls tab, on the other hand, seems to be working 

the missing result: https://www.loomio.org/d/KrPowjDp/4-financial-report-for-the-previous-year/1

**Comment by coopchange** [comment]
Interestingly, "4." and "financial" work, but not "report" nor "for"

**Comment by coopchange** [comment]
more spotty results; @robguthrie if you haven't taken a look here yet just notifying you of additional occurrences.

"[meeting](https://www.loomio.org/demo/?q=meeting&t=closed)" is missing March meeting thread ("[March](https://www.loomio.org/demo/?q=march&t=closed)" catches it tho)
https://www.loom.com/share/6bfe4fcad4cc4695bf1158319d29079a

**Comment by robguthrie** [comment]
thanks john!
