### ISSUE TITLE
sort Time Poll results table by respondees first

### ISSUE THREAD

**Issue by jnicho02** [loomio/loomio#7494]
On a time poll with many participants that is in progress it may be better to group those that have responded first. This would make it easier to see how it is going. I have 99 invitees and am only expecting 10 to reply.

Sure I can scroll all the way right and see the summary scores, but in reality some people's attendance matters more than others so I have to slide back-and-forth to see which slots are popular with major players.

e.g.

<img width="759" alt="Screenshot 2021-04-16 at 08 43 25" src="https://user-images.githubusercontent.com/83251/114990497-7926d780-9e90-11eb-9e90-4222cce651b2.png">
...and some votes off-screen to the right

**Comment by robguthrie** [comment]
thanks for raising this, much appreciated. Fixed and should be live in 15 minutes.
