### ISSUE TITLE
Show results – flicker behaviour of results on proposals and polls + missing pie chart

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7511]
You have probably noticed this or maybe I reported it, but just in case not, I thought to pop it up here again.

To repeat,
1. create poll
2. vote on it
3. show results
watch this video for my doing this with the console open: https://www.loom.com/share/bd9e501a64424948af29c2ab08ecb463

**Comment by robguthrie** [comment]
I think I've fixed this problem just now. it's been around for a while and is/was bad, but I haddn't had the idea of how to fix until now.
anyway. my tests show its fixed, can you confirm?

**Comment by robguthrie** [comment]
fixed
