### ISSUE TITLE
category tags – occasional broken link (tag button) from within thread

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7513]
Clicked on a tag in a thread to find it broken.

Went to reproduce it and document now, I clicked Minutes from [this thread](https://www.loomio.org/d/sHhNt6m5/june-board-meeting), and it seemed to work as intended (assuming it's meant to take me to the parent group thread page filtered to the tag; I was in a subgroup thread)

However, upon refreshing the page, it breaks to a 404, even though the URL looks the same as when it was working: https://www.loomio.org/g/Az2KfDEj/tags/Minutes
<img width="1403" alt="Screen Shot 2021-04-23 at 5 29 12 PM" src="https://user-images.githubusercontent.com/18379380/115822968-9132c400-a459-11eb-84cd-dcd4f6af7663.png">

It seems that upon hitting back I get this source map thing in the console...
<img width="1403" alt="Screen Shot 2021-04-23 at 5 17 36 PM" src="https://user-images.githubusercontent.com/18379380/115823069-c808da00-a459-11eb-9799-25120195168a.png">

**Comment by robguthrie** [comment]
fixed now
