### ISSUE TITLE
category tags – numbers vary from reality or filter not showing all threads

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7514]
clicking around the tags after initially filtering by one of them in loomio.org/demo
I see Company decision has (3) but I only surface one
https://www.loomio.org/g/Az2KfDEj/tags/Company%20decision

Or guides, 13, but actually none:
<img width="1403" alt="Screen Shot 2021-04-23 at 5 33 29 PM" src="https://user-images.githubusercontent.com/18379380/115823309-3d74aa80-a45a-11eb-9f2b-ffb020be304c.png">

**Comment by robguthrie** [comment]
i think this is all fixed now
