### ISSUE TITLE
Tagging threads from the overview page

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#7569]
If I want to tag a thread in Loomio 2.7.9, I have to open the thread, edit it, add the tags, save, and return to the overview.

I am pretty sure it used to be possible to add tags right there from the context menu (where you can close threads), and I'd really love to have this feature back.

**Comment by robguthrie** [comment]
Now that tagging is integrated into the edit forms. We'll be just adding an edit link to the dropdown. That do?

**Comment by madduck** [comment]
It'd mean 4 clicks instead of 5, so only really a minor improvement.

**Comment by robguthrie** [comment]
probably half the total time though

**Comment by robguthrie** [comment]
we're not going to add this feature
