### ISSUE TITLE
In-place creation of tags

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#7570]
In Loomio 2.7.9, if I want to tag a thread, I can only choose among existing tags, and have to use the button to the right to create a new tag before use. This is good as it prevents accidentally misspelt tags. However, it's also a pretty bad user experience, at least to me.

![image](https://user-images.githubusercontent.com/195073/117889240-4e049c00-b307-11eb-8357-b73270465a27.png)

Maybe under "No results found", the user could be given the option to create the tag?

**Comment by robguthrie** [comment]
I think i'll just change the "No results found" message to tell you to create one by clicking the button

**Comment by robguthrie** [comment]
oh i get it.. I don't think we can easily make a button within the no results message though. I'll see

**Comment by robguthrie** [comment]
you can add tags as you like, now
