### ISSUE TITLE
Formatting toolbar inaccessible on larger documents

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#7577]
I am just authoring a longer context for one of the threads, and the formatting toolbar being stuck at the bottom of the text area means I cannot create a heading without scrolling all the way down and back up, which is incredibly painful. Sure, I can use Markdown, but most other people won't even know that's an option.

**Comment by robguthrie** [comment]
the menu bar should be position sticky and stick to your screen when you scroll. I'm looking into why that's stopped. It's very hard to test for unfortunately

**Comment by madduck** [comment]
The Javascript for this is loaded from `static.cloudflareinsights.com`, which I had blocked (uMatrix). Maybe it's possible to import the code? Anyway, fixed for me now, but I suppose it'd be more privacy-preserving to not go out to 3rd party sites, especially since referrer URLs actually encode the title and thus might leak information.

**Comment by robguthrie** [comment]
that's not related actually. 

The floating menubar is position:sticky in css, no js required. 

The problem was a library update from vuetify which added a overflow: hidden to a parent element, and that disables sticky. 

anyway, thanks for alerting me about this, fix going up today.

**Comment by madduck** [comment]
Well, as soon as I enabled that site, it worked as expected, but now it also works as expected without the site.
