### ISSUE TITLE
Time poll: clocking "add" while field still in focus results in old value taken

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#7595]
If I add a slot to a time slot poll, and I type in the time (because e.g. it's not on the full hour), and I then hit "add slot" without leaving the field, the previous value is used instead.

To reproduce:
1. Edit time poll, select time field under "Add new time";
2. Let's assume it's currently "09:00". The choice list with full-hour times pops up;
3. Type "17:30" without hitting `<tab>` or anything;
4. Click on the "ADD TIME SLOT" button
5. Observe how "09:00" was added as time slot.

**Comment by robguthrie** [comment]
finally fixed this
