### ISSUE TITLE
Showing subgroups makes editor think we want to leave the page

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#7596]
While editing a thread context, if I click on a Loomio group on the sidepane for the purpose of expanding its subgroups (I want to right-click on one, as I need to read up on something while editing, cf. #7588), I am asked whether I want to "discard my changes". So I click "no", and the group expands, as expected. I don't think you should scare the user like that, and only threaten to discard changes when the page is actually being left.

![image](https://user-images.githubusercontent.com/195073/119051233-07095b80-ba17-11eb-94e3-76169da891ec.png)

**Comment by madduck** [comment]
Actually, it seems there is no simple container, as I had assumed (see #7597). Clicking on a group actually switches to the group, hence the Javascript protection makes sense. I guess I am just wondering why the group is expanded if I click "Cancel".

**Comment by robguthrie** [comment]
The group expands because while the route change was cancelled, the rest of the event went ahead.

**Comment by madduck** [comment]
I am okay with you closing this as long as the usability issue gets addressed perhaps under #7597. I should be able to expand and fold a group without having to navigate away.
