### ISSUE TITLE
Cache the list of names for mention-completion

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#7598]
Whenever I attempt to mention someone, it seems that Loomio has to go back to the server to obtain a list of possible names. Depending on Internet connection, this can take several seconds, which becomes very frustrating when one is mentioning a couple of names one after the other. Couldn't the list be cached, and if only for a few minutes, in the client?

**Comment by robguthrie** [comment]
It does this already. It's cached per thread currently.

**Comment by madduck** [comment]
@robguthrie It seems to be caching a name once I've used it alright. But when I try to add the next name, I have to wait another couple of seconds again for the names to be looked up. I am talking about caching the entire name list, rather than having to do a roundtrip each time. Compare to Github mention completion, which is instantaneous.

**Comment by robguthrie** [comment]
I've just pushed a change so mentioning is instant if the user is already in the thread or poll
