### ISSUE TITLE
Feature request: time poll dates to include day as ddd or dddd

### ISSUE THREAD

**Issue by eteb3** [loomio/loomio#7607]
Hi 

Just a request to consider slightly more intuitive time polls: 

The ISO date/time is good, but we need to refer to a calendar to know what day is being proposed. Could the format include ddd (or possibly dddd) to make this a bit easier to interact with? So:

{ddd yyyy-mm-dd hh:mm}

See the attached for the faintly confusing sea of digits. Possibly the month could also become {mmm} to aid readability? (Though there's benefit in the ISO date format, too.) 

Thanks for considering.

![Screenshot 2021-05-24 at 18 01 07](https://user-images.githubusercontent.com/11834131/119382538-0fcd8c00-bcba-11eb-9da6-fff928d82299.png)

**Comment by robguthrie** [comment]
you can choose your date format from preferences now
