### ISSUE TITLE
Confusing google doc preview

### ISSUE THREAD

**Issue by alanna** [loomio/loomio#7615]
Someone posted a link to a google spreadsheet in a discussion context, which seems to have triggered an auto-generated preview. But this preview is using really generic language instead of the actual document title, to the point that I literally thought this was an ad for google in the Loomio thread (!) - is there any way this could be made more clear, such as pulling through the document title? I've blocked out the text in between the link and preview so the screenshot looks odd but hopefully you get what I mean.

<img width="614" alt="Screen Shot 2021-05-31 at 3 39 10 PM" src="https://user-images.githubusercontent.com/5498878/120136628-b2d85580-c226-11eb-8317-cdb3bfd3ece2.png">

**Comment by robguthrie** [comment]
Oh dear. That really does look like an ad!

The problem is that the link is private. The server that fetches the preview information, and it's not able to read a private link. 
Browser security prohibits us from getting the user's browser to fetch the preview information for us.

Google is responding with a 200, so it's telling us we found the document, so we can't filter this behavior either.

I guess that just leaves changes to the style/design to hint that it's a link preview, but I'm not sure what I can do.

**Comment by alanna** [comment]
That makes sense. I think using styling and design could really help in this case. Like can you override the generic text google sense with other generic text like "Google Sheets document - click to open" or something that makes it more clear what that box is? As it is I don't think it's achieving its basic function of communication to the user "click here to view the google doc linked in this thread" because it looks like something else.

**Comment by alanna** [comment]
The same thing is happening with Loom links - looks like an advert.

![Screen Shot 2021-08-06 at 9 55 15 AM](https://user-images.githubusercontent.com/5498878/128426806-c47f20b2-193d-401d-a8e9-f0bb663e5528.png)

I've been removing link previews to get around this, but it would be nice to have them.

**Comment by robguthrie** [comment]
You can also edit the text of link previews.. was that obvious?

**Comment by alanna** [comment]
Ahhhh no I had no idea they were editable. I'll try that.

>

**Comment by robguthrie** [comment]
I guess I need to use words ('edit link preview') rather than icons, but
that can get busy.

**Comment by robguthrie** [comment]
We now filter out these link previews, so you wont see this confusing message.
