### ISSUE TITLE
Unread counters are wrong

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#7760]
My Loomio consistently tells me that I have unread threads and invite-only threads, but the numbers displayed do not reflect the reality. See this screenshot:

![image](https://user-images.githubusercontent.com/195073/128430871-a9f3a74d-8061-40b2-aa35-85f790b7bdd0.png)

There are supposed to be 2 unread threads, but there is only one. There is also no invite-only thread unread, despite it telling me there's supposed to be 1.

**Comment by madduck** [comment]
More to the point:
![image](https://user-images.githubusercontent.com/195073/128431906-4fa7ea91-cb34-49d2-863e-3b013da6b440.png)

**Comment by robguthrie** [comment]
Thank you. Will look into it.

**Comment by madduck** [comment]
There's an invite-only thread that's been closed weeks ago, but it just keeps coming back, no matter what I do:
![screencast](https://user-images.githubusercontent.com/195073/130154342-3a550530-5b57-4fd0-8845-8273e504cb9d.gif)

**Comment by robguthrie** [comment]
closing unless it comes up again
