### ISSUE TITLE
Quoted text is almost invisible in dark mode

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#7768]

**Comment by robguthrie** [comment]
it might be the text colours rather than the quoted text. do you have an example link you could provide me? I'm going to be removing text colours from the rich text editor so this can't happen in future.

**Comment by mhjb** [comment]
I'm sorry; it must have been a text colour copied in from an email. Forgive the distraction!

**Comment by robguthrie** [comment]
There was a really surprising amount of black text coded into much of the content on loomio, like half the threads I tested.

I've added CSS selectors that select for style="color: ..." tags, to turn black text white in dark mode.

CSS selectors for style tags. yep. They work.

**Comment by mhjb** [comment]
I wonder if that's lots of people copying and pasting stuff in?

That'sa fun CSS tip
