### ISSUE TITLE
Anchor link to heading does not take into account Loomio header

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#7789]
I have a fairly long context in a thread, and since I am using headings, I get a table of contents on the right:
![image](https://user-images.githubusercontent.com/195073/130376617-29280b64-f635-421f-b003-4085b24865a0.png)
But when I click on e.g. "Monday 23 Aug" (and browser appends `#monday-23-aug` to the link), then I am not actually shown the heading, but it seems as if the "Monday 23 Aug" heading is hidden beneath the Loomio bar at the top:
![image](https://user-images.githubusercontent.com/195073/130376716-5d51dc82-6b9f-4f6f-8033-3e75585bc157.png)
I have to scroll up just a notch to see the heading:
![image](https://user-images.githubusercontent.com/195073/130376777-54e6da34-fda7-4013-8f54-ab35bf0ad111.png)

**Comment by robguthrie** [comment]
not relevant now
