### ISSUE TITLE
Markup showing in slack webhook message

### ISSUE THREAD

**Issue by alanna** [loomio/loomio#7823]
![Screen Shot 2021-09-08 at 11 18 37 AM](https://user-images.githubusercontent.com/5498878/132422249-95211bd7-94b5-40b0-a283-6100bbf34f0a.png)

I'm not sure if this is a Loomio issue or a Slack issue.

**Comment by robguthrie** [comment]
thanks for reporting! I'll sort it out shortly.

**Comment by robguthrie** [comment]
Right, it's a bit of a weird one. I have a branch coming along that upgrades our text editor and will fix the root problem behind this. 

Did you copy and paste the "View the handbook" link from somewhere? (not that that's bad, just checking)

Also our links will all be underlined by default with the new branch, you won't have to add underline yourself.

**Comment by alanna** [comment]
Yes I copied it from the Loomio thread itself. I put the link in the
context box and wanted to include it in the proposal as well. The
formatting looked fine when composing the text in Loomio so I didn't think
to check the markup.

>

**Comment by robguthrie** [comment]
Oh, you're doing everything right, and you have no obligation to be checking markup :)

I just wanted to be sure that the source of the incompatible markup was copy paste rather than generated by the WYSIWYG formatting tools within the app. We'll be filtering the copy pasted markup better.... shortly.

**Comment by alanna** [comment]
Cool thanks! ❤

>

**Comment by robguthrie** [comment]
This is fixed for new content
