### ISSUE TITLE
Post templates

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#7835]
For things like a meeting agenda or the minutes, it would be really useful if templates could be stored and recalled within Loomio. Maybe a big feature request, but needs to be logged.

**Comment by robguthrie** [comment]
oohh right on. I've been working on this for the last few weeks. We have
cloning of record working now.

First feature to come is launching a demo group with content all
mid-stream, so you can see what Loomio looks like when it's in use, rather
than just starting an empty trial.
Right on the heels of that is using existing threads and polls as templates
for new ones.

So, next couple of weeks estimated release.

**Comment by madduck** [comment]
Great minds!

While on it, check out how Github let's you template issues now, e.g. try https://github.com/vector-im/element-web/issues/new?assignees=&labels=T-Defect&template=bug-web.yml and now imagine doing this for meeting minutes.

**Comment by robguthrie** [comment]
We have templates now! Help page coming, but check out the edit form on a thread.
