### ISSUE TITLE
Pasting a table from Calc/Excel results in an image

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#7840]
If I paste a table or parts of a table from Libreoffice Calc or Excel into the editor, somehow I end up with an image of the table. This is highly unexpected and not really desirable. The clipboard contains tab/newline-separated values, and while it would be ideal to have the editor actually render this into a table directly, at the very least I'd expect plain-text, not an image.

**Comment by robguthrie** [comment]
I don't think this happens now. Tables paste ok
