### ISSUE TITLE
Uploading an SVG as a cover image for a group crashes the group

### ISSUE THREAD

**Issue by despens** [loomio/loomio#7856]
After uploading an SVG graphic as a cover image for a group, the group "crashed," showing an Internal Server Error when its page is accessed. The group also does not appear anymore on the dashboard view or the side menu drawer.

There doesn't seem to be a way to replace the SVG image using Loomio itself, neither as a group user nor as an admin.

This seems to be the relevant part from the docker log:

```
loomio-app  | method=GET path=/my-group format=html controller=GroupsController action=show status=500 error='ActionView::Template::Error: ActiveStorage::UnrepresentableError' duration=96.49 view=0.00 db=16.13
loomio-app  |   
loomio-app  | ActionView::Template::Error (ActiveStorage::UnrepresentableError):
loomio-app  |     1: !!!
loomio-app  |     2: %html{lang: I18n.locale}
loomio-app  |     3:   %head
loomio-app  |     4:     %title= metadata[:title]
loomio-app  |     5:     %meta{charset: 'utf-8'}
loomio-app  |     6:     %meta{name: "viewport", content: "width=device-width, initial-scale=1.0" }
loomio-app  |     7:     %meta{:content => metadata[:title], :property => "og:title"}
loomio-app  |   
loomio-app  | app/models/group.rb:163:in `logo_url'
loomio-app  | app/serializers/metadata/group_serializer.rb:15:in `image_urls'
loomio-app  | (eval):5:in `_fast_attributes'
loomio-app  | app/helpers/application_helper.rb:17:in `metadata'
loomio-app  | app/views/layouts/application.html.haml:4
loomio-app  | app/helpers/locales_helper.rb:8:in `use_preferred_locale'
loomio-app  | app/helpers/locales_helper.rb:3:in `process_time_zone'
loomio-app  | source=rack-timeout id=a6370f3c-aada-4438-8982-475a07668d5a timeout=15000ms service=146ms state=completed
loomio-app  | source=rack-timeout id=e36786db-3d4e-4779-9138-2e8c0c889d54 timeout=15000ms state=ready
```

Looking into the database fields I thought are relevant, I found empty records:

```
loomio=> select id, theme_id, cover_photo_file_name, cover_photo_content_type, cover_photo_file_size from groups;
 id | theme_id | cover_photo_file_name | cover_photo_content_type | cover_photo_file_size 
----+----------+-----------------------+--------------------------+-----------------------
  1 |          |                       |                          |                      
(1 row)
```

**Comment by despens** [comment]
OK, it looks like these fields in the table `groups` are also empty for other, fully functional groups. But if there is a place where I should look for more hints on what is wrong or how this could be repaired, please let me know.

**Comment by robguthrie** [comment]
Hi, sorry for the delay, I've had an injured arm and needed time off the computer. 

We've recently switched from paperclip to activestorage for group and user images, the columns are still there for paperclip so the migration is forgiving in case people need to rollback - that's why you see empty columns.

If you login to the rails console, you can remove the cover_photo with something like 

```
g = Group.find_by(handle: 'yourgrouphandle')
g.cover_photo.purge
g.logo.purge
```

I'll update the file input filter so SVG's cannot be added via the UI

**Comment by despens** [comment]
Thanks Rob, this helped, my group is back. Hope your arm is all good again! :muscle:

**Comment by robguthrie** [comment]
Fixed - one cannot upload SVG's anymore
