### ISSUE TITLE
Images not coming through slack webhook

### ISSUE THREAD

**Issue by alanna** [loomio/loomio#7952]
I'm not sure whether this is an issue with Loomio, Slack, or an inherent limitation of webhooks.

Here's how a notification came through to slack:
<img width="757" alt="Screen Shot 2021-10-25 at 3 43 14 PM" src="https://user-images.githubusercontent.com/5498878/138627543-e47a8433-5e68-4c0b-93f9-35a3e71a310e.png">

It's showing the file path instead of the image itself. Is there any way to display the image? Or, if not, could it just say "image - click to view" and be a link to the image, or something like that?

**Comment by robguthrie** [comment]
Images now come through the slack webhook. I wonder if the big ugly links left over are a problem. I'm going to close this issue and feel free to open another if you think there needs to be more improvement :)
