### ISSUE TITLE
Unable to navigate to page 2 of closed threads

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#8149]
If I view only closed threads and want to switch to page 2 at the bottom of the thread list, I expect to be shown the next page of closed threads. However, the filter is reset, and I am instead shown the open threads. Therefore, older closed threads are currently completely inaccessible.

**Comment by anarute** [comment]
@robguthrie we also confirm having this issue and it's an important bug for us.

**Comment by robguthrie** [comment]
I'm happy to say that, finally, this is fixed.
