### ISSUE TITLE
Tags for subgroups

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#8150]
It seems that thread/proposal tags are a property of the root group, and cannot be overridden, altered, or added to in subgroups, but that might be quite useful, especially the ability to hide and add new tags, or even a control on whether tags should be inherited in the first place.

**Comment by robguthrie** [comment]
So, currently editing/adding/deleting tags is an admin role.  I think any member can apply a tag though. Maybe it should be optionally be a member permission like other things.

The idea is that there is only one set of tags per organization, it's supposed to be ignorant of subgroups but still work just fine within them. Can you tell me more detail about the issue?

**Comment by madduck** [comment]
I'm admin of a subgroup, but not a member of the main group, thus also not an admin. The subgroup is working on a confidential project, so having our own set of tags would actually be good, even to the point that those tags should not be available outside the subgroup.

**Comment by robguthrie** [comment]
ok great to know. I think the next evolution of the tags data structure will form in my mind shortly.

**Comment by robguthrie** [comment]
Billing aside, would it make sense for that subgroup to just be a stand alone group?

**Comment by madduck** [comment]
Yes, probably; though it started out as a strict subset of the main group, it has now evolved to include others.

**Comment by robguthrie** [comment]
Tag limitations are removed now. Anyone in the group can add any tag to a record. Admins can delete and rename tags across the group.
