### ISSUE TITLE
Poll is open after its closing time

### ISSUE THREAD

**Issue by jmallach** [loomio/loomio#8482]
I have a poll that remains open and accepting votes after its expiration time:

![image](https://user-images.githubusercontent.com/929712/160166183-10ffa2ed-64d2-40d5-b23c-37681ec05a6d.png)

(current time is 25/03/2022 17:55 CET)

**Comment by robguthrie** [comment]
Hi @jmallach - This is usually because the cronjob is not running.

See this for reference:
https://github.com/loomio/loomio-deploy#install-crontab

If you try:
```
docker exec loomio-worker bundle exec rake loomio:hourly_tasks
```
and it closes the poll, then I'd say that crontab is definately the problem.

Let me know how you get on

**Comment by jmallach** [comment]
Yeah, after some changes to the hosting server, this wasn't running anymore. :man_facepalming:  Sorry about the noise.
