### ISSUE TITLE
Missing  country_select plugin - DiscussionsController

### ISSUE THREAD

**Issue by celi28** [loomio/loomio#8500]
Hello,
**Description of the issue:**
After a fresh installation of loomio, I have a 500 error while asking for discussion edition from admin panel.

**Current stack:**
- Docker version 20.10.14, build a224086
- loomio/loomio:stable

**Steps to reproduce:**
1. Install loomio using loomio-deploy repository
2. Create a discussion on front panel
3. Get admin rights
4. Go to /admin
5. Try to edit a discussion
6. Get a 500 error.

**Expected behaviour:**
Do not have the 500 error.

**Logs:**
On app container:
```
method=GET path=/admin/discussions/5YgSEJe8/edit format=html controller=Admin::DiscussionsController action=edit status=500 error='ActionView::Template::Error: To use the :country input, please install a country_select plugin, like this one: https://github.com/stefanpenner/country_select' duration=51.43 view=0.00 db=16.48

ActionView::Template::Error (To use the :country input, please install a country_select plugin, like this one: https://github.com/stefanpenner/country_select):
    1: # frozen_string_literal: true
    2: insert_tag renderer_for(:edit)

app/helpers/locales_helper.rb:8:in `use_preferred_locale'
app/helpers/locales_helper.rb:3:in `process_time_zone'
```

**Comment by robguthrie** [comment]
Hi, thanks for the report. 

My fix for this would be removing the discussions section from the admin panel. There is no purpose for it :) 

There are some bugs with the admin panel, but nothing show stopping. The main one is editing things gives a 500, but it works, you just need to go back and reload.

As far as I can tell this is a bug with activeadmin.
