### ISSUE TITLE
Slack integration could be improved by including links

### ISSUE THREAD

**Issue by despens** [loomio/loomio#8557]
Using the Slack integration with Loomio 2.13.1, I noticed that it is possible to include the content of a Loomio discussion item, poll, etc, in the Slack message, but there is no link that would allow readers to go to the right place on Loomio to participate in a discussion or cast a vote. Providing a link to the item the bot is mentioning would be superb!

**Comment by robguthrie** [comment]
Oh, yea! Right. Thanks for giving it a go and letting me know.

**Comment by robguthrie** [comment]
fixed!
