### ISSUE TITLE
Unable to reference users in subgroup description field

### ISSUE THREAD

**Issue by despens** [loomio/loomio#8562]
I would like to name and mention the admins of subgroups in the subgroup description field.
However, typing `@` followed by user names does not work. An error is shown on the JavaScript console and the auto completer displays "no results found".

**Comment by despens** [comment]
Seeing a XHR request to `https://loomio.local/api/v1/profile/mentionable_users?q=dragan&group_id=14` -- and the response JSON contains all the user info for my account.

Then there's an error

```
Uncaught (in promise) TypeError: this.model.participantIds is not a function
    findMentionable mentioning.coffee:27
    fetchMentionable mentioning.coffee:21
    promise callback*81360/mounted/this.fetchMentionable< mentioning.coffee:18
    Lodash 6
    onUpdate mentioning.coffee:142
    update index.js:121
    updatePluginViews index.js:5120
    updateStateInner index.js:5069
    updateState index.js:5000
    dispatchTransaction index.js:3523
    dispatch index.js:5329
    Kn index.js:4763
    domObserver index.js:4942
    flush index.js:4402
    observer index.js:4258
mentioning.coffee:27:28
```

**Comment by robguthrie** [comment]
Thanks for the update, @despens . I'll look into this soon.

**Comment by robguthrie** [comment]
Hi @despens - I've fixed this so you can find people in your group and reference them in your description, but currently it won't actually send them a notification.

How's that?

**Comment by despens** [comment]
Well that's pretty nice @robguthrie :)
