### ISSUE TITLE
Unable to use Discord Chatbot

### ISSUE THREAD

**Issue by Danelem** [loomio/loomio#8569]
I tried to setup a Discord chatbot, but it doesn't seem to work. Discord doesn't seem to get the messages.

**Comment by robguthrie** [comment]
First, check that you've entered the webhook URL correctly.

If you're a Loomio customer, please email ***@***.*** so we can help
you in private, as this isn't likely a software bug, and we don't want to
ask for private details in a public forum.

**Comment by Danelem** [comment]
I'm not a Loomio customer.

I see that MS Teams work, but when trying setting up Discord, it doesn't seem to work.

It can be my installation, but I don't really have a way to check.

I don't see anything in logs.

**Comment by robguthrie** [comment]
Damn. It should work fine. I don't think I have enough information to help
you much, sorry.

If you start a trial group on Loomio, you can add a Discord bot and confirm
if your webhook url works.

I suspect the problem is not your install, but your webhook.

**Comment by Danelem** [comment]
I sent a message from Loomio.

**Comment by robguthrie** [comment]
Just checking, are you testing a real notification? I think the "test connection" button is broken.

**Comment by Danelem** [comment]
Right, you're correct, sorry for not updating you.

I found out that real notifications work, but the "test connection" doesn't.

**Comment by robguthrie** [comment]
Ok, maybe next time you can let me know instead.

Hope you find Loomio useful and continue to use it  :)
