### ISSUE TITLE
update_option_scores! can't cast Hash

### ISSUE THREAD

**Issue by asdofindia** [loomio/loomio#8575]
I'm running migration from an old version of loomio and at 20210809001931_fix_anonymous_stances.rb it came across this issue:

```
Migrating to FixAnonymousStances (20210809001931)
== 20210809001931 FixAnonymousStances: migrating ==============================
migrating poll data, please wait
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

can't cast Hash
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/quoting.rb:246:in `_type_cast'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/postgresql/quoting.rb:162:in `_type_cast'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/quoting.rb:43:in `type_cast'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/quoting.rb:205:in `block in type_casted_binds'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/quoting.rb:203:in `map'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/quoting.rb:203:in `type_casted_binds'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/postgresql_adapter.rb:669:in `exec_no_cache'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/postgresql_adapter.rb:649:in `execute_and_clear'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:70:in `exec_delete'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/database_statements.rb:179:in `update'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `update'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/persistence.rb:385:in `_update_record'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/persistence.rb:679:in `update_columns'
/loomio/app/models/stance.rb:72:in `update_option_scores!'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/relation/delegation.rb:88:in `each'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/relation/delegation.rb:88:in `each'
/loomio/db/migrate/20210809001931_fix_anonymous_stances.rb:6:in `block in change'
```

Based on https://github.com/rails/rails/issues/7190 update_columns cannot work with a hash value. 

One commenter suggests using to_yaml to avoid this. But I'm not sure if that works as intended.

update_option_scores! seems to be used in a few other places in the codebase too. So it might be good to look at those code branches too if they throw errors.

**Comment by robguthrie** [comment]
hrrmm i think that rails ticket is too old to be relevant. (rails 3 and we're on 6). It can take a hash. I'm sure the code works.

But I don't understand the error. Skip this one too, and if you find that your poll results are missing or weird. I can help you with a command to recount all the results.

Please tell me if there are further broken migrations and I'll go back and make them return.

**Comment by asdofindia** [comment]
The poll results were indeed all 0s

I did 
```
$ docker-compose run app rails c
Poll.find_each do |poll|
    poll.stances.each(&:update_option_scores!)
    poll.update_counts!
end
```

It took forever.

But it fixed it

**Comment by asdofindia** [comment]
![image](https://user-images.githubusercontent.com/945777/168648720-f7fd51a0-3504-4ff2-8adb-0bf3e2142451.png)

https://codema.in/p/wyRADYG9/should-we-accept-bitcoin-donations-

There is something still off

The voter count is 0, although score is correctly updated.

**Comment by robguthrie** [comment]
We can definitely resolve this. It's a cache rebuild thing.

Hopefully this is the right command for you:

Poll.all.pluck(:id).each { |id| ResetPollStanceDataWorker.perform_async(id) }

Let me know how you get on, I'd like to fix all the failing migrations now that you've done this hard work finding them.

**Comment by robguthrie** [comment]
It might take a while for the background jobs to finish, you can see them in /admin/sidekiq if you're a system admin (user.is_admin = true)

**Comment by asdofindia** [comment]
Thanks. It is [Free Software Community of India](https://fsci.in) that's running loomio at codema.in.

---

That command was useful in resetting vote count.

The stance matrix (?) still returns "Undecided" for voters (even those who have taken a stance). 
![image](https://user-images.githubusercontent.com/945777/168703064-6b94d727-00ec-4070-963f-90b4aa1191e7.png)

**Comment by robguthrie** [comment]
Yes, cast at means the vote has been issued to someone, but not used. If the cast_at value is incorrect, we can make a script to find those votes and fix them... like so:

```
Stance.where(cast_at: nil).each do |s|
  s.update(cast_at: s.updated_at) if s.option_scores != {}
end

```

I hope that works :)

**Comment by robguthrie** [comment]
Actually, use 
```
Stance.where(cast_at: nil).each do |s|
  s.update_columns(cast_at: s.updated_at) if s.option_scores != {}
end
```

**Comment by robguthrie** [comment]
Then rerun
```
Poll.all.pluck(:id).each { |id| ResetPollStanceDataWorker.perform_async(id) }
```

**Comment by asdofindia** [comment]
Ah, I was going to ask if I can run this:

```
Stance.find_each do |stance|
    unless stance.cast_at
        stance.cast_at = stance.created_at
        stance.save
    end
end
```

Thanks for suggesting:

```
Stance.where(cast_at: nil).each do |s|
  s.update_columns(cast_at: s.updated_at) if s.option_scores != {}
end
```

**Comment by asdofindia** [comment]
Just for documentation. Here's the (beautiful) result.

![image](https://user-images.githubusercontent.com/945777/168714369-fd5b3cba-1fb2-4038-b31a-07249e24779d.png)

Thanks Robert for all the help and for all the code in the software.

**Comment by robguthrie** [comment]
Hooray,  it's been a pleasure to see your work.
