### ISSUE TITLE
Avoid relying on record :id being ordered chronologically in development

### ISSUE THREAD

**Issue by asdofindia** [loomio/loomio#8579]
So, the nasty bug that was fixed in [v2.13.0](https://github.com/loomio/loomio/releases/tag/v2.13.0) - [we](https://codema.in/) were affected by that.

We exported data from loomio.org in 2020 March with the high IDs - and those were imported to a fresh database with id sequences at low numbers.

We didn't reach collisions in normal use, but only when trying to run migrations. So we avoided migrations for a long time. But eventually we figured out a workaround - 

For each table with serial id, do:

```
> select id from table order by id desc limit 1;

id
---
44056

```

to find the highest ID (which would have come from the import). And then reset the sequence to a value above that

```
> select setval('table_id_seq', 44057, false);
```

This must work, but if there is any assumption being made in the codebase that ids are ordered chronologically, it will cause problems.

So, I request loomio developers to avoid using ids for ordering chronologically (or any similar logic).

**Comment by robguthrie** [comment]
Thanks for letting me know. I'm sorry you had to work around the issues with that process. I'm so pleased it's fixed now.

I am also running a couple of servers which have the same problem/situation.

Yes, I'll keep this in mind. If you find any places where this is a problem, please let me know and I'll address them
