### ISSUE TITLE
Some posts in discussions become grey

### ISSUE THREAD

**Issue by livier** [loomio/loomio#8610]
I am a user on a loomio forum, instanced by https://framavox.org 
Some times, on some forum pages, It seems that somes messages had diseapered for me, replaced by a grey zone (excuses my english). 

Is it possibly that a moderation protecd me from seeing some messages ? Or a bug ? 

![Screenshot_20220602_100120](https://user-images.githubusercontent.com/2933203/171647596-af4b0ce1-a256-41ba-9170-f0db0b1e2ec6.png)

**Comment by robguthrie** [comment]
Also, if Framavox upgrade, you'll be able to export your group data and move to loomio.org or your own server, which means you can pay the community price and get paid support, and support the developers, both of which you cannot do on Framavox.
