### ISSUE TITLE
User have lost access to threads and members pages

### ISSUE THREAD

**Issue by pabelenda** [loomio/loomio#8722]
Hi,

we have an in-house deployment of Loomio at my company. I myself created most of the user groups and therefore am and admin on them all.

All of a sudden I cannot access members section neither can see the threads on some groups. The UI returns:

*You do not have permission to do this*

Other groups have disappeared completely and I cannot even see them.

I've opened the inspector and it's crowded with 403 errors referring to `/api/v1/[memberships|discussions|groups]`

My user is an admin of the platform.

Other users that still have access to the members section said that I'm still listed as an admin of the many group I cannot manage/see.

How can I help further debugging this?

**Comment by robguthrie** [comment]
Hi Pablo, are you sure you're logged into the correct user account. That's
the most common issue.

Another thing that might help is `docker-compose logs -f` when you're
sending events.

Happy to help with this.

**Comment by anarute** [comment]
I think it's safe to close this one :) this was fixed with the "Reactivate user" button. We don't know what caused but it didn't happen again.

**Comment by robguthrie** [comment]
excellent news!
