### ISSUE TITLE
Time poll showing in slack incorrectly

### ISSUE THREAD

**Issue by alanna** [loomio/loomio#8785]
Here's my time poll on Loomio, appearing correctly
![Screen Shot 2022-08-09 at 4 42 05 PM](https://user-images.githubusercontent.com/5498878/183565978-c74e2b9a-cbb0-485b-89fe-54737daab3b0.png)

And here it is on slack via webhook, with different times
![Screen Shot 2022-08-09 at 4 42 34 PM](https://user-images.githubusercontent.com/5498878/183566007-542e80f3-fd96-42f0-b29d-14e47d7a5fff.png)

**Comment by robguthrie** [comment]
Oh! Thanks for letting me know. I'll sort it out soon.

**Comment by robguthrie** [comment]
Ok, I've found the issue. Next release will have this fixed. Thank you for
taking the time to report it.

**Comment by robguthrie** [comment]
This should be fixed now :)

**Comment by alanna** [comment]
awesome, thanks!
