### ISSUE TITLE
Proposal outcome not rendering on slack

### ISSUE THREAD

**Issue by alanna** [loomio/loomio#8793]
![Screen Shot 2022-08-11 at 12 24 33 PM](https://user-images.githubusercontent.com/5498878/184045048-9df2cbb0-c4af-4fda-8475-aafc64559b9a.png)

**Comment by robguthrie** [comment]
Uh oh!

Really appreciate you letting me know. The screenshot tells the whole story
of what went wrong too.

I've fixed it in master and will deploy shortly. Hopefully tomorrow.

**Comment by robguthrie** [comment]
This should be fixed now :)

**Comment by alanna** [comment]
thank you!
