### ISSUE TITLE
Upgrade screen text broken

### ISSUE THREAD

**Issue by alanna** [loomio/loomio#8821]
![Screen Shot 2022-08-31 at 9 56 48 AM](https://user-images.githubusercontent.com/5498878/187550956-a8e7a9d3-2703-483a-ba0d-3e370f49ec60.png)

**Comment by robguthrie** [comment]
Sorry, this is only happening for mmt because it's a very unusual subscription. I'm probably not going to do anything about this. Thanks for letting me know though
