### ISSUE TITLE
Subgroups are not displayed in the admin Groups page

### ISSUE THREAD

**Issue by anarute** [loomio/loomio#8926]
In `/admin/groups` we can only see groups that are parents, the subgroups are not displayed.

There is a button "Parents Only" that I'd expected would toggle to display all groups or only parents, but clicking on it doesn't do anything.

<img width="258" alt="Screen Shot 2022-09-21 at 14 29 51" src="https://user-images.githubusercontent.com/333447/191504434-9d217d5d-be0c-4075-8d74-aa3585c118fe.png">

**Comment by robguthrie** [comment]
Thanks. I've fixed this in master.
