### ISSUE TITLE
Libre-Translate API support?

### ISSUE THREAD

**Issue by poVoq** [loomio/loomio#8966]
Would be nice if one could add translation via a self-hosted and FOSS translation service.

There is both the new browser based system by Mozilla and the Libre-Translate project that can be run on any server with CUDA support:

https://github.com/LibreTranslate/LibreTranslate

The is a similar PR for the discourse translate plugin with could probably give some hints how to implement this:
https://github.com/discourse/discourse-translator/pull/36

**Comment by robguthrie** [comment]
Thanks for raising this. It's a perfect opportunity for someone to contribute to Loomio - no UX decisions and an existing API for a similar service.

We will support someone to contribute, but won't be doing this ourselves.

**Comment by chetanmittaldev** [comment]
Hi,

I am interested in contributing.

**Comment by robguthrie** [comment]
Closing this. Happy to receive a PR.

**Comment by poVoq** [comment]
LibreTranslate now includes a Ruby API wrapper: https://github.com/LibreTranslate/LibreTranslate/pull/563
