### ISSUE TITLE
Don't show results on slack when first posting poll

### ISSUE THREAD

**Issue by alanna** [loomio/loomio#9052]
By definition, a poll which has just been created does not have useful info about results yet, but on slack the webhook displays the table, which takes up a lot of screen real estate and gives an impression of no one engaging. It's likely that by the time someone sees the slack message, others may have voted, but it still shows zeros on slack. So I think it should not display the results table when the message is triggered by a poll initially being started. Later on when there are results, like the 24 hour reminder message, the results table is helpful.
<img width="894" alt="Screen Shot 2022-10-07 at 9 25 26 AM" src="https://user-images.githubusercontent.com/5498878/194414735-e2f4c536-0f6f-4538-8689-0c037f0285af.png">
<img width="939" alt="Screen Shot 2022-10-07 at 9 25 47 AM" src="https://user-images.githubusercontent.com/5498878/194415059-9cfc1369-812b-4eea-af15-8a39aa5161a5.png">

**Comment by robguthrie** [comment]
Thank you. This is fixed in the next release.
