### ISSUE TITLE
Show result of time poll in slack message

### ISSUE THREAD

**Issue by alanna** [loomio/loomio#9060]
I expected the outcome message would automatically include the selected time poll winner, so I didn't repeat it in the description, but on slack it does not indicate the result and confusingly shows all the other not-selected options. For a time poll result, the most important bit of info by far is the winning time. All the other numbers and dates could go away.

<img width="827" alt="Screen Shot 2022-10-11 at 9 45 19 AM" src="https://user-images.githubusercontent.com/5498878/194949872-c318cf80-5eb9-44a5-bf3f-f7ed386cb9dd.png">

**Comment by robguthrie** [comment]
Really appreciate the feedback. I'll do this soon.

**Comment by robguthrie** [comment]
This is fixed now. Thanks @alanna!
