### ISSUE TITLE
Timeout / no save on editing vote inline in discussion thread 

### ISSUE THREAD

**Issue by vingle** [loomio/loomio#9167]
Apologies if issues with loomio.com should be posted elsewhere (feel free to close/delete/move if so) - but I noticed that editing a vote if it's inline in a discussion thread gives a timeout after 60 seconds and doesn't save. It works fine if edited on the dedicated page.

**Comment by robguthrie** [comment]
Hi!

I just tried this and it works fine for me. If you want me to look at a specific vote, please email contact@loomio.com with the URL of the thread and I'll see what's going on.
