### ISSUE TITLE
Don't show image filename in slack

### ISSUE THREAD

**Issue by alanna** [loomio/loomio#9232]
If you post a thread with an image and it gets pulled through to slack, it displays a very long image name, which seems unnecessary and takes up a lot of visual space.

<img width="1535" alt="Screen Shot 2022-11-30 at 11 48 25 AM" src="https://user-images.githubusercontent.com/5498878/204665729-133f4d9a-8804-4408-b151-d5956b837d2e.png">

**Comment by robguthrie** [comment]
Thanks for pointing it out @alanna - I've trimmed it so it just uses the filename part of the name. ie: "2.png" in this case.

**Comment by alanna** [comment]
Perfect thanks!
