### ISSUE TITLE
Notifications link to poll doesn't work when inside another poll

### ISSUE THREAD

**Issue by anarute** [loomio/loomio#9280]
@robguthrie When clicking in a notification to a poll when you are already in another poll, the link doesn't work. The address bar even switches to the correct link, but the page is not updated. No error is displayed in the browser console.

https://user-images.githubusercontent.com/333447/206492859-f85b11b4-6bed-4f55-9c59-61eb4195cfad.mov

Note that clicking in a thread or in a group page, it works. And other types of notification also works fine, it' s only the link to another poll.

**Comment by robguthrie** [comment]
Thanks @anarute - fixed now.
