### ISSUE TITLE
Implementation of Mastodon OAuth

### ISSUE THREAD

**Issue by alxsimon** [loomio/loomio#9382]
Hi, I am considering creating a Loomio server for users of a Mastodon instance.
I am wondering if it's possible to implement sign-in through Mastodon OAuth api (https://docs.joinmastodon.org/spec/oauth/) so that only server users can have access and they don't have to create an account.
Any pointer in this direction would be appreciated.
Thanks!

**Comment by sneakers-the-rat** [comment]
+1 would like to do the same thing. looking around for any examples of using mastodon as a login provider and not really finding any (but finding examples of the other direction, using other providers to log into masto)

**Comment by robguthrie** [comment]
Just to be clear, do you want Loomio to authenticate against Mastodon, or,
Mastondon to check if someone belongs to a Loomio group before allowing them to join?

**Comment by alxsimon** [comment]
The former, I'd like people to log-in in Loomio through their Mastodon login.

**Comment by robguthrie** [comment]
oh. that's not so hard. We have OAuth support - can Mastodon can act as an authenticator? 

I'm working on an integration for a microsoft azure oauth right now. You can probably just change settings on that.

**Comment by alxsimon** [comment]
Yes Mastodon is using OAuth 2.0 so this should work I imagine.
Oh great for the microsoft azure implementation, do you have a branch for the implementation? Couldn't find any with those keywords
Thanks!

**Comment by robguthrie** [comment]
https://github.com/loomio/loomio/pull/9394

**Comment by robguthrie** [comment]
@alxsimon just got this working. Happy to help you connect it to door-keeper/mastodon, should just be a matter of getting the ENV settings correct.. then documenting them :)

**Comment by alxsimon** [comment]
I didn't have time to experiment with it yet. I'll hopefully have a go this week-end. Thanks for the update.
