### ISSUE TITLE
Allow using GCS on active_storage

### ISSUE THREAD

**Issue by ludat** [loomio/loomio#9388]
I'd like to use GCS instead of s3 or disk to store the blobs from loomio.

After looking into the code it looks like this already works, but the `google` service should be added to the `config/storage.yaml` and the dependency for GCS is not installed by default in the `loomio/loomio` docker image.

I can create a PR with those changes if they are ok with you.

Thanks for creating loomio!

**Comment by robguthrie** [comment]
Hi, yes, would be happy to accept a PR for this. Thanks!
