### ISSUE TITLE
Logs changed to file instead of stdout in 2.17.0

### ISSUE THREAD

**Issue by ludat** [loomio/loomio#9628]
I think it was caused by [this commit](https://github.com/loomio/loomio/commit/e12fd6eb4aa8201d9444b8c4dc1a96e4b1cbc158) that removes the (deprecated) gem `rails_stdout_logging`.

I'd really like to be able to configure logs to stdout instead of a file.

They propose the following [fix](https://github.com/heroku/rails_stdout_logging#migrating-to-rails-5), if that's fine I can create a PR

**Comment by robguthrie** [comment]
Oh, that was unintentional, however you might find the ENV works without a
code change - try it first?

**Comment by ludat** [comment]
Yes and without the configuration somewhere rails doesn't pick up that variable by default so now, it's unconfigurable unless you edit the config files.

**Comment by robguthrie** [comment]
Right, thanks for bringing it up, I'll publish a fix today. We're going to
default to stdout, just like before

**Comment by robguthrie** [comment]
@ludat change is in master now. No env required. I'll publish a release in an hour or to.
