### ISSUE TITLE
Time poll buggy when language set to german

### ISSUE THREAD

**Issue by airblag** [loomio/loomio#9705]
Hi, I'm still running lastest tag from docker hub, but since a while, I have some problems by creating time polls.

how to reproduce : 

- set your profile to german
- create a time poll
- for some reasons, however reloading the page, under "**Optionen**" the block is shown in english for "**New option**". The default time is set in the format **12:00 PM**.
- The list for time shows the translated in the format **12:00 nachm.**
- Whatever you select from the list, the first option you get will be set to be shown as "**12:00nachm.**", so I think it's related to this issue https://github.com/loomio/loomio/issues/7595 that the old value stays
- If you then try to select another date to add a second option, the interface replies with the error **Option already added to poll** 
- if i type the english format like 04:00 PM in the field, then i can add further option
- I get the error even by changing the day and reclicking on "**option hinzufügen**" 

I guess the translated value is somehow wrongly passed somwhere where the english date format is expected.

I cannot see any error being logged server side, so i guess it's happening on javascript in the browser

**Comment by robguthrie** [comment]
Hi @airblag - thanks for posting this report. I did not get it at first, but someone else mentioned an issue with this.. and I finally clicked.

I've just fixed the problem in the master branch. Hope your Loomio server is working well.
