### ISSUE TITLE
Search is malfunctioning (from group page)

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#9770]
I try to search from group page and type in exact search terms from title of thread, but it does not surface the thread; please see below captures, thanks!
<img width="1386" alt="Screen Shot 2023-06-20 at 10 32 10 AM" src="https://github.com/loomio/loomio/assets/18379380/520c9a99-f7b5-49a1-8ebd-1d03ee5cc198">
<img width="1127" alt="Screen Shot 2023-06-20 at 10 32 37 AM" src="https://github.com/loomio/loomio/assets/18379380/12c7490c-e917-450a-bbf0-9ce506ae39ee">

**Comment by robguthrie** [comment]
Thanks for letting me know! I'll check it out next week

**Comment by robguthrie** [comment]
@coopchange I've just released a completely new search function. Please check it out!
