### ISSUE TITLE
Reaction notifications take users to their answers in Edition mode

### ISSUE THREAD

**Issue by anarute** [loomio/loomio#9783]
It seems that notifications done in a reason to vote of a poll that is still open takes the user to their reply in edition mode which is very confusing:

[Screencast from 2023-07-04 15-12-17.webm](https://github.com/loomio/loomio/assets/333447/47f866d3-10e2-4371-a026-63ca9a891bcc)

**Comment by robguthrie** [comment]
Wow, that is confusing! I'll look into the problem

**Comment by robguthrie** [comment]
Hi @anarute - I've just pushed a fix for this to master.
