### ISSUE TITLE
Comments from previous poll keeps being displayed when navigating to a new poll

### ISSUE THREAD

**Issue by anarute** [loomio/loomio#9795]
When you are *in a poll, not a thread*, and when the notification takes you to *a poll, not a thread* either, loomio opens the new poll but doesn't reload the list of votes/comments. The vote results chart is correct but it doesn't match the comments.

## Expected Behavior

When I click on a notification, it opens the target poll with its own results and list of votes.

[commentsnotereloaded.webm](https://github.com/loomio/loomio/assets/333447/2e6e17db-d874-4756-857a-a2a6393f1d51)

**Comment by anarute** [comment]
FYI this is still happening.

**Comment by robguthrie** [comment]
Your bug reports are so clear and helpful. Thanks for the reminder too.
