### ISSUE TITLE
Results for polls where "Results will be shown after you vote" are leaked in Context menu and emails

### ISSUE THREAD

**Issue by anarute** [loomio/loomio#9796]
It's possible to see in the context menu - right scrollbar - of a thread what are the current results of the poll even before voting.

The results are also displayed in the "Last week on loomio" email summary.

**Comment by robguthrie** [comment]
Hi @ana, thanks for reporting this.  I've fixed the problem in the right sidebar.

I don't think the results are showing in the email summary though. That template is used for all the emails and it's correctly coded - Do you have any more information about this?

**Comment by anarute** [comment]
Hi Rob, thank you for fixing it!

About the email, I'm trying to reproduce but wasn't able to, so feel free to close this issue and if  I'm able to reproduce the email I'll create a new one.

**Comment by robguthrie** [comment]
That's a great approach. Considering you opened this issue in July (thank you again), and I'm only addressing it now, it could very well have been resolved in the meantime.
