### ISSUE TITLE
Truncated text in poll options

### ISSUE THREAD

**Issue by aschrijver** [loomio/loomio#9808]
Text in poll options is truncated to be a single line, even if much more text is available. There is no way other than to "Inspect" the html or "View source" to be informed on the full text one is asked to vote for.

Screenshot Firefox 115 on Ubuntu:

![Screenshot from 2023-07-19 13-34-51](https://github.com/loomio/loomio/assets/5111931/0ff14bc3-6cc8-43bf-94dd-a5811666d2e3)

**Comment by robguthrie** [comment]
Thanks for raising this. I've just pushed a fix for it in master - we wrap the text and the meaning field in the poll option form has a 'soft' counter that turns red at 280 (about 3 lines).. you can continue to add more text but this is intended to steer you away from doing now.

<img width="725" alt="image" src="https://github.com/loomio/loomio/assets/486367/46dfff4a-23c7-4260-8dc4-d6ac2077ed1c">

on the vote form:
<img width="796" alt="image" src="https://github.com/loomio/loomio/assets/486367/f765442a-e0fc-4c49-80c0-64f24d7893a4">
