### ISSUE TITLE
Avoid migrations that trigger async workers

### ISSUE THREAD

**Issue by ludat** [loomio/loomio#9809]
Hi,

I'm having some issues with my current deploy of loomio that's caused by the fact that the migrations schedule
async jobs.

I deploy the migrations first (while the rest of the app is running) to avoid downtime, so if an async job is scheduled
while the migrations run, it'll get picked up by the old code which (probably) won't know how to handle.

Is it possible to run the job code synchronously instead, by using `perform` instead of `perform_async` in the
migrations.

**Comment by robguthrie** [comment]
Hi Lucas,

I intended that if the job fails, it will be retried, probably once the new
code is running. The async migrations are not critical so the app can come
up and these changes can happen shortly afterwards.

Am I missing something with this approach?

I will note that in some cases, I've needed to run
MigrateTagsWorker.new.perform manually - but I've improved the code since
the initial release so I think it was the code rather than the deploy
timing.

**Comment by ludat** [comment]
One thing that worries me is that the old code for `MigrateTagsWorker` might run.

I'd much rather have that in the release details. Something like "Run `MigrateTagsWorker.new.perform`
after deploying to sync the tags".

**Comment by robguthrie** [comment]
I want to ensure that the upgrade experience is the same every time.

It's a fair concern, I could add a `raise` if the Loomio version is wrong, so it will retry after new code is running

**Comment by ludat** [comment]
That sound a bit complex to be honest.

Is there a specific reason to avoid changing the migration to use `.perform` instead of `.perform_async`?

**Comment by robguthrie** [comment]
It does. 

> Is there a specific reason to avoid changing the migration to use .perform instead of .perform_async?

Actually, no, assuming that most hosts are much smaller than loomio.com (so wont take 10+ minutes) and don't have the same HA requirements. We can change it to inline job. That's a good solution.

Care to PR?

**Comment by ludat** [comment]
sure, the PR would be just to change the migration from `.perform_async` to `.perform`, right?

**Comment by robguthrie** [comment]
You were right with `MigrateTagsWorker.new.perform`
