### ISSUE TITLE
Time poll voting events pushed to slack list all available poll options

### ISSUE THREAD

**Issue by despens** [loomio/loomio#9890]
When opening a time poll, a nice overview ASCII table of all available dates is pushed to slack.

When a person votes, all possible time slots are listed, which is just repeating the information, but not indicating what time slots were selected.

It would be nice if either only the confirmed time slots would be contained in the Slack message, or if there was an indication noted next to each time slot how the person indicated their availability.

Current Slack message (example):

> Dragan Espenschied voted 
> [Example Time Poll](https://loomio.com/nowhere)
> Tue 19 Sep 2023 10:00AM
> Tue 19 Sep 2023  2:00PM
> Wed 20 Sep 2023 10:00AM
> Wed 20 Sep 2023  2:00PM
> Thu 21 Sep 2023 10:00AM
> Thu 21 Sep 2023  2:00PM
> Fri 22 Sep 2023 10:00AM
> Fri 22 Sep 2023  2:00PM

Possible improvement 1 (only showing confirmed slots):

> Dragan Espenschied voted 
> [Example Time Poll](https://loomio.com/nowhere)
> Availability:
> Tue 19 Sep 2023 10:00AM
> Tue 19 Sep 2023  2:00PM
> Fri 22 Sep 2023  2:00PM

Possible improvement 2 (showing confirmed, declined, and "if need be" slots):

> Dragan Espenschied voted 
> [Example Time Poll](https://loomio.com/nowhere)
> ✅ Tue 19 Sep 2023 10:00AM
> ✅ Tue 19 Sep 2023  2:00PM
> ❌ Wed 20 Sep 2023 10:00AM
> ❌ Wed 20 Sep 2023  2:00PM
> ❓ Thu 21 Sep 2023 10:00AM
> ❌ Thu 21 Sep 2023  2:00PM
> ❓ Fri 22 Sep 2023 10:00AM
> ✅ Fri 22 Sep 2023  2:00PM

**Comment by robguthrie** [comment]
Thanks, I've had a quick attempt to implement a per vote table.

<img width="463" alt="image" src="https://github.com/loomio/loomio/assets/486367/61c297c2-0505-42b5-965c-94f260620a18">

It's in master now

**Comment by despens** [comment]
@robguthrie Thank you so much this is great!

**Comment by robguthrie** [comment]
Great. Thanks for participating in the dev process.
