### ISSUE TITLE
Consensus process closing not showing outcome when closing automatically

### ISSUE THREAD

**Issue by Tunae** [loomio/loomio#9902]
Basically the issue we're having is that when a poll reaches it's closing time it doesn't clearly close unless manually closed by closing early.
It still looks like members can vote, although they cannot.

The only way to fix this as an admin is to reopen the poll and then close it early which then allows you to set a outcome.

This feels like a bug but I'm not so sure.
Cheers

**Comment by robguthrie** [comment]
Is this on your own server? 

Every time this has been reported before, the problem has been the cron tasks are not running.

https://github.com/loomio/loomio-deploy#install-crontab

**Comment by robguthrie** [comment]
No response. Happy to reopen if my advice does not work
