### ISSUE TITLE
Reusable invitation link does not allow creating an account?

### ISSUE THREAD

**Issue by poVoq** [loomio/loomio#9953]
It seems like the "reusable invitation link" does not allow people to create accounts? Or is this maybe a bug?

When clicking it only this view opens:

![grafik](https://github.com/loomio/loomio/assets/940360/e5730e5f-a388-4e5d-bd94-8c07867a4eb8)

I think it would be very nice for onboarding of close groups if it was possible to also register via such an link.

Sending direct invitations via email works, but then you need to know all the email addresses beforehand.

Thanks!

**Comment by robguthrie** [comment]
Thanks for the report. It was a simple fix
